### ISSUE TITLE
It does not work!

### ISSUE THREAD

**Issue by TomWeasley** [bergerhealer/TrainCarts#102]
##### Spigot version:1.9/1.10

<hr>

**Comment by TomWeasley** [comment]
Console displays 'synchronize a network controller'.

**Comment by JackDn** [comment]
TrainCarts does not support 1.9.

**Comment by TomWeasley** [comment]
Thanks. But will mg-1999's version work? It is in 1.9 branch.

**Comment by VanStorm** [comment]
That's just a development branch. It will probably take some time.

**Comment by TomWeasley** [comment]
Oh. The development is still continuing, isn't it?

**Comment by VanStorm** [comment]
That question could only be answered by @mg-1999
