### ISSUE TITLE
Not working corectly

### ISSUE THREAD

**Issue by GoMini-01** [bergerhealer/TrainCarts#104]
#### Problem or bug:

Hello
I have problems with the Plugin in minecraft 1.8.x the plugin wont be enabled and wont work but in 1.9 it enables but wont work corectly no signs work and carts get invisible instant 

#### Steps to reproduce: Install it in 1.8.8 and 1.9

MFG GoMini

**Comment by mg-1999** [comment]
Please use the correct version for 1.8
