### ISSUE TITLE
Trains colliding on track (Please read problem/bug section)

### ISSUE THREAD

**Issue by KensterLeKen** [bergerhealer/TrainCarts#105]
#### Problem or bug:

I build a train line on a loop line with 13 stations, each station is 13 rails long and each car is 9 carriages long. I sent 12 trains from the termini of the line and made sure they ran over the property 'keepcloaded' sign, and they did keep loaded; they didn't disappear, however, I left the server running for about 12 hours overnight with no-one online and they had all collided by the morning. I think that they are stopping on the track after a while, since I sent them all down at regular intervals and they should never all stop at the same station at once and collide with each other mid-track?
#### Expected behaviour:

Keep constantly following the loop, without stopping on the track and colliding with each other.
#### Steps to reproduce:

Create a very long loop line underground with 13 stations which stop for 10s each, and two 'maintenance depots' overground, stopping for 20s each, send 12 lots of 9 carriage trains down the track at regular intervals in such a way as they don't collide, then disconnect from the server and wait 12-24 hours. When you next go online, they should have merged into one train.

I need this to be fixed, as it's useless making all the lines that I have, only to have them defunct at the start of every day. Thanks!

**Comment by FriwiDev** [comment]
Suggestion: Let a "driver" bot travel in the first minecart of each train (Simulated player, could be a NPC Player

**Comment by KensterLeKen** [comment]
Could that be a Villager? Or a Furnace Minecart?

**Comment by KensterLeKen** [comment]
*The villager despawned.

**Comment by JackDn** [comment]
Try setting loadchunks to true:
[+train]
property
loadchunks
true
