### ISSUE TITLE
Not working with enable BKCommonlib

### ISSUE THREAD

**Issue by CooleCat** [bergerhealer/TrainCarts#109]
##### Spigot version: 1.9

<hr> I have make a server with server.pro and i install the latest version from BKCommonlib and Traincarts from the website BKCommonlib is working but Traincarts not its traincarts outdated?
Or my server? I have already set my server on 1.8.8 but then working BKCommonlib and Traincarts not...   Please send something back....

**Comment by harm27** [comment]
@CooleCat At first, you can't combine BKCommonLib and Spigot for 1.9 with Traincarts 1.8. So far i know, BKCommonLib doesn't have a stable 1.9 build for yet.
Also so far i know @mg-1999 said he doesn't have time to update BKCommonLib or TrainCarts.
You would need to be really patience until he finds time or someone else takes over the project or you need to find an alternative or stay on 1.8.

**Comment by CooleCat** [comment]
Thanks!

But i have a new problem!
My minecarts desp
