### ISSUE TITLE
Trains derail at speed above 0.4 blocks/tick

### ISSUE THREAD

**Issue by FuntasiaPark** [bergerhealer/TrainCarts#111]
##### Spigot version: spigot-1.8.8-R0.1-SNAPSHOT

<hr>

#### Steps to reproduce: I really don't know how to reproduce this problem, from the minecraft server I know I am the only one having this problem.

(I am sorry for possibly bad english, I am dyslectic and it's not my native language)

**Comment by mg-1999** [comment]
Hey man,

This is a bug that i cant fix. I dont know how other servers fix it.

Also there is a 1.11.2 release coming soon and fixed almost al bugs.

- Matthijs

**Comment by FuntasiaPark** [comment]
and what is soon, april, may, june? I need it al fixed by the beginning of june

**Comment by mg-1999** [comment]
Don't have any idea myself. It should be ready in a few weeks.
