### ISSUE TITLE
Remote control signs should be limited

### ISSUE THREAD

**Issue by ghost** [bergerhealer/TrainCarts#113]
##### Spigot version:
CraftBukkit version git-Spigot-54ec0b8-e17c3d2 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

<hr>

#### Problem or bug:
Using [train *] or any other syntax which matches all trains allows you to make TrainCarts unusable on the whole server. For example you could make a redstone clock which destroys all trains.

#### Expected behaviour:
Trains with the default names should not support remote control.

#### Steps to reproduce:
Create a redstone clock and connect it to a sign which says
```
[train *]
destroy
```
Carts will instantly be destroyed when they are placed.

![Example](http://i.imgur.com/AspAdeO.png)

**Comment by DynamicThijs** [comment]
Please no, I use this all the time. Just name the carts you want to control remotely "remote" or something like that. They will get names like remote1, remote2 and so on, then you can make a sign like this: "[train remote*] destroy" to destroy them.

P.S. @mg-1999 this is no bug ;)
