### ISSUE TITLE
Improperly Working Signs

### ISSUE THREAD

**Issue by RubbrDukky** [bergerhealer/TrainCarts#115]
##### Spigot version: 1.11

<hr>

#### Problem or bug:
Signs (for stations, destroy, etc.) do not properly function when being created. The tag "parseOldSigns" was added to the config and set to "true" because I am using a Mac but the issue is still there.

#### Expected behaviour:
When signs are placed correctly below tracks and powered with redstone (when applicable), the trains and carts are expected to behave according to the first line of the sign.

#### Steps to reproduce:
Create signs to set behaviour of trains using Mac keyboard.

**Comment by bergerkiller** [comment]
This is a tough issue to fix, because the mac keyboard basically has no keys for [, ], {, }, etc. I do consider using ( ) as an alternative syntax to get around this, as I'm not particularly fond of the 'old' naked format.

**Comment by bergerkiller** [comment]
Please let me know if this did not fully answer your problem.
You can now create (train) / (+train), etc. Signs. Parse old formats should work too, as it had a length >= 15 check which made no sense and was never fulfilled.

https://github.com/bergerhealer/TrainCarts/commit/f12b3869f3efeccdaff6d76d5c13ad08bc78dfa4

https://ci.mg-dev.eu/job/TrainCarts/29/
