### ISSUE TITLE
Incompatibility with PaperSpigot

### ISSUE THREAD

**Issue by TomWeasley** [bergerhealer/TrainCarts#117]
### Spigot version: 1.11.2

<hr>

### Problem or bug:
TrainCarts works well in spigot but it is does not work in PaperSpigot. Players cannot interact with trains created by this plugin. Console(PaperSpigot) displays NullPointerExceptions after creating a train.

### Expected behaviour:
Being compatible with PaperSpigot

### Steps to reproduce:
Just put enable BKCommonLib and TrainCarts in a PaperSpigot server and then create a train.

### More:
First, thanks to all of you developers. This plugin is the best one ever! And will you continue the development on higher versions of Minecraft? Or is it possible to adapt all versions of Minecraft(Not using NMS)? I found a "useNetworkSynchronizer" in config.yml and is disabling this means not using NMS functions? Please leave a comment, thank you very much! (I am not quite familiar with plugins developments, if there're any problems just don't mind them. Also I am not an English speaker so just ignore those improper words.)  :)

**Comment by Bart-0110** [comment]
PaperSpigot is using some custom NMS code so the plugin doesn't work with it. I tried to make it compatible but the PaperSpigot version is missing some functions, maybe @bergerkiller can take a look into it.

**Comment by bergerkiller** [comment]
I've made changes in the latest build of BKCommonLib to add full support of Paperspigot.
