### ISSUE TITLE
Uphill Track Pressure Plate Bug

### ISSUE THREAD

**Issue by GamerKM** [bergerhealer/TrainCarts#118]
BkCommonLib version: 1.11.2-v1
TrainCarts version: 1.11.2-v1
Spigot version: 1.11.2

<hr>

Problem or bug: On a uphill track, a train with multiple mine carts and multiple people in them will set off the a pressure plate once per player that passes over it.

Expected behaviour: The presseureplate should only be pressed once per connected train that passes over it, just as it would when laying flat.

Steps to reproduce: Setup a track going up a slope, and ride a train with 2 players or more going up the slope.

**Comment by bergerkiller** [comment]
Does this involve the detector rail? Because that has been fixed, or should be fixed anyway. Or actual flat pressure plates? I'm a bit confused because flat pressure plates dont go uphill
