### ISSUE TITLE
Error while initializing sign power states

### ISSUE THREAD

**Issue by DynamicThijs** [bergerhealer/TrainCarts#121]
##### Spigot version: 1.11.2

<hr>

#### Problem or bug:
I'm always getting this error when I start my server: https://pastebin.com/suaKcEea
#### Expected behaviour:
No error on startup ;)

**Comment by jmb1304** [comment]
i am also having this issue

**Comment by bergerkiller** [comment]
Is fixed in the latest build of BKCommonLib (CI: https://ci.mg-dev.eu/job/BKCommonLib/ )
