### ISSUE TITLE
Errors spammed into server consol and carts not linking

### ISSUE THREAD

**Issue by Will200399** [bergerhealer/TrainCarts#123]
##### Spigot version: using bukkit 1.11.2 latest

<hr>

#### Problem or bug:
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c$$FastClassByCGLIB$$ce62bf1e.invoke(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.CGLIB$A_$24(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartAbstract.A_(EntityMinecartAbstract.java:370)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.TCListener.onVehicleEntityCollision(TCListener.java:339)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.get(MinecartMemberStore.java:246)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.conversion.Converter.convert(Converter.java:35)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:13)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:32)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.entity.CommonEntity.get(CommonEntity.java:740)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.getController(EntityHook.java:27)
05.05 18:19:44 [Server] ERROR java.lang.RuntimeException: Controller is never allowed to be null!
05.05 18:19:44 [Server] ERROR at java.lang.Thread.run(Unknown Source)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:599)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1342)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.h(World.java:1487)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1509)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.A_(<generated>)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:596)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:59)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook$$EnhancerByCGLIB$$277d8531.onTick(<generated>)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:603)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassHook$HookMethodList$1$1.invoke(ClassHook.java:119)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c$$FastClassByCGLIB$$ce62bf1e.invoke(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.CGLIB$A_$24(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartAbstract.A_(EntityMinecartAbstract.java:370)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.TCListener.onVehicleEntityCollision(TCListener.java:339)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.get(MinecartMemberStore.java:246)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.conversion.Converter.convert(Converter.java:35)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:13)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:32)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.entity.CommonEntity.get(CommonEntity.java:740)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.getController(EntityHook.java:27)
05.05 18:19:44 [Server] ERROR java.lang.RuntimeException: Controller is never allowed to be null!
05.05 18:19:44 [Server] ERROR at java.lang.Thread.run(Unknown Source)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:599)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1342)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.h(World.java:1487)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1509)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.A_(<generated>)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:596)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:59)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1342)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.h(World.java:1487)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1509)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.A_(<generated>)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:596)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:59)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook$$EnhancerByCGLIB$$277d8531.onTick(<generated>)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:603)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassHook$HookMethodList$1$1.invoke(ClassHook.java:119)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c$$FastClassByCGLIB$$ce62bf1e.invoke(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.CGLIB$A_$24(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartAbstract.A_(EntityMinecartAbstract.java:370)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.TCListener.onVehicleEntityCollision(TCListener.java:339)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.get(MinecartMemberStore.java:246)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.conversion.Converter.convert(Converter.java:35)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:13)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:32)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.entity.CommonEntity.get(CommonEntity.java:740)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.getController(EntityHook.java:27)
05.05 18:19:44 [Server] ERROR java.lang.RuntimeException: Controller is never allowed to be null!
05.05 18:19:44 [Server] ERROR at java.lang.Thread.run(Unknown Source)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:13)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:32)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.entity.CommonEntity.get(CommonEntity.java:740)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.getController(EntityHook.java:27)
05.05 18:19:44 [Server] ERROR java.lang.RuntimeException: Controller is never allowed to be null!
05.05 18:19:44 [Server] ERROR at java.lang.Thread.run(Unknown Source)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:599)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1342)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.h(World.java:1487)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1509)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.A_(<generated>)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:596)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:59)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook$$EnhancerByCGLIB$$277d8531.onTick(<generated>)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:603)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassHook$HookMethodList$1$1.invoke(ClassHook.java:119)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c$$FastClassByCGLIB$$ce62bf1e.invoke(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.CGLIB$A_$24(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartAbstract.A_(EntityMinecartAbstract.java:370)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.TCListener.onVehicleEntityCollision(TCListener.java:339)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.get(MinecartMemberStore.java:246)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.conversion.Converter.convert(Converter.java:35)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:13)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:32)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.entity.CommonEntity.get(CommonEntity.java:740)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.getController(EntityHook.java:27)
05.05 18:19:44 [Server] ERROR java.lang.RuntimeException: Controller is never allowed to be null!
05.05 18:19:44 [Server] ERROR at java.lang.Thread.run(Unknown Source)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:599)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1342)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.h(World.java:1487)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1509)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.A_(<generated>)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:596)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:59)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook$$EnhancerByCGLIB$$277d8531.onTick(<generated>)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:603)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassHook$HookMethodList$1$1.invoke(ClassHook.java:119)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c$$FastClassByCGLIB$$ce62bf1e.invoke(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.CGLIB$A_$24(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartAbstract.A_(EntityMinecartAbstract.java:370)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.TCListener.onVehicleEntityCollision(TCListener.java:339)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.get(MinecartMemberStore.java:246)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.conversion.Converter.convert(Converter.java:35)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:13)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:32)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.entity.CommonEntity.get(CommonEntity.java:740)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.getController(EntityHook.java:27)
05.05 18:19:44 [Server] ERROR java.lang.RuntimeException: Controller is never allowed to be null!
05.05 18:19:44 [Server] ERROR at java.lang.Thread.run(Unknown Source)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:599)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1342)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.h(World.java:1487)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1509)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.A_(<generated>)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:596)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:59)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook$$EnhancerByCGLIB$$277d8531.onTick(<generated>)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:603)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.reflection.ClassHook$HookMethodList$1$1.invoke(ClassHook.java:119)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c$$FastClassByCGLIB$$ce62bf1e.invoke(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartRideable$$EnhancerByCGLIB$$efd4548c.CGLIB$A_$24(<generated>)
05.05 18:19:44 [Server] ERROR at net.minecraft.server.v1_11_R1.EntityMinecartAbstract.A_(EntityMinecartAbstract.java:370)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
05.05 18:19:44 [Server] ERROR at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296)
05.05 18:19:44 [Server] ERROR at java.lang.reflect.Method.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.TCListener.onVehicleEntityCollision(TCListener.java:339)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.get(MinecartMemberStore.java:246)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.conversion.Converter.convert(Converter.java:35)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:13)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MemberConverter.convert(MemberConverter.java:32)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.entity.CommonEntity.get(CommonEntity.java:740)
05.05 18:19:44 [Server] ERROR at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.getController(EntityHook.java:27)
05.05 18:19:44 [Server] ERROR java.lang.RuntimeException: Controller is never allowed to be null!

**Comment by FranciscoContreras** [comment]
I'm having the same or similar issues.   
  
Here is what I get followed by spam similar or exactly the same as above.   
  
`[11:31:02 ERROR]: [Train_Carts] Failed to synchronize a network controller:
[11:31:02 ERROR]: [BKCommonLib] java.lang.NullPointerException
[11:31:02 ERROR]: [BKCommonLib]   at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1026)
[11:31:02 ERROR]: [BKCommonLib]   at java.util.Collections.unmodifiableCollection(Collections.java:1013)
[11:31:02 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.controller.EntityNetworkController.getViewers(EntityNetworkController.java:393)
[11:31:02 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMemberNetwork.syncSelf(MinecartMemberNetwork.java:218)
[11:31:02 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMemberNetwork.onSync(MinecartMemberNetwork.java:171)
[11:31:02 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.EntityTrackerHook.track(EntityTrackerHook.java:35)
[11:31:02 ERROR]: [BKCommonLib]   at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
[11:31:02 ERROR]: [BKCommonLib]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:31:02 ERROR]: [BKCommonLib]   at java.lang.reflect.Method.invoke(Method.java:498)
[11:31:02 ERROR]: [BKCommonLib]   at com.bergerkiller.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:596)
[11:31:02 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.EntityTrackerEntry$$EnhancerByCGLIB$$1be119b1.track(<generated>)
[11:31:02 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.EntityTracker.updatePlayers(EntityTracker.java:182)
[11:31:02 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:914)
[11:31:02 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[11:31:02 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754)
[11:31:02 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652)
[11:31:02 ERROR]: [BKCommonLib]   at java.lang.Thread.run(Thread.java:748)`

**Comment by mg-1999** [comment]
Please update bkc and tc to the latest version provided on the spigot pages. Those version should work.

If not please provide a pastebin of your log file so we can see the errors and help you.

**Comment by DynamicThijs** [comment]
@FranciscoContreras You are using PaperSpigot, update to the latest development build found here: https://ci.mg-dev.eu/job/BKCommonLib/lastSuccessfulBuild/

**Comment by bergerkiller** [comment]
Paperspigot (1.11.2) is now supported as of the later -v2 and 1.12 versions of BKCommonLib and TrainCarts. Closing the issue, can be re-opened if more compatibility issues crop up.
