### ISSUE TITLE
Station bugs out when launching over longer distances involving multiple stations

### ISSUE THREAD

**Issue by bergerkiller** [bergerhealer/TrainCarts#129]
##### Spigot version: 1.11.2

<hr>
Issue put here in the name of bbayu (from spigotmc resource forums).

[Spigotmc forums post link](https://www.spigotmc.org/threads/traincarts.233672/#post-2387897)

#### Issue description
I'm having an issue where trains will suddenly bounce back after leaving the station. Here's what happened:
1. The train was going forward (I will call this direction "right" from now) until it reached a station sign which pointed it to launch to the left (in other words reverse the direction)
2. The train successfully left the station going left until it reached another station pointing in the same direction (in this case left).
3. The train will accelerate away from the station sign (towards left) for around 100 blocks and then suddenly halt, then accelerate in the other direction within a second.
If you need more information please say so, I'll try to provide as much information as I can.

P.S. I was using this plugin since 2015. It's great to see it finally being updated to 1.11 :)

#### Steps to reproduce:
[YouTube video uploaded by bbayu detailing this bug](https://youtu.be/0XrgXk5_iMs)

**Comment by bbayu123** [comment]
Here's [another video](https://youtu.be/e9_1nniAnB0) featuring a similar bug, where the train "bounces back", although it's a different situation.

Some information in case you need it:
Video 1: 
Station 1: Train entered from West, left from East.
Station 2: Train entered from West, left from West.
Station 3: Train entered from East, left from West, and the bug occurred.

Video 2 (The one in this comment):
Station 1: Train entered from North, left from South.
Station 2: Train entered from South, left from North, and the bug occurred.

**Comment by bergerkiller** [comment]
Ive now made several pretty huge changes to train launching and station logic, can you verify that the problems you were having are still present for this latest build?

https://ci.mg-dev.eu/job/TrainCarts/49/

Last bug I fixed may be of interest: spawning a train on tracks with a station sign caused some strange behaviors.

**Comment by frozenMC** [comment]
Im curious-- would a bug like this be possible with an [launcher] sign as well? I may have run into this bug recently, with 1.12-v1.

Updated my TC to 1.12-v2 (build 75) and it still persists. 

https://i.imgur.com/pa087F3.jpg <-- the setup. It is a industry spur in this instance, with two "launchers" to stop/launch trains from nearest the dock, a item collector on the 2nd track from the dock (not revelant to this), and trash/binning trains on the third track. I was working on the tech underneath, so I set it up so the train goes from 1st track, then to 3rd track to get trashed.

Now, on the first track nearest the dock, theres "slot A" and "slot B". (in the picture above, the train visible is at slot A-- the furthest from the turn). If you send the train out to the trash track from Slot A with [train]/launch 8/0.8/right, it works perfectly and as intended.

If you send the train out to the trash track from Slot B with [train]launch 8/.8/right (the same setup), it will go to the switch, go around, then suddenly reverse into the dock. I extracted the land underneath it AND changed the trackage AND /train reroute, thinking I screwed up something somewhere. 

HOWEVER: if I changed the Slot B launch to [train]/launch 6/0.8/right, it works fine. 

Just wanted to report that this bug still exist, but I have worked around it.

**Comment by bergerkiller** [comment]
Station and launcher logic has changed so much over all this time, many bugs fixed and uncovered. Some also tie in with that frozenMC mentions, so I'm closing this ticket. If new problems are still found with the station/launcher signs, feel free to make a new ticket specific to that.
