### ISSUE TITLE
Can't move minecarts in creative mode

### ISSUE THREAD

**Issue by ontertree** [bergerhealer/TrainCarts#13]
May be same issue as #12 ?
Using version: Train_Carts v1.74-SNAPSHOT using BKCommonLib v1.66-SNAPSHOT

1. Place minecart on rail
2. Set /gamemode 1
3. Right-click on cart
4. Press 'W'  
Result: cart does not move

Also:
1. Place minecart on rail
2. Set /gamemode 1
3. Attempt to move cart on rail by walking into it
Result: cart does not move

**Comment by Bart-0110** [comment]
It is the same issue.
Also it schouldn't matter if you're in survival or in creative

**Comment by ontertree** [comment]
If it is same issue sorry for duplicate report. But if I do:

1. Place minecart on rail
2. Set /gamemode 0
3. Right-click on cart
4. Press 'W'  
Result is I am able to move. Does that not happen for you?

**Comment by kpaulisse** [comment]
I will submit a PR with a fix shortly.
