### ISSUE TITLE
Launchers don't have a constant acceleration

### ISSUE THREAD

**Issue by MinePlayer64** [bergerhealer/TrainCarts#130]
![Speed Curves](https://vgy.me/Lo0xC7.png)

Currently the speed of a launcher is proportional to the distance travelled.
This means it's quadratic to the time (red curve).
Trains accelerate very slowly in the beginning.

The speed should be proportional to the time instead (green curve).

**Comment by bergerkiller** [comment]
I think you may very well have a point there. A little risky to change it now (because of people's timings and whatnot), but I will consider adding a configurable means to change it.

**Comment by MinePlayer64** [comment]
I think the best way to do this is to have a target time instead of a target distance on the second line.

Example:
```
[+train]
launcher 10
0.4
right
```
This sign should behave just like it currently does (red curve).

---
```
[+train]
launcher 3s
0.4
right
```
This sign should use 3 seconds to accelerate the train (green curve).

---

Doing this will not change how launchers currently work.

**Comment by bergerkiller** [comment]
You are correct that there is a missing "time" configuration option. There are several options for this. Whatever option I choose, it must stay backwards compatible. I may choose to use an @ or space character to split it up. For example:

```
[+train]
launcher <distance>
<speed>@<duration>
right
```

Tricky is that the same applies to stations and others. I will have to figure out an option that works for everything.

**Comment by MinePlayer64** [comment]
The distance is not needed, the duration already does that.
I would just make new signs (slauncher, sstation, ...?) which use the duration instead of distance.

**Comment by bergerkiller** [comment]
The distance is needed, because you need to know when the train achieves the velocity set on the sign. You can launch the train to a speed of 0.4 in 1 block, in 10 blocks, in 20 blocks, etc. The distance determines how fast velocity is incremented and how far away from the sign the final velocity is achieved.

**Comment by MinePlayer64** [comment]
Acceleretion: `a = (targetVel - startVel)/  time`
Velocity: `v = startVel + a * t`
Distance: `d = 0.5 * a * t²`

There are 2 ways to calculate the acceleration from the target velocity:

1. `a = (targetVel - startVel) / time`
2. `a = (targetVel - startVel)² / (2 * d)`

1 needs the velocity and time.
2 needs the velocity and distance.

If you specify time **and** distance you can't choose the velocity: `a = 2 * d / t²`

I think the best way to do it is to allow using a time **or** distance on the sign.

**Comment by bergerkiller** [comment]
Took me a moment but I think you're right. I was seeing distance traveled different from the velocity applied, but they are related by the function used. Indeed, it should be quite possible to include time under the same placement as distance, with the difference that you put 's' or 'm' or 'ms' or 't' (ticks) after it to denote the time. More tricky will be how to convert time into distance and such. But, I'm sure theres an answer to that equation, too.

**Comment by MinePlayer64** [comment]
@bergerkiller `d = 0.5 * a * t²`

**Comment by bergerkiller** [comment]
Right now I'm dealing with different problems fixing this. The first is that, to center trains, it must absolutely use distance to guarantee proper placement. But for launching away it needs to also support time. This, in combination with a distance approximation algorithm that has no predefined time period, makes it very difficult to implement.

It will be done, but it will take a little longer while I figure out the cleanest way of fixing this. It's not simple matter of adding a time variable and making a f(t) out of it, not just yet anyway.

The biggest complexity, and that is also what had me confused, is that the whole calculations is, like you say, not linear. As a result there is another hidden variable right now that controls the curve of the velocity over time, which in turn can cause the time to vary. My first challenge is making a linear and quadratic version of the same algorithm that complete the whole launching action in exactly the same timeframe.

**Comment by bergerkiller** [comment]
After some days in a sandbox I cooked up two launch algorithms: Bezier (easing) and linear velocity change over time. I'll default to bezier because it looks so fancy, and allow configurable change to use linear instead. Both algorithms complete in the same timeframe/distance.

https://gist.github.com/bergerkiller/9cced438741e1ef67de647a9eef412f5

**Comment by bergerkiller** [comment]
Launch functions are now implemented. After a first run you can change 'bezier' to 'linear' in the config.yml to change the way it launches.

https://github.com/bergerhealer/TrainCarts/commit/5f0c2ea6cb262f6d4cd0e7ebe13277ad4a3c8866

https://ci.mg-dev.eu/job/TrainCarts/39/

**Comment by MinePlayer64** [comment]
I like that a lot. I think it would be nice to be able to choose the launch function from the sign though.
Currently it seems like linear is better for roller coasters and bezier is better for trains (starts accelerating slowly).

**Comment by bergerkiller** [comment]
Perhaps another token used on the line where right now launch force is used? It would only work for launchers tho, since stations lack that.

**Comment by MinePlayer64** [comment]
I think it's easier to have bstation, lstation, blauncher and llauncher sign types (just like effect and meffect).

**Comment by bergerkiller** [comment]
That feels a little nasty though. Would you be okay with putting it after the distance/time statement? 'b' and 'l' dont match any time notation so for that it works fine.

[train]
station 20l

**Comment by MinePlayer64** [comment]
That makes much more sense. I'm fine with that.

**Comment by bergerkiller** [comment]
This setup works for me. Both signs result in the same duration of 5s, but you see one launch linearly and the other accelerates more slowly at the start. https://puu.sh/wmf1D/0b40fbb112.png

https://github.com/bergerhealer/TrainCarts/commit/48ac9e38fa0eb1f75462328b6be31327a7deafc7

https://ci.mg-dev.eu/job/TrainCarts/45/

**Comment by MinePlayer64** [comment]
I'm getting weird results with speeds above 0.4. When launching a cart to 0.8 it suddenly has the full speed at approximately 50% of the launch distance.

```
[+train]
launcher 100b
0.8
left
```

**Comment by bergerkiller** [comment]
I used trigger signs to verify this is not happening on my test server. I made it launch for 10 blocks, linear and bezier. Both were about 0.2 halfway the way there.

```
[+train]
trigger
triggername
```

Then on sign: %triggernameV%

(uses SignLink)

**Comment by bergerkiller** [comment]
ACTUALLY, now that I think about it, I'm not entirely sure now. The problem is that, while velocity ramps up at a constant rate when linear, and is 0.2 in the middle time-wise, the middle time-wise is definitely not the middle distance-wise. Thats impossible, considering it will move much slower the first half of the launch compared to the second half. As a result, it will travel less distance the first half than the second half.

This distance curve shows it better: https://puu.sh/wmFYe/73621a980b.jpg

Around half (253) you can see it is at distance 20 / 100. This means the velocity will be half (0.2) at distance 20. At distance 50 ("halfway there") the tick time is 361/500.

What you see is correct but not the way you think. Velocity simply does not change as much the second half of the way there.

**Comment by MinePlayer64** [comment]
This is was I was talking about:
https://gfycat.com/SimilarRegularAmericanindianhorse
The carts suddenly get a pretty big speed boost at the end of that video.

**Comment by bergerkiller** [comment]
That is indeed irregular, but I don't see it happening here. There are no other signs influencing it? If you can figure out more in detail when it occurs that would be helpful. I've made a 120-length long track and set it off, and it worked fine there.

**Comment by MinePlayer64** [comment]
https://gfycat.com/SatisfiedImportantChevrotain
It seems to do some weird stuff when getting above 0.4.
Could it be caused by the update factor which is applied at speeds above that?

Spigot version: git-Spigot-cd6ba67-6aa0fa3 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
I'm on the latest BKCommonLib, TrainCarts and SignLink dev builds (my test server start script downloads them automatically).

**Comment by bergerkiller** [comment]
Hmm yes, that could definitely be. Especially because it uses getmaxSpeed to figure out what speed to launch at so you get a visual ramping up. I will have to look into launch speeds above the default 0.4 when train maxspeed is changed.

**Comment by bergerkiller** [comment]
Can you confirm where this is fixed, too? @MinePlayer64

**Comment by MinePlayer64** [comment]
Seems to work correctly
