### ISSUE TITLE
Trains are not centered on stations correctly

### ISSUE THREAD

**Issue by MinePlayer64** [bergerhealer/TrainCarts#132]
![1 cart](https://vgy.me/mXwRHb.png)
![2 carts](https://vgy.me/nKelem.png)

The trains were coming quite slowly.

**Comment by bergerkiller** [comment]
Just wanted to let know that I'm working on this. Its already fixed for the simple case, more complex cases I'm still figuring out with track iterators and centering two carts.

![screenshot_2017-06-10 22-49-51](https://user-images.githubusercontent.com/957601/27006234-1fad3ca4-4e2f-11e7-863b-41b5ee1c264b.png)

**Comment by bergerkiller** [comment]
I have fixed this centering issue after many hours of debugging why offsets kept occurring one way or another. In any case, it appears to work now in all the following test cases:
- Single minecarts/odd size trains above sign, even size trains center in the middle of two carts
- Centers correctly when the train drives up onto the station to stop
- Centers correctly when the train drives up to launch in the opposite direction
- Centers correctly when minecarts are added to a station-waiting train

https://github.com/bergerhealer/TrainCarts/commit/bed191d4608658fe92430032612bccd1956dfc40

Please have a test before I close it @MinePlayer64 
https://ci.mg-dev.eu/job/TrainCarts/35/

Your other issue (launch speed not being linear) is not yet fixed, I'm working on that.

**Comment by MinePlayer64** [comment]
Seems to work really well, I couldn't find any problem with it (even at speed 5).
