### ISSUE TITLE
Station will delay more than timer with train (2+ carts)

### ISSUE THREAD

**Issue by david50407** [bergerhealer/TrainCarts#138]
##### Spigot version: 1.11.2-R0.1-SNAPSHOT (git-Spigot-283de8b)

<hr>

#### Steps to reproduce:

1. Place a station sign like:

```
[train]
station
3
right
```

2. Place 2+ carts on the station, or just power a spawn sign like this:

```
[train]
spawn
mmm

```

3. Power up station sign.

4. The train will delayed more than the time set (2 carts will delayed 6 secs, 3 for 9 secs, etc.) and the train will move pass-through the station slowly during timer counting.

And if the train only has one cart, it won't be affected by this issue.

edit:

I selected each cart and use `/train info` to check if they are in the same train group, they give me the same infos, so that means they are in the same group.

**Comment by bergerkiller** [comment]
This is also with the latest builds of TC/BKC? Theres been a lot of changes with this and the last -v1 release is definitely outdated when it comes to that bug.

https://ci.mg-dev.eu/

**Comment by david50407** [comment]
Worked on build 49 on Jenkins, I was on build 45. Thanks
