### ISSUE TITLE
Train goes back on a slope

### ISSUE THREAD

**Issue by david50407** [bergerhealer/TrainCarts#139]
##### Spigot version: 1.11.2-R0.1-SNAPSHOT (git-Spigot-283de8b)

<hr>

#### Steps to reproduce: 

1. Make a slope like this:

![image](https://user-images.githubusercontent.com/841969/27255071-cbf7edbc-53c8-11e7-958b-48d7742ea83c.png)

2. Place a train on the top side.

3. Launch the train, in this case train gained maxspeed=1 and launch by station by going from north (upper-side) to south (lower-side).

4. After the train get onto the slope, the train goes back to the north (goes up) instantly.

**Comment by david50407** [comment]
More info, if the train has speed low enough, this won't happen.

But this also happened when maxspeed=0.3.

**Comment by bergerkiller** [comment]
Interesting, what kind of information did you put on the station sign? A length or not? It looks to me like it does this as part of the station launch. Does it also go back like that when you place the train manually and send it downwards?

**Comment by sntc06** [comment]
I've record a small video showing how this happens.
http://recordit.co/BdbWQa7WPE

It does not happen when trains are placed manually and pushed down.
The 1st example is the problematic one.
The 2nd example works find, with added maxspeed=0.2 property.

**Comment by david50407** [comment]
This will happened while using `launch` sign like this:

```
[+train]
launch
0.5

```

![image](https://user-images.githubusercontent.com/841969/27258134-a13c0304-5424-11e7-958b-058c1d7167da.png)

**Comment by MinePlayer64** [comment]
Probably related to https://github.com/bergerhealer/TrainCarts/issues/130#issuecomment-309238513 (carts getting very high speeds from launchers)

**Comment by david50407** [comment]
@MinePlayer64 how this issue relates to high speed? Does the timing/speeding function wrong?

**Comment by bergerkiller** [comment]
Both have to do with changing the maxspeed, possibly. I will look into this and it may very well fix both issues at once.

**Comment by bergerkiller** [comment]
I can 100% confirm this bug on my test server. Will be fixing it.

**Comment by bergerkiller** [comment]
Problem is in the getMovedDistance() function that is being used. This is not the same as the velocity that is applied, so on sloped tracks this screws up. I will be switching it to use a 'blind' approach instead, lacking a feedback loop of actual moved distance vs requested. That appears to fix it, but I'm testing more cases first.

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/TrainCarts/commit/f7f99b132e09cb0c03bc90ebb0944e06b34de085

I have fixed that bug to the point I can no longer reproduce it. I have also fixed that bug @MinePlayer64 was suffering from. Launching at speeds above 0.4 now functions exactly as expected, with smoothened motion all along the way.

https://ci.mg-dev.eu/job/TrainCarts/50/

**Comment by david50407** [comment]
It works! 👍
