### ISSUE TITLE
Multiverse support

### ISSUE THREAD

**Issue by Rocologo** [bergerhealer/TrainCarts#141]
##### Spigot version: 1.12

I wish you had Multiverse Teleport support instead of MyWorld. Im not able to replace Multiverse with MyWorlds because it is used by to many other plugins

**Comment by bergerkiller** [comment]
Does multiverse have some sort of sign system too, to set up these portals? All I need to know from Multiverse are when a sign is a portal and what the destination of the portal is.

**Comment by Rocologo** [comment]
Hi, sorry for the delay. Yes Multiverse has a sign system too. 

I will show you two examples. A world portal which teleports the player, mob or cart to spawn in that world 

![2017-06-24_09 27 03](https://user-images.githubusercontent.com/1008133/27506767-b54e6526-58c0-11e7-9be6-ea5d31d17089.png)

Or the one which is better for traincarts. Portal to portal teleports

![2017-06-24_09 34 08](https://user-images.githubusercontent.com/1008133/27506772-e028ae64-58c0-11e7-965e-960decd5125c.png)

In this case I have made 2 test portals where the player or a cart teleports to the portal behind. The sign on the first portal tell you which portal is the end portal. "p:" is to specifiy that it is a portalname (and not a world name like  my first screendump) the name after "p:" is the name of the portal behind. 

I have tested traincarts on this little portal system. It partly works. Meaning it takes the carts one after one, and not as a train, so the cart does not seems to know where to go.... 

Multiverse has also  SignPortals which maybe could be used instead(?) just an idea. Multiverse SignPortals works much like the portals above. I write [mv] and where to go on the sign, and when the player hits the sign he is teleported. Multiverse SignPortals support redstone signals by the way. 

Or maybe you could make similar Signs so I could teleport a train when it passes a "teleport sign" much like all the other signs you have made. 

MultiVerse has an API which maybe could be used? 
https://github.com/Multiverse/Multiverse-Core/tree/master/src/main/java/com/onarandombox/MultiverseCore/api

I hope this will help you, or please ask, I and will try to help/answer

**Comment by bergerkiller** [comment]
Hmn I did try to use the [mv] on signs but it didnt do anything with Multiverse Core installed. Do I need to do something special for it to work? I also tried on an actual portal but nada. Didnt change color, no messages.

**Comment by Rocologo** [comment]
It probably mission permissions. 

I think you should install multiverse-portals too. 

Did you try to make a portal from one world to another world or from one portal to another portal in the same world?

you will need this
multiverse.access.WORLDNAME
to get access one special world or
multiverse.access.*
to get access to all worlds.

Maybe its something with your multiverse "worlds.yml" the world you are jumping from and jumping to must exists in the worlds.yml file. 

Does "/mv list" show the worlds? 

You can import existing worlds with "/mv import ...."

**Comment by Rocologo** [comment]
I you are testing on a test-server ( i guess you do) the you can add permission to yourself 

multiverse.*

and get access to all commands....

**Comment by bergerkiller** [comment]
Thank you for all your help, this will surely get me going to get it working. I only need very little information from multiverse so this should not be hard to implement.

**Comment by Rocologo** [comment]
I'm developer myself, I know how important it is to get help, with the testing and integration to plugins you dont know, because you dont use them yourself.

I have added support for  / hook in to more then 30 plugins, and I dont use most of them myself. (https://www.spigotmc.org/resources/mobhunting.3582/) 

I'm happy that I can help, and in return I might get a feature for my server I really want to have and use. I'm planning to make a tour around in my different worlds, so new players can get an introduction to by server, by train. 

Let me know if you need more help....

**Comment by bergerkiller** [comment]
I needed to install Multiverse Sign-Portals, which I found on dev.bukkit after some looking around. I can now teleport with it, so that's a big step of the way there. Once I have a demo setup going for potential traincarts teleport I can go and implement some API to interface it to TC.

**Comment by bergerkiller** [comment]
@Rocologo 
After a lot of testing and playing with portals I tried to get the basic nether portals to work. Unfortunately, while multiverse portals teleports me as player to the right portal, it teleports any items and minecarts to the nether. Minecart teleport appears entirely broken with plenty fun errors in the console, which I've fixed. The minecart disappears on the nether end, though, because of it being wrongly created by Minecraft itself.

Nether teleportation I can get working by overriding Entity Portal event, cancelling it and performing a train teleport to the nearest rail found at the destination. (if there is no rail, it will simply cancel the teleportation entirely). That part is easy. However, since I can't get multiverse to even teleport items to the right destination, I can't use this same logic for portal to portal right now. Any suggestions how I can configure these portals to also teleport those?

Finally I consider simply adding a [train] portal sign that looks for portals from either multiverse or MyWorlds and teleports to them. Having to detect portals automatically will incur a performance loss or require a big block mapping to be maintained. But with a simple TrainCarts sign like so many, it's possible to allow both.

**Comment by Rocologo** [comment]
1) Any solution which can teleport train and passengers without involving MyWorld would fulfill my needs for teleportation. 

If you could make a simple Sign like all the other signs you have made, with a format like this (example)
[train]
Teleport
_destination_
_direction (N,E,W,S)_

Then I could use this. It don't not have to Multiverse Portals. If a sign could trigger the teleportation. 

2) On my test-server I can easily teleport a train from one portal to another (see picture 2). The carts is actually teleported, but when it appear in portal number 2, all carts are disconneted and the do not act as a train anymore. The carts push to each other but the do not connect again. 

The can configure Multiverse-Portals to teleport carts in the config file /plugins/Multiverse-Portals/config.yml


wand: 290
useonmove: true
portalsdefaulttonether: true
enforceportalaccess: true
portalcooldown: 1000
clearonremove: false
**teleportvehicles: true**
framematerials: []
version: 2.7

My guess is that you have "**teleportvehicles: false** in your config file?

**Comment by bergerkiller** [comment]
Its actually set on true already. But I think I'll just go with a [train] teleport sign. That is the easiest method by far. It does not allow simple portal to portal (and back) teleport, but adding a sign underneath the tracks shouldn't be too much of a problem...

**Comment by bergerkiller** [comment]
I have added support for Multiverse-Portals for teleporting to named portals using a [train] teleport sign in this commit: https://github.com/bergerhealer/TrainCarts/commit/73d94d7a5d206e08e5eaa8064b85cfec595181be

Usage:
```
[+train]
teleport
portalname:w
```
The portal name on the third line has an optional direction set after it. If none is set, it will also work and will select the best direction automatically. It has a search function for this. When you place rails 'against' a portal, you will rarely if ever have to put a direction. When the rails go through the portal, it is a good idea to do so. The direction is NOT multiverse's direction, meaning that besides n/e/s/w it also supports f/b/l/r for forwards/backwards/etc, which will look relative to how the portal is facing. This can make things simpler.

Fourth line is presently unused, though I might come up with some use in the future.

https://ci.mg-dev.eu/job/TrainCarts/68/

**Comment by Rocologo** [comment]
Thanks Bergerkiller, I will install the new version and do some testing. Unfortunately I have some players on my server now, so I have to wait restarting the server. 

I will get back to you when I have tested the sign. Its not clear to me ifg I place the sign on the portal or under the rail, but I guess I will find out, when I start testing.

**Comment by bergerkiller** [comment]
Under the rail. The teleporter sign is purely for teleporting to another portal. You dont have to put any TrainCarts signs in/around/at the portal you teleport to. Its more like a trigger for teleportation.

**Comment by Rocologo** [comment]
1) SUCCES!.  First test done . I placed a sign under the test portal on the picture above using "flat_rail_p2:w" as destination and it worked.
2) "flat_rail_p2:f", worked too.
3) "flat_rail_p2:b" worked to, except it did not work because it then drove into the first portal again.  (I had rails between the portals) 

Everything seems to work as intended!

It seems that Im no able to make a train station in my lobby world, with trains to the other worlds and maybe a roundtrip for new players. Thank you for this GREAT plugin. I know how muct time it takes to make a good plugin. I think i have spend so much time on my own plugin MobHunting, that I will NEWER admit it :-D

When I was a kid I had a very big Märklin collection (I actually still have it on the roof in old boxes). I think you are german, so I guess you know what Märklin is :-) No I can start playing again - without too much notice! :-D

**Comment by Rocologo** [comment]
You can close the ticket now. I create a new one if i find a bug.

**Comment by Rocologo** [comment]
Second test didnt work well... I think I have to play with it when I am back from work in 8 hours.

**Comment by Rocologo** [comment]
So I have been testing some more now. And I am fighting with some kind of bug. 
This setup works fine (using a sign in FRONT of the portal)
![2017-07-10_17 55 55](https://user-images.githubusercontent.com/1008133/28027533-ad390068-6599-11e7-9fc0-ee591efda2d9.png)

This one works fine. (using a SignPost directly under the rail/portal)
![2017-07-10_17 56 37](https://user-images.githubusercontent.com/1008133/28027544-b7fdea36-6599-11e7-8a9b-4708ead58228.png)

But this one does not work. If I place a sign (not signpost) under the rail/portal the sign disapears without any error messages. If I place an empty sign is okay, so it must be TrainCarts which removes the sign without a warning. I guess you remove the sign because its placed the wrong place? But the you should write a message and spawn a sign naturally in front of the player so he can pickup his sign again, 
![2017-07-10_17 58 57](https://user-images.githubusercontent.com/1008133/28027669-2e9b4e9a-659a-11e7-8574-7198bee90350.png)

**Comment by Rocologo** [comment]
Except for this minor problem, I think it works and I will start using this on my server :-)

**Comment by bergerkiller** [comment]
The reason it removes that rail is, I presume, because there is no rails above the sign. Remember that for wall signs, it targets the rails on top of the block pillar the wall sign is attached to. So in your first example, the sign would target the rail inside the portal. In the last example, it targets the rail one block after.

It doesn't show a message though, and that is indeed wrong.

**Comment by Rocologo** [comment]
You are right there were no rail on top of the pillar. I removed all rails between the two portals. 

I have not tested if is  possible to send a train both ways through the portals. I think I can live without, but it would be nice if is possible. 

Im not sure if I am going to use "flat_rail_p2:w" and "flat_rail_p2:e" or "flat_rail_p2:f" and "flat_rail_p2:b" or... I will play with it a little bit more to understand the difference between w/e and f/b

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/TrainCarts/commit/d70690249e734b593145ad17216a5083674f9a1d
Fixed that building bug, though it does not change what I said before

**Comment by Rocologo** [comment]
Building bug? But you were right. There was no rail on top of the pillar.

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/TrainCarts/commit/545c7f6e1b0fb5fd23d04507c5cf2b3b8d9b1ec6
https://puu.sh/wGimG/fe3d9b9cdf.png

Adds support for remote control, so you can use redstone contraptions to time the teleportation, or in general, teleport trains to another spot any place they are. Will only teleport the first train targeted.

(you use /train rename to change train names to something you can match)

https://ci.mg-dev.eu/job/TrainCarts/71/

**Comment by Rocologo** [comment]
I am not that familiar with the remote control features. But if I understand you right I can teleport the train from where ever it is to the portal just by pulling the lever so it activates the redstone signal to the sign.

**Comment by bergerkiller** [comment]
Yup! Exactly. Remote control activates trains by name remotely. It works for several signs that don't rely on rails above it, or directional rail input.

**Comment by Rocologo** [comment]
Hi again, I have tested some more.

I have setup a small(test) train station in my lobby (spawner, station, teleport) and then teleport to the test portal  you saw on the pictures above, but I am having some problem. I seems to work most of the time, but sometimes the train stop after spawning in the end portal. And do never continue. Like they are "broken"

I tried to restart the server and I found this warnings in the server log:

https://pastebin.com/khMmK2ag

**Comment by bergerkiller** [comment]
What happens if you keep the area around the destination portal loaded? For example, put a minecart there with keepchunksloaded true to keep the 5x5 chunk area loaded.

The warnings you are seeing have to do with this issue ticket https://github.com/bergerhealer/TrainCarts/issues/145

**Comment by Rocologo** [comment]
![2017-07-22_14 03 55](https://user-images.githubusercontent.com/1008133/28490953-a84bbc2a-6ee6-11e7-82a8-1f255b0f2c74.png)
I'm not sure if I did this test right but it did not seem to solve the problem. This is how it looked after 20-30 min at the end portal.

**Comment by Rocologo** [comment]
the "from portal" is in another world.

**Comment by bergerkiller** [comment]
Very likely this is a bug in the teleport function itself, or that plugins are conflicting by teleporting back and forth. Once I have time I'll test it out extensively cross-world.

**Comment by Rocologo** [comment]
Thank you. I cant use the teleport feature for the moment being. Im not sure why but I can replicate the problem: If I spawn some trains (for hours) let the trains teleport across worlds, the I end up in a situation like about and I get so much lag that I have to do  "/train destroyall" and restart the server to remove the lag. Maybe it is a memory leak? Destorying the trains seems not to solve the lag, only a server restart. And if I disable the train spawning, then I get no lag at all.

**Comment by Rocologo** [comment]
I will test this again. I hope it works now
