### ISSUE TITLE
Trains break (when going up slopes)

### ISSUE THREAD

**Issue by lolzelig** [bergerhealer/TrainCarts#143]
##### Spigot version: b1344

<hr>

#### Problem or bug:
Occupied trains break when going up slopes (Carts with passengers are getting disconnected), there were no issues at all when the train was empty.

Video of bug (6 seconds)
https://www.youtube.com/watch?v=E_tXclnGUmA

**Comment by lolzelig** [comment]
Solved - NoCheatPlus Plugin causes these issues

**Comment by lolzelig** [comment]
The only thing I've found out is that NCP reports it as follows:

`17-07-03 17:28:30 [INFORMATION] Player failed SurvivalFly: tried to move unexpectedly. VL 126.
17-07-03 17:43:29 [INFORMATION] Player failed VehicleEnvelope: moved a vehicle too fast (entity.MINECART+ascend_much). VL 100.
17-07-03 17:48:52 [INFORMATION] Player failed Passable: moved into a block (0) from 3514.71, 81.24, 2359.98 to 3514.71, 81.18, 2359.98 distance 0.06 . VL 11.`

Other than that.. no idea why it would do that..

**Comment by bergerkiller** [comment]
Looks like it has to do with the vehicle steering logic. Which is odd, because steering action is already handled by the minecart, players dont cause changes in minecart speed themselves. If you can, link this issue to the creator of NoCheatPlus, maybe something is set up too strict.
