### ISSUE TITLE
Signs don't get triggered (under) sloped tracks

### ISSUE THREAD

**Issue by bergerkiller** [bergerhealer/TrainCarts#148]
##### Spigot version: 1.12

(from SpigotMC by TMCThomas00)

Trains don't trigger signs underneath sloped tracks. When put on the side, it works. (more information may be needed if I can't reproduce it as-is)

**Comment by bergerkiller** [comment]
![Setup_that_fails](https://puu.sh/wHPif/f831b2b171.png)

Confirmed

**Comment by bergerkiller** [comment]
Fixed it here:
https://github.com/bergerhealer/TrainCarts/commit/97dcd60455a4baa08798c70312a7d93de5075797

Development build:
https://ci.mg-dev.eu/job/TrainCarts/73/

**Comment by TMCThomas** [comment]
Thanks a lot for fixing the issue! My rides work again :D
