### ISSUE TITLE
Trains reverse backwards and forwards when a switcher sign is placed.

### ISSUE THREAD

**Issue by loftyD** [bergerhealer/TrainCarts#149]
##### Spigot version: git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2)

<hr>

**Comment by bergerkiller** [comment]
Does this also happen when you explicitly define the directions to go to? For example:
```
[+train]
switcher
n:passenger
s:default
```
So it goes north when there is a passenger in the train/minecart, and south when there is not

**Comment by loftyD** [comment]
I'll try this in a bit and let you know.

```
[!train]
switcher
1
1
```
This sign layout is what I'm currently using, and it worked when I was on 1.7.10, so it would toggle between one train to the left and right etc.

**Comment by loftyD** [comment]
Ok I've made your sign

When I'm in the cart it will proceed along the track and when I'm not , the cart will reverse and head back.

**Comment by loftyD** [comment]
Hi again

Sorry to waste your time. I've managed to get them working.  The reason they weren't working was due to where the signs were placed in relation to the rails. It's working as expected now.
