### ISSUE TITLE
Train is stopping and separated when he climb a grade

### ISSUE THREAD

**Issue by Maxi22700** [bergerhealer/TrainCarts#15]
Hi,
I installed yours train cart in 1.8 with a spigot server, but when I try to run a rollercoaster ride, the train (composed of 8 carts) is separated in to parts and stopped when he try to climb the first grade. I tried to modify the track to view if it could be better with smoother lines but that made anything.
Thanks.

(Sorry for my English, I'm french)

**Comment by mg-1999** [comment]
Any screenshots and/or descriptions that you can provide? Like of the first
grade it crashes on.

Op zo 12 jul. 2015 00:42 schreef Maxi22700 <notifications@github.com>:
