### ISSUE TITLE
Server wont start due to this error with traincars

### ISSUE THREAD

**Issue by Skestle01** [bergerhealer/TrainCarts#152]
##### Spigot version: 1.8.8

<hr>

#### Expected behaviour: won't load?
https://pastebin.com/WHx1EyFR

**Comment by bergerkiller** [comment]
`0:00:43 AM [SEVERE] Ambiguous plugin name `BKCommonLib' for files `plugins\BKCommonLib-1.12-v4.jar' and `plugins\BKCommonLib (1).jar' in `plugins'`

You need to make sure only one of these is in your plugins folder. It might be loading a very old BKCommonLib plugin, or its corrupting the original installation.
