### ISSUE TITLE
Traincarts isn't working/can't even place minecarts

### ISSUE THREAD

**Issue by nils6941i** [bergerhealer/TrainCarts#155]
##### Spigot version: Build #60 

<hr>

#### Problem or bug:
I installed the newest build of BKCommonLib and Spigot but TrainCarts isn't affecting anything. I can't even place minecarts without using a dispender. 

I already tried to install different versions but it still doesn't work.
I am using the following plugins: Dynmap, WorldEdit, Waypoints, TreeAssist, SetSpawn, Easywarp, Vault, SaneEconomy, ProtocolLib, Citizens, Essentials, BKCommonLib, SignShop, Train_Carts.
Hope you are able to help me.
Thx Alot,
Nils

**Comment by bergerkiller** [comment]
I have pushed a new version of BKCommonLib that adds 1.12.1 support. There was also a bug in PermissionDefaults.yml that caused all permissions for using TrainCarts were revoked by default. Delete the PermissionDefaults.yml file (in the Train_Carts folder) after updating so it can be regenerated and this bug will be fixed.

https://www.spigotmc.org/resources/bkcommonlib.39590/update?update=180187
