### ISSUE TITLE
Switcher sign doesn't work correctly.

### ISSUE THREAD

**Issue by TMCThomas** [bergerhealer/TrainCarts#156]
##### Spigot version: 1.11.2-r0.1-SNAPSHOT

<hr>

#### Steps to reproduce: Please look at the video!

Greetings Thomas Mulder.

ps. If you need any further information than don't hesitate to ask a question!

**Comment by bergerkiller** [comment]
Can you check the current latest development build https://ci.mg-dev.eu/job/TrainCarts/77/

I did recently had to fix the switcher sign, and it may have completely fixed your problems. Switcher has to detect what rails to switch to, and in that mechanic bugs seem to pop up a lot. Bugfixes then result in new bugs...tedious stuff.

**Comment by TMCThomas** [comment]
I'll take a look at it, Thanks!

**Comment by TMCThomas** [comment]
It did indeed fix the switcher bug. Thanks!
(the speed thing still happens though, but I'm not sure if you had included that fix)

**Comment by bergerkiller** [comment]
I have commented on that, since it wasn't really a bug :)

**Comment by bergerkiller** [comment]
Fixed in the new release of TC.
