### ISSUE TITLE
Signs not triggering in other directions

### ISSUE THREAD

**Issue by TMCThomas** [bergerhealer/TrainCarts#157]
##### Spigot version: 1.11.2-r0.1-SNAPSHOT

<hr>

#### Steps to reproduce: Please take a look at this video: https://www.youtube.com/watch?v=PZEbGzlw0wg&feature=youtu.be and again don't mind the chat please it's a public server.

Greetings Thomas Mulder.

**Comment by bergerkiller** [comment]
If you want to trigger it in both directions, put the sign down like this:
![Sign example](http://i.imgur.com/XOf58S7.png)

The signs are purposely designed so they only trigger the sign facing the text, or when facing the side of the sign. If you want to trigger the train like that anyway, you can put trigger directions on the first line to override this behavior:
```
[+train:fb]
property
maxspeed
0.8
```
