### ISSUE TITLE
90 degrees turns stops minecart

### ISSUE THREAD

**Issue by JBTollak** [bergerhealer/TrainCarts#16]
Minecarts get stuck when encountering a 90 degrees turn section. Sometimes they just go backwards like they collide with something.
Even when there's no blocks surrounding the rails, it still acts the same.

![2015-07-23_14 28 28](https://cloud.githubusercontent.com/assets/13320946/8850354/b86fe420-3147-11e5-91b1-e8cc17b81148.png)
![2015-07-23_14 28 42](https://cloud.githubusercontent.com/assets/13320946/8850357/bce1a62e-3147-11e5-871a-fc8905aa1cda.png)

**Comment by rustyshakelford2** [comment]
I am also having this issue. Can you elaborate on why it wasn't fixed?

**Comment by mg-1999** [comment]
It cant be fixed, this is a bug that is added by the pathfinding code. And
it is something you need to live with.

Op do 10 dec. 2015 03:39 schreef rustyshakelford2 <notifications@github.com
>:

> I am also having this issue. Can you elaborate on why it wasn't fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/16#issuecomment-163467641>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg
