### ISSUE TITLE
Doesn't work with 1.11.2 Spigot

### ISSUE THREAD

**Issue by Etienne-Wattebled** [bergerhealer/TrainCarts#160]
##### Spigot version: 1.11.2-R0.1-SNAPSHOT

<hr>

#### Problem or bug:
The server doesn't want to start if TrainCarts is installer (Thread dump)
I tested a lot of versions of ProtocolLib and BkComonLib before open this issue.

#### Expected behaviour:
The server should start.

#### Steps to reproduce:
Just put ProtocolLib, Bk and Traincarts and start the server

**Comment by DanielMarkink** [comment]
You know that if your are running 1.11.2 as spigot you need an traincarts + bkcommonlib version for 1.11.2 And NOT for 1.12.1.

**Comment by bergerkiller** [comment]
Hmn, I couldn't reproduce this issue. I ran Spigot 1.11.2 with latest BKCommonLib downloaded from spigotmc resource page and latest TC, and updated protocollib to 4.3.0, but it all runs just fine. Can also login and it all works. If there is a thread dump, I'm going to need it.

**Comment by Etienne-Wattebled** [comment]
I can try again at the end of the day if you want and send you logs ?

**Comment by bergerkiller** [comment]
Please do, I need logs otherwise I can't help you with this I'm afraid.

**Comment by Etienne-Wattebled** [comment]
Re,

Logs are here: 
http://textup.fr/218671wD

Thanks

**Comment by bergerkiller** [comment]
Is it by chance possible you have millions of minecarts in one of your world? It appears to be stuck endlessly loading minecart entities.

**Comment by Etienne-Wattebled** [comment]
Hello,

I tried "/killall minecarts" before creating this issue, I h ad minecarts but now I have : 0

Thanks.

**Comment by Etienne-Wattebled** [comment]
It's ok, a member of my STAFF did a spawn but no destroy, I think it will be ok now.
I will tell you news.
