### ISSUE TITLE
Signs are not working on Mac

### ISSUE THREAD

**Issue by giacalone99** [bergerhealer/TrainCarts#162]
##### Spigot version: 1.12.1

<hr>

#### Problem or bug: 
Signs are not working (e.g. I try to make a station, and there is no confirmation of a station made and the train blows by the station. I try to make an announce sign, there is no confirmation of an announce sign made, and no announcement is made when the train passes over). I have used TrainCarts in the past, so I'm sure it's not a syntax error when I make the stations, etc. Also, I know that TrainCarts is loaded properly because I can create a train, vertical tracks work, etc. I have also tried to use the 'parseOldSigns' trick—the signs seem to be parsed (since '!train' is replaced with '[!train]') but they still do not work.

#### Expected behavior: 
Signs work as they should.

#### Steps to reproduce: 
Make a section of track, and try to make a station, etc. Nothing happens. (I am using a mac with the latest software)

**Comment by giacalone99** [comment]
I logged into my server on a different machine and I could make stations etc. So, the problem has to do with the my computer, a mac with macOS 10.12.6 (using a windows machine works fine).

**Comment by bergerkiller** [comment]
Have you tried using (!train) instead of [!train]? The latest versions I've added that functionality precisely because of this.

**Comment by mg-1999** [comment]
I do have a Mac. What do I need to test?

**Comment by giacalone99** [comment]
I have tried using (!train), [!train], and !train, all of which do not successfully create a station on my mac. It doesn't seem to be the keyboard since on both windows and mac the []() keys exist (I'm not sure if it makes a difference, but I am using a US layout keyboard).

**Comment by bergerkiller** [comment]
Then I really do not know. I guess the []() keys use some sort of weird unicode value that is not understood as the same character in Java. Or it's adding strange characters before or after the text as part of typing. @mg-1999 if you can test this out and perhaps resolve it, would be appreciated.

**Comment by mg-1999** [comment]
Bug verified and I am looking for a fix. If I check the characters with third party software they are exactly the same. Now looking into why Java is doing this.

**Comment by mg-1999** [comment]
Hey @giacalone99 

Can you please [test this build](https://www.dropbox.com/s/i84b7r03marm6s3/TrainCarts.jar?dl=1) of TrainCarts and place a traincarts sign like normal. And then provide us with the log.

Thank you very much!

**Comment by giacalone99** [comment]
@mg-1999 Here is the log. Let me know what else I can do!
[latest.log.zip](https://github.com/bergerhealer/TrainCarts/files/1301289/latest.log.zip)

**Comment by bergerkiller** [comment]
@giacalone99
Can you disable all trains momentarily (so it does not spam the same log line this often) and then place down the sign with the mac keyboard that was having issues? Also, what kind of sign are you building (second line). It might be of interest; what is the country you're in? This could also be a keyboard locale issue, where simple characters like 'i' use a different character code.

**Comment by giacalone99** [comment]
@bergerkiller Here is the new log without spam. I placed one sign that said:
`[train]
station
5
continue`
I don't know much about the private use characters—I have only seen them in web fonts with icons, and they certainly don't show up in Minecraft. It must be something with macOS, or possible my specific computer, though I'm not sure (I am using a US keyboard).
[latest.log.zip](https://github.com/bergerhealer/TrainCarts/files/1302794/latest.log.zip)

**Comment by bergerkiller** [comment]
I have added additional debugging and also a hotfix that removes the private use characters. Can you repeat what you did with this new version? https://puu.sh/xzuGC/4dd08602fe.jar

It prints out the character codes on all lines of the sign this time.

**Comment by giacalone99** [comment]
This time the sign worked and the station was made! Here is the log, but what you did seems to have fixed the bug.
[latest.log.zip](https://github.com/bergerhealer/TrainCarts/files/1302971/latest.log.zip)

**Comment by bergerkiller** [comment]
Ah nice! I spot a uf701 in the log this time. I was right to assume it would have more characters than uf702 causing this. I will commit this fix shortly today, the build you have now works fine so you can use it for the moment. The logging might be a bit spammy but will not interfere. I just have to write up a proper-proper fix that does not cause all signs to have these characters removed when placed, and only targets TrainCarts signs.

**Comment by bergerkiller** [comment]
Can you confirm this fixes your issues? https://ci.mg-dev.eu/job/TrainCarts/98/

**Comment by giacalone99** [comment]
Yes, it works!

**Comment by bergerkiller** [comment]
Alright, then I can close this issue. It'll be part of the next release :)
