### ISSUE TITLE
No speedup on powered power rail

### ISSUE THREAD

**Issue by DanielMarkink** [bergerhealer/TrainCarts#165]
##### Spigot version: CraftBukkit version git-Spigot-da42974-8/bk76d22c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

<hr>

#### Problem or bug:
The train will not speed up if it is under a powered power rail

#### Expected behaviour:

The train should be speed up tp the max speed limit but that is not happening.

#### Steps to reproduce:

Set everting up.
Let the train go over the powered rail.

#### Extra information:
The train is on a powered power rail.
The train is not on his max speed.
and at some point we will speed up but not when it is exspected. And then it from 0.05 to 0.6 and not go ever 2 tracks 0.05 faster.

**Comment by bergerkiller** [comment]
Is the train nearby or was just launched by a station sign? Station signs disable powered rail / other speedup behavior while launching from the station, and that could cause this.

**Comment by DanielMarkink** [comment]
Nope but i have try that and olso then is happend

**Comment by bergerkiller** [comment]
Was slowdown set to false? (/train info to check). Otherwise I'll need to know what server this is run on, because that sounds pretty broken for something so simple.

**Comment by DanielMarkink** [comment]
slowdown is true

**Comment by DanielMarkink** [comment]
becouse that add realisme

**Comment by DanielMarkink** [comment]
and what server data do you need?

**Comment by DanielMarkink** [comment]
then i can send you it

**Comment by bergerkiller** [comment]
Server log will do

**Comment by DanielMarkink** [comment]
Hier kunt de log bestanden van de afgelopen 3 dagen downloaden:
http://servers.danielstylegames.nl/data/logs.zip

**Comment by DanielMarkink** [comment]
But the train is on a train station sign.

**Comment by DanielMarkink** [comment]
when he hits the first powered rail but my setup is:

detector rail, power rail, detector rail, power rail, ect.
So the station sign should not the prolem

**Comment by bergerkiller** [comment]
It is possible that the detector rail activates the sign. Redstone power from the detector rail can activate the station sign that way, I think at least. Is this possible?

**Comment by DanielMarkink** [comment]
For launcers speed changer i use [!train] and the train max speed changes but the train does not speed up.
Only after a view tracks

**Comment by DanielMarkink** [comment]
and then he goes from 0.05 to 0.6

and not after 2 tracks +0.05 as set

**Comment by bergerkiller** [comment]
If redstone power interferes use [+train] instead of [!train]. ! inverts power, and if powered will disable the sign. [+train] is always powered.

**Comment by DanielMarkink** [comment]
becouse the new speed will not used directly.
And then the goes he from 0.05 to 0.6 and not after 2 tracks speed up by 0.05 as set with max speed

**Comment by DanielMarkink** [comment]
and if ! is used for inverting. Why is then the new speed set if i do /train info but not used in the current speed?

**Comment by DanielMarkink** [comment]
if he is on powered power rail

**Comment by bergerkiller** [comment]
The only explanation for powered rails not speeding up the train (past max speed) is very likely due to launching. It is a bug in a way, but upon launch it takes the max speed and speeds up the train to that point. But if max speed is changed during the launch, it does not update until the launch is over, because the launch is controlled. Adding another launcher sign past the max speed change would fix it.

I think it can be considered a bug that it does not refresh max speed during a launch. A little tricky to work around, though, but not impossible.

**Comment by DanielMarkink** [comment]
I do now not use the launch sign. But this is olso happen if i use the launch sign

**Comment by bergerkiller** [comment]
Well, without any launcher or station signs it should definitely speed up the train. What if you re-place the train? Maybe the train is just bugged out.

**Comment by DanielMarkink** [comment]
A’m now on work but i’m at home in about 5 hours. Then i will make a video on it so you can olso see what is happening and is not a bugged train becouse its new spawned

**Comment by bergerkiller** [comment]
Alright, good idea. It could very well be a bug but it's hard for me to see through text what the setup is :)

In 5 hours I'm home too so I could just join the server if you prefer.

**Comment by DanielMarkink** [comment]
Is good but you need to join but you will not can join becouse you will kicked.
Becouse i need to add you to the allow people but i can only add you if there is player data of you.
So you have to join but you can’t join. Beouce you will get kicked and the server is dutch.
+ What is you username?

**Comment by bergerkiller** [comment]
I'm dutch myself! 

Username is bergerkiller

**Comment by DanielMarkink** [comment]
Like it! Only we are not ollowed to speak dutch on github :(

**Comment by bergerkiller** [comment]
Well I don't mind it if people do, but it's better to keep it English because others might run into the same issues. If it's all in Dutch, it wouldn't help them,

**Comment by DanielMarkink** [comment]
But some info over join in dutch:

U moet de server joinen via: play.danielstylegames.nl maar u zal worden gekicked omdat u niet op de allow lijst staat maar ik kan u niet toevoegen omdat uw UUID niet bekent is bij de server.
Dus als u heeft gejoin laat het me even weten. Dan zal ik even zorgen dat de server in kan.

**Comment by DanielMarkink** [comment]
And that olso the reason why its now allowed to speak not english

**Comment by bergerkiller** [comment]
Luckily there is an online service for it. My player UUID is b22d2644aa324af28f62a5108f93eae6

**Comment by DanielMarkink** [comment]
So let me know when i have join so that i can add you to the allowed list.

**Comment by DanielMarkink** [comment]
I use i bungeecord plugin and i can’t add user data manual

**Comment by bergerkiller** [comment]
Alright, then I'll let you know once Ive joined for the first time

**Comment by DanielMarkink** [comment]
And do u have discord?

**Comment by DanielMarkink** [comment]
Then we can speak on the voice chat.
(Is a bit easyer to talk)

**Comment by DanielMarkink** [comment]
Or TeamSpeak

**Comment by bergerkiller** [comment]
Sorry no, I only use skype for voice chat stuff related to minecraft.

**Comment by DanielMarkink** [comment]
Skype is olso no problem. Can u send me your skype name?

I will be adding: “From GitHub - TrainCarts issue”
So that you can know that i’m that.

**Comment by DanielMarkink** [comment]
@bergerkiller it can be that i'm a bit later becouse i have to call olso microsoft for an other windows issue

**Comment by bergerkiller** [comment]
Skype name is MCBergerkiller

**Comment by DanielMarkink** [comment]
I will add and call you when i am done with microsoft. oke?

**Comment by bergerkiller** [comment]
Alright
