### ISSUE TITLE
New collision mode: "wait"

### ISSUE THREAD

**Issue by chrispbs** [bergerhealer/TrainCarts#167]
##### Spigot version: 1.12.1

<hr>

#### Problem or bug:

This is related to issue #166, but would be useful to have independently of that.

Unless I misunderstood the existing collision modes, there's currently no way to prevent two trains moving in the same direction from colliding if the front train stops (e.g., at a waiter). My lines are thousands of blocks long, and it's impractical for me (not to mention almost certainly inefficient for TrainCarts) to put waiters every 12 or so rails to prevent the second train from rear-ending the first. 

#### Expected behaviour:

It'd be useful to have a collision mode that works as follows:

1. Stop the train.
2. When the path ahead is clear by at least *n* blocks (perhaps this could be a configurable property), launch the train (ideally at the velocity the train was travelling at before step 1).

**Comment by bergerkiller** [comment]
What I'm planning to do is not to have it based on collisions, but based on a separate train property. You can set the distance ahead to check for trains and wait for that. This solves problems not only for you, but also for other servers dealing with multiple trains queued to be sent down the track. For rollercoasters and tour guides this kind of logic is much needed. Right now they solve it by placing down hundreds of 7-block waiter signs, which is inefficient and buggy.

**Comment by bergerkiller** [comment]
There is now a new property called wait distance you can set using property signs or commands. It'll be part of the next release which, I think will be tomorrow. https://puu.sh/xXj6R/44aeaa4de8.mp4

**Comment by chrispbs** [comment]
Excellent, thanks - I'll download build <i>#</i>142 tonight and report any problems I find (although from your demo it looks like it works perfectly).

**Comment by chrispbs** [comment]
Working as advertised with TrainCarts build <i>#</i>142 and BKCommonLib build <i>#</i>250. Thanks again!
