### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by grayhouser** [bergerhealer/TrainCarts#17]
I'm loving TrainCarts, but I have been having a major bug over the past few weeks. When I attempt to place a sign, such as a launcher, the plugin will not recognize it, as in, it will not show up in chat, or affect the coaster, even if it is powered by redstone! A fix would be fantastic.

**Comment by mg-1999** [comment]
Can you please provide more information? Like traincarts version, bkcommonlib versiona and spigot version. Also what do you put on your signs and what brand of computer you have?

**Comment by grayhouser** [comment]
Ok, TrainCarts: 1.75 SNAPSHOT
BKcomandLib: 
Version 1.65
SHA 35e633be203f2cdbbfaa6371029476463995d1a1
MD5 b8af52e5092a4d4cda827db617185ada
Spigot: 1.8.8
Signs:
[!train] or [train]
spawn
mm

I have a mac

**Comment by grayhouser** [comment]
I'm trying 1.66 SNAPSHOT to see if that works. Fingers Crossed

**Comment by mg-1999** [comment]
We have a problem with mac keyboards, add 'parseOldSigns: true' in the
config and stop using the brackets.

Hopefully this will fix it.

Op vr 31 jul. 2015 07:02 schreef grayhouser <notifications@github.com>:

**Comment by grayhouser** [comment]
I'll try that when I get up.
Thanks!






On Fri, Jul 31, 2015 at 2:51 AM -0700, "Matthijs" <notifications@github.com> wrote:










We have a problem with mac keyboards, add 'parseOldSigns: true' in the

config and stop using the brackets.



Hopefully this will fix it.



Op vr 31 jul. 2015 07:02 schreef grayhouser <notifications@github.com>:

**Comment by mg-1999** [comment]
Did it work?

**Comment by grayhouser** [comment]
I just got up, I'm trying it now!

**Comment by grayhouser** [comment]
It doesn't appear to be working.

**Comment by mg-1999** [comment]
Do you still use the brackets? It just needs to be:
    train
    spawn
    mm

Op vr 31 jul. 2015 22:54 schreef grayhouser <notifications@github.com>:

**Comment by grayhouser** [comment]
I don't it might be working now... let me see

**Comment by grayhouser** [comment]
Its not working.

**Comment by mg-1999** [comment]
It should just work.

**Comment by mg-1999** [comment]
Can you please send a copy of your config and a screenshot of the sign you
are using?

Op vr 31 jul. 2015 23:05 schreef grayhouser <notifications@github.com>:

**Comment by grayhouser** [comment]
When I get home I will! I'm with a friend who just had surgery.






On Fri, Jul 31, 2015 at 2:26 PM -0700, "Matthijs" <notifications@github.com> wrote:










Can you please send a copy of your config and a screenshot of the sign you

are using?



Op vr 31 jul. 2015 23:05 schreef grayhouser <notifications@github.com>:

**Comment by grayhouser** [comment]
#> This is the configuration file of TrainCarts
#> In here you can tweak TrainCarts to what you want
#> For more information, you can visit the following websites:
#> http://www.minecraftwiki.net/wiki/Bukkit/TrainCarts
#> http://forums.bukkit.org/threads/traincarts.29491/

# Parse signs made in Minecraft 1.7 and before without re-creating
parseOldSigns: true

# The distance between two normally-aligned (straight) carts in a train
normal:
  # The distance between two carts in a train
  cartDistance: 1.5
  # The factor at which this distance is kept
  cartDistanceForcer: 0.1

# Settings for turned (in curve) carts
turned:
  # The distance between two carts in a train
  cartDistance: 1.6
  # The factor at which this distance is kept
  cartDistanceForcer: 0.2

# The 'keep distance' factor to apply when carts are too close to each other
nearCartDistanceFactor: 1.2

# The maximum allowed cart distance, after this distance the carts break apart
maxCartDistance: 4.0

# Whether or not the combined carts (powered/storage minecarts) break up into two items
breakCombinedCarts: false

# A performance boost to give to powered minecarts (0 = normal speed)
poweredCartBoost: 0.1

# The boosting factor of powered rails (default = 0.06)
poweredRailBoost: 0.06

# The maximum velocity (blocks/tick) a minecart can possibly have set
maxVelocity: 5.0

# The multiplier used to slow down minecarts
# Normal is the default, slow is when the minecart is meant to slow down.
slowDownMultiplier:
  normal: 0.997
  slow: 0.96

# The maximum allowed ejection distance for eject signs
maxEjectDistance: 10.0

# The amount of velocity stations give when launching trains
launchForce: 10.0

# Settings used when carts collide with entities
collision:
  # If train owners are ignored
  ignoreOwners: false
  # If global train owners are ignored
  ignoreGlobalOwners: false
  # The amount of force at which minecarts push away others
  pushAwayForce: 0.2

# Whether or not all minecarts spawned on the server turn into TrainCarts' Minecarts
# Note that the TrainCart placement permission is then no longer active
allMinecartsAreTrainCarts: false

# Whether or not powered minecarts obtain their coal from attached storage minecarts
useCoalFromStorageCart: false

# Whether or not the player that places a minecart is set owner
setOwnerOnPlacement: true

# Whether or not a hissing sound is made when trains stop at a station
playSoundAtStation: true

# Whether or not chunks are only kept loaded when the train is moving
keepChunksLoadedOnlyWhenMoving: false

# Advanced: Whether trains use a different way of server->client synchronization
# With this enabled, trains are expected to move smoother with less bumping
# With this disabled, no smoothing is applied. Only disable it if it causes problems/incompatibility
useNetworkSynchronizer: true

# The maximum length a detector region (between two detectors) can be
maxDetectorLength: 2000

# The maximum amount of minecart items that can be stacked in one item
maxMinecartStackSize: 64

# The maximum radius chest/furnace sign systems look for the needed blocks
maxTransferRadius: 5

# The default radius chest/furnace sign systems look for the needed blocks
defaultTransferRadius: 2

# Whether or not empty minecarts slow down faster than occupied minecarts
slowDownEmptyCarts: false

# Whether storage minecarts get fuel when launching from stations
refillAtStations: true

# Whether minecarts are instantly destroyed by creative players
# Note that manual minecart movement is not possible for creative players with this enabled
instantCreativeDestroy: false

# Whether minecarts are allowed to have a 90-degree pitch angle when going up vertical rails
# When disabled, minecarts will keep a 0-degree pitch angle instead
allowVerticalPitch: true

# Whether players (with build permissions) can edit existing rails by right-clicking on them
allowRailEditing: true

# What velocity to set when a player tries to manually move a train (by damaging it)
manualMovementSpeed: 12.0

# The currency Ticket signs will display in messages, %value% represents the displayed value
currencyFormat: '%value% Dollars'

# The delay (in ticks) between ejecting and re-entering by collision (e.g. mobs auto-entering carts)
collisionReEnterDelay: 100

# A list of world names where TrainCarts should be disabled
# World names are not case-sensitive
disabledWorlds:
- DefaultWorld1
- DefaultWorld2

# The block materials that can be broken using minecarts
# Players with the admin block break permission can use any type
# Others have to use one from this list
allowedBlockBreakTypes:
- LOG
- CROPS

# Whether or not to show item animations when transferring items
showTransferAnimations: true

# Several shortcuts you can use on announce signs (text is replaced)
messageShortcuts:
  welcome: &eWelcome to &f

# Several shortcuts you can use on switcher and detector signs (text is replaced)
statementShortcuts:
  diamond: i@diamond

# Several shortcuts you can use on signs to set the items
itemShortcuts:
  fuel: ''
  heatable: ''
  armor: diamond_boots;diamond_helmet;gold_leggings;leather_helmet;leather_chestplate;gold_helmet;gold_chestplate;chainmail_chestplate;diamond_chestplate;leather_boots;diamond_leggings;chainmail_boots;chainmail_helmet;iron_leggings;iron_chestplate;gold_boots;chainmail_leggings;leather_leggings;iron_helmet;iron_boots
  sword: wood_sword;stone_sword;iron_sword;gold_sword;iron_sword;diamond_sword
  boots: leather_boots;iron_boots;gold_boots;diamond_boots;chainmail_boots
  leggins: leather_leggings;iron_leggings;gold_leggings;diamond_leggings;chainmail_leggings
  chestplate: leather_chestplate;iron_chestplate;gold_chestplate;diamond_chestplate;chainmail_chestplate
  helmet: leather_helmet;iron_helmet;gold_helmet;diamond_helmet;chainmail_helmet

**Comment by grayhouser** [comment]
<img width="1440" alt="screen shot 2015-07-31 at 11 18 29 pm" src="https://cloud.githubusercontent.com/assets/6820820/9020580/9f0f4dba-37da-11e5-8664-fef26d80d8e8.png">

**Comment by grayhouser** [comment]
That was before

**Comment by grayhouser** [comment]
This is it, after being placed.
<img width="1440" alt="screen shot 2015-07-31 at 11 18 35 pm" src="https://cloud.githubusercontent.com/assets/6820820/9020581/b270aade-37da-11e5-961c-c6cb6054c878.png">

**Comment by mg-1999** [comment]
Very strange, because it should recognise that sign now. Only problem is
that is doesnt :(

Op za 1 aug. 2015 06:20 schreef grayhouser <notifications@github.com>:

**Comment by grayhouser** [comment]
If you want to test what's going on I can get you my server IP and let you test it.
-Gray





On Sat, Aug 1, 2015 at 1:52 AM -0700, "Matthijs" <notifications@github.com> wrote:










Very strange, because it should recognise that sign now. Only problem is

that is doesnt :(



Op za 1 aug. 2015 06:20 schreef grayhouser <notifications@github.com>:

**Comment by mg-1999** [comment]
I would appreciate that, but I don't have the time now. Going to work soon,
maybe another time?

Op za 1 aug. 2015 11:57 schreef grayhouser <notifications@github.com>:

**Comment by grayhouser** [comment]
Absolutely, it's 5 AM and I'm about to go to bed. When you get off work shoot me an email.





On Sat, Aug 1, 2015 at 3:10 AM -0700, "Matthijs" <notifications@github.com> wrote:










I would appreciate that, but I don't have the time now. Going to work soon,

maybe another time?



Op za 1 aug. 2015 11:57 schreef grayhouser <notifications@github.com>:

**Comment by grayhouser** [comment]
I guess it's a github comment, I'm emailing...
-Gray






On Sat, Aug 1, 2015 at 3:10 AM -0700, "Matthijs" <notifications@github.com> wrote:










I would appreciate that, but I don't have the time now. Going to work soon,

maybe another time?



Op za 1 aug. 2015 11:57 schreef grayhouser <notifications@github.com>:

**Comment by mg-1999** [comment]
Will so, only for me its midday. Different timezones I guess.

**Comment by grayhouser** [comment]
If you want to come just reply.

**Comment by mg-1999** [comment]
I am now available to test with you.

Op zo 2 aug. 2015 04:05 schreef grayhouser <notifications@github.com>:

**Comment by grayhouser** [comment]
Here's the IP 162.244.166.91:62515

I'm online

**Comment by grayhouser** [comment]
Did you leave?

**Comment by bergerkiller** [comment]
I seriously doubt this issue still exists.
