### ISSUE TITLE
TrainCarts 1.8 [Drive a train manually with the keyboard]

### ISSUE THREAD

**Issue by EndermanLetsPlay** [bergerhealer/TrainCarts#170]
##### Spigot version: 1.8.8

<hr>

#### Problem or bug:

How I can I drive the train manually with the keyboard? It doesn't work, also when I put in in the config "allowmanualmovement". 

Please help me!

**Comment by bergerkiller** [comment]
I dont think this works anymore, I'll have to go about and fix that for next release. Added to the list...

**Comment by bergerkiller** [comment]
After a bunch of digging I found the code in nms that does this. I'll try and restore it to my best abilities.

```
        if (entity instanceof EntityLiving) {
            d6 = (double) ((EntityLiving) entity).bg;
            if (d6 > 0.0D) {
                d7 = -Math.sin((double) (entity.yaw * 0.017453292F));
                d8 = Math.cos((double) (entity.yaw * 0.017453292F));
                d9 = this.motX * this.motX + this.motZ * this.motZ;
                if (d9 < 0.01D) {
                    this.motX += d7 * 0.1D;
                    this.motZ += d8 * 0.1D;
                    flag1 = false;
                }
            }
        }
```

**Comment by bergerkiller** [comment]
I have fixed manual movement bugs in these development build versions:
https://ci.mg-dev.eu/job/BKCommonLib/245/
https://ci.mg-dev.eu/job/TrainCarts/132/

On 1.8/8 upside-down rail logic isnt correctly working yet. If you plan on using that or vertical rails, wait shortly for me to fix that as well. Otherwise strange passenger glitches may occur.

**Comment by EndermanLetsPlay** [comment]
Thank you!

2017-10-11 20:27 GMT+02:00 Irmo van den Berge <notifications@github.com>:

**Comment by EndermanLetsPlay** [comment]
Can you please send me the files for 1.8? (please not the link) 😬

2017-10-12 14:39 GMT+02:00 Giulio <giulio.niedermeyr@gmail.com>:

**Comment by bergerkiller** [comment]
The download link is on the pages. Mind you that I only support 1.8.8, not before that. If you need versions before 1.8.8 it would need (a lot of) extra work before it can happen and Id suggest updating the server instead.

https://ci.mg-dev.eu/job/BKCommonLib/250/artifact/target/BKCommonLib-1.12.2-v3-SNAPSHOT.jar
https://ci.mg-dev.eu/job/TrainCarts/140/artifact/target/TrainCarts-1.12.2-v1-SNAPSHOT.jar

**Comment by EndermanLetsPlay** [comment]
Thank you so much! Best Support!

2017-10-12 20:31 GMT+02:00 Irmo van den Berge <notifications@github.com>:
