### ISSUE TITLE
Stations : trains are not centered at speed 3.95

### ISSUE THREAD

**Issue by Evewins** [bergerhealer/TrainCarts#176]
##### Spigot version: 1.12.2

<hr>

#### Problem or bug: 
[http://hpics.li/3577ca6](url)
[http://hpics.li/0d107b6](url)
#### Expected behaviour: 
train centered

#### Steps to reproduce:
[+train]
property
speedlimit
3.95

**Comment by bergerkiller** [comment]
Pictures arent available but the bug is clear. I'm not very surprised this happens though. As a workaround you can put a speed limit sign (or multiple), or a launch sign, before the station to slow the train down to acceptable levels.

**Comment by Evewins** [comment]
Thanks for your fast reply. :)
I tried to do this, with a velocity of 0.2, it did not work. 0.1 and 1 neither. I « fixed » the problem by changing the sign with [+cart] instead of train and placing it to the front. But there is another problem : even with low velocities, when there are 2 ways separated by 3 blocks (like a subway) (with chunks kept loaded) it’s like the trains are laging at some points (while my ping is ok), sometimes they slow like if they would freeze, then sometimes they are at the right speed...
(Sorry about my english)

Le 17 nov. 2017 à 15:31, Irmo van den Berge <notifications@github.com<mailto:notifications@github.com>> a écrit :


Pictures arent available but the bug is clear. I'm not very surprised this happens though. As a workaround you can put a speed limit sign (or multiple), or a launch sign, before the station to slow the train down to acceptable levels.

**Comment by bergerkiller** [comment]
Interesting, can you do a TPS measurement with /timings on your server? I'm currently engaged with someone else having issues with TrainCarts where with only 20 or so trains the server is already bogged down. This, when my circle test track can handle 600 minecarts without even dipping below 20tps. Im suspecting it has to do with the "keep chunks loaded" property.

Do the trains 'lag' with you nearby, or only when you're far away?

You mentioning the 3-block wide subway kinda layout is interesting. I can't really reason why that sort of layout would influence the physics in any way, but I'll go and make some test tracks in this layout.

If you have a screenshot of this layout, and the station layout, I'd like to see it so I can accurately reproduce it on my server. Sometimes these bugs lie in the details...

**Comment by Evewins** [comment]
I changed everything about it, but I kept a save of it so I will soon do the TPS measurement if it can help. I sent a screenshot of the "old configuration". The stations signs were like this :


[+cart] //but same problem with [+train]

station 1

4

left

I noticed that those "lags" started to happen after the last release of Spigot, even with chunks loaded on true and few carts/trains. It seemed that it has nothing to do with the signs.
I tried to update BKCommonLib and TrainCarts with the last versions on your dev builds page (TrainCarts-1.12.2-v2-SNAPSHOT & BKCommonLib-1.12.2-v4-SNAPSHOT), and everything's fine now !
If you need anything else to help fixing, just ask. :)
Thank you for your awesome work, your plugin is really cool !



________________________________
De : Irmo van den Berge <notifications@github.com>
Envoyé : mercredi 22 novembre 2017 00:13
À : bergerhealer/TrainCarts
Cc : Evewins; Author
Objet : Re: [bergerhealer/TrainCarts] Stations : trains are not centered at speed 3.95 (#176)


Interesting, can you do a TPS measurement with /timings on your server? I'm currently engaged with someone else having issues with TrainCarts where with only 20 or so trains the server is already bogged down. This, when my circle test track can handle 600 minecarts without even dipping below 20tps. Im suspecting it has to do with the "keep chunks loaded" property.

Do the trains 'lag' with you nearby, or only when you're far away?

You mentioning the 3-block wide subway kinda layout is interesting. I can't really reason why that sort of layout would influence the physics in any way, but I'll go and make some test tracks in this layout.

If you have a screenshot of this layout, and the station layout, I'd like to see it so I can accurately reproduce it on my server. Sometimes these bugs lie in the details...

**Comment by bergerkiller** [comment]
Oh, well good to hear its been resolved already :) I can't tell which commit would have done it, as I've done a lot of rewrites and changes last month(s). If anything else pops up with these latest development builds, you can post an update in here. I'll close the issue ticket after a little while.

Timings are always appreciated. I'm currently trying to absolutely optimize TrainCarts, and there's still some room of improvement even after the last fix (caching rail information to minimize lookup times of rails)
