### ISSUE TITLE
Kicked by Verticle minecart

### ISSUE THREAD

**Issue by ImagineerFuzzy** [bergerhealer/TrainCarts#177]
##### Spigot version: 1.12.2-R0.1

<hr>

#### Problem or bug:
Getting Kicked when going up Ladders
Here is the kick message. IlleagleArgumentException : Team BoredTCRiders already exists in this scoreboard @ com.google.common.base.Preconditions:191
#### Expected behaviour:
Going up Smoothly
#### Steps to reproduce:
Just go up or down a ladder in a mincer, and it will kick you

**Comment by bergerkiller** [comment]
This is a bug on bungeecord. The latest development builds of TrainCarts and BKCommonlib fix it. Do note that there are some experimental things in there. For stability, use this build of Traincarts with the official build of BKCommonLib from spigot:

https://ci.mg-dev.eu/job/TrainCarts/146/

**Comment by ImagineerFuzzy** [comment]
Thank you so much!
