### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Fabkuist** [bergerhealer/TrainCarts#184]
##### Spigot version:

<hr>

#### Problem or bug:
Any public permissions? Is it possible to set different permissions for different ranks?
#### Expected behaviour:
permissions eg: - traincarts.speedlimit

**Comment by bergerkiller** [comment]
I like to believe that there are (PermissionDefaults.yml), but after so many years it got outdated/superseded a bit. The big problem is that there are so many ways to change properties: through signs, through applying defaults, through a spawner and through commands. Commands are handled well, and all these properties have permissions for those, but you can quite easily bypass it with a properties sign.

I'd say probably the best way is to revoke permissions for using the property sign and then tailor the command permissions based on rank.
