### ISSUE TITLE
Can puch trains

### ISSUE THREAD

**Issue by CooleCat** [bergerhealer/TrainCarts#185]
##### Spigot version:1.12.2

<hr>

**Comment by ApocalypsjeNL** [comment]
Did you type of on the sign? Because it is push

**Comment by bergerkiller** [comment]
proper format (what you use is legacy)
```
[+train]
property
playercollision
push
```

Does this work?

**Comment by CooleCat** [comment]
thanks,
i have put on the sign 
[!train]
property
push
false

**Comment by bergerkiller** [comment]
I dont think that will work then. Also 'push' doesnt mean players can push it, but that the train pushes players. If you dont want players to push the train, set push to true (pushplayers true) or use the collision modes I mentioned before. 'push' is too vague now.

**Comment by CooleCat** [comment]
Ik heb dus een grote fout gemaakt dus shrijf ik het maar in het nederlands ik snap dus niet hoe je kan instellen dat de speler het karretje niet kan vooruit duwen.

**Comment by bergerkiller** [comment]
Zet dit op een Minecraft Sign en plaats hem on de rails als sign post, dan weet ik zeker dat het werkt. Kan ook als een sign tegen een block aan, zoals hier: https://minecraft.gamepedia.com/File:TrainCarts_signs_intro_image.png

```
[+train:nesw]
property
playercollision
cancel
```

Zoals dit: https://puu.sh/yT0DJ/509d04b5e8.png

Mocht dit nog steeds niet werken, misschien was het inderdaad wel kapot op de spigot release versie van traincarts. Probeer dan de dev-builds:
https://ci.mg-dev.eu/job/BKCommonLib/
https://ci.mg-dev.eu/job/TrainCarts/
