### ISSUE TITLE
Plugins don't work after reload

### ISSUE THREAD

**Issue by JustBlobvis** [bergerhealer/TrainCarts#186]
##### Spigot version: 1.11.2

<hr>

**Comment by bergerkiller** [comment]
When you say "dont work" whats the error you are seeing? I dont use /reload by principle, since it messes up most plugins, but it should work last time I checked. I'll test later today to verify it on the latest development build.

**Comment by bergerkiller** [comment]
It seems fine on the latest development build when I test this right now, both with and without trains active. Can you check for yourself?

https://ci.mg-dev.eu/job/BKCommonLib/336/
https://ci.mg-dev.eu/job/TrainCarts/225/
