### ISSUE TITLE
Bug when teleport to a player while the train is moving

### ISSUE THREAD

**Issue by DJmaxZPL4Y** [bergerhealer/TrainCarts#187]
##### Spigot version: 1.12.2-R0.1

<hr>

#### Problem or bug:
When we teleport to a player in a train with item models, we see the player on the location at the moment we teleport to the player so for we he isn't in the train but for he, he is in it.

#### Expected behaviour:
See the players correctly in the train and not out of the train
#### Steps to reproduce:
Teleport to a player who is in a train with models and which are moving.

**Comment by bergerkiller** [comment]
Its sending the attach/mount packets before the passengers are spawned. Working on a fix.

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/TrainCarts/commit/badc26853407e8f46f1cbbc46eadb28c932839e1

https://ci.mg-dev.eu/job/TrainCarts/225/ can you verify this fixes the problem?

**Comment by DJmaxZPL4Y** [comment]
Yes the problem is fixed, thank you !

**Comment by bergerkiller** [comment]
Alright, then my fix is too simple I suppose. I'll need to listen for the spawn packets of the passengers and send mount packets only after that, but it takes some effort to figure that out.

**Comment by bergerkiller** [comment]
@DJmaxZPL4Y 
Can you see if this build fixes the issue completely?
https://ci.mg-dev.eu/job/TrainCarts/231/

**Comment by DJmaxZPL4Y** [comment]
We aren't in the train when we enter it. The others are seeing we in the train but we didn't see ourselves in the train.

**Comment by bergerkiller** [comment]
Oooooops. Forgot to mark the player itself as spawned! Slipped my mind there :s Dangers of committing things without testing right away, I guess.

Fixed:
https://ci.mg-dev.eu/job/TrainCarts/235/

**Comment by DJmaxZPL4Y** [comment]
Yes it's fixed when we teleport to a player I see him in the train properly. Thank you bergerkiller for the quickness !
