### ISSUE TITLE
Can't get the 32 durability on golden sword variants

### ISSUE THREAD

**Issue by DJmaxZPL4Y** [bergerhealer/TrainCarts#188]
##### Spigot version: 1.12.2-R0.1

<hr>

#### Problem or bug:
I can't choose a texture from golden sword with variants. I can't get the golden sword with a durability of  32 with the attachments map.

#### Expected behaviour:
Have the 32 durability to
#### Steps to reproduce:
Try to set the 32 durability with the tag unbreakable of a golden sword variant with the attachments system

**Comment by bergerkiller** [comment]
I kinda need the resource pack / model to be able to test this. Have you tried changing the 'limb' the model is displayed at/in in the position menu? It has head/left_hand/right_hand/chest/legs/feet.

**Comment by DJmaxZPL4Y** [comment]
I think it's a problem with the displaying in the ui map from attachments because when I set manually the durability to 32 in the savedTrainProperties file it works, so the map display only 31 textures and not the 32nd texture. And we didn't see the custom models in the attachments menu we see only the golden sword

**Comment by bergerkiller** [comment]
Oh, but does it apply the 32th texture correctly to the entity itself? You can see the model there, just not in the attachment editor preview?

**Comment by DJmaxZPL4Y** [comment]
No we can't select the 32th texture, it's missing in the attachment edit. To put the 32th texture of a golden sword I have to set the durability to 32 in the file of the savedTrains

**Comment by bergerkiller** [comment]
This should take care of it: https://github.com/bergerhealer/TrainCarts/commit/363776f7ebbc653a5973260a62e95b88dd2699d1
https://ci.mg-dev.eu/job/TrainCarts/227/

I will add one more thing, which is a means to set an item from an item in your inventory. I'm sure more edge cases like these will pop up in the future.

**Comment by DJmaxZPL4Y** [comment]
Yes thank you now i can choose the last texture. Just to notice, I have some debug line now from bkcommonlib.
[debug bkcommonlib.txt](https://github.com/bergerhealer/TrainCarts/files/1609032/debug.bkcommonlib.txt)

**Comment by bergerkiller** [comment]
Yeah those happen. Its nothing serious, there are some items it cannot render because it lacks the 3d model to do so. Chests and such use a builtin renderer.

**Comment by bergerkiller** [comment]
Alright a couple fixes:
- Now displays the current durability number when it matters in the variant selector
- Switches between variant items faster the longer you press. Don't want to spend minutes for durability 1342...
- Allows setting the displayed item by dropping an item from your inventory while in the menu

https://ci.mg-dev.eu/job/BKCommonLib/339/
https://ci.mg-dev.eu/job/TrainCarts/228/
