### ISSUE TITLE
Enhancement on flip

### ISSUE THREAD

**Issue by DJmaxZPL4Y** [bergerhealer/TrainCarts#189]
Hello the TrainCart Team,

I would know if it's possible to add a degree argument on the flip panel in order to control the flip and so if we set a panel : 
[+cart]
flip
90

it rotates the cart of 90 degrees.

**Comment by bergerkiller** [comment]
Not at the moment, no. Only two orientations on the rails are allowed (wheels track along the rails). What you want isn't really something for the flip sign, more so rotating the model itself relative to the base node. This is something that is going to be added in a future version, which allows animations to be executed for attachment models.

**Comment by DJmaxZPL4Y** [comment]
Yes it's that I want, to rotate the model so no problem take your time, when I would have time I am going to do some pull requests in order to help for the plugin.
