### ISSUE TITLE
Rails in player's hand will disappear when putting upside-down rails in survival mode

### ISSUE THREAD

**Issue by tommycs127** [bergerhealer/TrainCarts#190]
##### Spigot version: 1.12

<hr>

#### Problem or bug:
My friends told me that when they put upside-down rails in survival mode, rails in their hand will disappear, no matter how many rails they are holding.

#### Expected behaviour:
Number of the rail in hand should deduct one only when putting one upside-down rail, just like putting rails on the floor.

#### Steps to reproduce:
By putting upside-down rails in survival mode.

**Comment by bergerkiller** [comment]
I usually only test in creative mode, so this bug seems likely. Should be a quick fix, I'll look into it after work.

**Comment by bergerkiller** [comment]
This bug may actually be even worse if what I think is true. I cant test it now, but I think it is taking the item in the off-hand slot and subtracting from that, putting the result in the main hand. This would open up some nasty duping logic by placing down an upside-down rails holding a stack of diamonds in the other.

This should hopefully fix it:
https://ci.mg-dev.eu/job/TrainCarts/232/
