### ISSUE TITLE
Player passenger doesn't sit properly

### ISSUE THREAD

**Issue by DJmaxZPL4Y** [bergerhealer/TrainCarts#191]
##### Spigot version: 1.12.2-R0.1

<hr>

#### Problem or bug:
The body of the player when he is on a seat isn't in the right direction. I think it's because the chicken below the player faces all the time toward the south. [Here you can see that the player looks straightforward but not the body ](http://image.noelshack.com/fichiers/2018/02/3/1515614394-2018-01-10-20-54-37.png)

#### Expected behaviour:
The chicken has to respect the y-axis rotation of the cart.

#### Steps to reproduce:
Have a model with seats and see a player on a seat on a circuit.

**Comment by bergerkiller** [comment]
Because it was difficult/glitchy to lock the player's model in a given direction in first person, I did not yet add any sort of orientation locking for players in a seat. It is definitely on my todo list for next release though, so this issue ticket is valid.

**Comment by DJmaxZPL4Y** [comment]
yes for our server it's a problem at most in third person, in first person it isn't so important.

**Comment by bergerkiller** [comment]
I will add a mode of locking before the next release, I can see its quite important and its not very difficult to add. :)

**Comment by bergerkiller** [comment]
Now I remember why it was delayed. Clients dont do what theyre told when you send rotation information packets. It can take a little while to get these workarounds...working.

**Comment by bergerkiller** [comment]
Should be fixed with the above and other fixes in the release
