### ISSUE TITLE
Attachments tutorial?

### ISSUE THREAD

**Issue by ApocalypsjeNL** [bergerhealer/TrainCarts#192]
### Maybe this is not a real "bug", but it could be helpful for people.

Hey, I found some quite interesting images about the new "model" / attachments system. But is there a place where I can find some of the basics of how to test it myself? I'm quite interested how it looks in my own server.

Kind Regards,
ApocalypsjeNL

**Comment by bergerkiller** [comment]
I plan on making a demo video on how to use it just like I did for maplands when the next release rolls out :)

For now, all you need to know is /train attachments - thats how you get the map UI to control everything.

**Comment by ApocalypsjeNL** [comment]
Thanks for your reaction, I'll test the command so far it's done and I'm looking forward for the demo video 😀
