### ISSUE TITLE
Attachment rotation is incorrect

### ISSUE THREAD

**Issue by ApocalypsjeNL** [bergerhealer/TrainCarts#193]
##### Spigot version: 1.12.2

I found out that the orientation of the main entity and all attachments are incorrect. [As shown on the screenshot](https://cdn.apocalypsje.ga/screenshots/2018-01-11_15.50.24.png) all entities are facing south. I don't know what causes this bug, but maybe it's an idea to set the orientation of all entities for that minecart to the direction where the track goes? Like with the default minecarts. I don't know if this is possible but that would look a lot more neutral.

Kind regards,
ApocalypsjeNL

**Comment by bergerkiller** [comment]
> but maybe it's an idea to set the orientation of all entities for that minecart to the direction where the track goes?
It already does this. The only orientation which is not controlled right now is the orientation of the passenger of seats. For sure the orientation of item attachments are correct, but it might be broken for entity attachments because of their slightly differing network sync.

**Comment by ApocalypsjeNL** [comment]
Ah, maybe this is then something for on the todo list?

**Comment by bergerkiller** [comment]
Probably :)

There is also this issue ticket: https://github.com/bergerhealer/TrainCarts/issues/191

**Comment by ApocalypsjeNL** [comment]
I did some more testing, and ot looks like some times it doesn't rotate at all.

**Comment by bergerkiller** [comment]
> Now I remember why it was delayed. Clients dont do what theyre told when you send rotation information packets. It can take a little while to get these workarounds...working.

Minecraft is awful. As a passenger it wasnt even implemented yet for this reason.
