### ISSUE TITLE
Damage Value problem

### ISSUE THREAD

**Issue by RuudSchutten** [bergerhealer/TrainCarts#194]
BkCommonLib version: Dev-343
TrainCarts version: Dev-235
Spigot version: 1.12.2
-----------------------------------
Best Bergerhealer,

Problem or bug: The damage value doesn't work.
diamond_sword.json file: https://pastebin.com/8mV9Zi5T
What should I improve?

Kind Regards,
Ruud Schutten

**Comment by bergerkiller** [comment]
Change "damaged": 1 to "damaged": 0. Or otherwise, you can with the latest version get an instance of your item the normal way, when open the map and drop the item from your inventory (while holding the map and in the menu to edit the item attachment's item)

**Comment by RuudSchutten** [comment]
Thanks! When will banking be ready? I love testing.

Kind Regards,
Ruud Schutten

**Comment by RuudSchutten** [comment]
What should I put on a sign?

**Comment by bergerkiller** [comment]
[+train]
property
banking
10

or 
[+train]
property
banking
10 5

for 5 smoothness. Try some values out and see what works best for your track

**Comment by RuudSchutten** [comment]
Thank You! What features are coming to?

Kind Regards,
Ruud Schutten

**Comment by bergerkiller** [comment]
Im currently working on locking the passenger's pose in the carts so it is following along, so feet face the right way. Tricky is to allow the head to still rotate based on player input without ruining the body pose.

I also need to slightly patch up the attachment editor's positioning window to add labels / maybe make it easier to position objects.

**Comment by RuudSchutten** [comment]
Have you discord or skype? Just for this kind of questions?

Kind Regards,
Ruud Schutten

**Comment by bergerkiller** [comment]
Im Bergerkiller (Irmo van den Berge) on skype ( mcbergerkiller )
