### ISSUE TITLE
Lead cannot be tied from minecart horse attachment to fence

### ISSUE THREAD

**Issue by bc-hill** [bergerhealer/TrainCarts#198]
#### Spigot version: 1.12.2

<hr>

#### Problem or bug:
Horse attached to a minecart can have a lead tied to it, but player cannot tie other end of lead to fence.

#### Expected behaviour:
Ability to tie off train horse as if it were a horse.

#### Steps to reproduce:
Create minecart, add attachment,
Change attachment to horse entity,
Tie lead to horse,
Attempt to tie lead to fence.

**Comment by bergerkiller** [comment]
Attachments aren't actual entities, so I don't see how this is ever supposed to work?

**Comment by bc-hill** [comment]
Yes, that makes sense of course.  The only reason I brought it up, is because I can attach the first half of the lead.
Thank you.

**Comment by bergerkiller** [comment]
Alright. To the client they are actual entities so that's probably why they can still interact with it that way. But on the server end, there is nothing handling their logic :)
