### ISSUE TITLE
Ladders do not work

### ISSUE THREAD

**Issue by DoraKlikOpDora** [bergerhealer/TrainCarts#2]
Ladders as rails does not work. The carts can go up the ladder, but don't go further on the actual rails.

**Comment by mg-1999** [comment]
How to reproduce? Or a picture of you're testing setup? Will look into it when I have this.

**Comment by DoraKlikOpDora** [comment]
https://snapr.pw/i/4c007b0a12.png

**Comment by mg-1999** [comment]
Thank you. I was able to reproduced the bug and I'm looking into it now.
