### ISSUE TITLE
Train derail in a bend

### ISSUE THREAD

**Issue by MrPufferFish** [bergerhealer/TrainCarts#20]
Sometimes a train derails at a high maxspeed. Most of the times it's in a bend which can be seen on the picture below. The train has a maxspeed of 2.0. In the 1.7 version it doesn't derail.

![image](https://cloud.githubusercontent.com/assets/12172140/9666497/aaaa5e92-5276-11e5-8cc2-b363bf5107c2.png)

**Comment by mg-1999** [comment]
How to reproduce?

**Comment by MrPufferFish** [comment]
Build a bend as shown on the picture, set slowdown false and maxspeed at 2.0. Sometimes it does work so it doesn't derail. But sometimes it does derail with this setup.

**Comment by mg-1999** [comment]
Change some properties in the config, this isnt a real bug. Just the standard config is messed up.

**Comment by MrPufferFish** [comment]
Wich option must get changed for this?

**Comment by MrPufferFish** [comment]
Just restored the config from 1.7.10 and it still happens.

**Comment by mg-1999** [comment]
There is no change in the config from the other versions, the problem is that the 1.8 train mechanics changed only I lost the file that has the changes. Will go search for it.

**Comment by MrPufferFish** [comment]
So there's a bugg in TrainCarts?

**Comment by mg-1999** [comment]
No, only some values have to be changed in the config to match 1.8 minecarts.

**Comment by MrPufferFish** [comment]
And you only need to find these values back?

**Comment by mg-1999** [comment]
Yes, had them somewhere on a notation pad,

**Comment by MrPufferFish** [comment]
Ok, when do you think that you have these changes so I can test these?

**Comment by MrPufferFish** [comment]
Any progress?

**Comment by MrPufferFish** [comment]
Still waiting for you to find a YML file?

**Comment by RyanHecht** [comment]
Yeah, I've noticed this as well, it broke a few rides on my server. Is this something we can fix config-side, or does it require an update to the plugin? If it is config side, what must be changed? Thanks :)

**Comment by mg-1999** [comment]
it is config side, and you need to change the distance between de individual carts to something like 0.4 or 1.0

**Comment by MrPufferFish** [comment]
Changed normal.cartDistance to 1.0 and 0.4, tested both. Still the same problem of breaking trains.

**Comment by mg-1999** [comment]
You need to change the turned.cartDistanceForcer to some value between 0.4 and 1.0. It should work then.

**Comment by MrPufferFish** [comment]
Didn't work either.

**Comment by MrPufferFish** [comment]
At a maxspeed of 0.8 the train breaks. With a maxspeed of 0.7 it didn't happend.

**Comment by mg-1999** [comment]
I found out that most of the bug came from 1.8 minecart behaviour itself. And there is not much that I can do about, because the values are different for each ride. The best solutions is to just thinker with it and find out what's working en what's not.
