### ISSUE TITLE
Is a more realistic cart model possible? 

### ISSUE THREAD

**Issue by TomWeasley** [bergerhealer/TrainCarts#201]
<hr>
As traincarts can customize cart models now, but the current version of traincarts can only customize models with the same size as a normal mine cart, is it possible to make the cart models longer like real carts? Maybe we can summon two invisible minecarts and keep their distance and then create a new entity in the middle of them which looks like a real cart.

**Comment by bergerkiller** [comment]
Yes. The attachment editor has a menu (second column top row) where you can specify the length and wheel distance of the cart. By changing this length you can make carts closer or farther apart.
