### ISSUE TITLE
Hopper Crash

### ISSUE THREAD

**Issue by Tigerhoernchen** [bergerhealer/TrainCarts#204]
##### Spigot version: spigot 1.8.8

<hr>

#### Problem or bug:
If a storagecart gets under a hopper, the Server crash.
#### Steps to reproduce:
![2018-02-10_22 52 23](https://user-images.githubusercontent.com/36344030/36067025-73cf6e82-0eb5-11e8-9e1d-8274883567a6.png)

**Comment by bergerkiller** [comment]
No issues here when I test it, but I did fix a bug impacting 1.8.8 in some ways. You can try and see if this version of BKCommonLib fixes anything https://ci.mg-dev.eu/job/BKCommonLib/355/

If not, do you have any server logs of the crash like a stack trace where its frozen?

**Comment by Tigerhoernchen** [comment]
I tried a little bit and I found out something new, that I had forgotten...
[Link to Video](https://youtu.be/m2nBjpDoYDI)

**Comment by Tigerhoernchen** [comment]
Console: https://pastebin.com/iseU4P2v
Error Log: https://pastebin.com/PQgw54up

**Comment by bergerkiller** [comment]
What I think is happening is that there is a clash between >1.8.8 'empty' (air) items and <= 1.8.8 empty air items. For sure its leaving behind an itemstack in the chest minecart with a null type, causing an error when it goes by the hopper. I will look into this tomorrow, the fix is probably in BKCommonLib though.

**Comment by bergerkiller** [comment]
Reproduced it easily and am now going to fix it.

**Comment by bergerkiller** [comment]
can you verify this version fixes the problems? https://ci.mg-dev.eu/job/BKCommonLib/356/

**Comment by Tigerhoernchen** [comment]
It works, thanks!
