### ISSUE TITLE
Spawn not working... (Fixed)

### ISSUE THREAD

**Issue by TheGameBoyz** [bergerhealer/TrainCarts#205]
##### Spigot version:Craftbukkit actually... (Version 1.12.2)

<hr>

#### Steps to reproduce: I just placed a sign 
[train]
spawn
green

and it didnt spawn anything. I decided to make another thing, also wouldn't spawn (It worked before

**Comment by TheGameBoyz** [comment]
did nothing :/

**Comment by TheGameBoyz** [comment]
Installed Spigiot: Did nothing.

**Comment by TheGameBoyz** [comment]
Re-installed traincarts: Also did nothing...

**Comment by bergerkiller** [comment]
Does the 'green' train even still exist? (SavedTrainProperties.yml). Also the sign must be powered by redstone for it to spawn (once).

**Comment by TheGameBoyz** [comment]
It does exist, is powered by redstone.

Here's the green config bdw

reen:
  allowPlayerTake: false
  collisionDamage: 1.0
  tickets: []
  collision:
    passive: DEFAULT
    neutral: DEFAULT
    hostile: DEFAULT
    tameable: DEFAULT
    utility: DEFAULT
    boss: DEFAULT
    misc: PUSH
  carts:
    '1':
      model:
        type: ITEM
        entityType: MINECART
        attachments:
          '1':
            type: SEAT
            lockRotation: false
        physical:
          cartLength: 0.98
          wheelCenter: 0.0
          wheelDistance: 0.0
        item:
          ==: org.bukkit.inventory.ItemStack
          type: CACTUS
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            Unbreakable: true
        lockRotation: false
      entityType: MINECART
      flipped: true

**Comment by TheGameBoyz** [comment]
![image](https://user-images.githubusercontent.com/29814452/36075797-063ef55a-0f54-11e8-84bc-4a8e360fc8dd.png)

**Comment by TheGameBoyz** [comment]
I just realised i should probably say what plugins i have.

Bannerletters
BKCommonLib
BungeeSuiteWarps
Chairstairs
Citizens
Color_sings_text
Essentials
Essentials chat
Essentials warp GUI
Holographic displays
iDisguise
MCPainter
noDamage
Permissions EX
Train Carts 1.12.2-v2
Viaversion
Worldedit

**Comment by bergerkiller** [comment]
The redstone block is continuously powering the sign. It causes a lack of a spawn trigger. Try repositioning the sign or removing the constant source of redstone power?

**Comment by TheGameBoyz** [comment]
Hey! I moved it under the track, it worked! Thanks!
