### ISSUE TITLE
Can't open chest in minecart since 1.12.2-v2

### ISSUE THREAD

**Issue by Hunnert** [bergerhealer/TrainCarts#207]
##### BkCommonLib version: 
1.12.2-v4
##### TrainCarts version: 
1.12.2-v2 (Also tested with 1.12.2-v3-SNAPSHOT)
##### Spigot version: 
Latest (git-Spigot-4bd94dc-bacaf92)

<hr>

#### Problem or bug: 
Chests in minecarts cannot be accessed with right click on latest version of traincarts. Works as expected on version 1.12.2-v1.

#### Expected behaviour: 
Contents of the chest should be opened and available for interaction. 

#### Steps to reproduce:
Create minecart with chest. Place cart with chest. Try to open chest with right click.

**Comment by bergerkiller** [comment]
Yeah I fixed this in the dev builds. Im working out a different bug with someone until I can release it, but you can get it earlier here:

https://ci.mg-dev.eu/job/BKCommonLib/
https://ci.mg-dev.eu/job/TrainCarts/

**Comment by Hunnert** [comment]
It is indeed fixed. You are doing a fantastic job with this mod!
