### ISSUE TITLE
Custom attachment / physical property minecarts not linking other minecarts

### ISSUE THREAD

**Issue by ThisTNTSquid** [bergerhealer/TrainCarts#211]
##### Spigot version: 1.12.2

<hr>

#### Problem or bug: 
Spawned custom saved minecarts not linking up to each other to form a train 

#### Expected behaviour: 
minecarts with custom attachment should link with other carts to form a train

#### Steps to reproduce:
1. Modify the attachments / physical prooerty of a minecart by using attachment editor obtined with `/train attachments`
2. Save the cart with `/train save custom`
3. Spawn multiple saved cart with spawner sign 
```
[train]
spawn
custom
```
4. attempt to link them up by pushing one to the other
5. They bounce away instead of linking up

**Comment by bergerkiller** [comment]
Dont know if you managed to resolve it, but my suggestion is to check whether the train collision property is set on link or something else. You set it using /train collision train link. These properties are also stored when saving a train.

**Comment by ThisTNTSquid** [comment]
Oh, i will try that out later on

**Comment by ThisTNTSquid** [comment]
Trains with custom property and attachments are now linking together as of latest development builds
