### ISSUE TITLE
not allowing multiple entities in the cart

### ISSUE THREAD

**Issue by alexvermaning0** [bergerhealer/TrainCarts#212]
BkCommonLib version: 1.12.2-v4
TrainCarts version: 1.12.2-v2
 Spigot version: 1.12.2

<hr>

Problem or bug:
the train doesent let more than 1 player in when it has more than 1 seats
Expected behaviour:
that the seats work
Steps to reproduce:
https://www.youtube.com/watch?v=7o0lH7Ewf14

**Comment by melerpe** [comment]
How many seats have you added? show the map gui!

**Comment by alexvermaning0** [comment]
you can look at the video i showed the map

**Comment by alexvermaning0** [comment]
ive got it fixed the tutorial on the traincarts website is incorrect

**Comment by alexvermaning0** [comment]
it doesent work again :/ the new mewthode and with the old one
video with map gui 
https://www.youtube.com/watch?v=sQ24DC4SPVY&feature=youtu.be

**Comment by ThisTNTSquid** [comment]
this is weird tho, the same thing doesn't happen on my server, maybe try joining here https://discord.gg/P34bUPT for a better and more direct conversation if  you have a discord account , since i notive this issue has been on hear nearly half a month and still not getting any reply

**Comment by bergerkiller** [comment]
Is this still happening? Sorry about the belated reply, Im happy others replied. I took a short hiatus while I was heavily loaded by work.

Im not sure if the problem is the seats themselves or interacting with the cart to enter it. You can try the dev-builds to see if anything has changed since last release.
https://ci.mg-dev.eu/job/BKCommonLib/
https://ci.mg-dev.eu/job/TrainCarts/

**Comment by bergerkiller** [comment]
Problem here is that MC 1.8.8 has zero support for more than one passenger per entity. I don't think there really is a way to get around this issue on that version of MC...

**Comment by thedejavunl** [comment]
Thank you for your reply @bergerkiller, it is time for us now to move on to the latest version.

**Comment by alexvermaning0** [comment]
i got it fixed by updating spigot from and old spigot 1.12.2 to the latest 1.12.2 (i havent posted because i stoped using traincarts) (dident update the plugins btw)
