### ISSUE TITLE
Summoned minecarts not linking

### ISSUE THREAD

**Issue by PeterAS17** [bergerhealer/TrainCarts#215]
##### Spigot version: 1.12.2 git-Spigot-c3093ef-7e94e65

<hr>

#### Problem or bug:
Minecarts spawned with the summon command are not capable of linking when pushed together.

#### Expected behaviour:
Summoned minecarts should link to provide a wider choice of customisation, such as blocks on top of them, display text, etc.

#### Steps to reproduce:
- Spawn two carts with /summon minecart
- Try to push them together

**Comment by ThisTNTSquid** [comment]
does the minecart you manually place down link up?

**Comment by PeterAS17** [comment]
Yes, they do link

**Comment by ThisTNTSquid** [comment]
but what is the purpose of using summon instead of placing them down?

**Comment by PeterAS17** [comment]
Customization. I was trying to show a custom name, with custom blocks rotated inside. Things that this plugin does not yet support. If I were to use simple minecarts, of course I'd place them down normally, not take the longest way

**Comment by ThisTNTSquid** [comment]
Try using the traincart built in spawner sign https://minecraft.gamepedia.com/Custom_servers/Bukkit/TrainCarts/Signs/Spawner , and then use `entitydata` to alter the nbt of the minecart, and see if it works

**Comment by ThisTNTSquid** [comment]
btw, if you have a discord account, you can join the official Traincarts / BKCommonLib discord server here for a more interactive and direct support https://discord.gg/P34bUPT

**Comment by PeterAS17** [comment]
Will try when I got a bit of time. I already joined the discord group, asked, and nobody answered for hours, so I just quit and filled an issue here instead
