### ISSUE TITLE
TrainCarts Sign & Attachment Issues

### ISSUE THREAD

**Issue by Holdensaurus** [bergerhealer/TrainCarts#218]
##### Spigot version: 1.12.2

<hr>

**Comment by bbayu123** [comment]
Can you provide screenshots or videos to show exactly what setup you have?

**Comment by ThisTNTSquid** [comment]
Is your setup consist of a spawner sign which spawns the train, and then a station sign ahead with a set delay time? If not, would you mind providing screenshot as @bbayu123 said and **exact text written on the signs** ?

**Comment by bbayu123** [comment]
Is this issue resolved yet?
