### ISSUE TITLE
players can't enter a train before they press the use key anywhere

### ISSUE THREAD

**Issue by donbubu** [bergerhealer/TrainCarts#22]
Nobody can enter a train before he presses the "USE" key anywhere in the world. After the player press the "USE" key on something, a block like stone, he can enter and leave the carts.

Spigot: 1.8.8 R0.1
Traincarts: 1.75
Tested with :
- BKC: 1.65
- BKC: 1.66 SNAPSHOT

And tested without any other plugins (only traincarts and bkcommonlib)

**Comment by mg-1999** [comment]
What is you BKCommonLib version?

**Comment by donbubu** [comment]
tested with :
BKCommonLib V.: 1.65
BKCommonLib V.: 1.66 SNAPSHOT

**Comment by mg-1999** [comment]
Does this also happen when TrainCarts is not installed?

**Comment by donbubu** [comment]
No, without traincarts the lores working normally.

**Comment by RyanHecht** [comment]
Yep, I've reproduced this as well

**Comment by timmaker** [comment]
I think this was in the the 1.7.10 version of traincarts too

**Comment by bergerkiller** [comment]
Very old bug but its actually fixed for some time now. Had to do with a click-timeout measure in TC to prevent entering minecarts while clicking on blocks to put down tracks / spawn minecarts. Incorrect initialization of the timeout timestamp was to blame. Its fixed.
