### ISSUE TITLE
Locking trains to prevent enter/exit while in motion?

### ISSUE THREAD

**Issue by ResqDiver1317** [bergerhealer/TrainCarts#222]
1.12.2-v4 BkCommonLib version:
1.12.2-v2 TrainCarts version:
1.12.2-R0.1-SNAPSHOT Spigot version:

<hr>

I was wondering if there is a way to "lock" the carts/trains so players cannot enter/exit them unless at a station. We tried a rollercoaster plugin a few days ago that allowed us to put signs under the track as it would leave the station that would lock them and then another sign as it entered the station that would unlock them. Unfortunately, that coaster plugin you HAD to use a texture pack with and we are setting up a server for kids to play on so I did not want to make that mandatory. So far, from trying out TrainCarts, I am really enjoying it now that I am starting to figure it out more. 

The only big concern I have at the moment is that I'd like to be able to lock the trains. I'm setting up a minigames world and in this world is also a funland with coasters to ride on and such, and I have added a train to go from the minigames hub out to the funland but I don't want kids to be able to jump off the trains in the middle of the trip there (the whole trip is only about 30 seconds so it's not like they are in the trains for a long time. I would also like to be able to prevent them from jumping out of the carts on the roller coasters as well. 

Please let me know if this is possible and keep up the great work!

**Comment by bbayu123** [comment]
![image](https://user-images.githubusercontent.com/26726381/41922081-e54ecbf6-7996-11e8-9037-ad49bdbb6429.png)

**Comment by ResqDiver1317** [comment]
yep, that is what I was looking for and I totally missed that! I was thinking this was too great of a plugin to not have that in it, I must have been in too big of an excited hurry trying to get it all figured out that I completely overlooked that.
