### ISSUE TITLE
Wiki Link issue

### ISSUE THREAD

**Issue by ResqDiver1317** [bergerhealer/TrainCarts#223]
The link to the wiki that is on the Spigot page that takes you to minecraft.gamepedia.com doesn't work. 

Right now it points to 
http://www.minecraftwiki.net/wiki/Bukkit/TrainCarts
It needs to point to 
https://minecraft.gamepedia.com/Custom_servers/Bukkit/TrainCarts

I spent last night and this morning trying to figure out the details for the different signs. I went through the wiki that is here on the GitHub but the sign links do not take you to more information as indicated. I managed to accidentally find the correct link to the wiki on the gamepedia a little while ago and it is a huge help.

**Comment by bbayu123** [comment]
Will change within 72 hours, thanks for your report.

**Comment by bergerkiller** [comment]
Fixed the link on the page :)
