### ISSUE TITLE
Minecart with chest don’t open.

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/TrainCarts#224]
##### Spigot version: 1.12.2-R0.1

<hr>

#### Problem or bug:
Inventory in **minecart with chest** and **minecart with hopper** don’t open. The **minecart with command block** can’t be placed on the tracks.
I tested on clean spigot server with only BkCommonLib and TrainCarts with default configuration.

**Comment by bergerkiller** [comment]
The problem of chests not being interactable has been fixed some time ago on the dev builds. Theres a whole lot more that is fixed and changed, but the builds are somewhat stable. You can find them here:
https://ci.mg-dev.eu/job/TrainCarts/

> The minecart with command block can’t be placed on the tracks.
That is still an issue though, can you verify this is still happening on the latest dev build?

**Comment by Vlader97** [comment]
In build #354 inventories work correctly. But I see one small text mistake. The minecart with chest/hopper is called "Minecart" instead "Minecart with Chest/Hopper"
The minecart with command block still cannot be placed on the tracks.

**Comment by Vlader97** [comment]
If you open their inventory you see the name "Minecart" in top left corner.
Yes I was enabled command blocks.
If I use [train] spawn c, the minecart with a command block placed on track but from my inventory not.

**Comment by bergerkiller** [comment]
I fixed both issues you were having (name not correct + command minecart items not functioning). Both plugins have to be updated.

https://ci.mg-dev.eu/job/BKCommonLib/389/
https://ci.mg-dev.eu/job/TrainCarts/355/

**Comment by bergerkiller** [comment]
It might indicate a problem but by itself its not going to do much harm when its removed from cache like this. I put that warning there for when there are issues with minecart entities unloading forcibly without it being handled right. Good to hear it worked out :)

**Comment by Vlader97** [comment]
OK this issue is solved.
