### ISSUE TITLE
BKComonLib errors

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/TrainCarts#225]
##### Spigot version: 1.12.2-R0.1

<hr>

#### Problem or bug:
The plugin often generate this error:
I do not know what the error is causing.
Error log here:
https://www.dropbox.com/s/3a8mm0ww763uq4u/BK_lib_error.txt?dl=0

**Comment by RyanHecht** [comment]
TrainCarts build 360 fixed this issue for me! 
https://ci.mg-dev.eu/job/TrainCarts/lastBuild/artifact/target/TrainCarts.jar

**Comment by Vlader97** [comment]
I did not see this error many days.
Well done!
This issue is solved.
