### ISSUE TITLE
Storage-minecart bug

### ISSUE THREAD

**Issue by Tigerhoernchen** [bergerhealer/TrainCarts#228]
##### Spigot version: 1.8.8

<hr>

#### Steps to reproduce: Place storage-minecart and rightclick on it.

Best regards Tiger.

**Comment by bergerkiller** [comment]
@Tigerhoernchen thanks for pointing this out, SHULKER entity doesnt exist on some older versions of Minecraft. I've patched it. https://ci.mg-dev.eu/job/TrainCarts/375/

**Comment by Tigerhoernchen** [comment]
Nice! Thanks!

**Comment by bergerkiller** [comment]
Fix is officially released now, 1.12.2-v3
