### ISSUE TITLE
TrainCarts not active.

### ISSUE THREAD

**Issue by rctfan1999** [bergerhealer/TrainCarts#23]
Hi, I'm having a simple issue. I've downloaded the BKCommonLib for Minecraft 1.8+ and installed that and this TrainCarts version onto my 1.8.8 server. When I run the server BKCommonLib is Green while TrainCarts is red. Does anybody know why this is?

Bukkit: 1.8.8 R0.1
Traincarts: 1.75
BKC: 1.66 SNAPSHOT

**Comment by mg-1999** [comment]
Any errors that log to the console? If so, please provide them.

**Comment by rctfan1999** [comment]
Now it is stuck on "[Train_Carts] Enabling Train_Carts v1.75-SNAPSHOT". The server won't load past it because of it.

**Comment by rctfan1999** [comment]
Just fixed the issue. I looked at another ticket and saw the parseOldSigns config option. It fixed it. Thank for your help anyways!
