### ISSUE TITLE
Pathfinding issue

### ISSUE THREAD

**Issue by BugArea51** [bergerhealer/TrainCarts#237]
##### Spigot version: git-Spigot-500ff5dlcead62 (MC 1.13.1)

<hr>

#### Problem or bug:
If I set the destination of a minecart to a specific destination, the minecart takes the wrong path and ends on a blocked railway.

#### Expected behaviour:
The minecart should take the right paths to the destination.

#### Steps to reproduce:
This is one of the crossings with issues. Sometimes it works, most of the time not.
![issue](https://user-images.githubusercontent.com/43294287/45585940-fad7b280-b8ed-11e8-9d1e-3a7fd07cb6d4.png)

I hope some one can help me.

**Comment by bergerkiller** [comment]
I cant tell from the question whether youve tried these things, so I'll mention some standard tips.

Have you used blocker signs to restrict illegal movement on the rails? You do this by putting a sign below the rails, facing in the direction you want to block:
```
[+train]
blocker
```

Or you can specify the direction to block, when putting it on the side of the rails:
```
[+train:right]
blocker
```

Verify that it is correctly blocking the incorrect directions by moving a minecart over it. It should stop the minecart in the wrong direction, allow it to pass in the correct direction.

Next, perform a /train reroute to recalculate all path finding information to avoid incorrectly cached paths.

**Comment by BugArea51** [comment]
I used the signs the right way as you described and they do work the right way as shown in the picture via the red arrows. After I change something, I always use the reroute command.

**Comment by bergerkiller** [comment]
When you are seated inside the cart, does it ever send you a message that the destination can not be reached?

**Comment by BugArea51** [comment]
No, it doesn't. It runs just into the blocker and stays still.

**Comment by bergerkiller** [comment]
Did you put the blocker sign very close to the switcher (tag) sign? Its best if theres at least 1 block between it, preferably more. Just put the blocker sign somewhere on the long straight track, not near the junction.

Has something to do with how it iterates the rails during discovery

**Comment by BugArea51** [comment]
I tried it with a space of 3 between the tag sign and the blocker sign.
Still no success and I did run the reroute command.

**Comment by bergerkiller** [comment]
I'm not very sure what to make of it, I'm afraid. I helped someone else with pathfinding woes but so far all such strange issues were resolved by placing down blocker signs in strategic positions.

The best I can recommend for now is to put a destination closer to the switching area, place down a minecart with that destination, and see whether or not it works then. Some minor track layout changes might help also.

**Comment by BugArea51** [comment]
Thanks for helping me, but I don't know to how to achieve a different rail layout for me that works as above in the picture. If I place the destination near the crossing it's working, but this is not the destination I want to have since the desired destination is further away, with a crossing in between.

Pathfinding seems to be a really complicated task. Doesn't the pathfinding go through the tracks to find the obstacles?

**Comment by bergerkiller** [comment]
Path finding indeed walks down the tracks (a task done over the course of multiple ticks if needed), discovering switcher/blocker signs and creating a node-node distance mapping. Rest is a basic A* algorithm.

I dont think it can work, but just in case it does...try stopping the server, deleting the destinations.dat file and restarting. It will do a complete 100% recalculation the first time a minecart hits a switcher sign.

**Comment by BugArea51** [comment]
I tested something in my creative world and even got the problem with this setup and deleting the destinations.dat didn't help.
![issue_2](https://user-images.githubusercontent.com/43294287/45596148-9bde7000-b9b7-11e8-911c-5fe7ea06103d.png)

**Comment by bergerkiller** [comment]
You used [+train] blocker and not [!train] blocker? Because for [!train] blocker path finding cant guarantee its always powered, so itll ignore it.

**Comment by BugArea51** [comment]
I would suggest to update the wiki and outdated links in the config of the plugin.
The wiki is minimalistic and outdated in some parts. Many features aren't listed there and the pathfinding article doesn't mention the [!train] conflict, or even the [tag] sign.

Thanks for support and kind help.

**Comment by bergerkiller** [comment]
Yeah, the [+train] thing did not exist at the time a lot of the wiki was written. I'll add some mention of it.
