### ISSUE TITLE
TrainCarts null event

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/TrainCarts#239]
##### Spigot version: 1.13.1-R0.1

<hr>

#### Problem or bug:
The plugin often generate this error:
I do not know what the error is causing.
Error log here:
https://www.dropbox.com/s/wwsxadlafeh73jv/TrainCraftError.txt?dl=0

**Comment by ThisTNTSquid** [comment]
What are you doing with traincarts while this error displayed in the console?

**Comment by Vlader97** [comment]
I was moving.
Console say that Vlader97 moved too quickly, but I could not repeat it. 
The error shows up randomly.

**Comment by bergerkiller** [comment]
Try using the latest builds of Paperspigot, that fix a couple asynchronous chunk loading bugs that occur. https://papermc.io/ci/job/Paper/1574/

**Comment by Vlader97** [comment]
I did not see this error many days.
I think that is solved.

**Comment by DeveloperBoy** [comment]
@bergerkiller You can close this issue ;)
