### ISSUE TITLE
Sign Issue - Possible Duplicate

### ISSUE THREAD

**Issue by rctfan1999** [bergerhealer/TrainCarts#24]
I'm currently connected to my server on a MAC, which is hosted on a PC. 
When I try to link carts together I get this message: "[22:54:33 ERROR]: Could not pass event EntityAddEvent to Train_Carts v1.75-SNAPSHOT".
When I try to create a sign nothing appears in chat, sign doesn't function when it receives power, and this appears in console: "[23:03:47 ERROR]: Could not pass event ChunkUnloadEvent to Train_Carts v1.75-SNAPSHOT"

Specs:
TrainCarts: 1.75 SNAPSHOT
BKcomandLib: 
Version 1.65
SHA 35e633be203f2cdbbfaa6371029476463995d1a1
MD5 b8af52e5092a4d4cda827db617185ada
Spigot: 1.8.8

**Comment by mg-1999** [comment]
Please use Spigot and not CraftBukkit. It doesn't work with CB.

**Comment by rctfan1999** [comment]
Oh okay. I'll try it with Spigot and let you know if it works.

**Comment by mg-1999** [comment]
Does it work now?
