### ISSUE TITLE
Unusual behavior of train spawners

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/TrainCarts#240]
##### Spigot version: 1.13.1-R0.1

<hr>

#### Problem or bug:
The train spawners ignore the redstone signal. If I power the spawner by redstone (redstone dust), the spawner ignore the signal.
If I use repeater before the spawner and turn signal on (as you can see on picture) the spawner not work. If I turn signal off the spawner spawn minecarts and after interval spawn again. After turn signal off spawn total two trains. I don’t understand.
If I use level next to the spawner, it works normally as I would expect.

#### Expected behaviour:
I would expect that it work as if I use level.

#### Steps to reproduce:
Build the spawner what I have in picture and test it.

Picture:
![spawner](https://user-images.githubusercontent.com/33423693/47734503-b8362380-dc6a-11e8-8ffb-e0011589557f.png)

**Comment by bbayu123** [comment]
I have been pondering what you mean by that passage for 6 days straight and I still don't fully understand your issue. Do you mind making a video to explain the issue?

**Comment by bbayu123** [comment]
If the spawner does nothing, then that's expected behaviour since the repeater and the redstone dust you place at that location does not power the sign at all, so it should not do anything. That's how Minecraft redstone mechanics should work.
If it does something else, then I have no idea what's happening.

**Comment by Vlader97** [comment]
In version 1.12.2 work perfectly.
But now not.

**Comment by Vlader97** [comment]
Well give me the picture on which it will work on redstone dust. If I try other connections, it just does not work on redstone dust.

**Comment by bbayu123** [comment]
.. pointing the dust directly into the sign? That's how I expect it's supposed to work

**Comment by Vlader97** [comment]
Yes I tried, but it does not work. :)

**Comment by bbayu123** [comment]
Give us an image of what you tried?

**Comment by bbayu123** [comment]
can i see the whole track that you're trying to spawn a train onto?

**Comment by Vlader97** [comment]
Yes you see. The track is 100 blocks long.

**Comment by bbayu123** [comment]
I can't see.

**Comment by Vlader97** [comment]
I do not know what you want to see on the track from iron rails.

**Comment by bbayu123** [comment]
I... just want to take a look?

**Comment by Vlader97** [comment]
OK
https://www.dropbox.com/s/xo971m0escinj55/track.png?dl=0

**Comment by bbayu123** [comment]
Ok, can successfully reproduce the bug. Please wait for a while to let berger fix it.

**Comment by bbayu123** [comment]
Try updating to the latest development build of BKCommonLib and TrainCarts and see if the issue persists.
https://ci.mg-dev.eu/job/BKCommonLib/462/artifact/target/BKCommonLib-1.13.2-v1-SNAPSHOT.jar
https://ci.mg-dev.eu/job/TrainCarts/407/artifact/target/TrainCarts-1.13.1-v2-SNAPSHOT.jar

**Comment by Vlader97** [comment]
It works.
Well done!

**Comment by Vlader97** [comment]
I have another problem. For some unknown reason, this fixed version does not work on older maps generated before 1.13. It behaves just as if the problem was not fixed. I tested it only with this plugin, but the result is the same. I really do not know what's a problem on the map.

**Comment by bbayu123** [comment]
I don't know what map you're talking about

**Comment by ThisTNTSquid** [comment]
do you mean the "world" generated before 1.13? because "map" may refer to the MapDisplay (the thing used by attachment menu)

**Comment by Vlader97** [comment]
You're right. There should be a "world" instead of a "map".

**Comment by bergerkiller** [comment]
What server version are you running on when it doesn't work?

**Comment by Vlader97** [comment]
Yes after restart same world still doesn't work. I also tried to use the "optimizing world" (a new option available in 1.13) but it did not help.

**Comment by Vlader97** [comment]
Any progress? Or what additional information is needed?

**Comment by bergerkiller** [comment]
Sorry, I have not yet had the time to look into this as other issues popped up at the same time. I don't need more information, just have to go and reproduce it, really. I'll bump it up in priority as this needs to be fixed for the next BKCommonLib release

**Comment by Vlader97** [comment]
By your steps it works. I done more tests with other worlds, but some work and some do not work. It's really interesting.
Could you add some debug outputs to the plugin to see what's going on when it does not work?

**Comment by bergerkiller** [comment]
Isnt it more likely that it works in some locations of a world, and not in others? Maybe there is a very specific situation going on somewhere. Another option is that this is caused by world-specific configuration introduced by Spigot (or Paperspigot) in the server-root located spigot.yml or paper.yml.

Difficult to add debug though, because of how many redstone events occur it would spam the console too much. I resolve this with a custom server console handler that can filter it.

**Comment by djbenbe** [comment]
I have also tested this. I have used my 2 worlds for both 1.12.2 and 1.13.2 and works perfectly. but if your example on a server of 1.13.2 on the version 1.12.2 plays, this does not work anymore because there are things that are very changing

**Comment by bergerkiller** [comment]
Also an option to send me some 1.12.2 world confidentially (maybe only those region files that matter) so I can test things out on my debug-infested server. I know what I have to look for, but it's core to BKCommonLib and would require many (I'm talking dozens) of different test builds to pinpoint where the logic is breaking.

**Comment by djbenbe** [comment]
you also have to download the new spigot because this can not be the plugin but also spigot itself does this first

**Comment by bergerkiller** [comment]
That is quite possible, although the redstone-specific <> MaterialData conversion is done by BKCommonLib itself. Bukkit's legacy support is limited: https://hub.spigotmc.org/jira/browse/SPIGOT-4230

**Comment by Vlader97** [comment]
Thank you for the idea with the paper.yml
I never thought that one stupid line in paper.yml would cause it not work. This was a line **fire-physics-event-for-redstone** that was set to **false**. When I set it to true, it worked.
Thanks a lot.
I think that is solved  :)

**Comment by bergerkiller** [comment]
I see, I'll add something to traincarts so it prints a warning when this is the case.
