### ISSUE TITLE
TrainCarts does not work with MC 1.7.10/Cauldron/Thermos

### ISSUE THREAD

**Issue by ResqDiver1317** [bergerhealer/TrainCarts#241]
1.59-Snapshot BkCommonLib version:
1.73.1-Snapshop TrainCarts version
Thermos 1.7.10-1614.57 Spigot version:

<hr>

I know this is an old version and support for 1.7.10 may not be offered, but I figured I'd at least ask.
I am building a modpack for 1.7.10 (retro pack based on our first modded server in our community). I found TrainCarts when working on roller coasters on our 1.12.x Bukkit server and really wanted to use it here as well to setup a train system to move players around the city we are building for Spawn. 

My issue is that I cannot place minecarts. The first time I try after a restart, it will place and then after a second or so, it vanishes. Further attempts to try to place carts just do nothing at all. I disabled griefprevention and worldguard protections on our spawn to see if they were the issue that made no difference. If I disable traincarts, then I can place carts like normal. 

If anyone has any suggestions, I would be very appreciative as I would really like to get these working for the spawn train and hopefully build some coasters for players to ride on in the near future on here.

**Comment by ResqDiver1317** [comment]
ah, well then that is most likely my issue. This is a Thermos based modded server :( Hopefully there is a workaround that I can implement that the dev may know of.

**Comment by bergerkiller** [comment]
Traincarts/BKCommonLib only support as far back as MC 1.8. On MC 1.7.10 and before the entire BlockData API is non-existent which makes it very difficult to support.

A very old version of traincarts, lacking most of the newly introduced features, is hosted in my personal old repository. https://github.com/bergerkiller/TrainCarts/
