### ISSUE TITLE
Push & Stop the train with player

### ISSUE THREAD

**Issue by JonasFS1234** [bergerhealer/TrainCarts#243]
##### Spigot version: 1.8

<hr>

**Comment by ThisTNTSquid** [comment]
select the cart by right-clicking it or `/train edit` while facing it, then execute `/train collision player cancel`.
if you prefer the sign way, put this on the rail action sign and power it
```
[train]
property
playercollision
cancel
```

**Comment by JonasFS1234** [comment]
Can not I generally disable this in the files of the plugin folder? Because if I have to add this sign to every attraction, I'm busy for a long time …?

**Comment by JonasFS1234** [comment]
I found it! I edited it in the DefaultTrainProperties.yml folder; there were the collision options are.
