### ISSUE TITLE
Train carts not working in 1.13 or 1.13.2

### ISSUE THREAD

**Issue by FlyFunMan** [bergerhealer/TrainCarts#244]
##### Spigot version:1.13/1.13.2

<hr>

**Comment by FlyFunMan** [comment]
upon startup, it says that this version of BKcommonlib isn't compatible with spigot and to download an updated version, then it says it's turning it off.  I'm confused though, I have the latest version.

**Comment by FriwiDev** [comment]
You can't run a 1.13.1 build on a 1.13.2 server. Please downgrade spigot.

**Comment by FlyFunMan** [comment]
That fixed it, thx. I wonder why the other one didn't work tho.

**Comment by bbayu123** [comment]
The latest Spigot release is only compatible up to 1.13.1. 1.13.2 Compatibility is still under development, along with several optimizations and bug fixes.
