### ISSUE TITLE
Saving and spawning trains

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/TrainCarts#245]
It is possible to store any train with the properties that I set it?
And then the stored train spawn on the train spawner?

I was looking on a wiki, but I did not find the answer.

**Comment by bergerkiller** [comment]
Yes, you would use the command
> /train save mytrain

And can then spawn the train using:
> [train]
> spawn
> mytrain

In addition to this basic mechanic, you can also store trains temporarily into something called 'train chests'. Use /train chest mytrain to get the train you saved as an item. With this item you can click on rails to spawn the train there. By right-clicking on a train with the chest, you can store it in the item (it despawns the train)

Saved trains are written to SavedTrainProperties.yml.

**Comment by Vlader97** [comment]
Nice thanks.
