### ISSUE TITLE
BKCommonLib & TrainCarts  Error messages in 1.13.2

### ISSUE THREAD

**Issue by Blueeyestar** [bergerhealer/TrainCarts#246]
##### BkCommonLib version:
BKCommonLib-1.13.2-v1-SNAPSHOT
##### TrainCarts version:
Train_Carts version 1.13.2-v1-SNAPSHOT (build: 425)
##### Spigot version:
CraftBukkit version git-Spigot-140f654-b446cb5 (MC: 1.13.2) 

#### Problem or bug:

https://pastebin.com/7ZM5FFHQ

**Comment by bergerkiller** [comment]
Should be fixed with https://github.com/bergerhealer/TrainCarts/commit/6f4748a17f1f3a25f10a91c328e20eef3aa952e9

https://ci.mg-dev.eu/job/BKCommonLib/483/
