### ISSUE TITLE
Exception generating new chunk

### ISSUE THREAD

**Issue by Sprax2013** [bergerhealer/TrainCarts#247]
##### Spigot version: git-Spigot-518206a-756c38d (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

<hr>

#### Problem or bug:
Loading a World (Name: Farmwelt) prints an exception. I don't see anything break but it's annoying.

https://pastebin.com/N16BLzaE

#### Expected behaviour:
idk.. Just no exception.

#### Steps to reproduce:
Load a world while server is running (and at least one player is online). Maybe it's because the world is 1.12.2 and firstly loaded into an Spigot 1.13.2 server

**Comment by bergerkiller** [comment]
I recommend trying out this new development build of BKCommonLib to see if it is then fixed: https://ci.mg-dev.eu/job/BKCommonLib/495/

**Comment by bbayu123** [comment]
Is this issue resolved?
