### ISSUE TITLE
Failed to save chunk

### ISSUE THREAD

**Issue by Kikisito** [bergerhealer/TrainCarts#248]
##### Spigot version: git-Spigot-2474d93-e693496 (1.13.2-R0.1-SNAPSHOT)

<hr>

#### Problem or bug: Can't save chunks because entities have an invalid NBT tag. It spams this error:

> [20:47:05 ERROR]: Failed to save chunk
net.minecraft.server.v1_13_R2.ReportedException: Saving entity NBT
at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1616) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.Entity.c(Entity.java:1510) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.Entity.d(Entity.java:1518) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveEntities(ChunkRegionLoader.java:525) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:290) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.ChunkProviderServer.saveChunk(ChunkProviderServer.java:211) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:337) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:288) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:286) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:956) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d
93-e693496]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException

After some hours, it crashed.

#### Steps to reproduce: Change this option `allMinecartsAreTrainCarts: false` at config.yml, and then put it back to false again.

**Comment by bergerkiller** [comment]
Is this a flat environment world it is happening on?

**Comment by Kikisito** [comment]
It happened in multiple worlds: in a normal one generated by spigot, in a custom one and in a superflat one. The only error was that one that I showed you before. I fixed it by killing all the minecarts of each world

**Comment by bergerkiller** [comment]
I just noticed, part of the error is cut-off. Can you find the remaining part that comes after 'Caused by: java.lang.NullPointerException' at the end there? I have a guess what it is, as this happened before, but just in case the error is different this time.

The problem likely has to do with a null DimensionManager instance, something in-part caused by some broken CraftBukkit code.

**Comment by Kikisito** [comment]
I think this is the full error message, I've been searching along all the generated log, and every single error is exactly like this

https://i.imgur.com/6V0uwtP.png

**Comment by bbayu123** [comment]
Do you mind sending the whole log file so we can investigate it?

**Comment by bergerkiller** [comment]
No need to post chat, just unfortunate the stack trace of the nullpointerexception is cut off. I see that more often, don't know what causes it. Maybe it's some java commandline switch used on the server.

In any case, I'm fairly certain what caused the NPE during saving, but just in case this is a new issue it would help to confirm the stack trace. I'll at the very least attempt to reproduce it using the method you described, with allMinecartsAreTrainCarts. Probably these are minecarts that spawned during chunk generation.

**Comment by bergerkiller** [comment]
Yep that confirms that:
Error:
```
Caused by: java.lang.NullPointerException
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1542) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
    ... 13 more
```
Code:
`1542:            nbttagcompound.setInt("Dimension", this.dimension.getDimensionID());`
'this.dimension' is null, something that occurred in the past but that I [did fix](https://github.com/bergerhealer/BKCommonLib/commit/e87a2759c3e33fdc13679ffecb08212740c96d1c). I'm not sure why it is happening again now.

Looking into it.

**Comment by Kikisito** [comment]
> @Kikisito I've added another 'null dimension' guard in a place it was missing, please check for any of the following messages in the log where it corrects itself:
> 
> > Entity had no valid dimension field set! Logging stack trace:
> 
> Dev build: https://ci.mg-dev.eu/job/BKCommonLib/499/
> 
> I also recommend updating Spigot server to the very latest 1.13.2 build, as you appear to be using an older one. Just in case this is something caused by the server itself.

I'm going to try it. About updating my Spigot version, actually I can't because the enterprise where we host the server doesn't have the last version.

I also killed almost all bugged Minecarts. Will the message display anyways or only when a bugged Minecart loads?

**Comment by bergerkiller** [comment]
It should display when a (new) minecart spawns or is loaded in, when traincarts goes to replace the entity with its own, and the dimension for the new entity replacing it is null. In technical terms.

**Comment by Kikisito** [comment]
I spawned a Minecart as a train, and when I moved it, your message appeared multiple times 

https://pastebin.com/QfcMx7dG

**Comment by bergerkiller** [comment]
At least the issue is narrowed down, I just don't really know why it is happening in the first place. I'll remove the warning so at least your console is clean. It should no longer give nullpointer exceptions when saving now at least.

**Comment by bergerkiller** [comment]
I'm afraid you'll have to manually delete those minecarts. Minecarts that used to be traincarts, but saved without a dimension, will be loaded in without dimension too. So basically, theres minecarts saved in a bugged way to disk, that cause save errors when saved again.

Workaround is to set allMinecartsAreTrainCarts to 'true' and load all chunks you know exist so they are all loaded in.

**Comment by bergerkiller** [comment]
(I can add something to BKCommonLib so that it will correct null dimensions for all entities loaded in, but that is probably not good courtesy)

**Comment by Kikisito** [comment]
> I'm afraid you'll have to manually delete those minecarts. Minecarts that used to be traincarts, but saved without a dimension, will be loaded in without dimension too. So basically, theres minecarts saved in a bugged way to disk, that cause save errors when saved again.
> 
> Workaround is to set allMinecartsAreTrainCarts to 'true' and load all chunks you know exist so they are all loaded in. Only when a minecart is turned into a traincart does it pass by that 'fix' of mine to set the dimension to a non-null value.

So, if I want to try again this option, and then I disable it, this error shouldn't appear with these new trains?

> I think what happened is that you used an older development build of BKCommonLib where this null dimension bug existed, and a bunch of minecarts were saved without dimension that way.

I started to use these plugins at the versions I said before



> (I can add something to BKCommonLib so that it will correct null dimensions for all entities loaded in, but that is probably not good courtesy)
> 
> *Actually, I can add it to Traincarts, so that I will do

That would be a big help, my world is a bit large and I would take too much time

**Comment by bergerkiller** [comment]
These versions should silence all errors from now on:
https://ci.mg-dev.eu/job/BKCommonLib/500/
https://ci.mg-dev.eu/job/TrainCarts/438/

**Comment by Kikisito** [comment]
I've put these new versions. If something fails, I'll tell you. Thank so much for your help!



> I think this is the full error message, I've been searching along all the generated log, and every single error is exactly like this
> 
> https://i.imgur.com/6V0uwtP.png
> (Red areas are users' messages)
> 
> There isn't any crash report, because the server crashed due to all the lag generated and not by the plugin

PS: For any reason, in some files, some parts of the error didn't appear. Sorry for that mistake!

**Comment by Kikisito** [comment]
Hi, today I've seen that some bugs haven't been fixed yet. When I disable the plugin, the same chunk error appears

**Comment by bergerkiller** [comment]
does the error appear before or after traincarts disables?

**Comment by Kikisito** [comment]
After disabling it. This time I used Plugman

**Comment by bergerkiller** [comment]
Can you upload the exact server jar youre using at the moment? I think I'll have to reproduce it locally and find out where these null dimensions come from. It appears as if all entities that are loaded in when chunks load, have a null dimension for some reason.

When the plugins are disabled I obviously have no control over what happens when chunks load that have entities in them with null dimensions, so this time I'll have to find out why entities are saved with a null dimension on that server version.

**Comment by bergerkiller** [comment]
Hmm now I get the same warnings myself, interesting. I don't think I need your server jar, looks like this is still present in 1.13.2.

`Entity had no valid dimension field set! Logging stack trace:`

**Comment by bergerkiller** [comment]
It's alright, I can look into it with the official 1.13.2 spigot jar

**Comment by bergerkiller** [comment]
Unfortunately this looks like a server bug. The issue is complex. In Entity.java, loading logic:
`this.dimension = DimensionManager.a(nbttagcompound.getInt("Dimension"));`

What this does is read an int (number) from the properties of the entities, looking that Id up in some table, and retrieves the dimension belonging to it. But what if the Id is invalid? Yep, it's null. But why is it null?

Entity.java, saving lgoic:
`nbttagcompound.setInt("Dimension", this.dimension.getDimensionID());`

Looks fine, right? The issue is that some dimensions in use on the server do not exist in the table. I had to write custom code to properly deal with those, as they appeared to come from nowhere. Now the server itself is choking on the very same issue.

This issue only occurs on 'flatlands'-esque worlds, basically anything not like normal/nether/the_end.

I'm not sure whether to report the issue, because technically, I'm introducing it myself by supporting these invalid dimension managers floating around from places I do not know. I think the best course of action here is to treat 'weird' dimensions as invalid, and set it to the NORMAL dimension in those cases instead.

**Comment by Kikisito** [comment]
So, will it be fixed for the next version? Or we need to wait for a new spigot version?

**Comment by bergerkiller** [comment]
This should completely fix all these issues from now on. https://ci.mg-dev.eu/job/BKCommonLib/501/

**Comment by Kikisito** [comment]
I'm going to try it. Thank you! I'll tell you if it works or not
