### ISSUE TITLE
Permission for '/train destination' not working

### ISSUE THREAD

**Issue by herboy8** [bergerhealer/TrainCarts#251]
##### Spigot version: CraftBukkit version git-Bukkit-ad6070d

<hr>

#### Problem or bug:
When granting the `train.command.setdestination` permission, players do not get access to the `/train destination` command. This command is instead granted by giving the `train.command.properties` permission.

#### Expected behaviour:
Allowing the `/train destination` command with the `train.command.setdestination` permission as described in `PermissionDefaults.yml`.

#### Steps to reproduce:
Negate the default permission setup (which gives players `train.command.properties` and `train.command.setdestination`), then do allow for `train.command.setdestination`. This will result in players not having access to the `/train destination` command.
Only allowing `train.command.properties` will give players access to this command.

**Comment by weeryan17** [comment]
that's weird i just looked at the code myself and it's set to the correct permission
https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/commands/TrainCommands.java#L337

**Comment by weeryan17** [comment]
Can confirm. although all the underlying code says it should be fine.

**Comment by bbayu123** [comment]
Is this issue still affecting you?
