### ISSUE TITLE
Unable to get into minecarts

### ISSUE THREAD

**Issue by kathryneo** [bergerhealer/TrainCarts#254]
##### Spigot version: Spigot 1.13.2

<hr>

#### Expected behavior: Able to sit in minecarts and see as if you are in the cart.

![collage 2019-02-18 13_04_44](https://user-images.githubusercontent.com/47755923/52971634-d2ad1d80-337d-11e9-8f2f-f932089de04e.jpg)

The top picture was taken right after I "got in" the cart, but once my friend reloaded she was able to see me in the cart although I was not on my screen. The bottom two pictures were taken at the same time from two different views. After a while I was teleported to where the traincart was but I was not sitting in it.

**Comment by djbenbe** [comment]
Best,
you may never reload the server.
so it's better that you restart the whole server.

**Comment by kathryneo** [comment]
> Best,
> you may never reload the server.
> so it's better that you restart the whole server.

We have restarted the server multiple times and have tried downloading a different BKCommonLib file.

**Comment by djbenbe** [comment]
I'm going to test

**Comment by kathryneo** [comment]
> I'm going to test

Haven't seen any other server with traincarts having this problem. If you would like to see (and hopefully discover something we are missing), please feel free to join funtimes.serv.nu. Thank you.

**Comment by weeryan17** [comment]
@kathryneo 1. please don't put server links in public issues
2. do you have any other plugins that affect minecarts
3. I suggest you update train carts to see if that fixes it

**Comment by kathryneo** [comment]
> @kathryneo 1. please don't put server links in public issues
> 2. do you have any other plugins that affect minecarts
> 3. I suggest you update train carts to see if that fixes it

Sorry, new to GitHub. As far as we are aware, there are no plugins that are affecting TrainCarts. We are used the most updated version on the plugin (as far as we are aware). We have also tried reinstalling and it did not anything.

**Comment by weeryan17** [comment]
You can try removing all plugins besides train carts (and bkcommonlib) and see if that fixes things (make a backup before you do this). If it does then you know it's a different plugin and you need to track it down, otherwise come back here and we'll see if we can figure out the problem. You can also try the latest dev build [https://ci.mg-dev.eu/job/TrainCarts/448/artifact/target/TrainCarts-1.13.2-v2-SNAPSHOT.jar](https://ci.mg-dev.eu/job/TrainCarts/448/artifact/target/TrainCarts-1.13.2-v2-SNAPSHOT.jar)

**Comment by kathryneo** [comment]
> You can try removing all plugins besides train carts (and bkcommonlib) and see if that fixes things (make a backup before you do this). If it does then you know it's a different plugin and you need to track it down, otherwise come back here and we'll see if we can figure out the problem. You can also try the latest dev build https://ci.mg-dev.eu/job/TrainCarts/448/artifact/target/TrainCarts-1.13.2-v2-SNAPSHOT.jar

We tried the latest dev build. We removed plugins and it seemed to be ProtocolLib.  We can now enter carts, carts are spawning where they should be and won't move on their own but it seems to be working.

**Comment by bergerkiller** [comment]
Is this the latest build of protocollib? Ill go have a look into this now, looks like its related to the player attach packet.

**Comment by bbayu123** [comment]
Does this issue still exist?

**Comment by JLyne** [comment]
I also seem to be encountering this issue, with the same mc and plugin versions as the OP.

Plugins (20): AdvancedPortals, AutoHub, BKCommonLib, DisableJoinMessage, dynmap, GiveMeSomeSpace, HackedCore, HackedServer, Images, LuckPerms, NametagEdit, PlugMan, ProtocolLib, SignLink, TCHangRail, Timer, Train_Carts, ViaVersion, WorldEdit, WorldGuard

I haven't yet tested without protocollib yet, however I am on the latest version of it (4.4.0). None of the other plugins installed seem like they would affect minecarts either, except for TCHangRail naturally.

**Comment by bergerkiller** [comment]
And that is with the latest development builds also? Im fairly sure it must be some plugin conflict doing this...

**Comment by JLyne** [comment]
Just to confirm, currently running without ProtocolLib and it seems fine now. All other plugins are the same as seems none of them depended on it.
