### ISSUE TITLE
TrainCarts won't load.

### ISSUE THREAD

**Issue by yogurtsyum** [bergerhealer/TrainCarts#255]
##### Spigot version: 1.8.9 (not sure which plugin version either, I have had it for a while though)

<hr>

**Comment by weeryan17** [comment]
try this version out [https://ci.mg-dev.eu/job/BKCommonLib/517/artifact/target/BKCommonLib-1.13.2-v3-SNAPSHOT.jar](https://ci.mg-dev.eu/job/BKCommonLib/517/artifact/target/BKCommonLib-1.13.2-v3-SNAPSHOT.jar)

**Comment by weeryan17** [comment]
@xLengoBug5 did that version fix the issue?

**Comment by xLengoBug5** [comment]
I'm trying it right now.

**Comment by xLengoBug5** [comment]
@weeryan17 didn't work.

**Comment by djbenbe** [comment]
do /train version
show screenshot of it

**Comment by xLengoBug5** [comment]
It just started working again. Sorry for the inconvenience.
