### ISSUE TITLE
Noone except Admins can use TrainCarts

### ISSUE THREAD

**Issue by TheSoulrester** [bergerhealer/TrainCarts#256]
##### Spigot version: => PaperMC latest (1.13.2)

<hr>

#### Problem or bug: noone except user with admin group are able to place and interact with all the features traincarts provides. i am using UltraPermission - moreover, i didn't find any permissions i have to set up for several groups. 

 also the wiki didn't tell me how to set up permissions.
 what i have to do?

**Comment by ryando123** [comment]
Change permissions in the permission file

**Comment by TheSoulrester** [comment]
ah, ok. what i have to enter there? op = admin? default = everyone?
i have 4 different groups: admin, vip, member, guest
only member++ should be able to use traincarts. guests aren't allow to do anything.

**Comment by bbayu123** [comment]
Sorry it took so long, I believe just entering the group/rank name would work in there.
