### ISSUE TITLE
Collision cancel ignored

### ISSUE THREAD

**Issue by RyanHecht** [bergerhealer/TrainCarts#26]
Ever since 1.75, when pushing minecarts was fixed, any property sign/defaulttrainproperties.yml values that cancelled collisions have been ignored. This means that minecarts are ALWAYS able to be pushed, even when they are intended to have cancelled collisions. 

Edit 1: I've only tested this with player collisions, not sure if any other collision types act the same way

Edit 2: A staff member on my server informed me that collisions with other trains don't appear to be affected by this

**Comment by RyanHecht** [comment]
Edit: I've only tested this with player collisions, not sure if any other collision types act the same way

**Comment by mg-1999** [comment]
How do I test this? Because I think that I've found the problem.

**Comment by RyanHecht** [comment]
Ensure that a train's collision property is set to 'cancel,' then have a player push the train. The player will be able to, despite the collision cancellation

**Comment by MrPufferFish** [comment]
Als happend by me. Player collision CANCEL is ignored.

**Comment by MrPufferFish** [comment]
When is this getting fixed? It's quite annoying.

**Comment by mg-1999** [comment]
Try the latest version, it is fixed now. Only you cant push trains/carts with playercollision set to cancel.
