### ISSUE TITLE
How to make custom carts looks longer?

### ISSUE THREAD

**Issue by ARTI5T** [bergerhealer/TrainCarts#260]
##### Spigot version:1.13.2

<hr>

#### The resource pack to make minecarts look real is really great, but they still look too short. Is there any way to make them look longer like a real train (without loosing its resolution)? BTW, can we use .obj models in minecraft?
Thank you!

**Comment by weeryan17** [comment]
You can edit the resource pack with a program like [blockbench](https://blockbench.net/), and minecraft doesn't accept .obj files.

Also in the future if you have questions like this ask on the [discord server](https://discord.gg/P34bUPT) not in an issue.
