### ISSUE TITLE
ProtocolLib

### ISSUE THREAD

**Issue by ryando123** [bergerhealer/TrainCarts#261]
##### Spigot version: 1.12.2

<hr>

#### Steps to reproduce: Remove ProtocolLib and try to sit in a model.

**Comment by bbayu123** [comment]
Not really that surprising, however, it's either a bug with BK, or a working-as-intended

**Comment by bergerkiller** [comment]
Can't reproduce this anymore, Im assuming it has been fixed in BKCommonLib by now.
