### ISSUE TITLE
Failed to load data for block entity

### ISSUE THREAD

**Issue by J0schlZ** [bergerhealer/TrainCarts#264]
##### (Paper)Spigot version: git-Paper-76 (MC: 1.14.2)
<hr>

#### Problem or bug:
Console is spamming this error every second for a while after startup:

https://pastebin.com/fWgsHcxv

#### Expected behaviour:
No Errors

#### Steps to reproduce:
idk

**Comment by bergerkiller** [comment]
See if this fix helps: https://ci.mg-dev.eu/job/BKCommonLib/560/

**Comment by J0schlZ** [comment]
Yes, it does for the structure block. Thank you!

But i get this errors too:
https://pastebin.com/jNSrZYKG

Full Log:
https://pastebin.com/MB4HePvt

**Comment by bergerkiller** [comment]
Took a while to figure out why my fix wasn't working, but eventually figured it out.

https://ci.mg-dev.eu/job/BKCommonLib/561/

**Comment by J0schlZ** [comment]
It works! Thank you!
