### ISSUE TITLE
Server not responding when using TC

### ISSUE THREAD

**Issue by GeursRobert361** [bergerhealer/TrainCarts#265]
##### Paper version: Paper-68 (1.14.2)

<hr>

#### Problem or bug: Console spams this error and stops server from responding
https://pastebin.com/FpBs8jvR

**Comment by bergerkiller** [comment]
Signlink doesnt work with 1.14 yet. There's many problems of chunks being loaded from inside a chunk load event freezing the server. See: https://hub.spigotmc.org/jira/browse/SPIGOT-5032

**Comment by bergerkiller** [comment]
1.14.4 will fix this issue, as well as using the latest builds of signlink
