### ISSUE TITLE
Get wrong sign when no permission

### ISSUE THREAD

**Issue by Nekuroi** [bergerhealer/TrainCarts#266]
##### BkCommonLib version: 
1.14.2 556
##### TrainCarts version: 
1.14.2 466
##### Spigot version: 
1.14.2 git-Spigot-baafee9-17543ec

<hr>

#### Problem or bug:
When you don't have permission to place a sign you always get an oak sign.

#### Expected behaviour:
Get the sign of the type of wood used

#### Steps to reproduce:
Place a [train] station sign without the proper permission with a wooden sign that is not oak.

**Comment by bbayu123** [comment]
Should work with latest dev builds, can you take a look?
