### ISSUE TITLE
BlockChanger sign doesn't support data values

### ISSUE THREAD

**Issue by JackDn** [bergerhealer/TrainCarts#27]
When using data values on a BlockChanger sign, it ignores the data value.
For example 35:11 (blue wool) is shown as white wool.

**Comment by mg-1999** [comment]
If found the classes that could cause the problem. Only my time is limited now and cant see a quick fix for this. Nothing changed in that class since 1.7 so it should work. I am further investigating in my free time now.

**Comment by M64mc** [comment]
Any updates on this?

**Comment by bergerkiller** [comment]
Verified and fixed since [https://github.com/bergerhealer/BKCommonLib/commit/0d1058a3b65e425fbb9d5fd4273ed899ff4f406e](url)
