### ISSUE TITLE
Unused config options

### ISSUE THREAD

**Issue by 56738** [bergerhealer/TrainCarts#276]
##### Spigot version: git-Spigot-d05d3c1-fca4157 (MC: 1.14.3)

<hr>

#### Problem or bug:

The following config options are unused:

* `maxEnterDistance` ([hardcoded to 50.0](https://github.com/bergerhealer/TrainCarts/blob/35a9304020f3d273a900ab765334e2940b8a461c/src/main/java/com/bergerkiller/bukkit/tc/signactions/SignActionEnter.java#L50))
* `maxCartDistance` (possibly replaced by `cartDistanceGapMax` which isn't configurable)
* `manualMovementSpeed`
* `allowVerticalPitch`

**Comment by bergerkiller** [comment]
Fixed as of https://github.com/bergerhealer/TrainCarts/commit/0ae424bc789807269873bdfe226ca516bf0faa88
