### ISSUE TITLE
custom models CustomModelData  instead of DamagaValues

### ISSUE THREAD

**Issue by thunderlight411** [bergerhealer/TrainCarts#277]
##### Spigot version: git-Paper-129

<hr>

#### Problem or bug: 
Damagevalues for custom Models is to limited

#### Expected behaviour:
Is there a way to use CustomModelData for the trains so we can make custom designs with a resoucepack. the damagevalues right now are way to limited to work with.

Thanks for the support.

**Comment by bbayu123** [comment]
Have you tried dropping the item (that you want to be the model) when you have the item selection menu opened?

**Comment by weeryan17** [comment]
> 
> 
> Have you tried dropping the item (that you want to be the model) when you have the item selection menu opened?

This allows you to put any item in. although I think it would be nice if traincarts supported this new format directly as it has the systems to do so. In fact I might make a pr to do so later.

**Comment by bergerkiller** [comment]
yeah input methods could be more broad, Im just afraid the UI becomes very clunky when I support the full item configuration. If you do add something, try to put such things under a button-activated menu

**Comment by bergerkiller** [comment]
Ill be working on adding a menu system for this myself

**Comment by bergerkiller** [comment]
I've added a custom model data area in the item selector menu. After the latest commit this also works for items that dont have durability, like blocks.
