### ISSUE TITLE
Traincarts tickets.yml playerBound property

### ISSUE THREAD

**Issue by MrKittle** [bergerhealer/TrainCarts#279]
##### Spigot version: 1.12.2-R0.1-SNAPSHOT

<hr>

#### Steps to reproduce: Type /train ticket give <ticketName> <myName>
and drop the ticket to another player who will be able to enter a train with it.

**Comment by bergerkiller** [comment]
![ScreenShot_2019-07-30 16-55-52](https://user-images.githubusercontent.com/957601/62140229-e7a5b980-b2ea-11e9-8bc8-379669031bb0.png)
You were right, and I've fixed it. Thanks!

https://github.com/bergerhealer/TrainCarts/commit/9cc56f5ab8bd53e2ea8bc2192ad2ef976e583805

**Comment by MrKittle** [comment]
Thanks a lot ! :-)

**Comment by bbayu123** [comment]
The version linked above works on 1.12.2

**Comment by MrKittle** [comment]
Hello, I tried Traincarts latest version on 1.12.2 but it needs latest
version of BkCommonLib which doesn't load on my 1.12.2 Spigot.

Cordially.

**Comment by bbayu123** [comment]
It loads on my 1.12.2 spigot server just fine, what error are you having?

**Comment by bergerkiller** [comment]
Also use the BKCommonLib version I linked in my answer above ( https://ci.mg-dev.eu/job/BKCommonLib/593/ )

**Comment by MrKittle** [comment]
I have this error: https://paste.md-5.net/wilideyami.css
I use Traincarts #487 and BkCommonLib latest version 1.13.2-v3

Cordially,
Mr_Kittle.

**Comment by bbayu123** [comment]
you need to update BOTH BKCommonLib AND TrainCarts

**Comment by MrKittle** [comment]
Thank you very much, it works now :-)

Have a good day.

Mr_Kittle.
