### ISSUE TITLE
Trains stop randomly when waitdistance is engaged (multiple times?)

### ISSUE THREAD

**Issue by bbayu123** [bergerhealer/TrainCarts#281]
##### Spigot version: b1573-j (MC 1.12.2)

<hr>

Have notified bergerkiller a while ago, but it seems like he's having difficulty reproducing it, and didn't want t just leaving it hanging in his DM, so moved it here.
Basically, when trains engage in waitdistance WHILE the launcher sign is changing its speed, there's a CHANCE that the launcher will bring it to a full stop, more noticeably during the engagement of the waitdistance a second time.
What I would describe the situation would be:
1. train1 stopped, train2 just went over a launcher sign and is decelerating
2. train2 reaches the point where it is too close to train1, thus stopping due to waitdistance, however, the train is still "decelerating" due to the launcher
3. train2 finally finishes its deceleration and continues to wait for train1 to move
4. train1 moves, causing train2 to move again
5. Here's where the chance part comes in to play, train1 stops again, causing train2 to stop due to being in close proximity with train1, and for SOME reason there's a CHANCE that the launcher (which is long gone) will kick into effect again and decelerate the train to... idk... 0?, thus stopping the train completely
6. Finally, train1 leaves the scene via stage left, leaving train2 on the scene, unable to move due to no signs under it and no one to help him.

I have attached kind of a test track that sometimes, but not always, produces the situation, however, I would say luck is also involved in this issue, so I can't say for certain whether you will get it or not.

<hr>

ATTACHMENTS:
YouTube video: showing the situation looks like, and how infrequent it is.
https://youtu.be/-NknBnH61d0

[IssueAttachments.zip](https://github.com/bergerhealer/TrainCarts/files/3453923/IssueAttachments.zip)
TestTrack.schematic (within IssueAttachments.zip): a test track that occasionally does cause the bug to appear, note that this is a 1.12.2 MCEdit schematic.

SavedTrainProperties-EXTRACT.yml (within IssueAttachments.zip): includes the test train with the set properties that is used on the test track (see above TestTrack.schematic)

**Comment by bergerkiller** [comment]
That's a good summary, I don't think I can fix this before the next release cycle as I have limited time. (I'm leaving for 2 weeks of holiday next week). When I have time for it I will pick this up on 1.12.2 server and see what I can do.

I do think the decelerating action of the launcher sign plays an important role here. There are a few thresholds used during this launching which may explain the 'rareness' of this bug, as it can then depend on the start velocity of the train when it hits the launcher sign.

**Comment by bbayu123** [comment]
Okie, Update: Yes reproducible, me and berger saw it happen multiple times; Yes still persists on latest snapshot; Turns out it has nothing to do with the launcher, just the random positions of the trains making random trains' speed drop to 0.

**Comment by bbayu123** [comment]
Ok, think it's fixed, I need to test it myself though, so give me some time...

**Comment by bbayu123** [comment]
Will reopen when I see this again
