### ISSUE TITLE
Train ticket player display name

### ISSUE THREAD

**Issue by MrKittle** [bergerhealer/TrainCarts#283]
##### Spigot version: 1.12.2-R0.1-SNAPSHOT

<hr>

#### Steps to reproduce:
Give you a train ticket and take it in your hand and see.

**Comment by bergerkiller** [comment]
looks to me like there is chat color in your player's name, which as a result, gets printed like that on the ticket. The right way to go would be to filter chat color styling from names before displaying them.

**Comment by MrKittle** [comment]
It works now :-) Thank you for all.

Cordially.
