### ISSUE TITLE
Property sign cannot understand mixed case key values.

### ISSUE THREAD

**Issue by bbayu123** [bergerhealer/TrainCarts#284]
##### Spigot version: -Unrelated-

<hr>

#### Steps to reproduce:
![image](https://user-images.githubusercontent.com/26726381/62775172-1b9c8e00-bae6-11e9-8abb-f31d9ef473c0.png)

**Comment by bbayu123** [comment]
PR created, see above.

**Comment by bbayu123** [comment]
Nature of above PR changed, unable to fix issue, require further changes.

**Comment by bergerkiller** [comment]
Ill make the further changes needed

**Comment by bergerkiller** [comment]
This should do it: https://github.com/bergerhealer/TrainCarts/commit/5d7dd49c4eff2fca6352655ff7e4f12590809900
