### ISSUE TITLE
Trains disappear bug (ProtocolSupport incompatability)

### ISSUE THREAD

**Issue by AsmodeusZ** [bergerhealer/TrainCarts#286]
##### Spigot version: 1.12.2

<hr>

#### Problem or bug: Trains disappear when the server is restarted in 1.12.2.
The trains are working normally as expected, but they can't be seen, sometimes they look stopped on certain part of the track, but they can't be destroyed.

When you use /train info, the train is moving and working, but, it can't be destroyed, ridden, etc.
#### Steps to reproduce: Placed a train on a 1.12.2 server, put it keepchunksload true, [Set speed to 1.2], let it go and restarted the server.

The train is still there because it activates the station sign and you can hear the sound of the station.

**Comment by bbayu123** [comment]
We need the type of the server as well (CraftBukkit/Spigot/Paper/etc), can you provide that?

**Comment by AsmodeusZ** [comment]
![image](https://user-images.githubusercontent.com/28993591/62885112-a3a8b080-bcfd-11e9-85c7-9203d6e3a55c.png)

**Comment by bbayu123** [comment]
Can you get a video here to show exactly what you mean? The dev is not able to respond immediately, so we would like to collect as much information as possible before he looks into this.

**Comment by AsmodeusZ** [comment]
Ok, well, looks like ProtocolSupport was the reason of that problem, i'll update if this appears again.

**Comment by bbayu123** [comment]
So protocolsupport? Seems like an incompatibility, might be fixable within bktc, but will have to check with dev

**Comment by bbayu123** [comment]
Yep after all the reports about protocolsupport that we've been getting, I can safely say that protocolsupport is not compatible. I shall be closing this.
