### ISSUE TITLE
Routing Not Choosing Shortest Route

### ISSUE THREAD

**Issue by gxmy** [bergerhealer/TrainCarts#288]
##### Spigot version: 1.14.4

<hr>

#### Problem or bug:

The routing algorithm is choosing routes that are longer than they need to be and look odd in terms of train movement. Below is a track layout diagram.

>                   Platform
>                  +---X-----+
>     --- Q -----+--------Z----+--------------------- Y --

A train at the platform, position X, with destination Y, is routed initially away from Y before doing a 180 degrees turn passing by Z and onto Y. This looks odd in terms of train movement. Furthermore in my case I have a destroyer sign to the left of X for incoming trains from Q so any train traveling from X to Y gets destroyed. I can workaround this by breaking the track to the left of X forcing the routing algorithm to move to the right initially rather than left.

This world is an old 1.7 one which didn't have this issue so something has changed with the routing algorithm in the interim.

#### Expected behaviour:

Train moves from X to Y moving initially to the right in the diagram above and hence doesn't reverse.

#### Steps to reproduce:

Setup the track above and check the routing algorithm output.

**Comment by bbayu123** [comment]
Did you try /train reroute? Are you able to show a video?

**Comment by gxmy** [comment]
Yes I tried /train reroute & I'll see what I can do about a video although it's not something I've done before.

**Comment by gxmy** [comment]
Here's a video that demonstrates the issue. 

https://youtu.be/bdrWPI-2F_w

When I set destination to 'y' the minecart moves correctly. However with destination set to 'z' it sets off in the wrong direction before doing 180 degree turn to get to 'z'.

While making the video I learnt that I can use the 4th line of the launcher sign to workaround this issue & force the direction in which the minecart starts moving. If you want to close this issue with an as designed or will not fix then that's fine. It's just surprising that with the old 1.7 code the workaround was unnecessary.

**Comment by bbayu123** [comment]
That looks like correct behaviour, and what you had on 1.7 is probably an unintended side effect. Trains always spawn with a forward orientation, and if the 4th line of the launcher sign is empty, it always launches in the direction of its forward orientation.

**Comment by gxmy** [comment]
Ok thank you for your help.

**Comment by bbayu123** [comment]
Even though I said that, I'll keep this open to let dev take a look about this before closing.

**Comment by bbayu123** [comment]
After half a year, I can safely say that the issue you were having is indeed correct behaviour, I shall close this issue with that note.
