### ISSUE TITLE
Trains appear as minecarts and not what they were saved as or showed up as after restart

### ISSUE THREAD

**Issue by bbayu123** [bergerhealer/TrainCarts#289]
One more bug to Report in that when trains are present on a server when it goes down and restarted they appear as minecarts and not what they were saved as or showed up as.

_Originally posted by @Disneykid93 in https://github.com/bergerhealer/TrainCarts/issues/285#issuecomment-520662555_

**Comment by bbayu123** [comment]
I did notice it happening to me as well.

**Comment by Disneykid93** [comment]
Good to know, also if you have not seen it yet our server dev has posted the video you requested on the switcher bug.

**Comment by Imbuzi** [comment]
Hi guys, same issue here ...

**Comment by bergerkiller** [comment]
Any clues that can help me to reproduce the issue? It doesn't happen to me, what I'm thinking of is that either during saving or startup some errors occur and data is lost as a result.

**Comment by Disneykid93** [comment]
Have you tried leaving a train on a track and rebooting the server? If you have not done that already. That's what is happening to the server i work on. because we leave some for decoration or for rides that would look better if it stayed there and not despawned.

**Comment by bergerkiller** [comment]
@Disneykid93 I leave trains on the tracks all the time while im rebooting the server dozens of times to debug things. It never disappeared or reverted to a normal minecart for me. Something is different from how Im testing things. Can it be related to the 'keep chunks loaded' property? Are you running the latest dev build of traincarts from the jenkins ci? (in case I already fixed it as a side-effect of something else)

**Comment by Disneykid93** [comment]
Hmm, well the version we have is TrainCarts 1.14.4-v2 (build:504) as well as TCCoasters 1.14.4-v2-SNAPSHOT. I'm not sure why you are not seeing it but we are on the server, as for chunkloading i doubt that would be the cause but maybe? I will have to put that to the test when we need a reboot of the server as i don't have access to the console for the server we have this problem on.

**Comment by bergerkiller** [comment]
Yesterday I fixed several problems of trains reverting to Minecarts when the server restarts and a player is inside the cart at that time. Similar problems existed when players logged off/back in while inside a cart. I'm leaving this issue ticket open in case there are more cases where this happens

**Comment by Disneykid93** [comment]
Looks like what you did Fixed the issue. My server needed a reboot and when i came back on the train was intact just how i left it.

**Comment by bbayu123** [comment]
Gotcha, I shall close this then.
