### ISSUE TITLE
Trains derailing on track split junctions

### ISSUE THREAD

**Issue by Disneykid93** [bergerhealer/TrainCarts#290]
##### Spigot version: 1.14.4-R01-SNAPSHOT

<hr>

#### Steps to reproduce: Look to the screen shots as posted below. pics show the track set up 
 and what happens when it reaches the merge. The trains are being moved from this building using the /train launch (speed) chat command and unless its on the straight track the train will derail and even if the desired track isn't selected it will stop and squish together. (I do not know if there are console errors but i will try and get the Dev to see when he is available)
![2019-08-15_17 46 59](https://user-images.githubusercontent.com/54014064/63136494-2bedb680-bf87-11e9-9e0b-c717df24e731.png)

![2019-08-15_17 45 45](https://user-images.githubusercontent.com/54014064/63136355-6dca2d00-bf86-11e9-89c4-67fa5f31a52e.png)

**Comment by bbayu123** [comment]
Can you post a video about it instead? That looks like a discrepancy between reality and user expectations, so when berger comes back he might do something about it.

**Comment by Disneykid93** [comment]
I will see what i can do.

**Comment by bbayu123** [comment]
I mean, it could also be intentional, as the node has been defined at some point to switch the train towards, idk, say 2, no matter the input direction, unless a switching table has been configured or it has a switcher sign.

**Comment by Disneykid93** [comment]
we have been manually changing the track nodes for these monorails, but it still happens on this track.

**Comment by Disneykid93** [comment]
oops dont mind that tried to upload the video here but it didnt work.

**Comment by Disneykid93** [comment]
Here is the video as requested. https://youtu.be/bEWXZR4Dm_U

**Comment by Disneykid93** [comment]
One more thing to add, and that is this Bug doesn't seem to happen on all the track splits we have on the server it just seems to be on this kind with the 3 split track.

**Comment by bbayu123** [comment]
Should be fixed since bergerhealer/TC-Coasters@d78cc77a9d04aef0da40a3bdcc124c47a60cf7f6
https://ci.mg-dev.eu/job/TC%20Coasters/80/artifact/target/TCCoasters-1.14.4-v2-SNAPSHOT.jar
