### ISSUE TITLE
Pathfinding not working between normal rails and TCC

### ISSUE THREAD

**Issue by OfficialBenjy** [bergerhealer/TrainCarts#291]
##### Spigot version: git-Paper-624

<hr>

#### Problem or bug:

It seems that Pathfinding doesnt seem to work when transitioning from normal rails to TCCoasters.

The train doesnt even try to go towards the station on the correct route.

also what isnt shown on the video is when the train is going over the switcher sign it completely stops and and all the carriages bundle together in one single spot. Similar to Issue# #290 
https://www.youtube.com/watch?v=RMeveXP4f5s

#### Expected behaviour:

The train should go to the destination, there are switcher and blocker signs in all of the corect places.

#### Steps to reproduce:

Create a small network making it so that one destination is on branch that is made from TCC and the other is on normal rails.

**Comment by bbayu123** [comment]
Try converting the switching node at the straight piece to a tcc node, and see if that works

**Comment by bbayu123** [comment]
I doubt this is still an issue as Benjy hasn't been responding to this.

**Comment by bbayu123** [comment]
Situation unknown, will close until further response is made.
