### ISSUE TITLE
Suggestion: Add a name field to item attachment editor (ChatColor)

### ISSUE THREAD

**Issue by bbayu123** [bergerhealer/TrainCarts#293]
##### Spigot version: -

<hr>

#### Description
In commit 7ce7cb9, fields have been added to toggle Unbreakable and CustomModelData, but I want to suggest a name field since I have attachments change texture using different item names, controlled by Optifine. (Oh and ChatColor as well)

**Comment by bergerkiller** [comment]
I could add a little button on the same page as the custom model data field which when activated opens up an anvil editor where you can input this. (with a command equivalent of course)

**Comment by bbayu123** [comment]
🤗

**Comment by bergerkiller** [comment]
I've implemented this now. https://github.com/bergerhealer/TrainCarts/commit/59db1af910fa223c6f53bb9130ca371dbf6c24bf

**Comment by bbayu123** [comment]
Thanks, sometimes colour may also be required, do you think you can parse some colours in the input widget?

**Comment by bergerkiller** [comment]
Pasting those weird color code characters doesnt work?

**Comment by bbayu123** [comment]
They never worked properly on lower versions, i.e. 1.12.2 and also 1.8.9

**Comment by bergerkiller** [comment]
strange, because Im using the Bukkit ChatFormat -> IChatComponent stuff which does accept those characters regardless of mc version. Or does the client side not send those characters back when you type it in?

**Comment by bbayu123** [comment]
It's the client that refuses to put those characters in, using the windows shortcut of ALT+that number, as well as doing a copy and paste has never succeeded back in 1.12.2 as well as 1.8.8. However, if the item (talking about anvils) already had colour, then it can be manipulated as long as you don't delete the section signs

**Comment by bergerkiller** [comment]
I see. Then the same applies to the text attachment. I can add some color code handling to the MapWidgetSubmitText in BKCommonLib so it covers all future ground

**Comment by bbayu123** [comment]
Can confirm that pasting the section sign into 1.12.2 does not work, also doesn't work in 1.14.4

**Comment by bbayu123** [comment]
Pasting text will section signs mixed within causes the section signs to be completely removed on paste, not even changing the colours.

**Comment by bbayu123** [comment]
This is also true for the player chat, meaning that the command /train menu set value will also be affected.

**Comment by bbayu123** [comment]
![image](https://user-images.githubusercontent.com/26726381/126266480-1ba5eddd-b917-467f-b587-62c2e6d0d929.png)

**Comment by bbayu123** [comment]
Eh, you know what, it's good enough. Closing my own issue.
