### ISSUE TITLE
Train separation in hills.

### ISSUE THREAD

**Issue by Maxi22700** [bergerhealer/TrainCarts#30]
Here is a video with explains a problem in hills on my server. I cannot fix it. I've tried to remove all others plugins except BK and TC both still nothing. Can you help me ?
https://www.dropbox.com/s/2ppwbzvcio6ywmi/Train%20separation%20problem....zip?dl=0 (nearly available) 
I'm french, sorry for my bad english.
If you want to try to fix issue, here's the server link : play.mydisney.tk. The ./pl command is enabled !

**Comment by mg-1999** [comment]
Check #20 for the solutions.

**Comment by Maxi22700** [comment]
Thank's for awnser. Is there any option to lock the view forward of the people onboard the trains ?

**Comment by mg-1999** [comment]
No

Op do 5 nov. 2015 19:39 schreef Maxi22700 <notifications@github.com>:
