### ISSUE TITLE
Showing invalid command when using command to set property with properties that have not been explicitely specified in if-clauses

### ISSUE THREAD

**Issue by bbayu123** [bergerhealer/TrainCarts#301]
##### Spigot version: 1573-j

<hr>

Related to #299

**Comment by bergerkiller** [comment]
The entire property system needs to be rewritten so that it has metadata such as description, usage, aliases, etc. for every property. There should not be a long list of if-clauses at all, but that's how years of laziness made it turn out to be :)

Question is when I finally start working on that

**Comment by bbayu123** [comment]
Closing as it's working in progress, should be released in next TrainCarts release version (supposedly 1.16.4-v2)
