### ISSUE TITLE
Switcher Bug

### ISSUE THREAD

**Issue by TREGuy365** [bergerhealer/TrainCarts#302]
##### Spigot version: 1.13.2

<hr>

#### Problem or bug: Switcher signs only work for trains five carts or less. Any train 6+ carts or more is always switched to the left. The syntax is: 
 [+train]
switcher
1
1

#### Steps to reproduce: 

P.S was going to put in a vid but file was too big

**Comment by bbayu123** [comment]
Update BKCommonLib and TrainCarts to version 1.14.4-v1. Those work on 1.13.2, and check if issue persists there.

**Comment by TREGuy365** [comment]
how do i update? im on an aternos server platform

**Comment by weeryan17** [comment]
You don't use alternos. they don't give you direct control over files witch is needed as they don't have an updated version of bkcommonlib and traincarts

**Comment by TREGuy365** [comment]
and i use linux mint

**Comment by weeryan17** [comment]
What os you use has nothing to do with this unless you plan to host it yourself

**Comment by TREGuy365** [comment]
> You don't use alternos. they don't give you direct control over files witch is needed as they don't have an updated version of bkcommonlib and traincarts

**Comment by TREGuy365** [comment]
well how do i UPDATE?

**Comment by weeryan17** [comment]
You can't on alternos. I said this already.

**Comment by TREGuy365** [comment]
so ill be stuck on 1.13.2?

**Comment by bbayu123** [comment]
If they don't allow you to update, then it's not our problem at this point, contact them for the problem. We can't do anything about your problem.
