### ISSUE TITLE
Switcher Signs Not Working Properly 1.14.4

### ISSUE THREAD

**Issue by TREGuy365** [bergerhealer/TrainCarts#308]
##### Spigot version: 1.14.4

<hr>

#### Problem or bug: Switcher signs don't work when trains roll over them. I have a double track mainline and trains are always being sent to the right, not right, straight, right (vice-versa)
Syntax: Line 1: [train] 
             Line 2: switcher
             Line 3: 1
             Line 4: 1

**Comment by bbayu123** [comment]
Switcher signs need to be powered with redstone or have [!train] / [+train] on the first line in order for them to switch the track

**Comment by TREGuy365** [comment]
I know. i used a redstone torch next to it to power, but my trains(mhmmmmmmhmhmmmmmmhm-Thats the train)never activate it.

**Comment by bbayu123** [comment]
can i take a look at your sign?

**Comment by TREGuy365** [comment]
sure

**Comment by TREGuy365** [comment]
lemmie take a screenshot

**Comment by TREGuy365** [comment]
![Minecradfr](https://user-images.githubusercontent.com/49600812/65818715-dfc6a080-e1d9-11e9-8006-4a79682fcfc2.png)

**Comment by TREGuy365** [comment]
you cant really see the top line, but its [train]

**Comment by TREGuy365** [comment]
and i can send a Video with trains not obeying the signs if you want

**Comment by bbayu123** [comment]
I need the rails as well, and the travel direction of the train with respect to the sign

**Comment by TREGuy365** [comment]
ok

**Comment by TREGuy365** [comment]
![hhhhhhh](https://user-images.githubusercontent.com/49600812/65818834-14872780-e1db-11e9-9d2b-0f72899cc8ff.png)
![bbbbbb](https://user-images.githubusercontent.com/49600812/65818836-1650eb00-e1db-11e9-87c3-5d943799a1c8.png)

**Comment by TREGuy365** [comment]
maybe the lever is causing the problem

**Comment by bbayu123** [comment]
Change the sign
Line 3 `f:1`
Line 4 `r:1`

**Comment by TREGuy365** [comment]
okay

**Comment by TREGuy365** [comment]
what does f:1 and r:1 mean? im not very familiar with mechanics of TC

**Comment by bbayu123** [comment]
By default, line 3 turns the train to the left and line 4 to the right. F means forward, and overrides the left direction

**Comment by TREGuy365** [comment]
ok

**Comment by TREGuy365** [comment]
sadly it didn't work, even with f:1, r:1

**Comment by TREGuy365** [comment]
my trains are pretty long, 19 cars

**Comment by bbayu123** [comment]
Any errors in the console?

**Comment by bbayu123** [comment]
Oh and yes video would help since I can only guess what's happening right now

**Comment by bergerkiller** [comment]
Do you make use of path finding at all? (destination signs)

**Comment by bbayu123** [comment]
Please reopen when you are able to answer the question.
