### ISSUE TITLE
Cart Collision

### ISSUE THREAD

**Issue by DaFuz3** [bergerhealer/TrainCarts#31]
Found a pretty annoying problem that is not allowing me to make something work that alot of time has been spend on. The problem is is when TrainCarts is loaded you are no longer to push a cart, even is the 'allCartsareTraincarts' option is disabled. This is not allowing things such as having carts linked to armor stands or vectors.

The problem still exists when a cart has been made and the plugin is unloaded. however, when you then create a cart while the plugin is unloaded you are able to push that one while the other one remains stationary.

**Comment by mg-1999** [comment]
Enable playerCollision for the train.

Op vr 6 nov. 2015 21:35 schreef DaFuz3 <notifications@github.com>:

**Comment by DaFuz3** [comment]
Hmm. Enabled every type of collision there is but doesn't seem to work. Any specific option I need to look at?

**Comment by mg-1999** [comment]
What kind of movement are you trying to accomplish?

Op vr 6 nov. 2015 22:31 schreef DaFuz3 <notifications@github.com>:

**Comment by DaFuz3** [comment]
Basicly carts stuck to an armor stand. the armor stand moves but the cart is not because of this.

**Comment by mg-1999** [comment]
I have on my personal server traincarts installed and we can still move the
carts with TrainCarts only we use a custom entity for the minecarts so it
doesn't interfere with TrainCarts.

Op za 7 nov. 2015 11:27 schreef DaFuz3 <notifications@github.com>:

**Comment by DaFuz3** [comment]
Hmm. I guess that's why when we want to have the minecarts move by something that is not a sign or a player it doesn't work with the option enabled... Do you know any fix for this because it is quite essential of what we are trying to accomplish. Maybe that when vectors are used to move traincarts they don't become unlinked?

**Comment by mg-1999** [comment]
What we do is create a custom minecart entity and put in in a "group" and
then we apply the vector to the group and they all move together nicely

Op za 7 nov. 2015 16:48 schreef DaFuz3 <notifications@github.com>:
