### ISSUE TITLE
Empty map 1.14.4

### ISSUE THREAD

**Issue by IIuoneR** [bergerhealer/TrainCarts#310]
##### Spigot version: git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

<hr>

#### Problem or bug:
Map empty
https://pastebin.com/C2qRh9RK

**Comment by bergerkiller** [comment]
Known issue, update protocollib to the latest version. They removed a library from the server that protocollib used, as a result, the plugin broke. Newer versions of protocollib have included that library inside the jar itself to fix this issue.
