### ISSUE TITLE
Kick from the server

### ISSUE THREAD

**Issue by IIuoneR** [bergerhealer/TrainCarts#311]
BkCommonLib version: 1.14.4-v1
TrainCarts version: 1.14.4-v1
Spigot version: git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

<hr>

#### Problem or bug:
Opened the configuration through the card. Chose train change. I flipped through the blocks, kicked through several blocks and did not let them into the server anymore.
Console kick: 
"IIuoneR lost connection: Internal Exception: java.lang.IllegalArgumentException: Unknown object entity network type id 51"

*sorry for english.

**Comment by bergerkiller** [comment]
Are you by chance connecting through viaversion?

**Comment by bergerkiller** [comment]
Network type id 51 appears to be a painting, but when I spawn that one myself it works just fine. (though it moves in block steps). Do you have anything in the server log that might help?

**Comment by bergerkiller** [comment]
Not sure if it'll help you, but it's worth a try. https://github.com/bergerhealer/TrainCarts/commit/6fa6017d1fd1f29ff8b9dff715e35bcc1dce35d7

https://ci.mg-dev.eu/job/TrainCarts/529/

**Comment by IIuoneR** [comment]
The server has ProtocolSupport
I usually connect from 1.12.2.
Caused an error on 1.12.2.
Then I tried to connect with 1.14.4 but it did not help.

*Your version does not start
https://pastebin.com/KCWzYFPC

**Comment by bergerkiller** [comment]
You need BKCommonLib too:
https://ci.mg-dev.eu/job/BKCommonLib/631/

**Comment by IIuoneR** [comment]
new
https://pastebin.com/nUA6s7XG

**Comment by bergerkiller** [comment]
So its -1 now. Ill look at the npe that comes before in an hour when I get home, its very likely related.

**Comment by bergerkiller** [comment]
![ScreenShot_2019-10-04 18-28-20](https://user-images.githubusercontent.com/957601/66223838-becbe700-e6d4-11e9-8e9a-0a1338ef077b.png)
Ive added error checking inside BKCommonLib for entity types being set in packets that aren't actually supported. I'll exclude these problematic entity types from the list in Traincarts. This silent failing was causing entity type id to be set to -1 or 0, which is obviously not good as a silent failure.

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/BKCommonLib/632/
https://ci.mg-dev.eu/job/TrainCarts/530/

This should hopefully end the kicking. Also fixes the error you had, though it was unrelated to this bug.

**Comment by IIuoneR** [comment]
and new :(
IIuoneR lost connection: Internal Exception: java.lang.IllegalArgumentException: Unknown object entity network type id 23

**Comment by bergerkiller** [comment]
Can you confirm this happens when you select the ender signal entity in the traincarts menu?

Im starting to think this error comes from ProtocolSupport so Im installing that now to test

**Comment by bergerkiller** [comment]
This should do it. https://ci.mg-dev.eu/job/TrainCarts/531/

**Comment by bergerkiller** [comment]
A more serious issue is that, when I use protocolsupport on 1.14.4, it completely breaks entity movement updated. I'm afraid protocol support doesn't really work well together with traincarts.

**Comment by bbayu123** [comment]
Late update, I believe ProtocolSupport is now working with the latest build of TrainCarts. You may want to take a look if it works :)
