### ISSUE TITLE
Attachments Editor resets the sub-attachment model back to the state when the editor is opened when the player enters the Appearance menu of that sub-attachment

### ISSUE THREAD

**Issue by bbayu123** [bergerhealer/TrainCarts#315]
##### Spigot version: MC 1.12.2 b1571-j

<hr>

#### Problem or bug:
Attachment resets when entering appearance menu if the attachment is changed externally after the editor is opened

#### Expected behaviour:
Don't reset it

#### Steps to reproduce:
1. Select a train and open the attachments editor
2. Change one of the sub-attachments to a different model (data value)
3. Select the same sub-attachment that was just changed and enter the Appearance menu
4. Watch that the attachment resets to the state in Step 1

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/TrainCarts/commit/a82916506913184c53351cbbae5b9caea403b0ea

You do have to actually re-open the attachment's menu for it to reload the configuration. It will not live update the appearance/animation/etc. menus while you have it open.

**Comment by bbayu123** [comment]
Good enough, I can see this as resolved
