### ISSUE TITLE
Train Attachments, Y position of a minecart

### ISSUE THREAD

**Issue by MrKittle** [bergerhealer/TrainCarts#316]
##### Spigot version: 1.12.2-R0.1 SNAPSHOT

<hr>

**Comment by bergerkiller** [comment]
It cannot be changed sadly. The minecart is snapped to the rails on the client side, and any changes above the rail have no effect. The only way around it is not using minecart entities, or by having 'fake rails' using armorstands

**Comment by MrKittle** [comment]
Thank you  for your answer :-)
Cordially.
