### ISSUE TITLE
TrainProperties.yml blockBreakTypes lists grow unbounded duplicating materials

### ISSUE THREAD

**Issue by blubberdiblub** [bergerhealer/TrainCarts#318]
##### Spigot version: git-Paper-221 (MC: 1.14.4)

<hr>

#### Problem or bug:

Since a few versions (I usually keep TC and the lib updated from the dev builds on a roughly weekly basis) `TrainProperties.yml` for existing trains gain duplicate blockBreakTypes each time the server is restarted.

I've got a couple of materials (grass, fern, flowers) in `blockBreakTypes` of `DefaultTrainProperties.yml` and it appears that since one or two weeks or so it just appends the items to the block break type lists of all carts in `TrainProperties.yml` causing unnecessary duplicates and blowing up the size.

#### Expected behaviour:

`blockBreakTypes` in `TrainProperties.yml` keeps the same items in the list as before when restarting and doesn't add duplicates.

#### Steps to reproduce:

1. add some block types to all `blockBreakTypes` lists in `DefaultTrainProperties.yml`, such as `- GRASS` and `- FERN`
2. reload config
3. place a minecart or train
4. restart the server a few times
5. see the lists in `TrainProperties.yml` grow longer each time by another set of the same materials

**Comment by bergerkiller** [comment]
This almost certainly has to do with the recent yaml changes, looking into it now

**Comment by bergerkiller** [comment]
Not a bug in BKCommonLib, but just a bug in TC that always existed but didn't trigger because it created a new file configuration object every time it saves. To optimize it this was changed, and now that bug appears. Thanks for reporting it!

https://ci.mg-dev.eu/job/TrainCarts/544/

**Comment by blubberdiblub** [comment]
That appears to have fixed it. Thank you.
