### ISSUE TITLE
Pathfinding fails when it should be able to succeed

### ISSUE THREAD

**Issue by TheAppleFreak** [bergerhealer/TrainCarts#320]
##### Spigot version: PaperMC 233

<hr>

#### Problem or bug: 
When using the pathfinding feature, it is possible to break TrainCart's ability to pathfind between different points even though the minecart should be able to navigate to the destination without a problem. Regardless of how the destination is set (`/train dest`, destination signs, or property signs), it is possible for the pathfinding to fail.

This video demonstrating the issue was recorded on a local test world I made to learn how best to use the plugin. Clearly the track layout demonstrated should allow trains to move between points just fine, but it doesn't. 

https://youtu.be/6LWhrFY_NQE

#### Expected behaviour:

The train should be able to navigate from destination e1 to destination e2 without issue.

#### Steps to reproduce:

1. Create a single track with a passing loop in the center. Make both switches switchers, add two blockers, and set a destination at both ends. 
2. Set the destination of a minecart at one end to the other end, then push it through the passing loop. It may take several tries before the issue manifests.

**Comment by bbayu123** [comment]
Hi, can you try reproducing the issue using the latest snapshots of bk and tc? Please provide the build numbers if the issue persists even after updating. The 1.15 snapshots are compatible with your version of paper.

**Comment by bbayu123** [comment]
I will be closing this for now. Please reopen if this issue persists.
