### ISSUE TITLE
Server Crashes when passing an announcer

### ISSUE THREAD

**Issue by Antlucl** [bergerhealer/TrainCarts#324]
##### Spigot version: 1.13.2 (1a3504a-dfa7583)

<hr>

#### Problem or bug: 

When driving over an announcer with a SignLink variable on it, the server crashes (the thing is though, that on 90% of them it works fine). The reason I have a SignLink variable on it is to announce the destination of the train. I am however not sure if this is an official feature that you can use SignLink variables on announcers, and if It's not then I understand that there isn't a way to fix this bug. 

When a train drivers over the announcer, it produces the following error code:
`29.12 18:45:57 [Server] ERROR Current Thread: Server thread
29.12 18:45:57 [Server] ERROR PID: 18 | Suspended: false | Native: false | State: RUNNABLE
29.12 18:45:57 [Server] ERROR Stack:
29.12 18:45:57 [Server] ERROR java.lang.String.toLowerCase(String.java:2670)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.sl.API.Variable.get(Variable.java:89)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.tc.TrainCarts.sendMessage(TrainCarts.java:151)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.tc.signactions.SignActionAnnounce.sendMessage(SignActionAnnounce.java:17)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.tc.signactions.SignActionAnnounce.execute(SignActionAnnounce.java:49)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:277)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.tc.controller.components.SignTrackerGroup.onSignChange(SignTrackerGroup.java:47)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.tc.controller.components.SignTracker.updateActiveSigns(SignTracker.java:104)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.tc.controller.components.SignTrackerGroup.refresh(SignTrackerGroup.java:193)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:1456)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1382)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.tc.controller.MinecartMember.onTick(MinecartMember.java:1906)
29.12 18:45:57 [Server] ERROR com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:118)
29.12 18:45:57 [Server] ERROR com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen129b95ae.invokeVA(Unknown Source)
29.12 18:45:57 [Server] ERROR com.bergerkiller.mountiplex.reflection.util.FastMethod.invokeVA(FastMethod.java:112)`

#### Expected behaviour: 
For an announcment to pop up with the destination (as it has previously triggered the same variable) Usually works except for at a few signs like this one I'm reporting about right now.

#### Steps to reproduce: 
Make an announcer sign with a signlink variable on it (ex; %platform1D%) which has then been triggered by a train, and then drive over it.

Sorry if I wrote something the wrong way - it's my first time posting an issue here.

**Comment by bbayu123** [comment]
Please update BKCommonLib, TrainCarts and SignLink to the latest version on spigot (1.14.4-v1) and try again. It is compatible with 1.13.2.

**Comment by Antlucl** [comment]
Tried again with 1.14.4-v1, and still recieved the same error.

**Comment by bbayu123** [comment]
Can you provide the updated error and the output of commands `/train version` and `/variable version`?

**Comment by bbayu123** [comment]
Also, I don't think you are running the latest build of Spigot 1.13.2. There should be a more up-to-date version of Spigot 1.13.2. Try building Spigot 1.13.2 again using build tools and run your server with that. However, I don't think that would be the fix. (Either that or you provided incorrect build numbers)

**Comment by Antlucl** [comment]
Train version: Train_Carts v1.13.2-v1 (build: 431) using BKCommonLib v1.13.2-v3 (build: 534)

Variable version: SignLink v1.14.4-v1 using BKCommonLib v1.13.2-v3 (build: 534)

`08.01 21:05:18 [Server] ERROR Spigot version: git-Spigot-1a3504a-dfa7583 (MC: 1.13.2)
08.01 21:05:18 [Server] ERROR ------------------------------
08.01 21:05:18 [Server] ERROR Server thread dump (Look for plugins here before reporting to Spigot!):
08.01 21:05:18 [Server] ERROR ------------------------------
08.01 21:05:18 [Server] ERROR Current Thread: Server thread
08.01 21:05:18 [Server] ERROR PID: 18 | Suspended: false | Native: false | State: RUNNABLE
08.01 21:05:18 [Server] ERROR Stack:
08.01 21:05:18 [Server] ERROR com.bergerkiller.bukkit.tc.TrainCarts.sendMessage(TrainCarts.java:151)
08.01 21:05:18 [Server] ERROR com.bergerkiller.bukkit.tc.signactions.SignActionAnnounce.sendMessage(SignActionAnnounce.java:17)
08.01 21:05:18 [Server] ERROR com.bergerkiller.bukkit.tc.signactions.SignActionAnnounce.execute(SignActionAnnounce.java:49)
08.01 21:05:18 [Server] ERROR com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:277)
08.01 21:05:18 [Server] ERROR com.bergerkiller.bukkit.tc.controller.components.SignTrackerGroup.onSignChange(SignTrackerGroup.java:47)
08.01 21:05:18 [Server] ERROR com.bergerkiller.bukkit.tc.controller.components.SignTracker.updateActiveSigns(SignTracker.java:104)
08.01 21:05:18 [Server] ERROR com.bergerkiller.bukkit.tc.controller.components.SignTrackerGroup.refresh(SignTrackerGroup.java:193)
08.01 21:05:18 [Server] ERROR com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:1456)
08.01 21:05:18 [Server] ERROR com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1382)
08.01 21:05:18 [Server] ERROR com.bergerkiller.bukkit.tc.controller.MinecartGroupStore.doFixedTick(MinecartGroupStore.java:32)
08.01 21:05:18 [Server] ERROR com.bergerkiller.bukkit.tc.TrainCarts$TrainUpdateTask.run(TrainCarts.java:574)
08.01 21:05:18 [Server] ERROR org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
08.01 21:05:18 [Server] ERROR org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
08.01 21:05:18 [Server] ERROR net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
08.01 21:05:18 [Server] ERROR net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
08.01 21:05:19 [Multicraft] Skipped 693 lines due to rate limit (30/s)`

Then in the end Multicraft skipped 693 lines, so I don't know what they said.

Should I update BKCommonLib and TrainCarts as well?

Okay, will look into updating Spigot. Thanks.

**Comment by bbayu123** [comment]
You should have updated those (BK and TC) ;)

**Comment by Antlucl** [comment]
Oh, I misred that, thought it only said SignLink. My bad, and thanks for the help!

**Comment by bbayu123** [comment]
Updating fixed it right? I shall close this then.
