### ISSUE TITLE
Train always goes maxspeed

### ISSUE THREAD

**Issue by ChickenAChicken** [bergerhealer/TrainCarts#325]
##### Spigot version: 1.14.4 

<hr>

#### Problem or bug:
Train always goes the max speed and cannot slow it down unless changing the max speed. Can't make a drop with a gradual gain in speed. *Also always has high energy* in /train info

#### Expected behaviour:
Have the train stay the same speed even if max speed is increased to over its current.

#### Steps to reproduce:
1.  Spawn in train
[train]
spawn
mmm
2.  Push train into station 
[train]
station
3
continue
3. set maxspeed to 0.1 (to recreate a chainlift)
[train]
property
maxspeed
0.1
4. Raise maxspeed to let train gradually gain speed downhill
[!train] (does not work without the '!')
property
maxspeed
1

**Comment by bbayu123** [comment]
Stations always launch the train at high energy, either reduce the energy launched by stations in the config or manually launch the trains to a lower energy state.

**Comment by ChickenAChicken** [comment]
Works perfectly now, thanks.
