### ISSUE TITLE
Incorrect lighting after using ejector sign

### ISSUE THREAD

**Issue by HIHIQY1** [bergerhealer/TrainCarts#329]
##### Minecraft version: 1.15.2 (vanilla)

<hr>

#### Problem or bug:
Incorrect lighting
![Incorrect lighting](https://puu.sh/F87Ak/16838920cb.png)
F3+A does not fix the problem.
F3+T does not fix the problem.
Rejoining the world fixes the problem (temporarily, until ejector is used again).

#### Expected behaviour:
![Expected](https://puu.sh/F87zB/4c545c4e68.png)

#### Steps to reproduce:
![Cart on rails](https://puu.sh/F87Vh/1df087f975.png)
1. Build the thing as shown above.
  \- Important thing is that you need to fill in at least line 3 and/or line 4 on the sign with coordinates.
  \- Include the torch, too.
2. Make it night time (18000)
3. Add and then push the car.
4. Enter the car before it rolls over the sign.
5. You get ejected out of the car. Press F3+A or build something in the chunk to update the lighting. The lighting will be different than before.

**Comment by bergerkiller** [comment]
Huh, that's a new one. I'll see if I see anything similar, but it almost seems like a clientside bug. It does look like lighting data is either erased, or chunk data is sent to players without lighting data in it.

Do you use light cleaner by chance?

**Comment by HIHIQY1** [comment]
\> Do you use light cleaner by chance?
No.

\> Are the coordinates put on the sign near to the sign itself or far away?
Ejector sign coordinates are always relative to the position of the cart.

**Comment by weeryan17** [comment]
> Ejector sign coordinates are always relative to the position of the cart.

That doesn't tell us if its near or far, relative coordinates can still teleport you far away,

**Comment by HIHIQY1** [comment]
> That doesn't tell us if its near or far, relative coordinates can still teleport you far away.

The coordinates are on the sign provided in the 3rd image. -2/1/-2 Doesn't seem like that far away from the cart to me.

**Comment by bergerkiller** [comment]
Ill test it out in an hour, if you got time, can you check whether the same glitch occurs with this build of BKCommonLib: https://ci.mg-dev.eu/job/BKCommonLib/686/

This is prior to a significant change to passenger handling that fixed issues with MC 1.8 - MC 1.13, which might be related

**Comment by HIHIQY1** [comment]
Yes, the bug still occurs with that build of BKCommonLib.

**Comment by bergerkiller** [comment]
Im not seeing the same bug, but the ejector sign is behaving really strangely, not actually ejecting me. I'll try and see what is going on and let you know when I've made some fixes

**Comment by bergerkiller** [comment]
I think I found the problem. To perform teleportation without the movement inbetween, it had code to despawn and respawn. This was also done for player entities. In the past this may have worked fine, but on 1.15 it causes all chunks to be resent (causing lag/stutter), likely also explaining your bug with the lighting getting removed.

See if things improve: https://ci.mg-dev.eu/job/BKCommonLib/690/

This does sort of re-open an issue with the elevator/train teleportation logic, because I do notice that this despawning-respawning doesn't work properly anyhow.

**Comment by HIHIQY1** [comment]
I think this fixed it. Thanks!
