### ISSUE TITLE
Hooking into minecart movement to get cart position

### ISSUE THREAD

**Issue by harm27** [bergerhealer/TrainCarts#33]
Hello,

For a server i work for they want a plugin to monitor for specific trains what positions this train moves to.
Is it in some way possible that i can hook in a event or override a function so that i can log positions into a file?

I can edit the jar, by adding something in the current code. 
But it is then broken after an update.

I was looking for a nice way of doing it without editing traincarts, but then i can't find a way to constant watching the position of the train. 
I saw already a function in MinecartMember, doPostMoveLogic, but i can't figure out a way to hook into that function nicely.

Harm(Harm27)

**Comment by mg-1999** [comment]
I am putting the JavaDocs online, so you can check that for some functions. Also i will add the an event for it if needed.

**Comment by harm27** [comment]
Oke, thanks. I will look into it.
I will conversate with the people who asked me to develop this to discuss what we are going to do.
If i need it, i will let it know.

Harm

**Comment by mg-1999** [comment]
Check http://jd.mg-dev.eu/tc for the javadocs
