### ISSUE TITLE
A strange bug with TCC/ Train carts

### ISSUE THREAD

**Issue by Disneykid93** [bergerhealer/TrainCarts#331]
##### Spigot version: 1.15.2

<hr>

**Comment by bergerkiller** [comment]
I have a difficult time comprehending what you're saying in the video, in part because of the poor audio. Can you put in text a summary of what it is you're experiencing?

**Comment by bbayu123** [comment]
I think he's having trouble with command blocks not providing block updates for traincarts signs when command blocks remove/place torches, we need the build number in that case.

**Comment by Disneykid93** [comment]
Yeah sorry about my poor mic quality, But bbayu123 is right and it is weird that in the video it has no problem when its the one car alone on that right side but then when two are there waiting on the left and right then it would not work. I do have a work around to just place and remove a block underneath the car like i showed in the video and that is making it work, but it seems i still have problems with the particular car not catching speed limit signs when its launched from that side and in some parts of the ride. Also the build number is (567)

**Comment by bergerkiller** [comment]
This isnt simply related to some spigot.yml options to enable redstone updates causing physics?

**Comment by Disneykid93** [comment]
I'm not sure, Because I'am using the same redstone system mirrored on both sides to power the dispatch stations and its only been the right dispatch that has issues as shown, The left one has no problem what so ever so I'm guessing it'something with the track going on an angle? I'm even having problems with the switchers under it at times, It will stop activating the switcher sign unless i get out and back in he car or i would move the sign on a different block face and it would go back to working as intended. I have always had problems on that particular track section, but before it was because the track nodes were too close together.

**Comment by bbayu123** [comment]
Probably would be a good idea to set that option to true first, the one where physics are triggered on redstone

**Comment by Disneykid93** [comment]
OK well this is now really weird, I haven't set the config like you had said but now all of a sudden it works. I did another video so I hope you can hear me better but it shows that it now works like it should and i haven't changed any plugin configs at all. https://www.youtube.com/watch?v=uRJcyuPJ5WY

**Comment by bbayu123** [comment]
Interesting, well not plugin config, the one line we wanted you to change is in paper.yml, but that does indeed sound like a weird bug. Meanwhile, please always provide the build numbers of bk and tc, as it would be impossible to decipher whether it has already been fixed in a newer snapshot without it.

**Comment by Disneykid93** [comment]
I will be sure to include the build numbers next time, I just forgot to do that when i first did the report. But at least if it starts to happen again i have a work around, now i just got to figure out why it wont trigger a certain speed limit sign when launched from that side.

**Comment by bbayu123** [comment]
Yea again, I'd say ensure the paper.yml option is set properly before you test further, or you'd be testing on an environment that is known to not be fully compatible with traincarts.

**Comment by Disneykid93** [comment]
Will do.

**Comment by bbayu123** [comment]
Any update?

**Comment by Disneykid93** [comment]
I haven't seen it happen again so far, But i will let you guys know if it does again.
