### ISSUE TITLE
Train Sound issue

### ISSUE THREAD

**Issue by TMCThomas** [bergerhealer/TrainCarts#333]
#### Expected behaviour:
No moving train sound while the train is not moving.
#### Steps to reproduce:
Launch a train with the launch sign at a high speed for example 100, further on the track make a speedlimit sign which is set to 0.

**Comment by bergerkiller** [comment]
Interesting that this bug (still) exists, I thought I patched it.

A workaround is to create a property sign like so:
```
[+train]
property
sound
false
```

**Comment by bbayu123** [comment]
Marking issue as HW, requires crossed out from WIP list in order to be closed.

**Comment by Vlader97** [comment]
For me it works correctly.
BkCommonLib: 1.15.2-v3
TrainCarts: 1.15.2-v2-611
Paper: 1.15.2-165

**Comment by bergerkiller** [comment]
I'll close this then
