### ISSUE TITLE
Some properties get wiped when the ticket has an empty properties ConfigurationNode

### ISSUE THREAD

**Issue by bbayu123** [bergerhealer/TrainCarts#334]
Some people want tickets to not override train properties, i.e. to use it only as a check to board trains. Is it possible to check whether the ticket properties are empty, and if so, not clone the properties onto the train?
See image attachment for an example of empty properties.
![image](https://user-images.githubusercontent.com/26726381/75334258-6d1c3700-58d7-11ea-8e6c-bbf03473b113.png)

Reference: Relevant file and line
https://github.com/bergerhealer/TrainCarts/blob/ea6ce1a4e15b173fbb7df1b256325a74b13dd4e0/src/main/java/com/bergerkiller/bukkit/tc/tickets/TicketStore.java#L388

**Comment by bergerkiller** [comment]
Strange thing is though, the load() keeps the original properties the train has when those keys aren't in the yaml. So with an empty settings block, the properties should be left unchanged. What properties are observed to be reset or change?

**Comment by bbayu123** [comment]
Oh really, I didn't dig any further, so I wasn't aware of this. Someone else in Discord was mentioning that they didn't want tickets overwriting their train properties, so I thought this wasn't a thing yet.

**Comment by bbayu123** [comment]
Update: It shouldn't have gotten reset in the first place, so now it's declared a bug.
Most properties are not wiped, but it has been noticed that some are wiped, so those need to be patched.

**Comment by bbayu123** [comment]
Should be fixed in latest dev builds, closing this.
