### ISSUE TITLE
NoClassDefFoundError causes StackOverFlowError and freezes server

### ISSUE THREAD

**Issue by Joren2087** [bergerhealer/TrainCarts#336]
##### Spigot version: paper-1.14.4-b243

<hr>

#### Problem or bug:
Getting the group of a MinecartMember spawned as a saved train in SavedTrainProperties causes a weird error: java.lang.NoClassDefFoundError: Could not initialize class com.bergerkiller.bukkit.tc.properties.TrainProperties - and causes an infinity loop with a StackOverFlowError as result.

This happens in my listener for the MemberAddEvent. 
Listener code:

```java
    @EventHandler(priority = EventPriority.HIGHEST)
    public void onMemberLink(MemberAddEvent event) {
        AbstractTrain train = RideCore.getTrainByGroup(event.getGroup());

    }
```
You can see in the stacktrace that it is not my plugin (eu.plopsamc.xxx) that causes the issue, it's the event.getGroup() method call:
```
	at com.bergerkiller.bukkit.tc.events.MemberAddEvent.call(MemberAddEvent.java:22) ~[?:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.add(MinecartGroup.java:258) ~[?:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroupStore.create(MinecartGroupStore.java:88) ~[?:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroupStore.create(MinecartGroupStore.java:74) ~[?:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartMember.getGroup(MinecartMember.java:207) ~[?:?]
	at com.bergerkiller.bukkit.tc.events.MemberEvent.getGroup(MemberEvent.java:19) ~[?:?]
	at eu.plopsamc.ridecore.traincarts.listeners.traincarts.LinkListener.onMemberLink(LinkListener.java:33) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor65.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.14.4-b243.jar:git-Paper-243]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.14.4-b243.jar:git-Paper-243]
```
I've tried a server restart, but still got the same issue.

The version I've downloaded is from the spigot page and not from other third-party sites.
#### Expected behaviour:
Just get a MinecartGroup of the member and if none exists without any issues.

#### Steps to reproduce:
1. Set a sign with the following text under a rail (with the savedTrainproperties loaded):
```
[train]
spawn
coaster1
```
2. Trigger the sign by pressing a button
3. enjoy an overflown console

#### Stacktrace:
https://paste.md-5.net/hazebizuci.sql
Note: The stacktrace is much larger (log file is 47mb, server was only 1m online). I just can't paste a whole 47mb in a hastebin and GitHub only supports files up to 10mb. Definitely an infinity loop is causing this.

#### Solution???
Somehow the SavedTrainProperties.yml file in the TrainCarts plugin folder got deleted and after a server restart only minecarts without any attachments spawned.

Could the SavedTrainProperties be corrupt?
[SavedTrainProperties.txt](https://github.com/bergerhealer/TrainCarts/files/4302477/SavedTrainProperties.txt)

**Comment by bbayu123** [comment]
Something that is not your plugin is causing it right? Can you remove the plugin and see what happens first? If it's something wrong with that plugin, we can't help you with it, unless it's your own.

**Comment by bbayu123** [comment]
We don't provide support for the RideCore plugin btw, if that's what you were wondering.

**Comment by Joren2087** [comment]
RideCore is my own custom Plugin. I've reported this issue here because I think it's traincarts that is causing the problem and not my Plugin. I can provide you tomorrow with the code behind getTrainByGroup(). It basically gets my custom train object out of a HashMap with the train name as key.

I will also try tomorrow to remove the Plugin and check for any issues.

However I don't think my Plugin could cause a ClassDefNotFoundError. This is a serious JVM error and should not be able to produce with the code I'm using. 

It is possible I've implemented the Traincarts API wrong. By my opinion, in general, the traincarts documentation is very incomplete.

**Comment by Joren2087** [comment]
So I've tried to reproduce this bug and it made things worse.
Now the JVM crashed instead of the server.

So here is the console log: https://paste.md-5.net/luhuvudigi.md
'Member linked' is printed each time the MemberAddEvent is called (and that's a lot)

Here is the code I've used. 
```java
    @EventHandler(priority = EventPriority.HIGHEST)
    public void onMemberLink(MemberAddEvent event) {
        try{
            System.out.println("Member linked");
            AbstractTrain train = RideCore.getTrainByGroup(event.getGroup());

            if(train != null) {
                System.out.println(train.getName() + " linked " + ((TrainCartsTrain) train).getTcGroup().head().getEntity().getLocation().toVector());

            }
        }catch (NoClassDefFoundError e) {
            e.printStackTrace();
            Bukkit.shutdown();
        }


    }
```
The catch clause also never caught the exception.

I've done what you've said and removed my custom plugin and tried again. Without my plugin everything works fine, so it's the event that causes the problem.

Later I've removed the RideCore.getTrainByGroup() line and got still the same issue (crash log is attached)
Code:
```java
    @EventHandler(priority = EventPriority.HIGHEST)
    public void onMemberLink(MemberAddEvent event) {
        try{
            System.out.println("Member linked");
            MinecartGroup group = event.getGroup();
            System.out.println(group);
        }catch (NoClassDefFoundError e) {
            e.printStackTrace();
            Bukkit.shutdown();
        }
    }
```

So it's seem to me like a TrainCarts API issue and not mine.

I've noticed there is a event.getTo() function that returns a MinecartGroup. If I use that it still works fine. However I need the MinecartMember that wants to link to another group it's group and not the group the minecart wants to connect with.

Got any ideas for a workaround or?
[latest.log](https://github.com/bergerhealer/TrainCarts/files/4303533/latest.log)

**Comment by bergerkiller** [comment]
Calling .getGroup() of the member in the member add event appears to cause the problem

**Comment by Joren2087** [comment]
It could be yes, but how do I work around this?
Could you maybe provide a fix?

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/TrainCarts/commit/4c388d703ccf9684acb620ce4bedfd985ce9fe1e see if this works

https://ci.mg-dev.eu/job/TrainCarts/597/

**Comment by Joren2087** [comment]
> [4c388d7](https://github.com/bergerhealer/TrainCarts/commit/4c388d703ccf9684acb620ce4bedfd985ce9fe1e) see if this works
> 
> https://ci.mg-dev.eu/job/TrainCarts/597/
> 
> Btw, the Group value of the member is the previous group before it was added to another train. The toGroup property has the new group. Changing this to instead have a 'getPreviousGroup()' property and perform this event after the member was added might be better, the event can't be cancelled anyway.

Yeah I've noticed that while I was testing my plugin.

So good news, my console stays clean and doesn't get blown up with errors thanks to the fix.
In other words, the issue is fixed. The event is now called 3 times for 4 carts spawning what exactly is what it is supposed to do.

And like you said, It would be helpful if the method names in some events were more clear.
In general the API documentation is a mess by my opinion.

Issue solved I guess?
Thanks for the help!
