### ISSUE TITLE
Plugin not working after reload

### ISSUE THREAD

**Issue by Sander0542** [bergerhealer/TrainCarts#338]
##### Spigot version: 1.15.2

<hr>

#### Problem or bug:

When the server starts, then the plugin loads fine. But when I do `/reload`, then the plugin does not load.

#### Expected behaviour:

The plugin works after a reload

#### Steps to reproduce:

Command: `/reload`

**Comment by weeryan17** [comment]
The plugins do not support reload as reload its self is a little broken, and reload is generally not recommended anyways.

**Comment by Sander0542** [comment]
Oh, okay. Normally I don't use `/reload`, but I am adding support for Ticket Signs to the plugin. During testing, I noticed that it wasn't working.

**Comment by bbayu123** [comment]
Closing with tag wontfix.
