### ISSUE TITLE
Divecoaster with Traincarts

### ISSUE THREAD

**Issue by harm27** [bergerhealer/TrainCarts#34]
Hey guys,

I am working on a solution for a divecoaster with 3 carts, with the middle cart on the rails/ladders.
That was the reason of my previous issue.
Only i can't get it working.

I do regular Java development, but i came stuck on this.
Do you have any idea or time to work on a traincarts divecoaster component?

It is not like hangrail or action block a independent component, but it base is the same as the normal trains, a rail or ladder to drive on. 

If needed i can help coding that plugin, but on this moment i don't know a working idea. 

Sorry for my bad english, my normal language is dutch, so sometimes english is a little bit a struggle to write.

Greetings,

Harm (Harm27)

**Comment by mg-1999** [comment]
Hello Harm,

You are not the only Dutch one here, I am also Dutch :P Are you creating
the baron? Also I don't know how I would create this but I am going to get
some information from my own dev team and will get back to you.

mg-1999

Op ma 7 dec. 2015 19:28 schreef harm27 <notifications@github.com>:

> Hey guys,
>
> I am working on a solution for a divecoaster with 3 carts, with the middle
> cart on the rails/ladders.
> That was the reason of my previous issue.
> Only i can't get it working.
>
> I do regular Java development, but i came stuck on this.
> Do you have any idea or time to work on a traincarts divecoaster component?
>
> It is not like hangrail or action block a independent component, but it
> base is the same as the normal trains, a rail or ladder to drive on.
>
> If needed i can code to at that plugin, but on this moment i don't know a
> working idea.
>
> Sorry for my bad english, my normal language is dutch, so sometimes
> english is a little bit a struggle to write.
>
> Greetings,
>
> Harm (Harm27)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/34>.
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by harm27** [comment]
Hey Matthijs,

Jep.
Is fine. 

Harm

**Comment by harm27** [comment]
Hey,

Another problem is that the lifthill is raising a block per two blocks. 
Like 
![image](https://cloud.githubusercontent.com/assets/2715359/11661092/73f0053c-9dd0-11e5-98fa-a0c46e636710.png)

Harm

**Comment by mg-1999** [comment]
That is something I can't do anything about.

Op di 8 dec. 2015 17:24 schreef harm27 <notifications@github.com>:

> Hey,
>
> Another problem is that the lifthill is raising a block per two blocks.
> Like
> [image: image]
> <https://cloud.githubusercontent.com/assets/2715359/11661092/73f0053c-9dd0-11e5-98fa-a0c46e636710.png>
>
> Harm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/34#issuecomment-162935148>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by harm27** [comment]
Hey Matthijs,

Oke, then that comes to my attraction builders to decide or solve.

Harm

**Comment by harm27** [comment]
Hey Matthijs,

I get questions from the builders how long it will take before they can open the attraction.
Do you have any idea how long it gonne take you to get a first version for this component?

Harm

**Comment by mg-1999** [comment]
Not soon, because I can't just copy paste existing code and edit it a
little bit. It is way more difficult, I need to write a thing that copy's
the minecarts velocity and then adjust it to the minecart it needs to be
applied to. So you can make this yourself if you want and could submit a
pull request and I will take a look at it.

Op za 12 dec. 2015 12:00 schreef harm27 <notifications@github.com>:

> Hey Matthijs,
>
> I get questions from the builders how long it will take before they can
> open the attraction.
> Do you have any idea how long it gonne take you to get a first version for
> this component?
>
> Harm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/34#issuecomment-164139028>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by harm27** [comment]
Hey Matthijs,

I already looked in to it and i can't fix that.
My knowledge is not so far in spigot/bukkit and traincarts.
And Math is not my strongest point.

I will say to the the builders that they need to be patiënt. 

Harm

**Comment by mg-1999** [comment]
Sorry for the late reply, but we are sort of making progress. We copy the velocity of the middle cart to the 2 outer carts. The outer carts are custom minecart entities so we can apply physics while in the air.

**Comment by harm27** [comment]
Hey Matthijs,

Nice work. 
I will tell them that.

Harm
