### ISSUE TITLE
(1.12.2) in the newest version of 1.12.2 the items with models as attachments dont work.

### ISSUE THREAD

**Issue by Calebplaysgames** [bergerhealer/TrainCarts#340]
##### Spigot version: Newest 1.12.2

<hr>

**Comment by bbayu123** [comment]
Outdated Version. Please update your BKCommonLib to 1.15.2-v2 and TrainCarts to 1.15.2-v1. Both of these versions work on Spigot 1.12.2.

**Comment by Calebplaysgames** [comment]
still doesnt work

**Comment by bbayu123** [comment]
What exactly did you do? Without steps to reproduce, we can't help you with your issue.

**Comment by Calebplaysgames** [comment]
I well added the addons then I did /train attachments it popped up the attachments menu when i got near the cart and then when I selected the desired damage value for the diamond sword it didnt work

**Comment by Calebplaysgames** [comment]
?

**Comment by bbayu123** [comment]
Did you install a resource pack that has the models?

**Comment by bbayu123** [comment]
You still need help?

**Comment by bbayu123** [comment]
Closing this, for now, feel to reopen whenever you can give more information regarding this issue.
