### ISSUE TITLE
TrainCarts does not work on Tuinity

### ISSUE THREAD

**Issue by breadbyte** [bergerhealer/TrainCarts#341]
##### Spigot version: git-Tuinity-"f036785" [Tuinity](https://github.com/Spottedleaf/Tuinity) | [commit f036785](https://github.com/Spottedleaf/Tuinity/actions/runs/56446755)

<hr>

#### Problem or bug: 
Tuinity is a performance-oriented fork of Paper.
TrainCarts work on Paper, however they do not on Tuinity.

I am getting this error on startup.
https://gist.github.com/breadbyte/3009e05ec45864af751f0f207a70622c
I am unsure as to where to report this, but given that this error originates(?) from TrainCarts, i figured this would be a good place to start.

By the look of the error though, i do not have much hope for this getting fixed, if at all.

#### Expected behaviour:
TrainCarts loads fine.

#### Steps to reproduce:
1. Download Tuinity.
2. Put TrainCarts and BKCommonLib into plugins folder.
3. Start the server.

**Comment by weeryan17** [comment]
Traincarts only supports select server software, and while the developer will usually attempt to support more as people report issues with specific ones it will still take him a bit. Just keep this in mind, and if you want to use traincarts in the mean time you can switch over to normal paper, or spigot.

**Comment by bergerkiller** [comment]
Guys if you keep bricking the server every time I commit I can't continue supporting it

**Comment by bergerkiller** [comment]
I see now what's going on. Purpur extends Tuinity extends Paperspigot extends Spigot extends CraftBukkit.

I added support for Purpur. But not for tuinity.

Oooooone second.

**Comment by bergerkiller** [comment]
Rant aside, try this https://github.com/bergerhealer/BKCommonLib/commit/0ac6af0e72c36d7d0a479c66d6f87a4109959f42

https://ci.mg-dev.eu/job/BKCommonLib/733/

**Comment by bbayu123** [comment]
Closing this for now. If it turns out that it still isn't working fully, feel free to reopen ;)
