### ISSUE TITLE
(1.15.2) A bug that makes it impossible to move on a trolley if you move on a minecart and get off and get back down

### ISSUE THREAD

**Issue by alphach0804** [bergerhealer/TrainCarts#344]
##### Spigot version:1.15.2 git-Spigot-6de3d4b-a6f8093

<hr>

**Comment by bbayu123** [comment]
What "trolley" are we talking about here?

**Comment by alphach0804** [comment]
sorry Im japanese I useing Google translate
It is a bug that moves to Minecart and returns to the original position when getting off

**Comment by bbayu123** [comment]
Yea I still have trouble understanding you. Are you able to get a friend that can help you explain this? I don't understand Japanese but you could also summarise your issue in Japanese and I might be able to figure it out.

**Comment by alphach0804** [comment]
申し訳ありません、では日本語でまとめさせていただきます
問題としてまして
TrainCartsを導入してからトロッコで移動して降りると元の位置に戻ってしまうんです

**Comment by bbayu123** [comment]
Ok I have a vague idea of what your issue is, but some details are still unclear to me. I should have asked you this earlier, but can you also provide a video showcasing what happens? From what you said there, I think your issue is something like "players returning to the position before entering a cart upon exit" or something like that, a video would definitely tell me what exact issue you are having.

**Comment by alphach0804** [comment]
https://www.youtube.com/watch?v=_qs48iNlZ0c
ここにUploadしましたよろしくお願いします

**Comment by bbayu123** [comment]
You pressed shift to exit the train right? That surely does not look normal.

**Comment by alphach0804** [comment]
Yes I push Shift Key

**Comment by bbayu123** [comment]
Does this happen to other minecarts or just this specific situation?

**Comment by alphach0804** [comment]
![image](https://user-images.githubusercontent.com/42644369/78574684-4f8ea580-7865-11ea-9367-a37338ab285e.png)
もしかしてこのプラグインの中に競合するプラグインがあるのかもしれません…

**Comment by alphach0804** [comment]
全ての状況下でこの現象は発生します

**Comment by bbayu123** [comment]
Aha, I see protocolsupport in there, that plugin is known to be incompatible in some cases, not sure if it applies to this one, but you can try removing it.

**Comment by alphach0804** [comment]
protcolsupportが競合しているということなのでしたら削除してみます

**Comment by alphach0804** [comment]
正常に動作しました！！thx!!!!!

**Comment by bbayu123** [comment]
No worries, glad to hear it fixed!

**Comment by bbayu123** [comment]
I don't think there's a way to fix the incompatibility with ProtocolSupport. The way they mess with packets is just so bad that it can't be fixed in most circumstances.

**Comment by alphach0804** [comment]
なるほど、有難うございました
OK,thx!

**Comment by bbayu123** [comment]
Hey, here's a very late update, I believe ProtocolSupport is now working with the latest build of TrainCarts. You may want to take a look if it works :)
