### ISSUE TITLE
Hopper fill rate is slow

### ISSUE THREAD

**Issue by Wumfie** [bergerhealer/TrainCarts#350]
##### Spigot version: Paper 1.14.4

<hr>

#### Steps to reproduce: Place a hopper and a minecart-hopper under it. Fill the hopper abover and see the reduced fill rate

Started happening when I installed TrainCarts. Any help would be appreciated!

**Comment by bbayu123** [comment]
Are you sure it's not a TPS issue?

**Comment by Wumfie** [comment]
Getting 20 TPS

**Comment by bbayu123** [comment]
Very interesting, will need dev to get back to you later. TrainCarts should not be modifying hopper transfer rate, but I wouldn't know what changes TC makes to hoppers as I don't use them.

**Comment by bergerkiller** [comment]
By chance, does this involve many hoppers in a row? Part of my implementation Im missing that it should reset the hopper cooldown when the block the minecart is at changes. This will cause it to cool down the moment the hopper wont accept more items (empty), even when going to another hopper block.

**Comment by bergerkiller** [comment]
This might help: https://github.com/bergerhealer/TrainCarts/commit/23f8ddd9bf58a35706a9614150ee2b9f7a1fdb80

https://ci.mg-dev.eu/job/TrainCarts/621/

**Comment by bergerkiller** [comment]
Any updates?

**Comment by Wumfie** [comment]
No, it doesn't involve multiple hoppers in a row. Fill rate is still slow. Have some screenshots of my setup:
![HopperSetup](https://user-images.githubusercontent.com/60324543/82229231-19434c00-9922-11ea-81d7-51ee74fa8471.PNG)
![Capture2](https://user-images.githubusercontent.com/60324543/82229250-1e080000-9922-11ea-9435-aaf8cd468655.PNG)
![Capture3](https://user-images.githubusercontent.com/60324543/82229267-2102f080-9922-11ea-8978-be6cd4269135.PNG)
Really not sure what the code is there for but any more help would be nice.

**Comment by Wumfie** [comment]
Ignore my previous comment. I just did the completely wron test oops!

**Comment by Wumfie** [comment]
Ok its working now, removed all the plugins and added the all back in stages to try and find the culprit and now it works

**Comment by Wumfie** [comment]
my luck... you can close it if you want

**Comment by Wumfie** [comment]
I'm speaking too soon 🤦‍♂️! When i installed all the plugins I put them all back except traincarts. I can give a proper update now... Put the plugin back on and im getting the same issue. Sorry if I wasted anyones time but I can provide some real info now.

First off, I notice that the fill rate is slower, same issue at the start. And yes, it only involves one hopper. After removing all plugins and isolating the problem, it is definitely TrainCarts. And it wasn't BKCommonLib as I tested it with that and the fill rate was normal. Also, when i started the server, for a split second after it started, before anyone else had joined, I noticed it filling much faster then shortly after slowing back down again.

Heres a video test and still getting roughly 6 items per second:
[https://www.youtube.com/watch?v=U7xxgNdwGfs](url)

Any help would be nice. I'm not really sure what you meant with the code, an explaination would be nice. Once again, thank you for your time.

**Comment by bbayu123** [comment]
Did you try nothing but BKCommonLib and TrainCarts?

**Comment by bbayu123** [comment]
Any updates?

**Comment by bbayu123** [comment]
Closing, for now. Reopen if you still have this issue.
