### ISSUE TITLE
Trigger - Command at a Sign

### ISSUE THREAD

**Issue by JCSweetHeart** [bergerhealer/TrainCarts#351]
##### Spigot version: 1.15.2

<hr>

#### Steps to reproduce: Used the following Setup at a Sign:

[!train] 
trigger
%s_on%
00:00:20

**Comment by bbayu123** [comment]
Do not include the % symbols when specifying the variables.

**Comment by JCSweetHeart** [comment]
I try it and write when i have a other or same Problem ;) ..thanks for the really fast Answer from you .. WTF, im shocked, but happy about this ;)

BTW: With the Time is so correctly?

**Comment by bbayu123** [comment]
Yes, the time you specified is in the correct format. This way when the train passes over the sign the variable counts down from 20 seconds until it reaches 0.

**Comment by JCSweetHeart** [comment]
OK its work finally, but i understand the trigger command with Destination?

What i must write on a sign, when the trigger called "st_dest" ?

**Comment by bbayu123** [comment]
No, when making that trigger sign, 4 variables get changed
In your case, **s_on** is the variable indicating the countdown timer, and the other 3 are **s_onD**, **s_onN**, and **s_onT**.
The one that ends in D, will show the destination that is set on the train.
N gives the name of the train.
Whereas T is just another variable for showing the countdown timer

**Comment by JCSweetHeart** [comment]
OKAY, thank you verry much .. now i must think how i can change the destination - momently i use Signlink for variable and have think its work`s when i before the sign passed the trigger Sign change the destination

[Spawner] --> Destination --> Trigger --> Station

(Hope anywhere can understand, what i mean :D )

**Comment by bbayu123** [comment]
Yep that looks good, to change the destination, use a destination sign. Leave line 3 blank, and specify the destination you want to show for the train on line 4. As long as you are not using pathfinding, nothing should change in your system.

**Comment by JCSweetHeart** [comment]
Can you make me a small Example for that with the s_dest - as from the Destination, Trigger and the other Sign that i can better understand it? Thank you !
> 
> 
> Yep that looks good, to change the destination, use a destination sign. Leave line 3 blank, and specify the destination you want to show for the train on line 4. As long as you are not using pathfinding, nothing should change in your system.

**Comment by bbayu123** [comment]
Example 1:
[+train]
trigger
s_on
00:00:20

%s_on% = 00:00:20
%s_onD% = Mineshaft (destination of train)
%s_onN% = train1 (name of train)
%s_onT% = 00:00:20

<hr>

Example 2:
[+train]
trigger
platform3
65

%platform3% = 00:01:05 (65 seconds is 1 minute and 5 seconds)
%platform3D% = Farm (destination of train)
%platform3N% = train2 (name of train)
%platform3T% = 00:01:05

**Comment by JCSweetHeart** [comment]
thank you for the quick help

can be closed

**Comment by bbayu123** [comment]
Nice, glad to help.
