### ISSUE TITLE
Multiple entitys starting to glitch together

### ISSUE THREAD

**Issue by DatIsVinnie** [bergerhealer/TrainCarts#352]
##### Spigot version: 1.14.4

<hr>

#### Problem or bug: 

I want to have multiple minecarts next to each other but in the corner, the minecarts are teleporting to each other If I am using blocks instead of entities this problem is solved but I really need to use entities like a minecart,

Here are some example's

![2020-05-09_18 40 02](https://user-images.githubusercontent.com/57494611/81479757-8ae61080-9225-11ea-8593-52be551af937.png)
![2020-05-09_18 40 03](https://user-images.githubusercontent.com/57494611/81479747-83266c00-9225-11ea-9e3a-6f3b6019d9f9.png)
![2020-05-09_18 40 15](https://user-images.githubusercontent.com/57494611/81479751-86b9f300-9225-11ea-9348-f913e75b20ba.png)
![2020-05-09_18 40 16](https://user-images.githubusercontent.com/57494611/81479756-891c4d00-9225-11ea-9c0f-f8f94a61e015.png)

#### Expected behavior:
The multiple minecarts need to move nicely with eachother

**Comment by bbayu123** [comment]
Do you have 2 minecarts side by side? If so that's a client bug, minecarts always snap to the rails whenever possible.

**Comment by DatIsVinnie** [comment]
Do you mean like that the carts try to move on the rails

**Comment by bbayu123** [comment]
The Minecraft client will put minecarts onto the nearest rail. This is its visual appearance. The server still sees the 2 minecarts side by side, only the clients don't.

**Comment by DatIsVinnie** [comment]
Is there a way to fix this problem?

**Comment by bbayu123** [comment]
No, it's a bug with minecraft itself.

**Comment by DatIsVinnie** [comment]
Alright thankyou for helping :))

**Comment by bbayu123** [comment]
No problem, I shall be closing this then.
