### ISSUE TITLE
Transfer signs break if items have additional NBT tags

### ISSUE THREAD

**Issue by DragonBallZeke** [bergerhealer/TrainCarts#353]
##### Spigot version: git-Spigot-e7dc2f5-a8ec1d6 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

<hr>

#### Documentation of the problem: 
All examples below were using the following sign:
```
[+train]
chest out 2
```
**Functional example**:
Chest:
![image](https://user-images.githubusercontent.com/11283815/81486128-4a33ca80-9218-11ea-9ad7-fac169d9eba4.png)

After transferring, the minecart looks like this:
![image](https://user-images.githubusercontent.com/11283815/81486138-6b94b680-9218-11ea-8a64-914c11c8496c.png)

**Non-functional example**:
Chest:
![image](https://user-images.githubusercontent.com/11283815/81486150-836c3a80-9218-11ea-932b-20a392c1b036.png)

Minecart:
![image](https://user-images.githubusercontent.com/11283815/81486158-8bc47580-9218-11ea-853c-f2fccafbe647.png)

The pickaxe and any subsequent items remain in the chest, like so:
![image](https://user-images.githubusercontent.com/11283815/81486169-9ed74580-9218-11ea-9fd0-5f5c124a7aca.png)

Despite a pickaxe being used in the example, this behavior is present with a variety of items, such as shulker boxes and fireworks. Other non-stackable items without additional NBT tags work fine (such as a bucket of water)

**Comment by bergerkiller** [comment]
Issue was fixed: https://github.com/bergerhealer/BKCommonLib/commit/432de059223687e0eed19b527437575206b2a6a6

https://ci.mg-dev.eu/job/BKCommonLib/769/

Thanks for reporting :)
