### ISSUE TITLE
"Ghost" - Sign

### ISSUE THREAD

**Issue by JCSweetHeart** [bergerhealer/TrainCarts#354]
BkCommonLib version: 1.15.2-v3
TrainCarts version: 1.15.2_V2 (build:616)
Spigot version: 1.15.2
Problem or bug: Change the Track of a Route of Trains called S1 now and everytime when the Train passed one Part of this Route, i become a Message that the Destination "bhf_w1" is missed - the "Joke": The Sign for that i can't find.

/train reroute is used, thats not work :'( - and i can't open the Destination - File for finding the f**cking Sign :'/

Expected behaviour: N / A
Steps to reproduce:

**Comment by bergerkiller** [comment]
Have you tried _/train debug destinations bhf_w1_ and clicking around in the world to see if it finds it? I dont know how I can help you. If the sign cant be found by traincarts then all you can do is hunt for it yourself.

**Comment by bbayu123** [comment]
If you want to, you can also send your destinations.dat file and I'll see what I can find in there.

**Comment by bbayu123** [comment]
Actually that might not help, so don't do it yet.

**Comment by bbayu123** [comment]
Ok it's good now, I wrote a crappy decoder to create human-readable information from that compressed data.

**Comment by JCSweetHeart** [comment]
I testet it it and when not work, then tell me how i can send you the destination.dat file :)
> 
> 
> Have you tried _/train debug destinations bhf_w1_ and clicking around in the world to see if it finds it? I dont know how I can help you. If the sign cant be found by traincarts then all you can do is hunt for it yourself.

**Comment by JCSweetHeart** [comment]
Destination bhf_w1 does not exist. Try rerouting ... ok i try it and .. NOT WORK :(

**Comment by bbayu123** [comment]
You could upload it here if you can, or you could use a cloud to share the link. To upload files here, you can drag and drop the file into the response box, copy the file and paste it in the response box, or clicking the bar below that says "Attach files by dra...."

**Comment by JCSweetHeart** [comment]
Here the destination.dat as ZIP - File :=

[destinations.zip](https://github.com/bergerhealer/TrainCarts/files/4611298/destinations.zip)

**Comment by bbayu123** [comment]
```
Total Nodes: 18
Node 0: Name -, Location (world, -93, 63, -600)
Node 1: Name bhf1_destroy, Location (world, -94, 50, -47)
Node 2: Name swampland1, Location (world, 1056, 63, -607)
Node 3: Name hbf_an, Location (world, -93, 50, -76)
Node 4: Name -, Location (world, -95, 50, -47)
Node 5: Name hbf1_destroy1, Location (world, -99, 50, -47)
Node 6: Name -, Location (world, 1054, 63, -607)
Node 7: Name -, Location (world, 1054, 63, -609)
Node 8: Name -, Location (world, -93, 50, -182)
Node 9: Name fw_bhf, Location (world, -93, 63, -613)
Node 10: Name -, Location (world, -91, 63, -606)
Node 11: Name -, Location (world, -85, 50, -66)
Node 12: Name -, Location (world, -93, 63, -606)
Node 13: Name hbf1_an, Location (world, -93, 50, -85)
Node 14: Name -, Location (world, -97, 50, -47)
Node 15: Name U1_HBF, Location (TestWorld, -240, 8, -110)
Node 16: Name test_bhf1, Location (TestWorld, -208, 8, -120)
Node 17: Name -, Location (TestWorld, -252, 8, -118)
```

Well, it really doesn't exist, can you check to see whether the destination of any train has been set to that?

**Comment by bbayu123** [comment]
This is the full decoded file that I have from your dat file.
[decodedDestinations.txt](https://github.com/bergerhealer/TrainCarts/files/4611321/decodedDestinations.txt)

**Comment by JCSweetHeart** [comment]
No train is set to this Destination, was a old Destination for change to other Track (1 to destination fw_bhf and one to hbf1_an but now isn`t set while i have change and reroute normally the Destination of all Trains - i think so
--------

MainStation (hbf) -> fw_bhf (2.Station)
Mainstation (hbf) -> swampland 1 (3. Station)

and back set to the 2./3. above the Destination hbf_an, while i use 2 Tracks for the Traintracks (forth and back).

**Comment by JCSweetHeart** [comment]
When i lock into the decoded Destination, im a little bit confused, while as Example Node 0 havn`t Name

**Comment by bbayu123** [comment]
those don't have names probably because they are switchers, not destinations

**Comment by bbayu123** [comment]
Well something definitely isn't changed then, because if you changed everything properly then that shouldn't show up...
Just in case it's not the problem, have you tried shutting your server down and starting it back up again?

**Comment by JCSweetHeart** [comment]
i can do it, but actually i teleport himself to all the Location from the decoded Destination and search for a Error / Bug - maybe i can find it ;). When not work, then i can shut down and restart the server

**Comment by bbayu123** [comment]
Sure thing, let us know what you find out after you do your thing.

**Comment by JCSweetHeart** [comment]
Have check all of the near of the old Destination - Sign but nothing found .. now i stop and start the Server...

I make a Message when the Server reboot

**Comment by JCSweetHeart** [comment]
Finally i try it again and let drive the Train the track ;) - i let me suprise what happening

**Comment by JCSweetHeart** [comment]
AND again the Message that missing bhf_w1 *cry* - i have hope that work now. I try it again with train retoute.

Not work, have try with train info to find the problem and can`t see any Sign there or in the near

**Comment by JCSweetHeart** [comment]
-91 63 -606 << that or there in the near is the Problem but i can found the normal switches that i need and not a other Sign exactly with the Destination

**Comment by JCSweetHeart** [comment]
I hope i have found the stupid Sign but was at -91, 48, -181 *WTF* .. try again ^^

**Comment by JCSweetHeart** [comment]
Momently no Problem with the Plugin ;) .. little confused for the Trainroute but now is momently work..thank you (again^^)
