### ISSUE TITLE
Announce in title, subtitle, actionbar

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/TrainCarts#355]
It would be useful for important messages if I could choose other output than chat on the sign. The Announce line might look like this:
- **Announce** or **Announce chat** - chat
- **Announce title** - title
- **Announce sub** - subtitle
- **Announce bar** - actionbar

**Comment by bbayu123** [comment]
Actionbar is fine, but on the current sign it would be hard to
1. Show title and subtitle at the same time without cutting out.
2. Set proper fade in, showtime and fade out on the titles and subtitles.

**Comment by Vlader97** [comment]
The sign with title will check if is next to sign with subtitle and check if fade in, showtime and fade out have same values on both signs. If yes show title and subtitle in same time. For example.

```
[train]             [train]
Title 20 5 20       Subtitle 20 5 20
Final station       Please get out
```
Show in same time.

**Comment by bbayu123** [comment]
Yea... since dev never responded to this... I don't know the feasibility of this, probably better if those were separate signs.

**Comment by bbayu123** [comment]
Workaround: You can use the `@ptrain` selector to target all players in a train. Combine this using a command block and a switcher sign.

**Comment by Vlader97** [comment]
Wow! I didn't believe you would ever add it. 
I didn't know that this tag _@ptrain_ existed. It will help me a lot.
Thank you :)
