### ISSUE TITLE
Missing wiki page entries

### ISSUE THREAD

**Issue by levelXlevel** [bergerhealer/TrainCarts#356]
##### Spigot version: N/A

<hr>

#### Problem or bug: 
The wiki page entries for each property under `wiki/Signs` are missing & default back to main page.

#### Expected behavior: 
List of additional information for the sign properties.

#### Steps to reproduce: 
- Visit the `wiki/Signs` section,
- Select any of the properties
- Observed: Reader is taken back to main page.
- Expected: Addition property details

**Comment by bbayu123** [comment]
Github's wiki page is not used, please refer to https://minecraft.gamepedia.com/Mods/TrainCarts
