### ISSUE TITLE
Minecarts makes hissing sound when connected

### ISSUE THREAD

**Issue by Disbee** [bergerhealer/TrainCarts#358]
when i connect minecarts it makes an hissing sound that i cant find a fix for anywhere 

Here a video showing what im talking about
(https://www.youtube.com/watch?v=8cebKdZ1e8Y&feature=youtu.be)

**Comment by bbayu123** [comment]
That's intentional and it cannot be disabled. Would you like to suggest an option to disable that?

**Comment by Disbee** [comment]
Yes, ingame its very loud and can get annoying after a while

**Comment by bbayu123** [comment]
I mean you could just lower your sounds, but sure I can list this as a suggestion.

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/TrainCarts/commit/4fab1568b6e6350afb11b79aeed8a506e89ec0a9 here you go. New 'sounds' section in TC-config. The old 'playSoundAtStation' option is migrated to there automatically.

**Comment by bbayu123** [comment]
Closing - resolved.
