### ISSUE TITLE
Traincarts won't WORK!

### ISSUE THREAD

**Issue by TREGuy365** [bergerhealer/TrainCarts#359]
##### Spigot version: 1.15.2 (paper)

<hr>

#### Problem or bug: Trains won't connect and certain functions aren't usable. 
Plugins: EssentialsX, TrainCarts, Signlink, ClearLag, WorldEdit and Worldgaurd.

**Comment by weeryan17** [comment]
Any errors? Does it actually show up in the plugin list? We need more info then "it doesn't work".

**Comment by bergerkiller** [comment]
This is a classic example of what type of issue reports you should **NOT** be making. Since it's paperspigot, it is very likely that something in paper broke stuff again, in which case using the v4 dev build of bkcommonlib will likely help.

https://ci.mg-dev.eu/job/BKCommonLib/784/

**Comment by weeryan17** [comment]
As you have failed to reply to this issue, and provide more info I'm going to close this issue. Feel free to re-open if when you provide more info.
