### ISSUE TITLE
Upon update from 1.7.10 to 1.8.8, signs go wierd.

### ISSUE THREAD

**Issue by DannyPokemon** [bergerhealer/TrainCarts#36]
so i updated my entire server from 1.7.10 to 1.8.8 and  it all boots up fine. but then i go to a sign and see that the plugin changed all my signs from (without quotes):
'[train]'
to:
'train'.
if i create a new sign, it works fine. but i have TONS AND TONS of them and i don't have that much time in my life to go to all edges of my map to rectify it. All help appreciated - Thanks in advance.

**Comment by mg-1999** [comment]
Add 'parseOldSings:true' the config

Op do 17 dec. 2015 19:34 schreef DannyPokemon <notifications@github.com>:

> so i updated my entire server from 1710 to 188 and it all boots up fine
> but then i go to a sign and see that the plugin changed all my signs from
> (without quotes):
> '[train]'
> to:
> 'train'
> if i create a new sign, it works fine but i have TONS AND TONS of them and
> i don't have that much time in my life to go to all edges of my map to
> rectify it All help appreciated - Thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/36>.
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by DannyPokemon** [comment]
thanks - i didn't know it was that obvious! LMAOOO

**Comment by DannyPokemon** [comment]
i'm asuming it's for world import protection?!!?

**Comment by DannyPokemon** [comment]
err..... it didn't work. infact if insert a new line in the config it throws a wobbly. idk y doe......

**Comment by DannyPokemon** [comment]
[21:49:25 INFO]: [Train_Carts] Enabling Train_Carts v1.75-SNAPSHOT
[21:49:25 ERROR]: [Configuration] An error occured while loading file 'plugins\T
rain_Carts\config.yml'
[21:49:25 ERROR]: [Configuration] A backup of this (corrupted?) file named 'conf
ig.yml.old' can be found in case you wish to restore
java.io.IOException: YAML file is corrupt
        at com.bergerkiller.bukkit.common.config.BasicConfiguration.loadFromStre
am(BasicConfiguration.java:103) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.config.FileConfiguration.load(FileConf
iguration.java:51) [BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.TrainCarts.loadConfig(TrainCarts.java:218)
 [TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:490) [Tr
ainCarts.jar:?]
        at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:75
6) [BKCommonLib.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [sp
igot.jar:git-Spigot-0359393-9a17f01]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:340) [spigot.jar:git-Spigot-0359393-9a17f01]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405) [spigot.jar:git-Spigot-0359393-9a17f01]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.jav
a:357) [spigot.jar:git-Spigot-0359393-9a17f01]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.
java:317) [spigot.jar:git-Spigot-0359393-9a17f01]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:4
14) [spigot.jar:git-Spigot-0359393-9a17f01]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:3
78) [spigot.jar:git-Spigot-0359393-9a17f01]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:3
33) [spigot.jar:git-Spigot-0359393-9a17f01]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.jav
a:263) [spigot.jar:git-Spigot-0359393-9a17f01]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:524) [spigot.jar:git-Spigot-0359393-9a17f01]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0]
Caused by: org.bukkit.configuration.InvalidConfigurationException: mapping value
s are not allowed here
 in 'string', line 2, column 7:
    normal:
          ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlCo
nfiguration.java:57) ~[spigot.jar:git-Spigot-0359393-9a17f01]
        at com.bergerkiller.bukkit.common.config.BasicConfiguration.loadFromStre
am(BasicConfiguration.java:101) ~[BKCommonLib.jar:?]
        ... 15 more
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not a
llowed here
 in 'string', line 2, column 7:
    normal:
          ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:87
1) ~[spigot.jar:git-Spigot-0359393-9a17f01]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.ja
va:360) ~[spigot.jar:git-Spigot-0359393-9a17f01]
        at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:249
) ~[spigot.jar:git-Spigot-0359393-9a17f01]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserI
mpl.java:253) ~[spigot.jar:git-Spigot-0359393-9a17f01]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~
[spigot.jar:git-Spigot-0359393-9a17f01]
        at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168) ~[
spigot.jar:git-Spigot-0359393-9a17f01]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:12
4) ~[spigot.jar:git-Spigot-0359393-9a17f01]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
 ~[spigot.jar:git-Spigot-0359393-9a17f01]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseCons
tructor.java:120) ~[spigot.jar:git-Spigot-0359393-9a17f01]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot.jar:gi
t-Spigot-0359393-9a17f01]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot.jar:git-Spigot-0
359393-9a17f01]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlCo
nfiguration.java:55) ~[spigot.jar:git-Spigot-0359393-9a17f01]
        at com.bergerkiller.bukkit.common.config.BasicConfiguration.loadFromStre
am(BasicConfiguration.java:101) ~[BKCommonLib.jar:?]
        ... 15 more

**Comment by mg-1999** [comment]
Put the file in a yml parser. And check what needs to be fixed.

Op do 17 dec. 2015 22:59 schreef DannyPokemon <notifications@github.com>:

> [21:49:25 INFO]: [Train_Carts] Enabling Train_Carts v1.75-SNAPSHOT
> [21:49:25 ERROR]: [Configuration] An error occured while loading file
> 'plugins\T
> rain_Carts\config.yml'
> [21:49:25 ERROR]: [Configuration] A backup of this (corrupted?) file named
> 'conf
> ig.yml.old' can be found in case you wish to restore
> java.io.IOException: YAML file is corrupt
> at com.bergerkiller.bukkit.common.config.BasicConfiguration.loadFromStre
> am(BasicConfiguration.java:103) ~[BKCommonLib.jar:?]
> at com.bergerkiller.bukkit.common.config.FileConfiguration.load(FileConf
> iguration.java:51) [BKCommonLib.jar:?]
> at com.bergerkiller.bukkit.tc.TrainCarts.loadConfig(TrainCarts.java:218)
> [TrainCarts.jar:?]
> at com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:490) [Tr
> ainCarts.jar:?]
> at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:75
> 6) [BKCommonLib.jar:?]
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [sp
> igot.jar:git-Spigot-0359393-9a17f01]
> at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
> .java:340) [spigot.jar:git-Spigot-0359393-9a17f01]
> at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
> r.java:405) [spigot.jar:git-Spigot-0359393-9a17f01]
> at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.jav
> a:357) [spigot.jar:git-Spigot-0359393-9a17f01]
> at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.
> java:317) [spigot.jar:git-Spigot-0359393-9a17f01]
> at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:4
> 14) [spigot.jar:git-Spigot-0359393-9a17f01]
> at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:3
> 78) [spigot.jar:git-Spigot-0359393-9a17f01]
> at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:3
> 33) [spigot.jar:git-Spigot-0359393-9a17f01]
> at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.jav
> a:263) [spigot.jar:git-Spigot-0359393-9a17f01]
> at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
> :524) [spigot.jar:git-Spigot-0359393-9a17f01]
> at java.lang.Thread.run(Unknown Source) [?:1.8.0]
> Caused by: org.bukkit.configuration.InvalidConfigurationException: mapping
> value
> s are not allowed here
> in 'string', line 2, column 7:
> normal:
> ^
>
>     at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlCo
>
> nfiguration.java:57) ~[spigot.jar:git-Spigot-0359393-9a17f01]
> at com.bergerkiller.bukkit.common.config.BasicConfiguration.loadFromStre
> am(BasicConfiguration.java:101) ~[BKCommonLib.jar:?]
> ... 15 more
> Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are
> not a
> llowed here
> in 'string', line 2, column 7:
> normal:
> ^
>
>     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:87
>
> 1) ~[spigot.jar:git-Spigot-0359393-9a17f01]
> at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.ja
> va:360) ~[spigot.jar:git-Spigot-0359393-9a17f01]
> at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:249
> ) ~[spigot.jar:git-Spigot-0359393-9a17f01]
> at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserI
> mpl.java:253) ~[spigot.jar:git-Spigot-0359393-9a17f01]
> at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~
> [spigot.jar:git-Spigot-0359393-9a17f01]
> at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168) ~[
> spigot.jar:git-Spigot-0359393-9a17f01]
> at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:12
> 4) ~[spigot.jar:git-Spigot-0359393-9a17f01]
> at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
> ~[spigot.jar:git-Spigot-0359393-9a17f01]
> at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseCons
> tructor.java:120) ~[spigot.jar:git-Spigot-0359393-9a17f01]
> at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot.jar:gi
> t-Spigot-0359393-9a17f01]
> at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot.jar:git-Spigot-0
> 359393-9a17f01]
> at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlCo
> nfiguration.java:55) ~[spigot.jar:git-Spigot-0359393-9a17f01]
> at com.bergerkiller.bukkit.common.config.BasicConfiguration.loadFromStre
> am(BasicConfiguration.java:101) ~[BKCommonLib.jar:?]
> ... 15 more
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/36#issuecomment-165592363>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by DannyPokemon** [comment]
Lol it was a tab issue :/ but it turns out its another problrm.
when i put that in, on boot it completely deletes that column without an error in console. this is annoying, help!!!!!!!!!
thanks in advance!

**Comment by mg-1999** [comment]
Can you please post your config with the value added?

Op do 17 dec. 2015 23:59 schreef DannyPokemon <notifications@github.com>:

> Lol it was a tab issue :/ but it turns out its another problrm.
> when i put that in, on boot it completely deletes that column without an
> error in console. this is annoying, help!!!!!!!!!
> thanks in advance!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/36#issuecomment-165609135>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by DannyPokemon** [comment]
sorry for late reply, time zones ;)
it's the default config, but i added `parseOldSings:` true to line 1:
```
parseOldSings: true
#> This is the configuration file of TrainCarts
#> In here you can tweak TrainCarts to what you want
#> For more information, you can visit the following websites:
#> http://www.minecraftwiki.net/wiki/Bukkit/TrainCarts
#> http://forums.bukkit.org/threads/traincarts.29491/

# The distance between two normally-aligned (straight) carts in a train
normal:
  # The distance between two carts in a train
  cartDistance: 1.5
  # The factor at which this distance is kept
  cartDistanceForcer: 0.1

# Settings for turned (in curve) carts
turned:
  # The distance between two carts in a train
  cartDistance: 1.6
  # The factor at which this distance is kept
  cartDistanceForcer: 0.2

# The 'keep distance' factor to apply when carts are too close to each other
nearCartDistanceFactor: 1.2

# The maximum allowed cart distance, after this distance the carts break apart
maxCartDistance: 4.0

# Whether or not the combined carts (powered/storage minecarts) break up into two items
breakCombinedCarts: false

# A performance boost to give to powered minecarts (0 = normal speed)
poweredCartBoost: 0.1

# The boosting factor of powered rails (default = 0.06)
poweredRailBoost: 0.06

# The maximum velocity (blocks/tick) a minecart can possibly have set
maxVelocity: 5.0

# The multiplier used to slow down minecarts
# Normal is the default, slow is when the minecart is meant to slow down.
slowDownMultiplier:
  normal: 0.997
  slow: 0.96

# The maximum allowed ejection distance for eject signs
maxEjectDistance: 10.0

# The amount of velocity stations give when launching trains
launchForce: 10.0

# Settings used when carts collide with entities
collision:
  # If train owners are ignored
  ignoreOwners: false
  # If global train owners are ignored
  ignoreGlobalOwners: false
  # The amount of force at which minecarts push away others
  pushAwayForce: 0.2

# Whether or not all minecarts spawned on the server turn into TrainCarts' Minecarts
# Note that the TrainCart placement permission is then no longer active
allMinecartsAreTrainCarts: false

# Whether or not powered minecarts obtain their coal from attached storage minecarts
useCoalFromStorageCart: false

# Whether or not the player that places a minecart is set owner
setOwnerOnPlacement: true

# Whether or not a hissing sound is made when trains stop at a station
playSoundAtStation: true

# Whether or not chunks are only kept loaded when the train is moving
keepChunksLoadedOnlyWhenMoving: false

# Advanced: Whether trains use a different way of server->client synchronization
# With this enabled, trains are expected to move smoother with less bumping
# With this disabled, no smoothing is applied. Only disable it if it causes problems/incompatibility
useNetworkSynchronizer: true

# The maximum length a detector region (between two detectors) can be
maxDetectorLength: 2000

# The maximum amount of minecart items that can be stacked in one item
maxMinecartStackSize: 64

# The maximum radius chest/furnace sign systems look for the needed blocks
maxTransferRadius: 5

# The default radius chest/furnace sign systems look for the needed blocks
defaultTransferRadius: 2

# Whether or not empty minecarts slow down faster than occupied minecarts
slowDownEmptyCarts: false

# Whether storage minecarts get fuel when launching from stations
refillAtStations: true

# Whether minecarts are instantly destroyed by creative players
# Note that manual minecart movement is not possible for creative players with this enabled
instantCreativeDestroy: false

# Whether minecarts are allowed to have a 90-degree pitch angle when going up vertical rails
# When disabled, minecarts will keep a 0-degree pitch angle instead
allowVerticalPitch: true

# Whether players (with build permissions) can edit existing rails by right-clicking on them
allowRailEditing: true

# What velocity to set when a player tries to manually move a train (by damaging it)
manualMovementSpeed: 12.0

# The currency Ticket signs will display in messages, %value% represents the displayed value
currencyFormat: '%value% Dollars'

# The delay (in ticks) between ejecting and re-entering by collision (e.g. mobs auto-entering carts)
collisionReEnterDelay: 100

# A list of world names where TrainCarts should be disabled
# World names are not case-sensitive
disabledWorlds:
- DefaultWorld1
- DefaultWorld2

# The block materials that can be broken using minecarts
# Players with the admin block break permission can use any type
# Others have to use one from this list
allowedBlockBreakTypes:
- LOG
- CROPS

# Whether or not to show item animations when transferring items
showTransferAnimations: true

# Several shortcuts you can use on announce signs (text is replaced)
messageShortcuts:
  welcome: '&eWelcome to &f'

# Several shortcuts you can use on switcher and detector signs (text is replaced)
statementShortcuts:
  diamond: i@diamond

# Several shortcuts you can use on signs to set the items
itemShortcuts:
  fuel: ''
  heatable: ''
  armor: chainmail_boots;gold_chestplate;leather_leggings;iron_leggings;diamond_leggings;leather_helmet;iron_helmet;gold_boots;iron_chestplate;leather_boots;leather_chestplate;diamond_helmet;gold_leggings;chainmail_leggings;chainmail_helmet;chainmail_chestplate;iron_boots;diamond_boots;gold_helmet;diamond_chestplate
  sword: wood_sword;stone_sword;iron_sword;gold_sword;iron_sword;diamond_sword
  boots: leather_boots;iron_boots;gold_boots;diamond_boots;chainmail_boots
  leggins: leather_leggings;iron_leggings;gold_leggings;diamond_leggings;chainmail_leggings
  chestplate: leather_chestplate;iron_chestplate;gold_chestplate;diamond_chestplate;chainmail_chestplate
  helmet: leather_helmet;iron_helmet;gold_helmet;diamond_helmet;chainmail_helmet
```

**Comment by mg-1999** [comment]
My fault. It is `parseOldSign: true` Typing is hard :tongue:

**Comment by DannyPokemon** [comment]
no it isn't - i noticed that and fixed it so ignore that error.
this time it is REMOVING ITSELF FROM THE CONFIG! idk why but it is. i get no error feed saying it doesn't like it, it removes the line. i'm gonna record it and show you. hold on...

**Comment by DannyPokemon** [comment]
https://onedrive.live.com/redir?resid=68A4D2CD06EF73D7!1303&authkey=!AHxOFcpBUguVbxA&ithint=file%2cmht

**Comment by mg-1999** [comment]
It does that because it was programmed to do so. Are you signs getting fixed? Because if they are then everything is working fine

**Comment by DannyPokemon** [comment]
no still not. can you step-by-step it for me?!?!?!?!?!

**Comment by mg-1999** [comment]
Stop server. Open config. Add 'parseOldSigns: true' to the bottom of the config. Safe file. Startup the server.

**Comment by DannyPokemon** [comment]
ok will try. thanks!

oh, and sorry to waste your time on petty things like this! :8ball:

**Comment by DannyPokemon** [comment]
no not fixing it. i am using Multiverse, maybe plugin conflict?!?! :angry:

**Comment by mg-1999** [comment]
Any error that is logging to the console? Can I get the whole log? Versions? Anything? Other plugins you are using?

**Comment by DannyPokemon** [comment]
Merry Xmas!

nothing, do you think it,s a multiverse issue??!???9

there doesnt seem a way arround it. ill fix it when i get home =issue closed.
