### ISSUE TITLE
Suggestion: allow seats to use the elytra

### ISSUE THREAD

**Issue by writeescape** [bergerhealer/TrainCarts#360]
Suggestion: allow the seat attachment to use the elytra mechanic 

#### wanted behaviour: check if the version has the elytra (1.9 and up) and call player.isGliding() or use packets to emulate it.  

Perhaps a option in the menu to say what type of seat a player would like

**Comment by bergerkiller** [comment]
Is it possible to put a player in an elytra flying state without placing an elytra item in the player's inventory? It's not a show stopper if I have to, as I can just resend the correct inventory state when the player exits / mode changes.

I suppose the main goal is visual appearance?

**Comment by bergerkiller** [comment]
I think this would make a pretty great addition, especially because it makes the whole upside-down dinnerbone hack unneeded.

**Comment by writeescape** [comment]
No you can just use packets to tell the client it's gliding, no need for an actual elytra.

You would have to disable an event I'm unsure what it's called

**Comment by bergerkiller** [comment]
![ScreenShot_2020-05-24 12-46-28](https://user-images.githubusercontent.com/957601/82752190-98ba9a80-9dbc-11ea-912d-3917addc09b1.png)
looks like all you need to do is set the entity FLYING flag. I thought this flag was for creative flight, but maybe I was wrong and is that done through abilities.

**Comment by writeescape** [comment]
Have you seen what angles you can use this mechanic for I think it's -90 to 90

**Comment by bergerkiller** [comment]
I did do some early experimenting a long time ago, but I haven't really checked the limitations yet. Honestly, having a player be superman on a ride is neat enough :)

**Comment by writeescape** [comment]
Can you close this issue when you've implemented it

**Comment by bergerkiller** [comment]
I will, going to work on this now since it seems quite a simple thing to implement

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/TrainCarts/commit/28ae6704c3db54185c863332b135cdb01c2a04fc this adds support for the elytra display mode while combined with the sitting animation. There's some room for improvement though.

Elytra flying is a todo, so Ill leave this open

**Comment by bergerkiller** [comment]
The 'sit' mode for the elytra is now fully implemented, including a bunch of fixes to do with passenger synchronization (both first and third person). The seat configuration menu is now more flexible this way.

Full elytra flying mode might be difficult, because I assume player input can easily override the movement the train ties to push the player. That said, I have not tried doing it yet.

**Comment by bbayu123** [comment]
Closing since berger says it's fully implemented.
