### ISSUE TITLE
Suggestion Train_Cart

### ISSUE THREAD

**Issue by Kawaks0** [bergerhealer/TrainCarts#361]
Suggestion:

I had an idea that can be simpa for the big coaster with a lot of inversion etc ... Add a function so that when we got on the train it puts us in spectator Gamemode so that when there are mounts and inversion it follow the curve

**Comment by bergerkiller** [comment]
That is something also discussed already yeah, I haven't looked into this yet. It would involve using the camera packet to switch the first person player view to that of a detached flying head. It would also allow roll, something not possible otherwise

**Comment by bbayu123** [comment]
Closing feature request: Already added - see seat options in attachment editor, or alternatively use [SmoothCoasters](https://modrinth.com/mod/smoothcoasters).
