### ISSUE TITLE
Getting the actual location of a passenger

### ISSUE THREAD

**Issue by csev98** [bergerhealer/TrainCarts#362]
https://github.com/bergerhealer/TrainCarts/blob/4fab1568b6e6350afb11b79aeed8a506e89ec0a9/src/main/java/com/bergerkiller/bukkit/tc/controller/MinecartMember.java#L575

Is there a reason why the function above is only returning a default vector? Because the name of the function and the parameter would suggest that I can request the actual location of a passenger with this function.

Is there maybe another way I can request the actual location of a passenger? Because when I'm using seat attachments, the location of a player seems to be always in the middle of the cart when requesting it.

**Comment by bbayu123** [comment]
The player only exists where the minecart exists on the server. The server does not know about any attachments being present, and thus does not know the exact player's location.

There is a way to return the actual location of the player as seen by the client, but I am not familiar with the way of doing so.

**Comment by bergerkiller** [comment]
Thats a very good question haha. Very old code, I very much doubt I still use that function. Instead I query the attachments (network controller) what the seat positions are.

**Comment by csev98** [comment]
I hate to be that guy, but could you give me an example on that? Lets say I have the minecart group of the passenger and I would like to know the exact location of that passenger.

**Comment by bergerkiller** [comment]
I think Ill just fix that function up instead of explaining, but the code to do it is in TCListener as part of the vehicle exit event handling

**Comment by csev98** [comment]
Aah okay that is awesome, in the mean time I'll keep trying to figure it out.

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/TrainCarts/commit/3dd5a3251c1f9b3714c2f32c82f9ab60f9b321ed

**Comment by csev98** [comment]
Awesome! I was almost there with the code from the exit event, but this makes it much better. Thanks!
