### ISSUE TITLE
When placing minecarts it spawns a duplicate of itself and refuses to connect with other carts

### ISSUE THREAD

**Issue by TREGuy365** [bergerhealer/TrainCarts#363]
##### Spigot version: 1.15.2 (BungeeCord)

<hr>

#### Steps to reproduce: None, may be a server issue (An internal Error occurred when performing this command)

Plugins: bPerms, Signlink, EssentialsX, EssentialsChat, GSit, TrainCarts, Vault, CCTV, ChestShop and WorldEdit.

**Comment by bergerkiller** [comment]
Can you confirm this version fixes this? Ive seen this reported many times, so far this was the solution.

https://ci.mg-dev.eu/job/BKCommonLib/789/

**Comment by TREGuy365** [comment]
I'll test it
Thanks!
