### ISSUE TITLE
When Deselecting a TCC Node it Selects A Batch of Nodes

### ISSUE THREAD

**Issue by dfreak5** [bergerhealer/TrainCarts#368]
##### Spigot version: 112 (Latest)

<hr>

**Comment by bbayu123** [comment]
Problem unclear, please provide video to explain.

**Comment by dfreak5** [comment]
Here you go! 
[https://www.youtube.com/watch?v=2n8JvKFVBfo&feature=youtu.be](url)

**Comment by bergerkiller** [comment]
Oof this explains a lot of things. Thanks for reporting this! It's quite a big issue.

Hopefully this fixes it: https://github.com/bergerhealer/TC-Coasters/commit/8eeb919ef0ddcc0b35e2c8e91c9e56d3122e5f3d
https://ci.mg-dev.eu/job/TC%20Coasters/171/

**Comment by dfreak5** [comment]
Yes that did indeed fix it, thank you so much!
