### ISSUE TITLE
[FeatureRequest] Lever on waiter-signs

### ISSUE THREAD

**Issue by J0schlZ** [bergerhealer/TrainCarts#369]
Not a bug, just another feature-request

Please add a lever on waiter-signs to respond if a train is stopped/released which acts the same way like the lever on station-sign does.

<3

**Comment by bbayu123** [comment]
Moved to correct repository.

**Comment by bbayu123** [comment]
Good suggestion.

**Comment by bergerkiller** [comment]
Implemented as of https://github.com/bergerhealer/TrainCarts/commit/9a4cb2e606f115ae3a634c85c46e0dbe5076071e
