### ISSUE TITLE
Suggestion: Friction property signs

### ISSUE THREAD

**Issue by ImNotAlexx** [bergerhealer/TrainCarts#370]
Essentially what i mean by this is like what the gravity signs are. A property sign in which you can define a value and this value chooses how fast/slow the train loses speed whilst travelling on the track. Currently the gravity sign only changes this speed when going up and down, but not flat tracks, meaning the train can stall very fast depending on the situation. 
The use would be somewhat like this:
[+train]
property
friction
1
this would apply the normal friction setting that is defined in config
[+train]
property
friction
0.5
this would be half the amount of friction, causing it to slow down half as fast, and finally
[+train]
property
friction
2
this would be twice the amount of friction, causing it to slowdown twice as fast.

**Comment by bbayu123** [comment]
Suggestion was accepted and implemented. See c6c6192.
https://ci.mg-dev.eu/job/TrainCarts/915/
