### ISSUE TITLE
New blockchanger options

### ISSUE THREAD

**Issue by Andre601** [bergerhealer/TrainCarts#371]
##### Spigot version: PaperMC 334 (MC 1.15.2)

<hr>

#### Idea
There are two separate ideas related to the `blockchanger` sign which would allow more customisation in various places.

##### Idea 1: Skip option
I thought about making a hangrail system, but I dislike the look of when all minecarts (including the ones that players sit in) have a cobble fence or similar.
An option to skip specific amounts of minecarts would be nice to have. The skiped minecarts would just keep the current block displayed.
I imagine this as either a specific name (i.e. `skip`) or just having empty sections.

So a sign could either be this:
![image](https://user-images.githubusercontent.com/11576465/84721384-d86e3f80-af80-11ea-8162-2f0009f1d149.png)

or this:
![image](https://user-images.githubusercontent.com/11576465/84721423-ed4ad300-af80-11ea-9ff9-cb485fbacb36.png)

##### Idea 2: Random collection
I'm sure a few people use the blockchanger to set ores or similar in their train composition, to mimic mining carts.
It would be a nice option to have, if you could randomize the blocks displayed.
An idea I have would be a separate type of sign called `rblockchanger` which would use the provided blocks (or shortcuts) and randomly selects one for each cart (or for x cart if it is a shortcut), making it look different each time the train passes by that sign.

Idea of the sign's look
![image](https://user-images.githubusercontent.com/11576465/84721740-9eea0400-af81-11ea-8d9d-8dba7ea77c83.png)

**Comment by bbayu123** [comment]
Blockchanger is no longer supported, please use attachments and animations to change blocks.

**Comment by Andre601** [comment]
Sure, but the thing is that attachments don't look as fluid as when the block inside a minecart was actually changed (Always moves in front/behind a minecart and just looks wrong), and from what I can tell is there no way of randomly setting attachments in the minecarts, skipping some, etc. with just signs.
So no longer supporting this is - to put it simple - shit.
