### ISSUE TITLE
Stations act buggy when using levers

### ISSUE THREAD

**Issue by Andre601** [bergerhealer/TrainCarts#373]
It would be nice, if the station sign could have an option where it would send a redstone signal (or activate a lever) once a train is above it.

Comment containing nessesary Info:
https://github.com/bergerhealer/TrainCarts/issues/373#issuecomment-644975724

**Comment by Galactinaut** [comment]
This is already a thing lol

**Comment by Andre601** [comment]
I see. Thanks for the info.

**Comment by Andre601** [comment]
I reopen this, because the lever seems to cause some minor issues when directly attached to the block with the station sign.

In more detail, here's the setup I have for the station sign.

Front:
![2020-06-16_21 43 04](https://user-images.githubusercontent.com/11576465/84820784-6c401a00-b01a-11ea-8715-fe8124bf8bd7.png)

Back:
![2020-06-16_21 42 04](https://user-images.githubusercontent.com/11576465/84820803-7235fb00-b01a-11ea-97b5-2fa234e81cbe.png)

Having this setup causes the lever on the back to activate once the train is on it, but the train won't continue after the specified time, even when you power the sign on either the left or right side.
It just gives the "hiss" sound after the specified time while the train remains unchanged.

BkCommonLib version: 1.15.2-v4
TrainCarts version: 1.15.2-v1
Server: PaperMC 334 (MC 1.15.2)

**Comment by Andre601** [comment]
In more detail.

Having this setup causes this issue. The right level will always turn off and on again, "resetting" the timer.
![2020-06-16_21 51 53](https://user-images.githubusercontent.com/11576465/84821670-c4c3e700-b01b-11ea-9420-50fbf4b3a08d.png)

**Comment by jaystocky** [comment]
Set up the station sign like this:
[+train]
station
10

This configuration means that the sign will not respond to any inputted power which will prevent the issue from happening.

**Comment by Andre601** [comment]
This isn't the system I want to have.

I want to have a central station where the trains would wait until all are there, before they start again (preventing them from any possible collision happening)

**Comment by bbayu123** [comment]
Try using redstone torches to control station signs instead of levers directly

**Comment by LoyaltyGamer72** [comment]
It happens to me too, i need to control the signal AND have an output, it just downt work, the output lever intefres with the sign and makes a clock

**Comment by Andre601** [comment]
I close this as A) the lever can be attached to the back of the sign without issues and B) I no longer use this at all but found a differen solution that worked (Essentially putting the sign on the other side...)

**Comment by LoyaltyGamer72** [comment]
No it can't, I attach it to the back even with +train and it still bugs because of the lever in the back, I'm in 1.15.2.
