### ISSUE TITLE
[1.16] Trains become invisible after server restart

### ISSUE THREAD

**Issue by JLyne** [bergerhealer/TrainCarts#379]
##### Spigot version: git-Tuinity-"9f21359" (MC: 1.16.1)

<hr>

I'm aware this is a dev version, but thought I'd make an issue anyway in case no-one has run into it.

#### Problem or bug:
Trains become invisible after a server restart. They still exist, show up in /train list, can be teleported to with /train tp, and still play hissing sounds when at a station etc. However they are invisible on the client side and cannot be interacted with at all. Mobs that were in the carts still appear, but cannot be interacted with.

#### Expected behaviour:
Trains do not disappear on server restart.

#### Steps to reproduce:
1. Create a train
2. Restart the server
3. Observe how the train is no longer visible, but still exists from the plugin's perspective

**Comment by weeryan17** [comment]
If you find a bug like this in the 1.16 version please ask about it in the [support server](https://discord.gg/DAhNQaB) before making an issue report.
1.16 is currently very much unstable and bugs like this are already known. We don't need to clog up the issues reports with issues like this if we don't have to. I'm going to keep this open as it is still a valid issue, just please report 1.16 errors in discord in the future.

**Comment by JLyne** [comment]
Very well, my mistake

**Comment by bergerkiller** [comment]
Can you check if its fixed? https://github.com/bergerhealer/BKCommonLib/commit/7c24eef8216c258a291c55b9971016d0622f99fb

https://ci.mg-dev.eu/job/BKCommonLib/827/

**Comment by JLyne** [comment]
Appears to be fixed. Can no longer reproduce under the same conditions.
