### ISSUE TITLE
Can I get the trains of TrainsCarts into my own plugin?

### ISSUE THREAD

**Issue by lgplay** [bergerhealer/TrainCarts#384]
Hi, I want to add sounds to the carts depending on its speed. I was trying to calculate this myself using the vehiclemoveevent, but the problem is, it is never the same as the /train info speed, can I somehow get that from the TrainCarts Plugin? Or get all trains out of it? Already thank you if you reply

**Comment by bergerkiller** [comment]
Yup, the MinecartMemberStore class has a method to obtain the MinecartMember of an Entity. A MinecartMember is basically a single cart of a train. It provides methods to get the speed ('Force'), and you can query options using .getProperties(). The train is called a MinecartGroup, and is obtained using .getGroup().

**Comment by lgplay** [comment]
That you very much for your answer, really helped me a lot
