### ISSUE TITLE
attachment edditor

### ISSUE THREAD

**Issue by marlis999** [bergerhealer/TrainCarts#389]
## Info
Please provide the following information:

- BkCommonLib Version (`/1.16.1 v1`): 
- TrainCarts Version (`/1.15.2 v1`): 
- Server Type and Version (`/spigot 1.16.1`):

----
### Description
if i open the attachment editor and select a minecart, you cant see all the images on the editor and the buttons like space bar dont work. i cant edit the minecart. 

### Expected behaviour
What do you expect TrainCarts to do?
i expect a working menu to edit the minecarts.
### Actual behaviour
instead there is 1 working image and all the buttons dont work.

### Steps to reproduce
/train attachments
select the minecart
try to edit it

###other things
i removed the ferris out of the code, because my server cant handel it.
i is a free server on aternos

sorry for bad english, i am from the netherlands.
![attachment bug](https://user-images.githubusercontent.com/69416803/89728632-ed21fd80-da2e-11ea-9919-1e9cc038612d.png)

**Comment by bbayu123** [comment]
Outdated Version, use TrainCarts 1.16.1-v1.

**Comment by bbayu123** [comment]
If 1.16.1-v1 is not provided on Aternos, then there's nothing we can do.

**Comment by marlis999** [comment]
> 
> 
> If 1.16.1-v1 is not provided on Aternos, then there's nothing we can do.

oh, sad. than i cant use skins on the minecarts

**Comment by bbayu123** [comment]
Yea, unfortunately, we have no control over when Aternos updates a plugin, so if you have any more issues, you should just complain to Aternos for not updating.
