### ISSUE TITLE
Automatically cleaning up empty carts

### ISSUE THREAD

**Issue by sparky222b** [bergerhealer/TrainCarts#39]
Not sure if this is a missing feature or if I just don't know how to configure it - but is there a way to periodically "garbage collect" empty carts? Would be useful to prevent overcrowding.

**Comment by RyanHecht** [comment]
I've been thinking about this lately too; I think it's less helpful to garbage collect empty CARTS, and more helpful to garbage collect empty TRAINS. Think about it, if you're in row one of a train, your friend is in row three, and the garbage collector runs, there will just be an empty space...but yeah, to my knowledge, this feature doesn't exist (yet, fingers crossed)

**Comment by mg-1999** [comment]
Just make a plugin that extends TC. Check if all carts in a train are empty and remove them. Add this in a runnable and you've just nailed it.

**Comment by JackDn** [comment]
@mg-1999 I think this issue can be closed.
