### ISSUE TITLE
Magma - server console floods with errors after a player joins

### ISSUE THREAD

**Issue by vico93** [bergerhealer/TrainCarts#390]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): - BKCommonLib-1.16.2-v1-SNAPSHOT.jar - Build #877 (Wed Aug 19 21:10:21 UTC 2020);
- TrainCarts Version (`/train version`): TrainCarts-1.16.1-v2-SNAPSHOT.jar - Build #698 (Sun Jul 26 22:55:12 UTC 2020);
- Server Type and Version (`/version`): [Magma](https://github.com/magmafoundation/Magma) Dev HEAD-e458366 (Forge/Paper hybrid for 1.12);

----
### Description
After testing my modpack with Magma 1.12 and it didnt give me any errors or unintended behavior, i tried to test BKCommonLib and TrainCarts with the stack.
On placing BKCommonLib on `plugins` and running the server (without changing any Bukkit/Spigot-specific setting - aka leaving all .ymls on server root as default) i got some warnings for BKCL at start. But bergerkiller just said it could be safely ignored, and after the warnings BkCommonLib seems to be loaded correctly.

- [First log](https://hastebin.com/afikumexon.sql)

After the server finished loading, i tried to join the world and when i did it the console began to flood exponentially with errors, and although i was able to play seemingly normally, when i tried to make a basic train nothing happened. The plugin seems to not work correctly.

- [Partial log right after joining (and not messing with minecarts)](https://hastebin.com/imigevomol.rb)
- [Log when trying to make a train](https://hastebin.com/osuhiyawim.sql)

I'm posting bits of the log file because it got an whooping **118mb** of size, and i can share the whole only if i upload via some cloud or WeTransfer.

### Expected behaviour
Abeit some small errors in the console like bergerkiller was expecting, the plugin should work fine

### Actual behaviour
Not only it doesnt work, the log size scalated in size to ~100mb in circa 5 minutes of gameplay, with a single player connected.

### Steps to reproduce
- Install the Magma release "Dev HEAD-e458366" (available on its github);
- Install some mods, possibly GalacticCraft, CC:Tweaked, FutureMC or Quark (the three most complex on my modpack);
- After a run only with mods install both BKCommonLib and TrainCarts, run again the server (leaving Magma's settings for Paper side as default) and try to join it.

### Additional Information
If the devs have interest i can send privately my profile (aka modpack) for further testing.
Client-side i'm currently using Forge 2854 (which i believe is the same version Magma uses).

**Comment by bergerkiller** [comment]
Sorry for late reply, know that I acknowledge these issues and will look at them after I've finished working out some problems in MyWorlds' portal/teleportation system.

**Comment by bergerkiller** [comment]
I failed to get Magma to boot with some of the mods in your suggestion. I tried galacticraft, since its a pretty large modpack, but it errors out on NoSuchField REGISTRY. Im probably using the wrong version/download?

Are mods required to run into these errors?

**Comment by vico93** [comment]
I can send my whole profile folder privately (~150 MB) if you wish; my discord user is `vico#9414`.

**Comment by bergerkiller** [comment]
I've run your modpack and now after several fixes all errors appear to be resolved. Have a try.

https://ci.mg-dev.eu/job/BKCommonLib/890/

**Comment by vico93** [comment]
Thank you so much!
