### ISSUE TITLE
Why there're many pages of wiki are mission(I can't find)?

### ISSUE THREAD

**Issue by xiaolizi20070827** [bergerhealer/TrainCarts#391]
Mean in title.

**Comment by xiaolizi20070827** [comment]
Sorry, that word in title "Mission" mean "Can't find"

**Comment by bergerkiller** [comment]
What pages are missing from what wiki exactly? Minecraft wiki? The wiki of Traincarts itself isn't really maintained. https://minecraft.gamepedia.com/Custom_servers/Bukkit/TrainCarts

**Comment by xiaolizi20070827** [comment]
...
ok
(I mean github)

**Comment by bergerkiller** [comment]
Yeah the wiki hosted here should probably be removed, or just point to the minecraft wiki. Only the custom mods minecraft wiki page is actively updated at this time. There were some plans to do something with the github-hosted wiki, but nothing much came of it.
