### ISSUE TITLE
Spigot page wiki link is outdated

### ISSUE THREAD

**Issue by Freddo3000** [bergerhealer/TrainCarts#394]
https://www.spigotmc.org/resources/traincarts.39592/

It still points towards https://minecraft.gamepedia.com/Mods/TrainCarts which refers to a page that doesn't exist. It should probably link to the wiki here on Github.

**Comment by Andre601** [comment]
The actual wiki is found under https://wiki.traincarts.net as the original one, which was previously on the Minecraft Wiki is being moved to the FTB wiki (without any prior notice or warning).

**Comment by bergerkiller** [comment]
We've had a long conversation on the minecraft wiki talk pages with various people. We are migrating the old wiki to wiki.traincarts.net, OR, traincarts.net/wiki. Not sure yet which one will be the final decision. I'll update the link to that one for now, but it might change as we decide on a final url, so I'm leaving this issue ticket open.

**Comment by Andre601** [comment]
I personally would recommend a more generic domain to use, IF the wiki should also contain info from other plugins such as BKCommonLib, MyWorlds, etc.
Because when reading either wiki.traincarts.net or traincarts.net/wiki I immediately think about it being only for traincarts and not the entire plugin stuff.

**Comment by bergerkiller** [comment]
I agree, but I don't know of a good generic name to use. Traincarts.net should probably be traincarts only, maybe its worth buying another domain (for the same server) hosting the other wiki pages. Maybe bergerhealer.org?

**Comment by Andre601** [comment]
Would be an option... There is sadly no .lib TLD or otherwhise bkcommon.lib would've been a nice option to have.
But I think the .org domain would indeed be an option.

On that note, maybe also consider to change the CI domain? mg-dev.eu is a really weird domain to have if you ask me... But at the end is this all up to you.

**Comment by bergerkiller** [comment]
Well, I bought the bergerhealer.org domain before some troll snatches it. I'll discuss with ryan, but will probably setup some system where both wikis are hosted on the same server, but with different domains to get there.

**Comment by Andre601** [comment]
The best (and imo easiest) way would be to have the traincarts act as a redirect to the TC part of the wiki.

But I think we should move this to the Discord, to not flood Freddo's e-mails/notification feed.

**Comment by Freddo3000** [comment]
> But I think we should move this to the Discord, to not flood Freddo's e-mails/notification feed.

I don't mind ¯\_(ツ)_/¯

**Comment by bbayu123** [comment]
Closing this as I can personally confirm this has been fixed.
