### ISSUE TITLE
Switcher ignores blocker signs

### ISSUE THREAD

**Issue by Tigerhoernchen** [bergerhealer/TrainCarts#396]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): 1.16.3-v2-SNAPSHOT (build: 925)
- TrainCarts Version (`/train version`): 1.16.3-v2-SNAPSHOT (build: 726)
- Server Type and Version (`/version`): git-Paper-655 (MC: 1.13.2)

----
### Description
The switcher sign is not looking for an alternative route if there is a blocker sign in it.

### Expected behaviour
Check if there is a blocker on the path.

### Actual behaviour
The switcher sends the train directly to the best track, without considering blocker signs.

### Steps to reproduce
Place a train with a destination. The destination to reach is behind that blocker.
Let the train drive over a switcher so he can search for alternative paths because there is a blocker in the way.
Images below: Destination behind the stopper is K1102
![2020-10-18_07 31 00](https://user-images.githubusercontent.com/36344030/96359505-e5a86000-1113-11eb-96f3-8292004fe1e4.png)

![2020-10-18_07 31 42](https://user-images.githubusercontent.com/36344030/96359510-fb1d8a00-1113-11eb-8aa2-de9624033a1b.png)

![2020-10-18_07 22 10](https://user-images.githubusercontent.com/36344030/96359465-66b32780-1113-11eb-8828-6eb7e132e004.png)

Red: Blocker
Blue: Theoretically best alternative path
Green: Switcher
Weird drawn circle in black: Destination sign to reach
![grafik](https://user-images.githubusercontent.com/36344030/96359707-20ab9300-1116-11eb-9d7a-5b2bfe558a2c.png)

### Additional Information
Any additional information we should know of? Ehm. I don't think so ✌️

**Comment by bbayu123** [comment]
It probably can't find it because the alternative path is too long, I do believe there's some kind of limit, don't remember what the limit is though.

**Comment by bergerkiller** [comment]
The debug stick since 1.16.3 v1-2 should work fine with that, so that's not it. The path finding itself has no limit, it just takes longer to find the other routes when its far away.

Have you tried /train reroute, or crouching (shift) while hitting the rails with the stick to reroute that local area?

**Comment by Tigerhoernchen** [comment]
Shifting helped (didn't do the general reroute yet). I updated the plugin today and tought because everything is running fine and was new it should do that already automatically.

**Comment by bergerkiller** [comment]
It only does it automatically when you place and remove switcher signs. Tracking all the track part of a route would be too memory-intensive, so placing down a blocker sign doesn't refresh any previous routes.
