### ISSUE TITLE
Traincart don't work

### ISSUE THREAD

**Issue by issac4892** [bergerhealer/TrainCarts#397]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): 
- TrainCarts Version (`/train version`): 
- Server Type and Version (`/version`):
[월, 19. 10월 2020 09:40:05 KST INFO] Train_Carts v1.12.2-v1 using BKCommonLib v1.12.2-v5
This server is running Paper version git-TacoSpigot-"f8ba67d6" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[월, 19. 10월 2020 09:40:16 KST INFO] Previous version: git-Paper-1618 (MC: 1.12.2)
[월, 19. 10월 2020 09:40:16 KST INFO] Checking version, please wait...
[월, 19. 10월 2020 09:40:17 KST INFO] You are 1 commits behind the latest version!
----
### Description
Please replace this sentence with a detailed description of what exactly happens that you consider a bug.  
Try to explain it as if you would tell a friend.
The server's players say that it just doesn't work
### Expected behavior
What do you expect TrainCarts to do?
Just work properly
### Actual behavior
What is TrainCarts doing instead?

### Steps to reproduce
Please list the steps to take, in order to reproduce the bug.
It just once started to happen
### Additional Information
`
<[월, 19. 10월 2020 09:39:40 KST ERROR] Failed to perform physics on train 'train700' at null:
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at java.util.ArrayList.rangeCheck(Unknown Source)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at java.util.ArrayList.get(Unknown Source)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.head(MinecartGroup.java:115)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.head(MinecartGroup.java:119)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.getSpeedAhead(MinecartGroup.java:994)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:1137)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:955)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMember.onTick(MinecartMember.java:1424)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:117)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen3036d523.invokeVA(Unknown Source)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.FastMethod.invokeVA(FastMethod.java:112)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:654)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at net.minecraft.server.v1_12_R1.EntityMinecartRideable$$EnhancerByCGLIB$$6e471449.B_(<generated>)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1779)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at net.minecraft.server.v1_12_R1.World.h(World.java:1749)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1564)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[월, 19. 10월 2020 09:39:40 KST ERROR] [BKCommonLib]   at java.lang.Thread.run(Unknown Source)>
`

**Comment by bergerkiller** [comment]
`Train_Carts v1.12.2-v1 using BKCommonLib v1.12.2-v5`

Wow thats a pretty old version! Please install BKCommonLib 1.16.3 and Traincarts 1.16.3 release from spigot. These versions **also** work with Minecraft 1.12.2.

**Comment by issac4892** [comment]
ok, i will try it

2020년 10월 19일 (월) 오전 9:53, Irmo van den Berge <notifications@github.com>님이
작성:

**Comment by issac4892** [comment]
LOL IT WORKED
