### ISSUE TITLE
TCC switch track bug

### ISSUE THREAD

**Issue by Disneykid93** [bergerhealer/TrainCarts#399]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): 1.16.3-v1
- TrainCarts Version (`/train version`): 1.16.3-v1
- Server Type and Version (`/version`): 1.15.2

----
### Description
The track switches when there is no sign underneath after manually selecting track to send the car in the direction I want it.

### Expected behaviour
Track switch is supposed to stay on the selected track 

### Actual behaviour
Track is switching back to "default" and not staying on the desired track

### Steps to reproduce
Please list the steps to take, in order to reproduce the bug.

### Additional Information
Video showing what has been happening.- https://www.youtube.com/watch?v=mpqXtO6pHS0&feature=youtu.be

**Comment by bbayu123** [comment]
Just wondering, since it's been a while, is this issue still relevant?

**Comment by Disneykid93** [comment]
No it's not anymore.

**Comment by bbayu123** [comment]
Got it, closing it then.
