### ISSUE TITLE
Trains no longer spawn

### ISSUE THREAD

**Issue by DomPrice** [bergerhealer/TrainCarts#400]
I changed the spawn time from 1:30 on all my carts to 1:40... As a result, Trains have stopped spawning, even when I change the time back to 1:30... I've even tried uninstalling and reinstalling the plugin. 

Format I am using:
[+train]
spawn
1:30 0.5
mmmmmmmm

I have tried both "spawn" and  "spawner" and neither work

**Comment by bergerkiller** [comment]
You put the time and speed on the wrong lines. They must be on the same line as spawn, with a space between

**Comment by DomPrice** [comment]
Oh doh! I'm an idiot. Thanks! Minecraft wiki took down all the TrainCarts Stuff, so I no longer have my goto reference. :(

**Comment by bergerkiller** [comment]
The wiki is now here: https://wiki.traincarts.net/index.php/TrainCarts
