### ISSUE TITLE
Launcher command problem

### ISSUE THREAD

**Issue by Tigerhoernchen** [bergerhealer/TrainCarts#401]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.16.4-v1 (build: 742)
- TrainCarts Version (`/train version`): v1.16.4-v2 (build: 939)
- Server Type and Version (`/version`): git-Paper-655 (MC: 1.13.2)

----
### Description
It's not possible to change the direction with the /train launch command.
Even with giving direction (forward, backward, north, eath, south, west) it's not changing.

### Expected behaviour
Changing the direction by giving the direction or by looking at the direction.

### Actual behaviour
It's rolling forward in the current direction.

### Steps to reproduce
Place minecart.
Sit in or not.
/train launch (and look to the direction)
/train launch <forward, backward, north, eath, south, west>

### Additional Information
Nope.

**Comment by bergerkiller** [comment]
I noticed this too myself, it should at least launch you to where you're looking. Will need to be fixed

**Comment by Tigerhoernchen** [comment]
I tried with different facing directions directions but nah didn't really work.

**Comment by bergerkiller** [comment]
Im fairly certain that now, after all the command changes, this should now properly work with the latest snapshot
