### ISSUE TITLE
Waitdistance and saved trains

### ISSUE THREAD

**Issue by Tigerhoernchen** [bergerhealer/TrainCarts#402]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.16.4-v1 (build: 742)
- TrainCarts Version (`/train version`): v1.16.4-v2 (build: 939)
- Server Type and Version (`/version`): git-Paper-655 (MC: 1.13.2)

----
### Description
The waitdistance is not applied to a savedtrain when spawning.

### Expected behaviour
The saved train spawns and when it's near to collide with a train it should stop.
https://paste.traincarts.net/radahaloka <- My train

### Actual behaviour
It's crashing into the front one. Cause it seems that it's not getting the properties.

### Steps to reproduce
Give the train a waitdistance.
Save the train.
Spawn the saved train.
Launch it into another train.
BOOOOMMM

### Additional Information
Nope.

**Comment by bergerkiller** [comment]
Was a bug in last release and has since been fixed as part of the commands/properties rewrite
