### ISSUE TITLE
master does not compile

### ISSUE THREAD

**Issue by JaegerP** [bergerhealer/TrainCarts#404]
I'm trying to upgrade my server from mc 1.15.2 to 1.16.4/latest. When compiling the TrainCarts plugin from source 
`mvn clean package`
I get
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.012 s
[INFO] Finished at: 2020-12-31T10:33:45-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project TrainCarts: Could not resolve dependencies for project com.bergerkiller.bukkit:TrainCarts:jar:1.16.4-v2-SNAPSHOT: Failed to collect dependencies at org.spigotmc:spigot:jar:1.13.2-R0.1-SNAPSHOT: Failed to read artifact descriptor for org.spigotmc:spigot:jar:1.13.2-R0.1-SNAPSHOT: Could not transfer artifact org.spigotmc:spigot:pom:1.13.2-R0.1-SNAPSHOT from/to mvnrepository (https://mvnrepository.com/artifact/): Access denied to: https://mvnrepository.com/artifact/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.pom -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

Checking `-e` shows that `https://mvnrepository.com/artifact/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.pom` can't be found and 404s.

I tried setting some dependency versions in `pom.xml` manually, and to update the repository location as indicated here https://www.spigotmc.org/wiki/spigot-maven/, but couldn't resolve the issue. As long as it's a maven issue only, I'm happy helping to fix it, but I feel like someone involved in the project might have more insight regarding which dependencies should be pulled for a specific version of mc.

(There are binaries here https://www.spigotmc.org/resources/traincarts.39592/history which seem to work, I'd just prefer to be able to compile all plugins from source)

**Comment by Andre601** [comment]
> I tried setting some dependency versions in pom.xml manually, and to update the repository location as indicated here https://www.spigotmc.org/wiki/spigot-maven/, but couldn't resolve the issue. As long as it's a maven issue only, I'm happy helping to fix it, but I feel like someone involved in the project might have more insight regarding which dependencies should be pulled for a specific version of mc.

Did you make sure to also refresh the cache, so that it re-checks and downloads the dependencies?

**Comment by weeryan17** [comment]
1. I suggest just grabbing a build from jenkins [https://ci.mg-dev.eu/](https://ci.mg-dev.eu/), it automatically builds the latest commit.
2. You need to build spigot using build tools on the computer your trying to compile the plugin. The maven repos don't provide the jar files due the the mojang eula. When you build spigot it will put the jar in your computers maven folder.

**Comment by JaegerP** [comment]
Thanks @Andre601  and @weeryan17 for replying so quickly.

Here's what I tried on a clean VM, so initially no local repository present:
1. Clone and compile build tools (latest git version)
2. Compile spigot-1.16.4 using build tools (`java -jar BuildTools.jar --rev 1.16.4 --compile SPIGOT`)
3. Clone and compile TrainCarts, with the above results

Am I missing a step?

**Comment by Andre601** [comment]
Already done
https://github.com/PlaceholderAPI/PlaceholderAPI/commit/8fa0f73a46a5e452dc12c57580704ea394659193

**Comment by weeryan17** [comment]
You need to compile 1.13.2 as well (as indicated by the fact it says it can't download 1.13.2)

**Comment by JaegerP** [comment]
That does it...thanks again.

If I remember correctly it is possible to pull maven dependencies from git directly. I could try to come up with a `pom.xml` that does that and submit a pull request, if there is any interest in that. (Or a *NIX style configure script...)
