### ISSUE TITLE
Minecarts sometimes get stuck on 180 degree turns

### ISSUE THREAD

**Issue by JLyne** [bergerhealer/TrainCarts#405]
## Info
Please provide the following information:

- Train_Carts: v1.16.4-v2-SNAPSHOT (build: 822)
- BKCommonLib: v1.16.4-v3-SNAPSHOT (build: 991)
- Server: git-Spigot-a93cbb1-7a6c3c9 (MC: 1.16.4)

(Issue was initially encountered on the spigot TrainCarts v1.16.4-v1 release and is still present when testing with the above versions).

----
### Description
Minecarts sometimes seem to have trouble navigating 180 degree turns, which causes them to start bouncing between 2 such turns when multiple are placed together. The exact position they get stuck in seems to vary, so this doesn't appear to be intended behaviour.

See the attached video for a demonstration.

https://user-images.githubusercontent.com/4615316/104820631-1f315a00-582e-11eb-91ae-851bf8d054b4.mp4

This issue persists when using Purpur/Paper/Spigot, Java 15/11/8, and after removing all non traincarts plugins and resetting the config.

### Expected behaviour
Minecarts correctly navigate 180 degree turns

### Actual behaviour
Minecarts will often get stuck bouncing between 180 degree turns, but not 100% of the time.

### Steps to reproduce
1. Create a minecart track that features multiple 180 degree turns. A simple S shape should do.
2. Place a minecart on one end of the track and get it moving
3. Observe how the minecart likely gets stuck between 2 of the turns at some point.

**Comment by bergerkiller** [comment]
Ah this is a classic bug, I guess it re-appeared unfortunately. Problem is that, to fix this, it ends to break other physics in its wake. Which is probably why this is now broken again, a previous 'fix' mustve done it.

Thanks for reporting, will need to be looked at soon

Related is the glitch of tc-coasters when going on a junction at < 90 degree sharp turns

**Comment by djbenbe** [comment]
I have tested this and only with powered rails it does not have this problem with regular rails

**Comment by bergerkiller** [comment]
Did a rewrite of some of the movement physics, which definitely has an impact on this too. It seems fixed. Have a test :)

https://github.com/bergerhealer/TrainCarts/commit/e58a40551842e4fc0756fb9e8b5dc50fe62d59f1

https://ci.mg-dev.eu/job/TrainCarts/828/

**Comment by JLyne** [comment]
Gave that build a go. I can't reproduce the turn issue anymore, so that does seem to be fixed.

Unfortunately it seems block collisions are no longer working correctly in that build, as trains are now going into the blocks at either end of the track (similar to #380 except without having to actively push the cart). Don't know if that's worth it's own issue or not.

![image](https://user-images.githubusercontent.com/4615316/105563706-071e7680-5d17-11eb-825b-1ca239aa0a4d.png)

**Comment by bergerkiller** [comment]
Thanks for letting me know about that, yeah that issue makes sense. No need for an extra issue ticket, Ill look into this tomorrow

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/TrainCarts/829/ this fixes this problem for me. It wasn't detecting train reversal initiated by the powered rail (launching away from block), which caused the train to move into the block rather than away during the post-update.

**Comment by JLyne** [comment]
Working fine for me now, thanks for the quick fix
