### ISSUE TITLE
When the hopper minecart encounters an air block, it will drift and fly out

### ISSUE THREAD

**Issue by vc606** [bergerhealer/TrainCarts#407]
## Info
Please provide the following information:

- BKCommonLib-1.16.5-v1 Version (/train version):
- TrainCarts-1.16.5-v1-SNAPSHOT (/train version):
- Paper1.16.5_444 (/version):

----
### Description
I accidentally discovered that when the hopper minecart is pushed out, it will fly out until it hits the wall.
https://i.imgur.com/O0rYtgk.mp4

### Expected behaviour
The hopper minecart should follow the rails instead of flying out

### Actual behaviour
When the hopper minecart encounters a broken track, it floats in parallel until it hits the wall

### Steps to reproduce
Put the hopper minecart on the rails
Push him directly into the air block and break the rail
The minecart will fly out
[https://i.imgur.com/O0rYtgk.mp4](url)

### Additional Information
Any additional information we should know of?

**Comment by bergerkiller** [comment]
Did you have slowdown on false? Because that also disables gravity, and as a result, will cause it to float.

**Comment by vc606** [comment]
Hello, the settings in my DefaultTrainProperties.yml are
:slowDown: true

So is it true that causes the lack of gravity? Thank you for your explanation

**Comment by bergerkiller** [comment]
WIKI is here: https://wiki.traincarts.net/p/TrainCarts

The slowdown property can be split in two: slowfriction and slowgravity. So if you want only one disabled, that is possible to do.

**Comment by bbayu123** [comment]
Is it safe for me to assume this issue can be closed?

**Comment by bbayu123** [comment]
Is this still a problem? You said you had `slowdown: true` but it doesn't look like it's slowing down in the video. Since this is an old issue, I would like to know whether this is still relevant before proceeding.
