### ISSUE TITLE
People up-side-down

### ISSUE THREAD

**Issue by C0der-ai** [bergerhealer/TrainCarts#408]
## Info
Please provide the following information:

- BkCommonLib build #994: 
- TrainCarts  build #832: 
- TCCoaster build #186:
- Paper 1.16.5

----
### Description
When people leave the vehicle of traincarts, there model is sometimes up-side-down. Only the people that were close to the person see the model up-side-down i think it has something to do with packets. And also my suspicion is that the model go up-side-down if you make a looping. I have not yet done any research on this.

### Expected behaviour
Show the model normal if you left the train

### Actual behaviour
Show the model of the player up-side-down

### Steps to reproduce
I dont know to be honest, sometimes you see people up-side-down and sometimes not. The most of the time if you see them up-side-down they did a looping with the train they left.

### Additional Information
![image](https://user-images.githubusercontent.com/78218472/106287904-a972b880-6247-11eb-8d25-31b0c737ae9b.png)

**Comment by bbayu123** [comment]
Sorry for the late response, I know this has been a while, but check the latest development builds and see if it is fixed there, so I can confirm whether this is still relevant.

**Comment by C0der-ai** [comment]
@bbayu123  Hi thanks for the reaction, I'll check this afternoon if this bug is still there. You'll hear from me.

**Comment by C0der-ai** [comment]
@bbayu123  Sorry for the late reaction, seems to be fixed.
