### ISSUE TITLE
Signlink feat. Destination (Property)

### ISSUE THREAD

**Issue by JCSweetHeart** [bergerhealer/TrainCarts#411]
BkCommonLib version: -1.16.5-v2
TrainCarts version: 1.16.5-v1-843
Spigot version: 1.16,5
Problem or bug: Destination via Signlink not work
Expected behaviour: N / A
Steps to reproduce: Used the following Setup at a Sign:

MainStation (Only for automatic Pathfinding / Destination - Display)
 A
    [!train]                           
    property
    destination
    %Dest1%

B (DISPLAY!)
Currently Destionation

%Dest1%

---------

The Problem is, that the Sign change the Sign, but the Train have always  %Dest1 as Destination, as not change this (on the "Display, the Destinaton is changed).

Hopply any can help me - i understand what is the wrong way and without % it is not work :'(

**Comment by Tigerhoernchen** [comment]
To trigger that you need the trigger sign (see [https://wiki.traincarts.net/p/TrainCarts/Signs/Trigger](https://wiki.traincarts.net/p/TrainCarts/Signs/Trigger))

A:
[!train]
property
destination
Dest1

Second sign for the train:
[!train]
trigger
<variable>

**Comment by JCSweetHeart** [comment]
As first the Property - Sign but with or without the % and after that directly the Trigger sign or how do you mean it?

**Comment by JCSweetHeart** [comment]
As I have a Mainstation, the Train start from there and my Idea was with a Destination as Variable (Sign link) that we can change des destination for the Train as

Mainstation > { via Destination Sign} > Train find the Way to STATION A, B or C

Hopply you understand what I mean

**Comment by Tigerhoernchen** [comment]
Sorry I read something wrongly or so.

(Example)
-> Train comes in, gets the destination (or has it already)
-> trigger sign triggers B1 (SignLink variable) (make sure you're writing 'D' behind the word, see image below)
-> other signs for example a station sign
![grafik](https://user-images.githubusercontent.com/36344030/111372973-a585e300-869b-11eb-9073-5f899bf42d5a.png)

**Comment by JCSweetHeart** [comment]
I have try it but not work... Can you Tigerhoernchen or anybody help me? In case (when is possible) write me privat for the IP that do you see in real what I mean sometime im not the best writer for define anything sorry for that

**Comment by JCSweetHeart** [comment]
> Sorry I read something wrongly or so.
> 
> (Example)
> -> Train comes in, gets the destination (or has it already)
> -> trigger sign triggers B1 (SignLink variable) (make sure you're writing 'D' behind the word, see image below)
> -> other signs for example a station sign
> ![grafik](https://user-images.githubusercontent.com/36344030/111372973-a585e300-869b-11eb-9073-5f899bf42d5a.png)
> 
> I don't recommend using % in destinations.

I have try it and it is not work :(...

As User click a button for a Destination and Sign link save it as Dest1 - after this you call a Train and the Train become after the Station as Property the destination (Des1) as Goal, but that not work.

So that is the Idea

**Comment by bbayu123** [comment]
Not `[+train] property trigger B1`, it's `[+train] trigger B1 00:00`, other than that, the system shown by Tigerhoernchen should be correct. Can you show what you (JCSweetHeart) have using a screenshot or a video? It's especially important if English is not a fluent language for you.
