### ISSUE TITLE
Switcher intermittent issue

### ISSUE THREAD

**Issue by Sleinous** [bergerhealer/TrainCarts#412]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.16.5-v2 (build: 1000)
- TrainCarts Version (`/train version`): v1.16.5 (build: 843)
- Server Type and Version (`/version`): git-Paper-562 

----
### Description
When using switchers (either through path finding or through manual switching (with tags or other) trains sometimes get split apart on first wagon due to rail switching into wrong position.

### Expected behaviour
In the video below i'm expecting the 2nd train to behave exactly as the first (they are both tagged M1)

### Actual behaviour
It's shifting the rail to the opposite direction, derailing and unlinking first cart, then switching back the rail to correct position (and this bounces rest of train in reverse) - train hits a blocker which for testing purposes is allowing me to funnel the train back down the line for an attempt number 2 which usually suceeds. Running 6 trains on a loop will result in 30% failure rate on that switch-point.
Oddly enough this issue happens to me only when making a right turn, I haven't been able to reproduce when making a left turn (opposite track for instance) despite it being a more complicated switcher in X road format all train are turning left no problems (manual tag OR destination)

### Steps to reproduce
Please see video on how this is setup, essentially i'm placing a sign beneath the switchpoint with [+train] switcher r:M1 f:M2 but M1 trains sometimes get derailed to left.

### Additional Information
Any additional information we should know of?
Here's the youtube video I mentioned above : https://youtu.be/Ab4IkxHe5ac

**Comment by bbayu123** [comment]
That definitely doesn't look right... although signs are designed to detect trains from left and right as well.
Have you tried:
1. Using the latest development build (they can be found at https://ci.mg-dev.eu/)
2. Using [+train:b] on the first line to force detection from the direction of travel instead of left and right as well

**Comment by Sleinous** [comment]
Thanks for speedy response @bbayu123 
I've just tried using [+train:b] shifter r:M1 f:M2, after 3 trains it repeated same behaviour as above.
I'm now going to try latest dev build

**Comment by Sleinous** [comment]
So after testing this for a whole day I can confirm it's fixed in latest dev release of TrainCarts
Thanks @bbayu123
