### ISSUE TITLE
API Bug - When searching for train name, does not match name in savedtrainproperties

### ISSUE THREAD

**Issue by mrboog12** [bergerhealer/TrainCarts#415]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): V1.16.5-V3-Snapshot (Build 1038)
- TrainCarts Version (`/train version`): V1.16.5-V2-Snapshot (Build 890)
- Server Type and Version (`/version`): Git-PURPUR-1110 {MC: 1.16.5}

----
## Bug
When searching for train name with API, does not match name in savedtrainproperties

### Description

Either states:
"com.bergerkiller.bukkit.tc.controller.type.MinecartMemberRideable@xxxxxxxx"
or
"Train#"

### Expected behaviour
Return: {example}
"Speedrail03" (as name saved in savedtrailproperties)

### Actual behaviour
Either states:
"com.bergerkiller.bukkit.tc.controller.type.MinecartMemberRideable@xxxxxxxx"
or
"Train#"

### Steps to reproduce
MinecartMember<?> member = MinecartMemberStore.getFromEntity(p.getVehicle());
if (member != null) {
    p.sendMessage("Data: " +member.getGroup().getProperties().getTrainName());
}

### Additional Information
Any additional information we should know of?

**Comment by bbayu123** [comment]
Not a bug, that is correct.
The SavedTrain name has nothing to do with the spawned train name.

**Comment by bergerkiller** [comment]
Does he mean this one? https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/properties/standard/category/TrainNameFormatProperty.java#L31

The getTrainName() should work fine, though. That's the current name of the train, which definitely shouldn't be the output of MinecartMember.toString(). That part appears to be a bug on his end.

**Comment by bbayu123** [comment]
He wants to get the SavedTrain name, not the format, not the name, and obviously not the MM string. He's calling the wrong methods and reporting the discrepancy from what he expects as a bug, which obviously is not true.

Once a train is spawned, there is no direct way to figure out which SavedTrain spawned it I believe.

**Comment by bergerkiller** [comment]
Ahh okay. In the newer traincarts version it does maintain the train name set in properties I believe, when spawning. But last release definitely doesn't do that.

**Comment by bbayu123** [comment]
@mrboog12 since you are on the latest dev version, the correct way to obtain the name of the SavedTrain is through the `savedName` train property (Which may or may not be visible in the API...)

**Comment by bergerkiller** [comment]
After having properly given the train a name using /train rename, and **then** saving it, the train should be spawned with the name given. The name format you provide to /train rename can also be obtained using

`properties.get(StandardProperties.TRAIN_NAME_FORMAT)`

**Comment by mrboog12** [comment]
> After having properly given the train a name using /train rename, and **then** saving it, the train should be spawned with the name given. The name format you provide to /train rename can also be obtained using
> 
> `properties.get(StandardProperties.TRAIN_NAME_FORMAT)`

Oh, so its changed out a bit, my apologies then, I thought this was a bug.  So in which way would I use to check against player P to see what his traincarts name is?
