### ISSUE TITLE
Speed for each node in the tcc editor.

### ISSUE THREAD

**Issue by GwnJernoow** [bergerhealer/TrainCarts#417]
Speed for each node in the tcc editor.

## Description
This would be really usefull because the signs aren't working sometimes... It just would be really much better if you can do everything in the TCC editor instead of signs.

### Examples
It really makes my minecraft crash when i load in much nodes and blocks i can place above a sign. So it would be usefull if i can just change speeds and maybe property's in the tcc editor.

**Comment by bbayu123** [comment]
Closing feature request: Alternative feature exists. Refer to the wiki page section on [Node Signs](https://wiki.traincarts.net/p/TC-Coasters/Signs#Node_Signs).
