### ISSUE TITLE
Destroy sign with timer

### ISSUE THREAD

**Issue by Disneykid93** [bergerhealer/TrainCarts#418]
### Description
This destroy sign works like a station sign would, but removes the train instead after a selected amount of time. Video explaining it some here- https://www.youtube.com/watch?v=RChO2T0TpJE

### Examples
Can be used in stations where you wouldn't want to remove the train right away when powered by default, and not need or want to use redstone to remove it.

**Comment by bbayu123** [comment]
Closing feature request: Use alternative method - Link the station sign output to a destroy sign in falling-edge power
![image](https://github.com/bergerhealer/TrainCarts/assets/26726381/b6bbac32-df68-425c-b02f-79aee7e7599a)

Details of signs:
<table>
<tr>
<td>

```
[+train]
station
10
continue
```

</td><td>

```
[\train:*]
destroy
```

</td>
</tr>
</table>
