### ISSUE TITLE
Slowdown broken

### ISSUE THREAD

**Issue by The2doctor** [bergerhealer/TrainCarts#419]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): 1.16.5-v3 snapchot (build 1033 ) 
- TrainCarts Version (`/train version`): 1.16.5-v2 snapchot (build 887 ) 
- Server Type and Version (`/version`): yatopia 1.16.4

----
## Bug
slowdown
### Description
when the slowdown is activated ( all ) and the train decelerates, at a certain point the train continues but does not go back immediately it goes back when it reaches a certain height, which is a problem when using the slowdown for a disck'o coaster in my case the problem appeared when we switched to 1.16.5 all version snapchot 
### Expected behaviour
that gravity (slowdown all) works in the sense that the train moves back and forth continuously until it comes to a complete stop pleas

### Actual behaviour
he never stops he goes back and forth but when the train arrives at a slow speed the back and forth is not continuous sometimes he slows down a lot gets on a certain point and goes back to repeat this action several times without stopping

### Steps to reproduce
make a parabola with tccoaster nodes then put a train on the track and push it very slowly and watch what happens after 2 or 3 goes and the bug appears

### Additional Information
Any additional information we should know of?
No thank you for your understanding

**Comment by LaurenceBarnes** [comment]
Can you reproduce that on a sane fork, such as Paper or Tuinity?

**Comment by The2doctor** [comment]
It's the same problem on paper and Tuinity

**Comment by LaurenceBarnes** [comment]
it might help if you sent a screenshot of the setup so it can be reproduced

**Comment by The2doctor** [comment]
https://i.gyazo.com/69ddc53b89f85b0e792dd1318a0cf3a8.mp4

**Comment by bbayu123** [comment]
You might want to send the output of `/train info` when the train bugs out.

**Comment by The2doctor** [comment]
![image](https://user-images.githubusercontent.com/86190777/126221134-c2bdca89-5de5-4e33-a16e-63658c6a3e27.png)

**Comment by bergerkiller** [comment]
If I understand correctly: this is a train that slowly crawls up a slope until some point (I guess steepness?) and gravity finally kicks in?  Can you also show the curve? (tc-coasters?)

**Comment by The2doctor** [comment]
Yes it's that and yes here is the tccoaster curve but it makes the bug with any curve
![image](https://user-images.githubusercontent.com/86190777/126343439-c17cc02c-69c2-48ec-88dc-aba70f728043.png)

**Comment by bergerkiller** [comment]
Ive managed to reproduce it with a setup similar to that, though in my case it seems to mostly glitch out close to the center. I don't know if I can fix it because gravity fixes in the past too often resulted in new bugs. But hopefully I can figure something out.

**Comment by bergerkiller** [comment]
I found that one major cause was an incorrect threshold set for 'not moving', it caused it to not detect the very small motion initiated through gravity. Changing this threshold fixed the hanging problem.

https://github.com/bergerhealer/TrainCarts/commit/a6509542f85bec33e3c796413d718b5ba00a2b2e

Note: you **will need BKCommonLib 1.17.1** as well. BKC 1.16.5 + TC 1.17.1 = not work. Yes, the 1.17.1 version works on 1.16.x.

https://ci.mg-dev.eu/job/BKCommonLib/1084/
https://ci.mg-dev.eu/job/TrainCarts/922/
https://ci.mg-dev.eu/job/TC%20Coasters/207/

**Comment by The2doctor** [comment]
Thank you very much Berger
