### ISSUE TITLE
A permission to disable the use of /savedtrain

### ISSUE THREAD

**Issue by jaapieaapie1** [bergerhealer/TrainCarts#424]
## Feature Request
There doesn't seem to be any permission to disable the /savedtrain command.
This command allows everyone to see what the train names are and some information about the saved trains

### Description
This will be helpfull because now everyone can see saved train names, and most servers don't want that.

**Comment by bergerkiller** [comment]
Committed something for this, a train.command.savedtrain.list permission (by default true). Can set it to false or op in permissiondefaults.yml and the /savedtrain command will be hidden to non-ops entirely.

Lemme know if you have any problems.

https://ci.mg-dev.eu/job/TrainCarts/926/
