### ISSUE TITLE
TrackMovingPoint skipping

### ISSUE THREAD

**Issue by lavaglijder** [bergerhealer/TrainCarts#425]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): V1.17.1-V1-SNAPSHOT (Build 930)
- TrainCarts Version (`/train version`): V1.17.1-V1-SNAPSHOT (Build 1094)
- Server Type and Version (`/version`): git-Paper-119 (MC: 1.17.1)

----
### Description
TrackMovingPoint sometimes skippes over blocks

### Expected behaviour
The TrackMovingPoint will list every block of the rails

### Actual behaviour
After a turn on rails it skips the turn itself. Except if its a north west turn. 
It also sometimes just works. 

### Steps to reproduce
Create a track moving point to run on a track with multiple turns. 
And then you can see it sometimes skippes over a track.
I detected it by just getting the distance of the track and see if its higher then 1.

**Comment by bergerkiller** [comment]
Sounds bad because of how instrumental that moving point is to basically all physics of traincarts. I'll try to look at it...

Does it skip it in the middle of iteration, or only at the very start? That is, if I make a loop of vanilla rails, will it eventually skip one of the curved rails?

**Comment by lavaglijder** [comment]
From what I have seen it is in the middle of the iteration. I can test it to night if you want me to do it.

**Comment by bergerkiller** [comment]
Some super minimal test track and the coordinates to start iterating would help me get started debugging it. But could be I run into it fairly quickly, I'll look at it in a few hours. Mostly its a time-saver :)

**Comment by lavaglijder** [comment]
![image](https://user-images.githubusercontent.com/8274648/127776563-08637dac-20e0-49ad-b1c0-751b60ed06f2.png)
Track starting at -56 80 2, currently looking north

But it seems only 2 curves are skipped this time. So it seems to be random on which one is skipped and which one isnt

**Comment by bergerkiller** [comment]
Excellent illustration, Ive rebuilt it on my flatworld for testing. What do you do exactly to reproduce it? Through code, or using that /train debug distance item?

Do I create a new track moving point starting at -56/80/2 facing north and then do what exactly?

**Comment by lavaglijder** [comment]
I did it through code. I dont know what train debug distance need to show exactly

I use it to get the blocks between certain coordinates so this is my implementation
`public static List<Block> findShortestPath(Location startLocation, Vector vector, Location endLocation, int blocksFollowed, List<Integer> blocksHad, int maxDistance) {
        TrackMovingPoint trackMovingPoint = new TrackMovingPoint(startLocation.toBlockLocation(), vector);
        List<Block> blocks = new ArrayList<>();
        trackMovingPoint.next();
        trackMovingPoint.next();
        blocks.add(trackMovingPoint.current);

        if(endLocation != null) endLocation = endLocation.toBlockLocation();

        if(!trackMovingPoint.hasNext()) return new ArrayList<>();

        trackMovingPoint.next();

        if(blocksHad.contains(trackMovingPoint.current.hashCode())) {
            return new ArrayList<>();
        }

        blocksHad.add(trackMovingPoint.current.hashCode());

        while(blocksFollowed < maxDistance) {
            Block current = trackMovingPoint.current;
            blocks.add(current);
            if(endLocation != null && current.getLocation().equals(endLocation)) {
                return blocks;
            }

            if(isSwitcher(current.getLocation())) {
                RailType type = RailType.getType(current);
                if(type == null) break;

                List<Rail.Shape> shapes = railsPossibleRoutes(current.getLocation());

                Location finalEndLocation = endLocation.clone();
                int finalBlocksFollowed = blocksFollowed;
                AtomicReference<List<Block>> shortestPathFound = new AtomicReference<>();

                shapes.forEach(shape -> {
                    Rail rail = (Rail) current.getBlockData();
                    rail.setShape(shape);
                    current.setBlockData(rail);
                    List<Block> shortestPath = findShortestPath(current.getLocation(), trackMovingPoint.currentDirection, finalEndLocation.clone(), finalBlocksFollowed, blocksHad, maxDistance);
                    shortestPathFound.set(getShortest(shortestPathFound.get(), shortestPath));
                });
                List<Block> c = shortestPathFound.get();
                if(c.size() > 0) {
                    blocks.addAll(c);
                    return blocks;
                }
                break;
            }
            blocksFollowed++;
            if(trackMovingPoint.hasNext()) {
                Block next = trackMovingPoint.next;
                Location clone = current.getLocation().clone();
                clone.setY(1);
                Location clone1 = next.getLocation().clone();
                clone1.setY(1);

                // Check if it skipped a block
                if(clone.distance(clone1) > 1.2) {
                    System.out.println("Block skip detected -> (" + clone + "," + clone1 + String.format(") /tp @p %s %s %s", next.getLocation().getBlockX(),
                            next.getLocation().getBlockY(), next.getLocation().getBlockZ()) );
                }
                trackMovingPoint.next();
            } else break;
        }
        System.out.println(blocksFollowed);
        if(endLocation == null) return blocks;
        return new ArrayList<>();
    }
`

**Comment by bergerkiller** [comment]
I feel like the way youre using it, it would be much better to use the TrackWalkingPoint instead. Its a bit ambiguous I know, but moving point is a bit legacy. Walking point gives you more granularity and shows the exact total distance traveled so you don't have to calculate this yourself.

That said, most of the moving point code relies on walking point anyway. The only difference is that moving point operates per rail block, while walking point can also move sub-full rail distances. So I think the bug still stands.

https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/utils/TrackMovingPoint.java

**Comment by bergerkiller** [comment]
Also since you're interested in calculating distances or paths, this is how it's done in pure traincarts code. https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/debug/types/DebugToolTypeTrackDistance.java#L90

**Comment by lavaglijder** [comment]
Well I am intested in getting the blocks between two rails, so that I can create an detection region.

**Comment by bergerkiller** [comment]
Yeah for that this is fine, this is how you get all rail blocks trains go over. Can also use setLoopFilter(true) so that if it encounters the same rail a second time it aborts early. I think youre using hashCode() in some places for that now, but hashCode() might cause problems as theres collisions.

**Comment by lavaglijder** [comment]
But it seems like TrackWalkingPoint moveFull() sometimes skippes a block and sometimes it does the same block twice.

And the problem is that I need to test it myself. But yeah maybe I should change it so it lists blocks instead of hashcodes.

**Comment by lavaglijder** [comment]
It only happens at curves tho. So yeah

**Comment by bergerkiller** [comment]
Yeah I'll look at why moveFull() skips blocks

**Comment by bergerkiller** [comment]
So that's weird. I made two shortened versions of your code. One uses the moving point, other walking point. Im now finding that the moving point shows skips while the walking point does not. I'll need to fix that problem with the moving point, but I don't yet know why as the underlying code is identical...

```
    public static void findShortestPath(Location startLocation, Vector vector) {
        TrackMovingPoint trackMovingPoint = new TrackMovingPoint(startLocation, vector);
        int numRails = 0;
        while(true) {
            Block prev = trackMovingPoint.current;
            if(trackMovingPoint.hasNext()) {
                trackMovingPoint.next();
                numRails++;

                // Check if it skipped a block
                if (prev.getLocation().distance(trackMovingPoint.current.getLocation()) > 1.2) {
                    System.out.println("Block skip detected after " + prev.getX() + " / " + prev.getY() + " / " + prev.getZ());
                }
            } else break;
        }
        System.out.println("Num rails: " + numRails);
    }

    public static void findShortestPath2(Location startLocation, Vector vector) {
        TrackWalkingPoint walker = new TrackWalkingPoint(startLocation, vector);
        int numRails = 0;
        Block prev = walker.state.railBlock();
        while (walker.moveFull()) {
            Block current = walker.state.railBlock();
            if (prev.getLocation().distance(current.getLocation()) > 1.2) {
                System.out.println("BLOCK SKIP AFTER " + prev.getX() + " / " + prev.getY() + " / " + prev.getZ());
            }
            prev = current;
            numRails++;
        }
        System.out.println("Num rails: " + numRails);
    }
```

**Comment by bergerkiller** [comment]
Found the problem. You will want to use currentTrack and nextTrack rather than current and next. The current and next values arent of the rails, but of the minecart position 'block'. Really old deprecated logic that I think will just remove entirely because of how confusing it is.

**Comment by lavaglijder** [comment]
It seems that it indeed fixes the problem. Thanks for the help!

**Comment by bergerkiller** [comment]
To avoid confusion in the future Ive changed it so both current and currentTrack refer to the rails. Added a separate current/nextLocation field for this purpose instead. https://github.com/bergerhealer/TrainCarts/commit/095b5f3cacf9ad0c706ff7ea2f6a55529874abcd
