### ISSUE TITLE
TrainCarts and BKCommonLib not working

### ISSUE THREAD

**Issue by ItzBoony** [bergerhealer/TrainCarts#426]
So I was joining my server with the plugin then it cannot load the both plugin
[https://imgur.com/8K7ZeU6](url)

**Comment by bergerkiller** [comment]
Is there anything in your server log? Ingame information isn't enough to really help you.

Server software type? Plugin versions?

**Comment by ItzBoony** [comment]
I'm using Spigot/Bukkit and The lastest version

**Comment by bergerkiller** [comment]
Then check server log for any and all errors. Please dont cut only the last error out, I need all errors you see related to 'bergerkiller.common'

**Comment by ItzBoony** [comment]
I don't see any errors with 'bergerkiller.common'

**Comment by bergerkiller** [comment]
Well theres a reason why BKCommonLib is red in plugins, this only and only happens if theres an error. So look for it. Or just post the full server log and redact stuff you dont want to share.

**Comment by ItzBoony** [comment]
![image](https://user-images.githubusercontent.com/89066536/129703341-f8568d72-cc09-4bdc-8768-e071cc272fb8.png)
The error log

**Comment by bergerkiller** [comment]
Lol why are you using that ancient BKCommonLib from dev-bukkit? Download the one from spigot https://www.spigotmc.org/resources/bkcommonlib.39590/

Traincarts and other plugins too.

**Comment by ItzBoony** [comment]
Ooh that's why it didn't work thx thx!
