### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Grinkon** [bergerhealer/TrainCarts#427]
## Info
Please provide the following information:

- BkCommonLib Version (1.12.2 v3): 
- TrainCarts Version (1.12.2 v3): 
- Server Type and Version (Magma 1.12.2):

----
## Bug
Server Crash at startup 
### Description
Server Crash at startup with error "out of memory" 

### Expected behaviour
I want to start my server with TrainCarts

### Actual behaviour
I guess that BkCommonLib makes server to crash

### Steps to reproduce
I dont know what to put to this place

### Additional Information
Sorry for my bad english

**Comment by bbayu123** [comment]
Give your server more memory, and don't use such an outdated version of the plugins
