### ISSUE TITLE
Redstone torch bug

### ISSUE THREAD

**Issue by houtknots** [bergerhealer/TrainCarts#431]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): BKCommonLib: v1.17.1-v3 (build: 1117)
- TrainCarts Version (`/train version`):  Train_Carts: v1.17.1-v1 (build: 941)
- Server Type and Version (`/version`): Server: git-Paper-255 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c3d5018)

----
### Description
When placing a redstone torch next to a destination sign we see error messages pop-up within the server console.

```
[12:29:18 ERROR]: [Train_Carts] Failed to execute REDSTONE_ON for SignActionDestination:
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getWorld()" because "block" is null
        at com.bergerkiller.bukkit.common.BlockLocation.<init>(BlockLocation.java:38) ~[BKCommonLib-1.17.1-v3-1117.jar:?]
        at com.bergerkiller.bukkit.tc.pathfinding.PathNode.getOrCreate(PathNode.java:83) ~[TrainCarts-1.17.1-v1-941.jar:?]
        at com.bergerkiller.bukkit.tc.pathfinding.PathNode.getOrCreate(PathNode.java:61) ~[TrainCarts-1.17.1-v1-941.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionDestination.execute(SignActionDestination.java:73) ~[TrainCarts-1.17.1-v1-941.jar:?]
```

### Steps to reproduce
Place a redstone torch next to a destination sign (Other signs not tested):
https://youtu.be/xCcnC_hGZXo

**Comment by bergerkiller** [comment]
Are there no rails the sign is coupled to? Seems like that would trigger this.

**Comment by heras1** [comment]
This is the setup that is used here. The track is a diagonal section which continues a bit more to both sides  
![afbeelding](https://user-images.githubusercontent.com/19785214/134506267-4b3fed69-e06d-4608-9183-1174e7045274.png)

**Comment by bergerkiller** [comment]
This might be a bug finding the rails in this setup then. If you remove the sign post and put the rails on top of the block does the error go away?

**Comment by houtknots** [comment]
@bergerkiller It indeed was the sign in the middle, when we place wall signs the issue does not occur.

Video: https://youtu.be/0L1fPcTX3wM

**Comment by houtknots** [comment]
@bergerkiller, The issue is indeed fixed but with the new version TrainCartsCoasters doesn't work, When it type `/tcc give` nothing happens and no logs show.

I tried it on two different servers with the same result

**Comment by bergerkiller** [comment]
That's a bit strange, that commit changed nothing about the api that would cause this. Are you sure there's no logs? The /tcc is a main command and if it does 'nothing' then I would at least expect something in the server log about it. Or there's another plugin that also registers /tcc, in which case you can try and see if /tccoasters does anything.

**Comment by houtknots** [comment]
In the video below you see what I see in Minecraft and in the server console:

https://jhcsmedia.com/?f=2021-09-24-SsQbDaAcK3HrmqXd.mp4

**Comment by bergerkiller** [comment]
Recent versions have changed it to be clearer, check the server log and search for:
`Loading TCCoasters v1.17.1-`

Around there should be an error of what's going wrong. You can also update BKCommonLib and TC-Coasters to these versions on jenkins:
https://ci.mg-dev.eu/job/TC%20Coasters/215/
https://ci.mg-dev.eu/job/BKCommonLib/1121/

which will provide an option to upload the error log to pastebin. (if it doesnt also just work)

**Comment by houtknots** [comment]
Updating everything to the Snapshot version as you suggested works like a charm. All errors are gone and TCCoaster also works again.

**Comment by bergerkiller** [comment]
Most likely it was a bug in the preloader, some people had that. Thanks for confirming :)
