### ISSUE TITLE
Minecarts are invisible or incomplete (incomplete train)

### ISSUE THREAD

**Issue by Miluek** [bergerhealer/TrainCarts#432]
## Info
Please provide the following information:

Train_Carts: v1.17.1-v1 (build: 941)
BKCommonLib: v1.17.1-v3 (build: 1117)
Server: 3242-Spigot-6c1c1b2-d3cc412 (MC: 1.17.1)

----
## Bug

Minecarts are invisible or incomplete (incomplete train)

### Description

I have a problem with the Minecarts, I have made public transport on the server using the TrainCarts plugin, I have of course set that Minecarts are chunkloaders, it happens to me quite often that the train, I mean the whole train set, that the train is not visible, is invisible, I know by sound effects that when the train stops ringing. I also observe that some trains are sometimes half as long when they are not exactly invisible ... I tried to update Spigot to the latest build using buildtools, I also have the TrainCarts plugin for the current version, as well as the BKCommonLib plugin, could anyone help me please?

### Expected behaviour

So that the train sets are visible and not incomplete

### Actual behaviour

The trainsets are invisible or incomplete

### Steps to reproduce

I don't know, I need help...

### Additional Information

No additional information...

**Comment by bergerkiller** [comment]
Its quite possible this commit https://github.com/bergerhealer/BKCommonLib/commit/c742f3ea90d96f27feac8ff17fee10ce7931b6b6 already fixed this issue, can you check if you still have this problem on dev? I would expect errors in the server log about addEntity failing.

https://ci.mg-dev.eu/job/BKCommonLib/1124/

**Comment by Miluek** [comment]
Okay, now I will try update it to the DEV version and I'll see if the problem is solved, or I'll provide the log...

**Comment by Miluek** [comment]
Great, everything works as it should, thank you! :-)
