### ISSUE TITLE
allow destroyall to destroy trains/carts with matching tags

### ISSUE THREAD

**Issue by loftyD** [bergerhealer/TrainCarts#436]
### Description
Allow Destroyall to pass in an optional tag selector that destroys all applicable trains that match

### Examples
This might be useful when wanting to nuke certain problem trains on a route.

**Comment by bergerkiller** [comment]
Try /train destroy --train @train[tag=sometag*]

**Comment by loftyD** [comment]
omg if that works you're my hero . let me try this out and i'll let you know

**Comment by loftyD** [comment]
yeeeah! hero! cheers! i'll make a note of that!

**Comment by bergerkiller** [comment]
It's a very new feature, but most properties should work with that selector syntax, including things like destination and name. So try some out besides tag, and if you need some selector in there that's missing, can ask on discord to have it added :)
