### ISSUE TITLE
ERROR tcc

### ISSUE THREAD

**Issue by Nalkos** [bergerhealer/TrainCarts#438]
## Info

Train_Carts: v1.18.1-v1 (build: 995)
BKCommonLib: v1.18.1-v1 (build: 1172)
Server: 3171-Spigot-610a8c0-fb556bf (MC: 1.17.1)

----
### Description
When I do /tcc give everything is fine, but when I create a trail I get an error in my logs: https://paste.traincarts.net/jofudomere.cs

**Comment by bergerkiller** [comment]
Update BKCommonLib, v2 has been out for a while now.

**Comment by Nalkos** [comment]
Ok its function I had forgotten to update it 😅, but I have this when I create the plot : https://www.zupimages.net/up/22/02/m0gl.png

Any idea?

**Comment by bergerkiller** [comment]
Known issue. Copy-paste from discord:

Leash bug
- vote for this bug: https://bugs.mojang.com/browse/MC-212629
- resourcepack fix: https://www.dropbox.com/s/bmbufltqjxok3l3/leashFix.zip?dl=1

**Comment by Nalkos** [comment]
Super thank you for your help and your responsiveness 😄

**Comment by Nalkos** [comment]
I have a new error after a server restart: https://paste.traincarts.net/ovagayojay.bash

**Comment by bergerkiller** [comment]
Did you use /reload at any time? Because it seems the server glitched out and didn't load certain jar files fully.

Make sure to update any other plugins like TC-Coasters as well.

**Comment by Nalkos** [comment]
I just restarted my server and deactivate then reactivate another plugin, it is MotionCaptureRewritten

TC-Coasters is well up to date

**Comment by bergerkiller** [comment]
Its probably related to https://github.com/bergerhealer/Mountiplex/commit/a9742445b7b655dd37698cf57f943984aca72a72

https://ci.mg-dev.eu/job/BKCommonLib/1207/ probably doesnt have this issue anymore

**Comment by Nalkos** [comment]
I no longer have the BKCommonLib error but a TCCoasters error : https://paste.traincarts.net/zelicehuso.sql

**Comment by bergerkiller** [comment]
It's worth a try. This closing of class loaders is a huge pain with bukkit. https://ci.mg-dev.eu/job/BKCommonLib/1208/

**Comment by Nalkos** [comment]
I still have the error, but it spams in the logs when I hold the track editior :/ https://paste.traincarts.net/alohezaliz.bash

But he gives it to me while before he didn't give it to me

**Comment by bergerkiller** [comment]
Frustrating. Im trying to understand why you have this issue. Are there any plugins that show up red in /plugins? What if you remove these plugins that fail to enable?

**Comment by Nalkos** [comment]
All my plugins are in green

**Comment by Nalkos** [comment]
All my plugins are in green

**Comment by bergerkiller** [comment]
Well, just to rule out some bugs caused on spigots end. Unlucky build /etc. Try paper 1.17.1 to see if the same happens or not.

https://papermc.io/downloads#Paper-1.17

**Comment by Nalkos** [comment]
My server is running on Bungeecord, can it be from there?

I will change it to PaperSpigot

**Comment by bergerkiller** [comment]
I really dont know as youre the first to report this specific error. If its not the server having a bug, it must be some other plugin youre using thats closing its own class loader causing this.

In that case youll have to do a binary search (disable all and enable half of half until the error occurs and you find the plugin that causes it)

**Comment by Nalkos** [comment]
I found the plugin that makes tcc bellow I contact the creator of the plugin in question ?

**Comment by bergerkiller** [comment]
Can you tell me which plugin? If its open source I can have a look, Ill contact them myself if I find out what causes it. If its closed-source/paid premium, you can contact the dev yourself and maybe link this issue ticket.

A summary for the author: Jar file classloader is being closed.
My guess: plugin is a jar-in-jar solution, and something is going wrong.

**Comment by bbayu123** [comment]
Closing issue, assuming resolved
