### ISSUE TITLE
Allow player to enter only with a ticket or certain item

### ISSUE THREAD

**Issue by mitchngwen** [bergerhealer/TrainCarts#439]
New property to allow player to enter only with a ticket or certain item.

I know this would make the plugin more useful. You can now have a ticket counter where players can buy a ticket for the ride and then only be able to enter the ride if they have a ticket or some item.

**Comment by bergerkiller** [comment]
Its missing on the wiki, but there is a /train ticket feature already. You can add names of tickets players can use on the train, and only when they have that ticket item can they enter. You can also set the ticket up to apply properties to the train when players enter, for example, to assign a destination.

The ticket item is a map of which you can change the background image.

**Comment by mitchngwen** [comment]
This is awesome! Thank you for taking the time to post this on your wiki!
