### ISSUE TITLE
TrainCarts crash on Paper Spigot

### ISSUE THREAD

**Issue by MrPufferFish** [bergerhealer/TrainCarts#44]
When using Paper Spigot as server software. TrainCarts is crashing on startup.

EDIT:
Reflection in WorldRef field `entityRemovalList`

**Comment by mg-1999** [comment]
Please post the full log. Also there paperspigot  changes some nms things
so it is not expected to work.

Op zo 24 jan. 2016 14:10 schreef MrPufferFish <notifications@github.com>:

> When using Paper Spigot as server software TrainCarts is crashing on
> startup
>
> Using the latest version from Droneio
>
> 2401 14:01:07 [Multicraft] Skipped 38 lines due to rate limit (30/s)
> 2401 14:01:06 [Server] ERROR at
> orgbukkitpluginjavaJavaPluginsetEnabled(JavaPluginjava:321)
> 2401 14:01:06 [Server] ERROR at
> combergerkillerbukkitcommonPluginBaseonEnable(PluginBasejava:756)
> 2401 14:01:06 [Server] ERROR at
> combergerkillerbukkittcTrainCartsenable(TrainCartsjava:516)
> 2401 14:01:06 [Server] ERROR at
> combergerkillerbukkittccontrollerMinecartMemberStoreconvertAll(MinecartMemberStorejava:57)
> 2401 14:01:06 [Server] ERROR at
> combergerkillerbukkittccontrollerMinecartMemberStoreconvert(MinecartMemberStorejava:115)
> 2401 14:01:06 [Server] ERROR at
> combergerkillerbukkitcommonentityCommonEntitysetController(CommonEntityjava:353)
> 2401 14:01:06 [Server] ERROR at
> combergerkillerbukkitcommonentityCommonEntityprepareHook(CommonEntityjava:238)
> 2401 14:01:06 [Server] ERROR javalangRuntimeException: Failed to set
> controller:
> 2401 14:01:06 [Server] ERROR An error occurred while enabling, the plugin
> will be disabled:
> 2401 14:01:06 [Server] WARN at javalangThreadrun(Threadjava:745)
> 2401 14:01:06 [Server] WARN at
> netminecraftserverv1_8_R3MinecraftServerrun(MinecraftServerjava:563)
> 2401 14:01:06 [Server] WARN at
> netminecraftserverv1_8_R3DedicatedServerinit(DedicatedServerjava:267)
> 2401 14:01:06 [Server] WARN at
> netminecraftserverv1_8_R3MinecraftServera(MinecraftServerjava:327)
> 2401 14:01:06 [Server] WARN at
> netminecraftserverv1_8_R3MinecraftServerk(MinecraftServerjava:372)
> 2401 14:01:06 [Server] WARN at
> netminecraftserverv1_8_R3MinecraftServers(MinecraftServerjava:408)
> 2401 14:01:06 [Server] WARN at
> orgbukkitcraftbukkitv1_8_R3CraftServerenablePlugins(CraftServerjava:317)
> 2401 14:01:06 [Server] WARN at
> orgbukkitcraftbukkitv1_8_R3CraftServerloadPlugin(CraftServerjava:358)
> 2401 14:01:06 [Server] WARN at
> orgbukkitpluginSimplePluginManagerenablePlugin(SimplePluginManagerjava:404)
> 2401 14:01:06 [Server] WARN at
> orgbukkitpluginjavaJavaPluginLoaderenablePlugin(JavaPluginLoaderjava:332)
> 2401 14:01:06 [Server] WARN at
> orgbukkitpluginjavaJavaPluginsetEnabled(JavaPluginjava:321)
> 2401 14:01:06 [Server] WARN at
> combergerkillerbukkitcommonPluginBaseonEnable(PluginBasejava:756)
> 2401 14:01:06 [Server] WARN at
> combergerkillerbukkittcTrainCartsenable(TrainCartsjava:516)
> 2401 14:01:06 [Server] WARN at
> combergerkillerbukkittccontrollerMinecartMemberStoreconvertAll(MinecartMemberStorejava:57)
> 2401 14:01:06 [Server] WARN at
> combergerkillerbukkittccontrollerMinecartMemberStoreconvert(MinecartMemberStorejava:115)
> 2401 14:01:06 [Server] WARN at
> combergerkillerbukkitcommonentityCommonEntitysetController(CommonEntityjava:353)
> 2401 14:01:06 [Server] WARN at
> combergerkillerbukkitcommonentityCommonEntityprepareHook(CommonEntityjava:235)
> 2401 14:01:06 [Server] WARN at
> combergerkillerbukkitcommonentityCommonEntityreplaceEntity(CommonEntityjava:301)
> 2401 14:01:06 [Server] WARN at
> combergerkillerbukkitcommonentityCommonEntityreplaceInList(CommonEntityjava:327)
> 2401 14:01:06 [Server] WARN javalangNullPointerException
> 2401 14:01:06 [Server] INFO 1 Train has been loaded in 1 world (55
> Minecarts)
> 2401 14:01:05 [Server] INFO Enabling Train_Carts v175-SNAPSHOT
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/44>.
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by Zbob750** [comment]
If this user does ever come back with some specific issues relating to the use of PaperSpigot, please let us know. We're more than willing to make sane changes to fix compatibility, though I'm not aware of any issues with this portion of NMS currently.

**Comment by mg-1999** [comment]
@Zbob750 In PaperSpigot is an list in the NMS class World called `h` commented out. Any reason for this? It says `unused list` but in my reflection it is an entityRemovalList.

**Comment by Zbob750** [comment]
```public final List<TileEntity> h``` in net.minecraft.server.World maps to MCP's ```public final List<TileEntity> loadedTileEntityList```
It was removed because its existence appears purely optional, and eats performance with TE removals.

**Comment by mg-1999** [comment]
@Zbob750 Thank you. Gonna make it drop support when PaperSpigot is recognized.

**Comment by mg-1999** [comment]
This is already fixed, closing for now.
