### ISSUE TITLE
Not working on NachoSpigot1.8.8

### ISSUE THREAD

**Issue by HowardZHY** [bergerhealer/TrainCarts#440]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): BKCommonLib v1.18.1-v2
- TrainCarts Version (`/train version`): Train_Carts v1.18.1-v2
- Server Type and Version (`/version`):NachoSpigot-"f5de3b6" (MC: 1.8.8)

----
### Description
Could not pass event EntityAddEvent to Train_Carts v1.18.1-v2
org.bukkit.event.EventException: null
And spamming errors

### Expected behaviour
What do you expect TrainCarts to do?
Works on NachoSpigot
### Actual behaviour
What is TrainCarts doing instead?
see log
### Steps to reproduce
Please list the steps to take, in order to reproduce the bug.
Use latest NachoSpigot and TrainCarts.
### Additional Information
Any additional information we should know of?
[latest.log](https://github.com/bergerhealer/TrainCarts/files/7965337/latest.log)

**Comment by bergerkiller** [comment]
Try it https://ci.mg-dev.eu/job/BKCommonLib/1224/

**Comment by HowardZHY** [comment]
works now.
