### ISSUE TITLE
WorldGuard Region Entering/Leaving on TrainCart 

### ISSUE THREAD

**Issue by halofreak894** [bergerhealer/TrainCarts#442]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.18.2-v1 (build: 1087)
- TrainCarts Version (`/train version`): v1.18.2-v2-SNAPSHOT (build: 1270)
- Server Type and Version (`/version`): git-Paper-792 (1.16.5)

----
### Description
After entering a TrainCart, and then the cart moves into the region from a speed sign, station, launch, or track animation, WorldGuard doesn't seem to detect you've entered that region. Using /rg info shows that the player has entered the region but none of the region flags work. For example, the greeting I've set to happen after the player enters is not appearing until they get out of the cart. Not sure if this has anything to do with TrainCarts or if that's more of a WG issue however.

### Expected behaviour
What do you expect TrainCarts to do?
I expect TrainCarts to put the player into the region in a way that will allow WorldGuard to send the necessary things to the client.

### Actual behaviour
What is TrainCarts doing instead?
Putting them into the region, but with none of the flags within the region being sent or working.

### Steps to reproduce
Please list the steps to take, in order to reproduce the bug.
1. Create a TrainCart track, or track animation that will lead into a separate WorldGuard region.
2. /rg flag [region] greeting [greeting]
3. Use a station or speedlimit sign to have the train go into the region

### Additional Information
Any additional information we should know of?
N/A

**Comment by RyanHecht** [comment]
Hmm I'm unable to reproduce this (with the `greeting` flag) on Paper 1.12.2/TC 1.18.1/WorldGuard 6.2.1

**Comment by bbayu123** [comment]
Can confirm that this is an issue, but only when the train is not moving, and a track animation is being played that causes the train to enter/leave a WG region.

**Comment by bbayu123** [comment]
Details to reproduce are as follows:

WorldGuard Region
![image](https://github.com/bergerhealer/TrainCarts/assets/26726381/cd7a488a-291a-4f2d-99ba-a41fc7060b5d)

Coaster track
https://paste.traincarts.net/isenejeciv

Steps:
1. Create the WorldGuard region and set the greeting and farewell flags
2. Import the coaster track
3. Place a cart on the only animated node on the track, enter the cart. (If the track is animated to `move2`, the greeting message should display)
4. Animate between `move` and `move2`. The greeting and farewell messages do not get displayed.

**Comment by bergerkiller** [comment]
The issue is that the server ticks the entity as well, and outside of the normal overrided tick() it calls entity.setOldPosAndRot(), which causes it to lose the 'last position' information. This in turn causes a vehicle move event to be fired with the wrong last position information, or not at all. TCC triggered this with animations because it moves the entity without a teleport event that WorldGuard would otherwise see.

I'm adding a change so that traincarts tracks the last position using its own field to avoid outside interference.

**Comment by bergerkiller** [comment]
This fixes the situation outlined by bbayu for me. https://github.com/bergerhealer/TrainCarts/commit/f86a2cd5765da1bf4eaef9c5c774502ab3ac4644

https://ci.mg-dev.eu/job/TrainCarts/1431/

**Comment by bergerkiller** [comment]
Another minor patch. https://github.com/bergerhealer/TrainCarts/commit/c0691cacffd811e904028ef8c67d82e80d6cf228

https://ci.mg-dev.eu/job/TrainCarts/1433/

**Comment by bergerkiller** [comment]
I think this is fixed
