### ISSUE TITLE
I ride out for the train.

### ISSUE THREAD

**Issue by IgnatiusMarenka** [bergerhealer/TrainCarts#445]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.18.2-v1
- TrainCarts Version (`/train version`): v1.18.2-v1
- Server Type and Version (`/version`): 3483-Spigot-42b6152-9cc7d76 (MC: 1.18.2)

----
## Bug
I glitch out before my boat.

### Description
So, if I am on a train and it's not moving everything seems fine, but as soon as the train starts moving I kinda move for it, so I am first and only then my train follows, I know it isn't really a good explanation. Overall I really think this is the best plugin to make a theme park, it's only a bit annoying that I glitch out of the cart.

### Expected behavior
I want to be seated on my train.

### Actual behavior
If the train starts riding I move before the train.

### Steps to reproduce
So I just made a track and on top, I have an oak_boat as a model with a y-position of 0.6 but I don't think that the model and position really matter as I already had this problem with other carts too. I don't have the problem if riding a normal minecart

### Additional Information
I use optifine, don't know if that could cause the problem or not

**Comment by bergerkiller** [comment]
Boats and armorstands update at different rates clientside. In the entity attachment of your boat, enable sitting mode.

**Comment by IgnatiusMarenka** [comment]
Ow, thank you
