### ISSUE TITLE
[Bug?] Items in container minecart didn't drop into the hopper

### ISSUE THREAD

**Issue by HowardZHY** [bergerhealer/TrainCarts#446]
- BkCommonLib Version (`/train version`): 1261
- TrainCarts Version (`/train version`): 1107
- Server Type and Version (`/version`):Burrito Spigot 1.8.8

----
### Description
![image](https://user-images.githubusercontent.com/96782166/168642346-24a16bdd-9e73-4c6c-bc18-976157f2adf9.png)

![image](https://user-images.githubusercontent.com/96782166/168641561-21686035-a263-498c-bd58-57ed65ccc9c5.png)

Items in container minecart didn't drop into the hopper under the rail with Train Carts.
Items drop from container minecart into the hopper under it after breaking the rail on the hopper.

### Expected behaviour
Items drop from minecart into hoppers normally.

### Steps to reproduce
1. place hoppers y chests
2. place golden rail on hoppers
3. run container carts on that rail
4. items in container carts wont drop into hoppers

### Additional Information
null

**Comment by HowardZHY** [comment]
tried BK 1289, still. Normal after removed TrainCarts.

**Comment by HowardZHY** [comment]
https://github.com/bergerhealer/TrainCarts/issues/437#issuecomment-997280880 ?

**Comment by bergerkiller** [comment]
In this situation its the responsibility if the hopper block to poll for entities - the hopper minecart is not the one initiating it. So the situation is different. It seems then that either the hopper isnt 'ticking' (paper config?) or the hopper isn't seeing traincarts minecart entities as valid containers to pull from.

This is 1.8.8 though, so theres a lot of possible causes. I wouldnt know without looking into it myself

**Comment by bergerkiller** [comment]
A stupid question, but as this happened once before-

You didnt change the minecart type in the attachment editor, right? Placed it with an actual storage minecart item?

**Comment by HowardZHY** [comment]
> 

wdym?

**Comment by bergerkiller** [comment]
Does the problem go away when you set train-carts/config.yml optimizeBlockActivation to false?

**Comment by HowardZHY** [comment]
Now I've disabled optimizeBlockActivation, but it still not working

**Comment by bergerkiller** [comment]
Im back home so Ill do some testing. Been a while since i booted up 1.8

**Comment by bergerkiller** [comment]
Yeah I can see the same on 1.8. Ill look into it

**Comment by bergerkiller** [comment]
Problem doesnt happen with Spigot and Paperspigot 1.8.8. But I find that NachoSpigot, which I happened to be using at the time, does. This is because they backported something paper added later, replacing some internal data structure of Chunk.

This likely causes incomplete replacement of the Entity during spawning, and causes it to not find the minecart anymore when searching in a cuboid region above the hopper block.

Fix is hopefully easy, Ill have to see what works best.

**Comment by bergerkiller** [comment]
![ScreenShot 2022-05-17 19 31 43](https://user-images.githubusercontent.com/957601/168874943-09f14705-d948-4c25-a617-a3df7b1bf4ba.jpg)
well that explains a lot

**Comment by bergerkiller** [comment]
This took me longer to figure out than I like to admit. After decompiling the entire nachospigot jar, I find that all these bugs have to do with changes done by the TacoSpigot base server. The most important change here is that hoppers can be configured not to pull from entities, but to have entities push items to hoppers, which is obviously more efficient.

Further digging into it showed that they crammed a hopper tick inside EntityMinecartContainer class onTick() function, which is obviously overrided by BKCL for controller/tc support. So it never ran.

Calling this method manually inside the onTick() hook seems to have fixed it.

There was another issue on TacoSpigot related to the chunk entity slices, but it was probably minor.

https://ci.mg-dev.eu/job/BKCommonLib/1291/

**Comment by HowardZHY** [comment]
I though it's a taco problem too, let me test this build

**Comment by HowardZHY** [comment]
![2022-05-18_11 01 03](https://user-images.githubusercontent.com/96782166/168948753-51075f5c-6373-4483-a5a0-b44121749fe6.png)
It looks like working fine now. THX for ur support.
