### ISSUE TITLE
My Worlds Portals Integration

### ISSUE THREAD

**Issue by furdozy** [bergerhealer/TrainCarts#45]
In the most current builds(as of 1/24/2016) the my worlds portal features appear unresponsive. My worlds functions as expected however traincarts completely disregard the portal signs. No error message shows in console. Acts as if feature isn't supported with many different setups/methods.

here is a very basic setup that [should] function, but isn't:
http://imgur.com/fkXFjOI

**Comment by mg-1999** [comment]
Cant find the problem that fast, are you using a mac?

**Comment by furdozy** [comment]
Not using a mac.

**Comment by mg-1999** [comment]
Then it is a bug, going to test some things out the following weekends.

**Comment by furdozy** [comment]
Is it working for you? If so I can try to isolate the issue.

**Comment by mg-1999** [comment]
MyWorlds is online ported and not really updated. So I think it is just that.

**Comment by mg-1999** [comment]
Portals are working but trains are not passing through them.

**Comment by FriwiDev** [comment]
Yeah sry, I can't afford the time atm to really update MyWorlds. Kinda sorry for that :/

**Comment by bergerkiller** [comment]
MyWorlds is updated and the teleporter signs now function properly, though some bugs may still exist as Im resolving them. Please make a new bug report when those occur.
