### ISSUE TITLE
Obstructed vision when riding on ladder

### ISSUE THREAD

**Issue by Jacold** [bergerhealer/TrainCarts#455]
## Info
Please provide the following information:

[11:01:46 INFO]: Train_Carts: v1.19-v3 (build: 1161)
[11:01:46 INFO]: BKCommonLib: v1.19-v2 (build: 1347)
[11:01:46 INFO]: Server: git-Purpur-1735 (MC: 1.19)

----
### Description
When train drive on a ladder vision is obstructed by next minecart

### Expected behaviour
Shift camera horizontally or force character to lay when cart is on ladder

### Actual behaviour
Camera's vision should not be obstructed by next minecart

### Steps to reproduce
Form train from few minecarts and make a downhill track using ladders - problem appears in FPP

### Additional Information
-

**Comment by bergerkiller** [comment]
But adjusting the camera when on a ladder is already a thing? config.yml -> enableSeatThirdPersonView must be true

**Comment by bergerkiller** [comment]
And if this was broken for some reason, try with https://ci.mg-dev.eu/job/TrainCarts/1224/ first

**Comment by Jacold** [comment]
Whoops, looks like I've missed that option while checking config. Now it works, thank you.
