### ISSUE TITLE
Max Entity Cap

### ISSUE THREAD

**Issue by Wild1145** [bergerhealer/TrainCarts#458]
### Description
A maximum number of trains able to exist in any given world at any given time. To be defined in the configuration file either on a per-world basis or as a global limit applied to each world. This will enable server owners to minimise the risk of trains being used to lag their servers significantly. 

### Examples
Servers where players can spawn their own trains at any time.

**Comment by bergerkiller** [comment]
Traincarts has a GroupCreateEvent, and Id be willing to add some special extra events for when a spawn signs spawns it / player spawns it. Would this be something you could implement yourself with a simple event listener + config and cancelling the event?

This is one of those things which is infinitely customizable, like adding player roles that bypass it or adding exceptions to 'main server spawn signs' or stuff. So I'm hesitant to add something substandard only for requests to come in to turn it into a homer car.

An add-on/custom plugin would fit better here I feel

**Comment by Wild1145** [comment]
That's fair, I hadn't really thought people would want exceptions to a hard limit cap which is what I was going for here when it comes to a world limit. I'll have to have a look to see if a custom plugin to handle a limit would work for our use-case or not and what we might need to either contribute here or ask to get added.

**Comment by bbayu123** [comment]
Closing issue, not suitable for adding into TrainCarts directly
