### ISSUE TITLE
Error - Does not Enable on start up

### ISSUE THREAD

**Issue by HollishKid** [bergerhealer/TrainCarts#46]
Hello,

I get the following error on startup:
http://pastebin.com/NuKqKdRj

I use the latest version of BKCommonLib:
https://drone.io/github.com/bergerhealer/BKCommonLib/files

Is there anything you can do about this?
Thanks in advance!

**Comment by mg-1999** [comment]
Use spigot! And nothing else.

Op ma 8 feb. 2016 02:07 schreef HollishKid <notifications@github.com>:

> Hello,
>
> I get the following error on startup:
> http://pastebincom/NuKqKdRj
>
> I use the latest version of BKCommonLib:
> https://droneio/githubcom/bergerhealer/BKCommonLib/files
>
> Is there anything you can do about this?
> Thanks in advance!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/46>.
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by HollishKid** [comment]
So if I'm a Bukkit user (something there is no way I can change ...) I am condemned not to use your plugin at all? =((
I was really looking forward to using these awesome features ....!

**Comment by mg-1999** [comment]
It is in deed awesome to use, but since we use some internals of spigot and
also that they are different after the optimizations from spigot :)

Op ma 8 feb. 2016 16:02 schreef HollishKid <notifications@github.com>:

> So if I'm a Bukkit user (something there is no way I can change ...) I am
> condemned not to use your plugin at all? =((
> I was really looking forward to using these awesome features ....!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/46#issuecomment-181402008>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by HollishKid** [comment]
Is there anywhere I can find an "old" build, eventhough not all features will be enabled, that will work on Bukkit 1.8.x ?

The basic features are already more than cool enough for me to use.

**Comment by mg-1999** [comment]
There isn't , we only updated for spigot because that's what 70% of our users used. Also I have some crazy ideas about a way to fix this 'issue'. But for now you could kindly ask your host to add spigot availability.
