### ISSUE TITLE
[1.19.3] Plugin freezes the server

### ISSUE THREAD

**Issue by LcyDev** [bergerhealer/TrainCarts#462]
## Info
Please provide the following information:

- BkCommonLib Version (`1.19.3-v1`): 
- TrainCarts Version (`1.19.3-v1`): 
- Server Type and Version (`purpur-1.19.3-1892`):

----
## Bug
https://paste.gg/p/ConaII_/eff7aca70a044cc6bd3925470660cb5f

### Description
N/A

### Expected behaviour
N/A

### Actual behaviour
Broken behaviour, lagging the server and generating these dumps

### Steps to reproduce
N/A

### Additional Information
N/A

**Comment by bergerkiller** [comment]
I made some fixes to Mountiplex 2 weeks ago which involved some deadlocks during class loading. Can you check if this problem is still present currently? https://ci.mg-dev.eu/job/BKCommonLib/1454/

**Comment by LcyDev** [comment]
It does seem fixed but i cannot confirm in production (Manteinance)

**Comment by LcyDev** [comment]
Everything seems good!
