### ISSUE TITLE
 Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by LcyDev** [bergerhealer/TrainCarts#463]
## Info
Please provide the following information:

- BkCommonLib Version (`BKCommonLib-1.19.3-v2-SNAPSHOT-1454`): 
- TrainCarts Version (`TrainCarts-1.19.3-v2-SNAPSHOT-1288`): 
- Server Type and Version (`purpur-1.19.3-1892`):

----
### Description
https://paste.gg/p/ConaII_/11a9fb2c1e5445598503b570ff6c0d9e

**Comment by bergerkiller** [comment]
This should help https://ci.mg-dev.eu/job/TrainCarts/1289/

**Comment by LcyDev** [comment]
Indeed it did
