### ISSUE TITLE
Cactus doesn't destroy minecarts

### ISSUE THREAD

**Issue by KabanFriends** [bergerhealer/TrainCarts#467]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.19.3-v1
- TrainCarts Version (`/train version`): v1.19.3-v1
- Server Type and Version (`/version`): git-Paper-386 (MC: 1.19.3)

----
### Description
When a minecart touches a cactus block, the minecart doesn't get destroyed.

### Expected behaviour
Cactus blocks should destroy minecarts.

### Actual behaviour
Minecart simply stops next to cactus block and stays there.

### Steps to reproduce
1. Place a rail in a way so that minecart touches cactus block
![image](https://user-images.githubusercontent.com/45000995/215614694-7c8a7147-c065-44d0-bb2e-0aa4b9d8f4d3.png)
2. Push a minecart into the cactus
![image](https://user-images.githubusercontent.com/45000995/215614751-2d35afb8-f0ba-4828-8e79-a1958061e263.png)

**Comment by bbayu123** [comment]
You can either
1. Go to `config.yml` in the `Train_Carts` folder, and set `optimizeBlockActivation` to `false`
2. Don't use a cactus. Use a [Destroy sign](https://wiki.traincarts.net/p/TrainCarts/Signs/Destroyer) instead
