### ISSUE TITLE
Unable to push carts whilst riding

### ISSUE THREAD

**Issue by imnofox** [bergerhealer/TrainCarts#47]
Appears to be very similar to #12 & #13.
Running Train_Carts v1.75-SNAPSHOT, BKCommonLib v1.67-SNAPSHOT on Spigot (git-Spigot-06ad352-4a7472d) : v1_8_R3 (Minecraft 1.8.8)

In both creative and survival modes, I am unable to push the carts while riding the cart (using `W` key). I can however push the cart by running into it.

This problem stops if I relog while in the cart, but returns when destroying & replacing the cart.

**Comment by mg-1999** [comment]
Just confirmed this in my testing, gonna debug the reported bug.

**Comment by EJT06** [comment]
I have the same problem. I'm running BKCommonLib v1.12.1 - v1 and same for TrainCarts.

**Comment by min20120907** [comment]
I have the same problem, what should I do now?

**Comment by min20120907** [comment]
I got the trobleshooting from developer,he said that you have to edit the DefaultTrainProperties.yml, and change setting "allowManualMovement" to true
