### ISSUE TITLE
"Failed to perform physics" when passing through spawner sign

### ISSUE THREAD

**Issue by 5AveLocal** [bergerhealer/TrainCarts#470]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.19.3-v2 (build: 1326)
- TrainCarts Version (`/train version`): v.1.19.3-v2 (build: 1501)
- Server Type and Version (`/version`): git-Paper-388 (MC: 1.18.2)

----
### Description
When I ride a train of a certain length (I used 40m), on a long, diagonal piece of track (45 degree), which in the bottom lies a sign which writes `[train:right] spawn 20m` (train spawner generating 20 minecarts, is unpowered),
the whole train will bug out and attempt to stop (you feel the speed of the train go down to 0 and then return to normal), and the console outputs `[Train_Carts] Failed to perform physics on train`.

### Expected behaviour
Ignore the sign as the `[train:right] spawn 20m` was not powered at all

### Actual behaviour
Stopping the train for a tick or so then the train runs at the same speed as before

### Steps to reproduce
1. Build a diagonal piece of track (e.g. 20 blocks, 45 degree)
2. Put a `[train:right] spawn 20m` sign at the bottom of the track
3. Spawn a train with certain length (probably > 1)
4. Ride on the piece of rail
5. Error is produced in the console

Error in console
![consoleerror](https://user-images.githubusercontent.com/78492816/222336401-947e5d73-9681-4aec-ab88-7cb326b45bd3.png)

Basic setup
![2023-03-02_13 06 22](https://user-images.githubusercontent.com/78492816/222336443-095653b6-897e-4203-b0bb-4ffad38e227e.png)

**Comment by bergerkiller** [comment]
Why dont you post the actual error??

**Comment by 5AveLocal** [comment]
> Why dont you post the actual error??

I have updated the description above with the error and a basic setup that you can follow

**Comment by bergerkiller** [comment]
Thank you, I'll look at it after work today. If I had to guess, I think it's because of that one sign post that is rotated 45 degrees. Try placing it aligned at 90 degrees and see if that changes anything.

**Comment by 5AveLocal** [comment]
> Thank you, I'll look at it after work today. If I had to guess, I think it's because of that one sign post that is rotated 45 degrees. Try placing it aligned at 90 degrees and see if that changes anything.

Placing it at **90 degrees** (N, S, E, W) **does not produce** the same bug
but placing it at **45 degrees** (NE, NW, SE, SW) **produces** the same bug

**Comment by bergerkiller** [comment]
I don't think it's fixed yet, it just doesnt handle :right stuff combined with 45 degrees very well. Needs a little more work

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/TrainCarts/1331/ this works for me ingame

**Comment by 5AveLocal** [comment]
> https://ci.mg-dev.eu/job/TrainCarts/1331/ this works for me ingame

Bug seems to be fixed for now using this build
Thanks!
Please make sure to include the fix in future releases though

**Comment by bergerkiller** [comment]
Anything built by ci.mg-dev.eu eventually ends in a release, so no worries
