### ISSUE TITLE
When typing `/train speedlimit` without any additional arguments, get the current speed of the train back.

### ISSUE THREAD

**Issue by Krakabraka** [bergerhealer/TrainCarts#471]
### Description
I think this is a good idea because it can be useful for debugging purposes, or maybe if you don't know the speed of the train but would like to know it?
### Examples
I[1]: /train speedlimit 0.4
I[2]: /train speedlimit
O[2]: This train is currently moving at 0.4 b/t.

Or something like that.

**Comment by bergerkiller** [comment]
Oh it doesn't? Thats an oversight on my part, I'll add this

**Comment by bergerkiller** [comment]
So it did, but didnt know km/h and mph, so I added those two units in the readout as well
![Screenshot_20230324_204611](https://user-images.githubusercontent.com/957601/227624781-b5f16394-690e-40ef-bf09-97f70a5bc99f.png)

https://ci.mg-dev.eu/job/TrainCarts/1356/

**Comment by bergerkiller** [comment]
Oh wait you probably meant ti **also** show the current speed of the train, like is in /train info. I can add that

**Comment by bergerkiller** [comment]
![Screenshot_20230324_205721](https://user-images.githubusercontent.com/957601/227626788-a02ff446-7c95-4452-bb35-bc4775442c50.png)
https://ci.mg-dev.eu/job/TrainCarts/1357/

shows current speed as red when moving at the speed limit.

**Comment by Krakabraka** [comment]
oh didn't klnow I could use /train info for that. Well in that case,

**Comment by bergerkiller** [comment]
There's also /train status for some more niche speed details, like mutexes and wait distance state
