### ISSUE TITLE
[Request] Option to exempt Weighted Pressure Plates (or pressure plates in general) from pressure plate logic

### ISSUE THREAD

**Issue by Mikkel136** [bergerhealer/TrainCarts#472]
## Feature Request
An option somewhere in the plugin config to disallow some Pressure Plate types to work as rails and X-crossings.

### Description
It should be possible to blacklist/whitelist specific types of pressure plates from TrainCarts' pressure plate logic to mitigate issues with Redstone contraptions. Considering Minecraft has four types of pressure plates It'd make sense to allow for some flexibility to futureproof interactions between Minecarts and Pressure Plates.

### Examples
This player detector using Pufferfish is broken by TrainCarts' pressure plate logic, This setup allow the minecart to seamlessly bypass the fence post (and its elevation change). Exempting Weighted Pressure Plates could be a very easy solution to allow the userbase to restore Vanilla behavior when intended.

![image](https://user-images.githubusercontent.com/6626966/235331017-c896afcb-5d40-4963-8e73-7c11869612bd.png)

**Comment by bbayu123** [comment]
That has less to do with the pressure plate itself, and more to do with TrainCarts overhauled physics engine. Trains flying off at the end of rails is part of the physics after all.
Regardless, you should not be using vanilla detection mechanisms for TrainCarts carts. Vanilla detection and TrainCarts physics are highly incompatible.

**Comment by bergerkiller** [comment]
Just spawn vanilla minecarts and traincarts wont touch them. You can use /summon, dropper or revoke train.place.traincart permission

**Comment by bbayu123** [comment]
> You can use /summon, **dropper** or revoke train.place.traincart permission

I think you mean dispenser there

**Comment by bergerkiller** [comment]
> > You can use /summon, **dropper** or revoke train.place.traincart permission
> 
> I think you mean dispenser there

Probably, dunno if dropper can do it too

**Comment by bbayu123** [comment]
> > > You can use /summon, **dropper** or revoke train.place.traincart permission
> > 
> > 
> > I think you mean dispenser there
> 
> Probably, dunno if dropper can do it too

Droppers drop items as items, dispensers actually place/use items

**Comment by bbayu123** [comment]
Closing issue, workaround suggested - don't use TrainCarts with vanilla detection mechanisms.
