### ISSUE TITLE
Teleporter from myworld does not seems to work.

### ISSUE THREAD

**Issue by fresser** [bergerhealer/TrainCarts#48]
I have tried tons of different things to try make this work. But i cannot get a train to teleport, as described here.
http://minecraft.gamepedia.com/Custom_servers/Bukkit/TrainCarts/Signs/Teleporter

I have powered both signs, and they are in 2 different worlds. Is the feature deprecated?

**Comment by mg-1999** [comment]
I've checked it out and is seems to be a bug. Gonna debug it in  the following days and hopefully come with a solution.

**Comment by fresser** [comment]
Nice. Anyhow, i found this issue in here, that i didn't find as first. Seems like the same problem and behavior. #45

**Comment by mg-1999** [comment]
That is indeed the same issue. Didn't notice it because i looked in the wrong place :P

**Comment by fresser** [comment]
So, not to stress you, but is there planned a fix to this? Because if not, we will not be able to use this for our server unfortunately. :3

**Comment by FriwiDev** [comment]
Duplicate of #35
