### ISSUE TITLE
Train chests don't always preserve cart orientation/flipped status

### ISSUE THREAD

**Issue by amalon** [bergerhealer/TrainCarts#484]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.20.1-v3-SNAPSHOT (build: 1612)
- TrainCarts Version (`/train version`): v1.20.1-v3-SNAPSHOT (build: 1450)
- Server Type and Version (`/version`): git-Paper-65 (MC: 1.20.1)

----
### Description
When a train consists of multiple carts, some of which are flipped (i.e. with `/cart flip`), and placed in a train chest (`/train chest`), restoring the train to track messes up the flipped status of the carts. Sometimes both carts are flipped around relative to how they were, sometimes only some. I haven't quite figured out the behaviour.

### Expected behaviour
Preserve the relative flipped state of the carts, such that a train of asymmetrical carts is restored without being messed up.

### Actual behaviour
Flipping some or all of the carts relative to one another.

### Steps to reproduce
One way is creating 2 carts next to one another, changing the carts to a mule & mushroom, doing `/cart flip` on one of them so they're facing away from one another, then using `/train chest` and right clicking the train, and restoring it to the same track.
In this case the first time it works (they're facing away from one another), but if I right click on the restored train and restore again to the same track, they're both facing the same way.

Another broken case if if i flip one cart (`/cart flip`, so they face away from one another), then flip the whole train (`/train flip`, still facing away from one another), then after the first restore both carts have turned around (facing towards one another).

**Comment by bergerkiller** [comment]
Not sure if this applies to you but Ill state it anyways

When you save a train make sure the train is moving forwards so the orientation is correct. You can specify --lockorientation to preserve that orientation in all future saves, regardless of what direction the train is moving.

That said, individual carts should not flip, so that sounds like a bug. Would be helpful if you could write the exact steps of reproducing it so I can see in my end.

**Comment by amalon** [comment]
Sure, hopefully this removes any ambiguity:
1) create a straight bit of normal minecart track (i had it in a north/south direction)
2) place two minecarts, next to one another (while stood on track, so they're the same orientation). They appear to become a train.
3) use the attachment editor to change the cart entity to something asymmetrical, i changed one cart to a mule, and the other to a mushroom (since they're nearby on the list of entities).
4) the animals should be pointing the same direction (if not, i suppose try again from a different angle so that they are). point at the animal behind the other, and `/train edit` the cart, then `/cart flip` to turn it so they both face outwards, away from one another
5) `/train chest`, and right click on the train (it disappears)
6) right click on the track, it reappears, looking the same
7) right click on the train, it disappears
8) right click on the track, it reappears with the animals facing the same direction as one another

The second example was similar, follow steps 1-4, then:
5) `/train flip`, the whole train flips around, animals still facing away from one another
6) `/train chest`, and right click on the train (it disappears)
7) right click on the track, it reappears, but with both animals facing the opposite direction, towards one another, either the carts have swapped place or both have flipped.
8) if you right click again on train, it disappears, and right clicking a second time the animals reappear facing the same direction as one another

I first noticed this when testing `/train chest` with my saved trains which make use of carts which are flipped (I think originally by just joining carts together which are spawned the right ways (i.e. not explicitly with `/cart flip`), but where the overall direction doesn't matter since the overall train is symmetrical

**Comment by bergerkiller** [comment]
I think I found the main cause behind this, which was that the initial direction face wasnt set right when a train was spawned. This would normally correct itself once the train was set in motion, but if you spawn it and right away save it, it caused carts to be flipped like you described. After the fix that particular bug didnt happen again.

https://ci.mg-dev.eu/job/TrainCarts/1454/

**Comment by amalon** [comment]
Perfect. Thanks!
