### ISSUE TITLE
Locked, Finite Train Chests Should Be Removed from the Player’s Inventory

### ISSUE THREAD

**Issue by FireController1847** [bergerhealer/TrainCarts#485]
### Description
I think the title is pretty self-explanatory. I would like to suggest that, when you give a locked, finite train chest, the chest item itself should be removed from the player's inventory. Currently, once you place the cart, the item is returned to you, but it now becomes useless, since a locked, finite train chest cannot be used for any other purpose.

### Examples
As described above, the item becomes useless once used.

Here is a video describing the issue and subsequent feature request:

https://github.com/bergerhealer/TrainCarts/assets/16494272/b053cd82-b020-4fef-8d50-f4bd9ee7b6b8

**Comment by bergerkiller** [comment]
Yeah it probably should. I can change that

**Comment by bergerkiller** [comment]
Added the requested feature, plus a way to change the spawn message or disable it ("")

https://ci.mg-dev.eu/job/TrainCarts/1466/

**Comment by bbayu123** [comment]
Closing - feature added.
