### ISSUE TITLE
Interesting deadmessage

### ISSUE THREAD

**Issue by BiDuang** [bergerhealer/TrainCarts#487]
### Description
How about allow user can edit the message of being run over by a train in config? The message now looks like it was killed by using the `/kill` command. User can provide a list of messages and the plugin will randomly select one of them as an announcement.

### Examples
For example, it can be set by default to:
- `Steve tried to stop a train, but the train didn’t stop for him.`
- `The train was faster than Steve. Much faster.`
- `Steve wanted to be a hero. He became a pancake.`

**Comment by bbayu123** [comment]
Is the `killmessage` train property enough, or do you need a list of messages to be selected randomly?
![image](https://github.com/bergerhealer/TrainCarts/assets/26726381/1a028d5d-0de7-4a1a-8917-f94bab0eb69b)
![image](https://github.com/bergerhealer/TrainCarts/assets/26726381/9718308f-a450-4f18-b2fc-83b2c19d8067)

**Comment by BiDuang** [comment]
> Is the `killmessage` train property enough, or do you need a list of messages to be selected randomly? ![image](https://user-images.githubusercontent.com/26726381/282387446-1a028d5d-0de7-4a1a-8917-f94bab0eb69b.png) ![image](https://user-images.githubusercontent.com/26726381/282387587-9718308f-a450-4f18-b2fc-83b2c19d8067.png)

Yes, does it support a random list?

**Comment by bbayu123** [comment]
No

**Comment by bbayu123** [comment]
It's hard to set properties on a sign when the property is a list

**Comment by BiDuang** [comment]
> No It's hard to set properties on a sign when the property is a list

Okay, thanks a lot!
