### ISSUE TITLE
Folia Support

### ISSUE THREAD

**Issue by pontaoski** [bergerhealer/TrainCarts#490]
## Feature Request
It would be neat if TrainCarts supported Folia.

### Examples
I run a server w/ Folia and would gladly adopt TrainCarts if it supported the platform.

**Comment by bbayu123** [comment]
To quote @bergerkiller from our Discord server on 30th March 2023:
> I wont be doing anything for folia support
> traincarts accesses a lot of blocks and I cant see that possibly working out on region ticked servers

Maybe berg will have a new stance, just wait for him to comment on this.

**Comment by bergerkiller** [comment]
Nope, no new stance. I rely heavily on a single thread to do everything in on the plugin. Commands from players and sign actions can target trains all over the server and that being on another thread makes it near-impossible to accomplish without a substantial rewrite. If folia included a synchronized step where all regions on the server wait for each other so it can run 'on one thread' I would have a chance, but that's not the case.

**Comment by bbayu123** [comment]
Closing this for now - cannot support.
