### ISSUE TITLE
Player sits on the minecart not in the minecart

### ISSUE THREAD

**Issue by kpaulisse** [bergerhealer/TrainCarts#5]
When entering a minecart the player is actually sitting on top of the minecart, not in the minecart. Also to enter the minecart the player sometimes has to click on the square one above where the minecart actually is.

**Comment by mg-1999** [comment]
@timmaker is working on this

**Comment by kpaulisse** [comment]
Yeah watching in 3rd person view looks like the player is one block too high when the cart is on a slope.
