### ISSUE TITLE
Player floats over minecart.

### ISSUE THREAD

**Issue by ZWarrior2** [bergerhealer/TrainCarts#50]
When a player is on a minecart which is on a rail, for some reason **he floats 1 block above it**. It gets really annoying, since the player will suffocate if there is a roof above the rail. Can anyone, if you can, provide me with a way to fix this problem?

![2016-02-18_18 08 27](https://cloud.githubusercontent.com/assets/17318746/13149609/238fb048-d673-11e5-94de-669ba16d701f.png)

**Comment by mg-1999** [comment]
This is already fixed in a recent release, please update your TrainCarts and BkCommonlib
