### ISSUE TITLE
Spawn trains with external plugin

### ISSUE THREAD

**Issue by harm27** [bergerhealer/TrainCarts#51]
Hey,

Is it possible to spawn a train above a specific train spawn sign from my own plugin?
Or do i need to place a blok that triggers the sign?

Harm

**Comment by HollishKid** [comment]
Hello,

@harm27 
I'm not sure it this is what you're looking for, but the /summon command has an interesting array of arguments. One of them is the coordinates to spawn the minecart ...

Hollish

**Comment by harm27** [comment]
Hey hollish,

I am specific searching for a way to spawn a traincarts train.
Since that is part of an existing system.
Only change is that the redstone stuff that was controlling the spawning will be replaced by a plugin.

Harm

**Comment by mg-1999** [comment]
There is no API available to excute placed signs directly form a plugin. you could use wireless redstone or build a system yourself.

**Comment by harm27** [comment]
Hey,

Okey, than i use the workaround by placing redstoneblocks. 
Will work to, but not the nicest sollution.

Harm
