### ISSUE TITLE
Section system

### ISSUE THREAD

**Issue by harm27** [bergerhealer/TrainCarts#52]
Hey,

I have some trouble with working on a plugin to get more info about a part of the track.
What i need to build is a system that spawns only a train if some parts of the track are not already having a train. 

The part of the triggering of that system is not a problem, but i have a trouble getting info about the track if there are trains or not.
I have looked into switchers with some kind of switching logic plugin that keeps remembering the current state. 
Only the problem is that there is no space for a lever without showing the lever to everybody, what i don't want. 

What i tried to realise is some kind of sign that can give his state to a single sign, so that sign can be used in some check systems. 
Only problem is, that if i know the start location and end location of a track part, i don't know how to check if the rails between that section is in use or not.

Is anyone have any idea there for?
Or does someone of traincarts have time to build something where you can check on a redstone system if a waiter, or a custum sign, something like a section, with [train]section startName endName.
Where startName means that is the name of the section that starts here, and endName the same, only that is the name of the section that ends here. 

Or has someone another idea to fix this?

Harm

@mg-1999 If my english explanation is not clear enough, i can maybe write a dutch explanation for you. I was really struggling to write my idea and problem in english.

**Comment by M64mc** [comment]
You can use detector signs:
http://minecraft.gamepedia.com/Custom_servers/Bukkit/TrainCarts/Signs/Detector
They detect trains between two signs.

**Comment by harm27** [comment]
Hey,

The problem is that the check system is triggert by some sort of region enter.
Let me explain that.
When a player enters a region the check system is triggert.
It needs to check if there is a train:
- In the get out area
- In the last scene before the get out area
- In the spawn area
If there is train in one of that areas, no train needs to be spawned.
But if there is no train there, then a train needs to be spawned.

**Comment by M64mc** [comment]
I don't understand what's the issue.
Detector signs can detect trains in a region:
![Detector](http://hydra-media.cursecdn.com/minecraft.gamepedia.com/e/e1/TrainCarts-detector.png)

**Comment by harm27** [comment]
![image](https://cloud.githubusercontent.com/assets/2715359/13400108/869f2538-df06-11e5-8c90-beae2f2a092b.png)
The track is like what stays above.
When a player enters the station region, there will be checked if there is a train on the step out or last scene or rangeer system. 
Since it is hangrail, i forgat to say that earlier, there is less space below. 
And most of the time, no space. 
This because of the scenery that is build arround the track. 

Harm

**Comment by M64mc** [comment]
I suggest having a look at this:
http://jd.mg-dev.eu/tc/com/bergerkiller/bukkit/tc/detector/DetectorRegion.html

**Comment by harm27** [comment]
Okey, i will try that. Looks what some part at what i am looking for.
Only problem is the length. 
I do have the start and end Location.
But i will look for a solition for that.

**Comment by M64mc** [comment]
Try this:
```java
TrackMap map = new TrackMap(startRail, direction, maxDistance); # maxDistance = maximum distance between the two blocks
while(map.hasNext()) {
    Block next = map.next(); # get next block
    if (next != null && /* check location */)
        break; # exit while
}
```
Don't use TrackMap#generate in this case.
I didn't test this but I'm 99% sure this works.

**Comment by harm27** [comment]
Okey, i think that will do that. Now coding it.
Thanks for the help.

**Comment by harm27** [comment]
I have been looking into the detector code. 
Maybe that is what i am looking for. 
Only problem is now how to get tracked of the detector. Is there a way to get the detectorregion name? So there can be a custom sign that tracks if that region is used and when not, spawn a train.

**Comment by M64mc** [comment]
You can activate a [Wireless Redstone](https://www.spigotmc.org/resources/wireless-redstone.8251/) channel in your DetectorListener.

**Comment by harm27** [comment]
What function do i need to use for that. Since there are multiple functions, for train or seperate cart.
Do i need to check in that function bv. for any groups, if there is a group, set status to off?

**Comment by M64mc** [comment]
You told me you didnt want to use detector signs 4 days ago...?

If you use detector signs you can just attach a lever to one of the signs and attach it to a wireless redstone transmitter.

**Comment by harm27** [comment]
Then i didn't understand it far enough. The problem with the lever thing is that there is next to the rail no space. Since it is a hangrail and the builders don't want some levers hanging, there is that problem what i am facing now. When i can one someway track what detectorregion the detectors are, then i can build a plugin with a DetectorListener that can track the channels.

**Comment by M64mc** [comment]
Try this:
![Detector](http://i.imgur.com/Ntiza1z.png)

**Comment by harm27** [comment]
Thanks for the help. That was exactly what i was looking for.

**Comment by M64mc** [comment]
No problem!
