### ISSUE TITLE
TrainCarts spams and crash the server. :(

### ISSUE THREAD

**Issue by VernoxPL** [bergerhealer/TrainCarts#54]
##### Spigot version: Latest 1.9

<hr>

#### Problem or bug: Crash a server, spam with errors and stop the server. I give you my server log. in the spigot 1.8 I have this error too. Sorry for my english.
[2016-03-13-7.log.gz](https://github.com/bergerhealer/TrainCarts/files/171114/2016-03-13-7.log.gz)

**Comment by Mr-toaster111** [comment]
Traincarts isn't currently on 1.9, only BKCommonlib

**Comment by riassmismans** [comment]
When is the release date for Traincarts and BKCommonlib 1.9?

**Comment by JackDn** [comment]
Soon
