### ISSUE TITLE
Can't Spawn a Minecart through TrainCarts

### ISSUE THREAD

**Issue by SpiderDead** [bergerhealer/TrainCarts#55]
BkCommonLib version: 1.70
TrainCarts version: 1.75
Spigot version: 1.9

<hr>

Problem or bug:
When I try to spawn a Minecart, TrainCarts doesn't allow it and "Destroys" it. Here's my latest log :
http://pastebin.com/0u8cF5v4 (Last part spams the console full like 100 times.)

**Comment by mg-1999** [comment]
TrainCarts isn't supported for 1.9

**Comment by SpiderDead** [comment]
Oh. Well rip. Couldn't find a 1.8 version of BKCOMMONLIB. Thanks for the help.
