### ISSUE TITLE
Failed to perform physics on train 'train1' at world_-703_24_1012:

### ISSUE THREAD

**Issue by woeterman94** [bergerhealer/TrainCarts#60]
Spigot version 1.8.9. Traincarts version: 1.8 

When a train passes a sign, the last car stops moving and the console is spammed with this error: 

6:59:41 PM [SEVERE] [Train_Carts] Failed to perform physics on train 'train1' at world_-703_24_1012:
6:59:41 PM [SEVERE] java.lang.NullPointerException

**Comment by mg-1999** [comment]
Please post BKC version

**Comment by woeterman94** [comment]
Got the issue. Problem caused when make a spelling mistake in the signs.
For example "colision" instead of "collision"

**Comment by woeterman94** [comment]
How can I find that version?
