### ISSUE TITLE
New Sign Station for TrainCarts

### ISSUE THREAD

**Issue by jugondavidlisto** [bergerhealer/TrainCarts#61]
Hello, I wanted to propose an improvement to traincarts. The improvement is that in sign station performs a check of the tags of minecarts an example: an example would sign station
[Train]
station (tags)
10
If the poster is written tags where there is a letter or number tag train has the same word or number, the train is stopped. But if the previous condition not met the train not stop. Should be that station you do not have any tag the train don't stopped. Also you can add more conditions by adding only : to separate each tag. 
Not if you can add this function yet it is easy to program. 
Sorry my english is very worst.

**Comment by Flin-Tin** [comment]
This can be a separate addon for the station sign (since there wont be enough space to fit all that)
but other than that..
Great suggestion! Adding more options to your stations can open more options to customise your rails :+1: 
P.S: Maybe set station names as well? Tags can be used to easily add trains to a rail system :D while for indivisual destinations > st. names :D

**Comment by timmaker** [comment]
I don't think this is possible with the current sign parsing, it basically looks at the second line and checks if it knows the sign type so if you would do station (tags) it won't recognize it anymore. therefor this will require a full rewrite of it :/

**Comment by frozenMC** [comment]
What I have done is set destination signs prior to the station and put stations on a bypass track. It works, and clears the mainline for any collision possiblities with incoming/outgoing trains.

**Comment by bergerkiller** [comment]
I am considering to instead add a new train property that specifies the amount of signs to 'skip'. When you hit a station and the counter is nonzero, the counter is decremented and the sign is skipped. You can set this counter with a property sign + switcher sign combo to check for tags and set the signs to skip there.

Unsure if I want it to only skip station signs or have it skip all signs. It could be useful for other intends and purposes too. Or perhaps have it a dedicated sign, like a switcher and property sign combined in one.

```
[+train]
skip 2
condition1
condition2
```
