### ISSUE TITLE
Download broken

### ISSUE THREAD

**Issue by dannyiscool4** [bergerhealer/TrainCarts#63]
##### Spigot version: 1.8.9

The download link on spigot page is broken and there are no other links/dev builds.

**Comment by FriwiDev** [comment]
This issue is already known. Please wait until mg_1999 fixed the builds again. The download is broken due to my attempt to update to 1.9.

**Comment by dannyiscool4** [comment]
Btw it's the same issue with BKCommonLib and SignLink.

**Comment by dannyiscool4** [comment]
UPDATE: SignLink works

**Comment by FriwiDev** [comment]
You can still grab downloads from mgs ci though

**Comment by FriwiDev** [comment]
https://ci.mg-dev.eu/

**Comment by mg-1999** [comment]
Fixed the download link for traincarts.

@FriwiDev You should update your download links to the CI I provided
