### ISSUE TITLE
server startup issue

### ISSUE THREAD

**Issue by TheCheesyOlympia** [bergerhealer/TrainCarts#66]
when I restart the server, the train reverts back to normal minecarts

**Comment by FriwiDev** [comment]
Please give details about used versions and other plugins active

**Comment by TheCheesyOlympia** [comment]
version: spigot 1.8.8
TrainCarts version: 17.5 Snapshot
BKCommonLib:1.70

**Comment by FriwiDev** [comment]
incompatible versions. Use BKCommonLib 1.65 please.
