### ISSUE TITLE
Crashes server every few minutes, many minecart related console errors

### ISSUE THREAD

**Issue by webb1234** [bergerhealer/TrainCarts#67]
#### Problem or bug:
**I recently installed TrainCarts (off here, latest version updated 01/05/2016 UK calendar) and the latest BKCommonLib, my server keeps stopping every 2m and then starting and showing the following errors. because its minecart related and has only started after I installed TrainCarts, I have reason to believe the plugin is causing me issues.**

#### Expected behaviour:
**No server crashing, none of the following errors: ** com.bergerkiller.bukkit.common.bases.ExtendedEntity.getWatchedData(ExtendedEntity.java:897) 02.05 11:36:42 [Server] ERROR at com.bergerkiller.bukkit.common.bases.ExtendedEntity.getWatchedData(ExtendedEntity.java:885) 02.05 11:36:42 [Server] ERROR at com.bergerkiller.bukkit.common.entity.type.CommonMinecart.getShakingFactor(CommonMinecart.java:85) 02.05 11:36:42 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MinecartMember.onPhysicsPreMove(MinecartMember.java:995) 02.05 11:36:42 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:902) 02.05 11:36:42 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:826) 02.05 11:36:42 [Server] ERROR at com.bergerkiller.bukkit.tc.controller.MinecartMember.onTick(MinecartMember.java:1170) 02.05 11:36:42 [Server] ERROR at com.bergerkiller.bukkit.common.entity.nms.NMSEntityHookImpl.m(NMSEntityHookImpl.java:46)
**PLUGIN LIST: TimeIsMoney, WorldEdit, Essentials, Vault, V10Lift, EssentialsSpawn, BKCommonLib, EssentialsChat, TrainCarts!
**

#### Steps to reproduce:
unsure

**Comment by FriwiDev** [comment]
Traincarts is not up2date yet. You are using 1.9 spigot with 1.9 bkcommonlib, but 1.8 traincarts. Please wait for an update or help us out :)
