### ISSUE TITLE
carts won't fall off rails

### ISSUE THREAD

**Issue by badfalcon** [bergerhealer/TrainCarts#68]
##### Spigot version:Spigot (git-Spigot-e4d4710-e1ebe52) : v1_8_R3 (Minecraft 1.8.8)

<hr>

#### Problem or bug:
problem
#### Expected behaviour:
https://youtu.be/R3Murxm7g4I
#### Steps to reproduce:
try to fall a cart off a rail

<hr>
Sorry if my English is terrible for me being a Japanese.
And sorry if this topic is duplicated.

https://youtu.be/mVo41Yq2S04
I don't know if it's working as intended but carts won't fall off rails.
We're trying to update our Tokyo Disneyland Map to 1.8 but due to this physics,some of our attractions won't work.
We'll be happy if this will be fixed as it worked before.

badfalcon
from Tokyo DisneyResort Reproduction Project
http://777labo.com/mc/index.php

**Comment by Driphosting** [comment]
Put on the end a station and your problem will be solved. Get a sign and typ this 
First row : [!train]
Second row : Station
It will stay there.

**Comment by mg-1999** [comment]
Freefall isn't possible in 1.9, minecraft physics dont support it anymore.

**Comment by badfalcon** [comment]
I tried freefall on a 1.9.4 vanilla server and I think it worked.
https://youtu.be/Udj7C5ikJzE

or did you mean that freefall isn't allowed in the new traincarts? or am I saying something wrong?
