### ISSUE TITLE
Make cart invisible

### ISSUE THREAD

**Issue by LimitedDani** [bergerhealer/TrainCarts#69]
##### Spigot version: 1.8.9

Dear BergerHealer, 

i have a issue about hiding a cart for players.

In my code:
                for(TrainProperties tc : TrainProperties.getAll()) {
                    if(tc.getTrainName().contains("pirana1")) {
                        Kar1.rideLocation = tc.getLocation().getLocation();
                        if(!pr1already) {
                                                        tc.setinvisible(true);
                            pr1already = true;
                            Kar1.start(tc);
                        }
                    }
                }
I want to make the train with the name pirana1 invisble but it won't work.

![2016-05-14_23 41 50](https://cloud.githubusercontent.com/assets/11191383/15270829/9df34090-1a2d-11e6-9353-91a5a894de3d.png)

As you see the cart in the middle is'nt invisible.

Hope you can help me!

Danique de Jong

**Comment by Mr-toaster111** [comment]
I could be wrong but I don't think there's a way to make non-living entities invisible.

**Comment by mg-1999** [comment]
It is possible, you could just disguise it as an chicken and make that one invisible. Really cheaty way, but is works :)

**Comment by LimitedDani** [comment]
Could you explain me about the disguising. Because why is their anyway an option to vanish traincarts carts when it won't work?

**Comment by JackDn** [comment]
You could cancel all outgoing packets about the minecart.

**Comment by mg-1999** [comment]
Tagging my friend @timmaker in this, because he is a master in disguise (pun intended)

**Comment by timmaker** [comment]
Hmm mabe take a look at this?
https://gist.github.com/aadnk/5871793

**Comment by mg-1999** [comment]
@timmaker but if you use BKC, You should also use protocollib

**Comment by mg-1999** [comment]
There is no setInvisible(boolean) method in TrainProperties only a setInvincible(boolean). So that could be the problem.

**Comment by bergerkiller** [comment]
https://bugs.mojang.com/browse/MC-118329

This will be relevant for readers

**Comment by bergerkiller** [comment]
This is now possible with the new attachment system.
