### ISSUE TITLE
Debug master

### ISSUE THREAD

**Issue by Driphosting** [bergerhealer/TrainCarts#73]
##### Spigot version: 1.9

<hr>

#### Expected behaviour:
Possibility to debug it
#### Steps to reproduce:
i try to fix the problems but i'm missing plugins in lib i believe : http://pastebin.com/rbbcmHet
no files on drone anymore either :: https://drone.io/github.com/bergerhealer/TrainCarts/files
@mg-1999  can you help me out:)?

**Comment by mg-1999** [comment]
Files  are back online now. Should be able to just download it now.
