### ISSUE TITLE
Trains get stuck

### ISSUE THREAD

**Issue by stanneman99** [bergerhealer/TrainCarts#74]
##### Spigot version: 1.8.8

<hr>

#### Problem or bug:
Trains get stuck in the floor after any drop.

#### Expected behaviour: 

Just cary on normal but this does not happen

#### Steps to reproduce:

Get a drop with like a train of 4 carts. with a station. It happend to me with 0.4 speed but it happens with other speeds as wel.

**Comment by stanneman99** [comment]
Sorry for bad english btw

**Comment by JackDn** [comment]
Duplicate of #43
