### ISSUE TITLE
Question about 1.9

### ISSUE THREAD

**Issue by Maxi22700** [bergerhealer/TrainCarts#76]
Hello. Just a question here and no issue to show.
Do you have an estimation about when you guys will be able to make a stable 1.9/1.9.2 build ?

I really appreciate this plugin and the work you're doing to keep it alive. This is the last plugin update I wait before I can update my server to 1.9 and I'm in a hurry waiting for an update !

**Comment by totoberg123** [comment]
I'm waiting too. They are very slow with updating..

**Comment by mg-1999** [comment]
And bugging me about wont get it faster. I will just ignore this even longer. I work on this in my free time and this shit keeps demotivating me. So just wait. :anger:

**Comment by FriwiDev** [comment]
*Like*

**Comment by Maxi22700** [comment]
I understand that you're working on this in your free time. I was just asking if you had a date. As you say, we just wait and as I said we all really like what you're doing to keep these plugs updated. The reason why I asked that is because TrainCarts is a major plugin on our server and is it the last plugin we need to update to be able to open in 1.9.2. So do I need a developper to update it fast or is it juste a matter of days before you'll update it ? Thanks again for your work

**Comment by Mr-toaster111** [comment]
You can't really ask them for a date. As things are fixed, things break. The plugin may be one of the most advanced in the game. You could go ahead and attempt to hire a developer to get it done faster, but just keep in mind the amount of time they're also going to have to spend understanding the plugin. I recommend just waiting like everyone else

**Comment by mg-1999** [comment]
It took me 6 months to learn how this plugin works. If you want to hire a
developer to fix this for you, you can be waiting for another 3 month. It
isn't copy/paste work. You need to actually understand the principle behind
this plugin and BKC, and if you understand that. You need to update it to
the next version without breaking backwards compatibility, but still adding
new features. And that is why its taking long. :)

Op zo 5 jun. 2016 om 17:39 schreef Mike <notifications@github.com>:

> You can't really ask them for a date. As things are fixed, things break.
> The plugin may be one of the most advanced in the game. You could go ahead
> and attempt to hire a developer to get it done faster, but just keep in
> mind the amount of time they're also going to have to spend understanding
> the plugin. I recommend just waiting like everyone else
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/76#issuecomment-223820029>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGmkdvdw2_e6ETykJmBn-C1cJOOmmMbFks5qIu2ggaJpZM4IkQbb>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by Maxi22700** [comment]
I understand that. I know it's not easy at all to update it and to create new features in same time, and I know that TrainCarts is probably one of the most complicated plugin.. My issue was just about the approximate time that it will take to finish your development work ? In fact, I don't need you to go faster, but for our organisation in servers, it could be helpful to have a period to planify our works. I could wait for this update for months if it's necessary, but I'm just asking in witch period do you think your work will be done ?
Thanks

**Comment by LazoYoung** [comment]
But I think it's taking way too long. It's been a year since 1.9 came out, 1.12 is coming up.
I think you could give up backward compatibility and using those old libraries.

**Comment by harm27** [comment]
@LazoYoung But the problem is that nobody has time to do any of it. Not the update nor the rewrite. @mg-1999 already said earlier that he didn't had time to do that. So it would need someone else that has a lot of Spigot/Bukkit internals knowledge to build a complete new rewrite version of this plugin. You just need to accept this situation or find another developer who is gonna do it, but probably you will need to pay him/her since it requires a lot of time to rewrite this kind of plugin.

**Comment by mg-1999** [comment]
@LazoYoung If it taking to long, why dont you just update it yourself? I just dont have enough time for it.
