### ISSUE TITLE
Could TC 1.9 change BlockPhysicsEvent to BlockRedstoneEvent?

### ISSUE THREAD

**Issue by PsychoLynx** [bergerhealer/TrainCarts#77]
Using Traincarts 1.75-SNAPSHOT, my timing report shows the plugin using 30% of my available CPU, which is just unacceptable. The biggest offenders (according to Aikar's) RedstoneTracker::onBlockPhysics(BlockPhysicsEvent) and TCListener::onBlockPhysics(BlockPhysicsEvent). 

AFAIK, plugins should be using BlockRedstoneEvent instead to detect redstone (which I believe this is doing), so I'm wondering if this will be changed in 1.9 to dramatically improve performance?

**Comment by mg-1999** [comment]
It could be a good change, but I don't know what the event currently is
doing. I am going to investigate the usage of it and, if possible, change
it to the BlockRedstoneEvent.

Op ma 23 mei 2016 om 17:01 schreef PsychoLynx <notifications@github.com>:

> Using Traincarts 1.75-SNAPSHOT, my timing report shows the plugin using
> 30% of my available CPU, which is just unacceptable. The biggest offenders
> (according to Aikar's) RedstoneTracker::onBlockPhysics(BlockPhysicsEvent)
> and TCListener::onBlockPhysics(BlockPhysicsEvent).
>
> AFAIK, plugins should be using BlockRedstoneEvent instead to detect
> redstone (which I believe this is doing), so I'm wondering if this will be
> changed in 1.9 to dramatically improve performance?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/77>
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by PsychoLynx** [comment]
To my knowledge, it is related to powering the train signs with redstone to summon carts etc. 
Thank you so much!

**Comment by bergerkiller** [comment]
This should now be fixed in the latest build, as I now cache the block physics events and fire them later the next tick. This saves excessive updates when nothing happens. In addition, it no longer parses the sign format when redstone events occur, saving on cpu there.
