### ISSUE TITLE
TC-Hangrail sign problem AND maxspeed problem

### ISSUE THREAD

**Issue by xXYasinXx** [bergerhealer/TrainCarts#78]
##### Spigot version:1.8.8

<hr>

#### Expected behaviour:that they work

a pic of how i do the formatting(BTW i am dutch so my english isnt good)
![2016-05-24_19 29 00](https://cloud.githubusercontent.com/assets/19556863/15513678/010f6784-21e6-11e6-9c91-05f28d046b26.png)

**Comment by JackDn** [comment]
> Expected behaviour:that they work

That's not very detailed...
What is supposed to happen?

**Comment by xXYasinXx** [comment]
@JackDn when it goes over the maxspeed - i want it to go faster and that what actually supposed to happen but it doesn't even if i put it on the side of a normal track
if you can see here 
![2016-05-24_21 04 56](https://cloud.githubusercontent.com/assets/19556863/15516452/44d3dc22-21f3-11e6-8448-5a2936642650.png)
and when using TC-hangrail(ADD-ON for Traincarts) - it doesn't do anything! i could't get any sign working and should work

link for 1.8 spigot Traincarts https://www.spigotmc.org/resources/traincarts.8557/

**Comment by JackDn** [comment]
This is supposed to happen. The maxspeed sign doesn't change the speed, it changes how fast the cart **can** go.

**Comment by xXYasinXx** [comment]
@JackDn do you know any way to force the carts to go faster??

**Comment by JackDn** [comment]
You can use launcher signs.

**Comment by Mr-toaster111** [comment]
I can't recall if it still works but you should be able to place powered rails to speed it up to the maxspeed

**Comment by xXYasinXx** [comment]
@Mr-toaster11 i know but i want it to go faster than that.... instead of 0.4 i wanted it on 1 or 2

**Comment by Mr-toaster111** [comment]
@xXYasinXx Again i may be wrong but I'm pretty sure if you set the maxspeed with a property the powered rail will accelerate the car to that max speed.

**Comment by FriwiDev** [comment]
Not a bug for our github. Just some language misunderstandings.
