### ISSUE TITLE
Calculate Waiter Distance

### ISSUE THREAD

**Issue by JackDn** [bergerhealer/TrainCarts#79]
Waiters should be able to automatically calculate the distance to the next waiter or station.
This would make it possible to have waiters without having to count the distance.

**Comment by FriwiDev** [comment]
This feature would have even more performance downsides then Traincarts already has. All chunks in between would need to stay loaded for this all the time.

**Comment by JackDn** [comment]
The signs could just calculate the distance when they are placed and store them on the sign.
