### ISSUE TITLE
"Could not pass event BlockRedstoneEvent to Train_Carts"

### ISSUE THREAD

**Issue by HairyDaddy** [bergerhealer/TrainCarts#80]
**BkCommonLib version:** 1.67
**TrainCarts version:** 1.75
**Spigot version:** 1.8.8-R0.1-SNAPSHOT

Carts will take a while to teleport (they stand still for a few secs and then teleport) up/down, creating a lag spike thus generating an error. 

You can reproduce the error by using an elevator sign powered by a switcher sign (tag statements) and a lever. This is what I have right now: [*link*](http://imgur.com/a/LkVU7) there’s a sign below the lever stating that the cart should teleport up (I keep saying teleport but I’m actually using an elevator sign)

[*This*](http://pastebin.com/F5qH6Z0U) is what I’m getting on my cmdp.

**Comment by JackDn** [comment]
Please try the following:

- Move the elevator sign a bit
- Wire it up using redstone dust

If that doesn't work, try adding a repeater.

**Comment by HairyDaddy** [comment]
I did all of the above which.. worked?!I I can’t believe I haven’t thought of that before. Thank you! Tho I couldn’t issue the bug again, it’s still there if I come to use a simple system with a lever so I hope there are solutions soon.
