### ISSUE TITLE
Delicious Crashes

### ISSUE THREAD

**Issue by Kushbird** [bergerhealer/TrainCarts#82]
##### Spigot version: Latest

<hr>

#### Problem or bug:
Minecarts will disappear when placed and the server will crash moments after.
#### Expected behaviour:
Allowing me to spawn and place minecarts.
#### Steps to reproduce:
Place a minecart.

Please help me fix this problem, I'd love to have this awesome plugin in my server. I'm looking forward to it to use on my server.

**Comment by Blitheness** [comment]
You're going to need to provide actual versions. Saying 'Latest' isn't specific enough.

**Comment by Kushbird** [comment]
mate dont go crazy on my when i aint got access to the version files at request

but since u can like help, and this plugin is more of an essential than essentials i gotta give u the versions number thanks so much already k?

BkCommonLib version: 1.70

TrainCarts version: 1.75-downloadfix

Spigot version: 1.9.4(Don't know how Spigot handles version names nowadays.)

i see many poeple use that version n working i dunno if right can u tell? thanks

grotjes an tim en matthijs

**Comment by mg-1999** [comment]
Traincarts isn't ready for 1.9. So please dont use it.

Op ma 6 jun. 2016 om 18:19 schreef Kushbird <notifications@github.com>:

> mate dont go crazy on my when i aint got access to the version files at
> request
>
> but since u can like help, and this plugin is more of an essential than
> essentials i gotta give u the versions number thanks so much already k?
>
> BkCommonLib version: 1.70
>
> TrainCarts version: 1.75-downloadfix
>
> Spigot version: 1.9.4(Don't know how Spigot handles version names
> nowadays.)
>
> i see many poeple use that version n working i dunno if right can u tell?
> thanks
>
> grotjes an tim en matthijs
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/82#issuecomment-224009167>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGmkdgI0TBNyS9Eo75WfKG64qD-aNRJJks5qJEh3gaJpZM4It458>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by Kushbird** [comment]
so when is it? and why do i see poepl using it?

k thanks bye

tenks matthijs echt supre bedank!

**Comment by Mr-toaster111** [comment]
Most likely you are seeing people running the protocol hack as you can run 1.8 plugins. There is also still no defined date of release for 1.9 version of traincarts

**Comment by Kushbird** [comment]
well i'd like to know this plugin is really good and i'd love to see it updated

k tenks

**Comment by Driphosting** [comment]
Give Matthijs his time that he need.
Everyone thinks that it's easy or something but it isn't.
When you fix 1 bug another one pops up.
And because people are sending awesome ideas it's taking a little bit
longer because the plug-in is getting better and better.

And in the Netherlands it'seems also exam period so i'my not sure if he is
also in it.

So please wait while matthijs and his team are making a awesome 1.9 plugin


Op maandag 6 juni 2016 heeft Kushbird <notifications@github.com> het
volgende geschreven:

**Comment by HairyDaddy** [comment]
Well, I just hope the author updates the plugin soon enough. I know how hard it is to keep up a plugin plus your daily routine and having things to attend irl and all of that.. so well, I just wish you could give us a date? months? weeks? I don’t know, anything would be helpful. This plugin is core to my server and I need to know how long I’ll hold back before updating the server to further versions. I honestly don’t mind waiting, I just wish to know approximately when a new version will be up.

**Comment by Kushbird** [comment]
Same goes for me. I understand very well that these things take time, but it'd be very helpful to server owners to give an estimate. Nothing precise, just to give a little idea on how far progress is going.

**Comment by Maxi22700** [comment]
Same for me too. Waiting for an update. Actually the guest experience on my server is really compromised...
