### ISSUE TITLE
Play custom sounds

### ISSUE THREAD

**Issue by ghost** [bergerhealer/TrainCarts#84]
There should be a way to play custom resource pack sounds.

Sign layout:
- [train]
- sound [pitch] [volume]
- ...

It could work similarly to the announcer sign (parse signs below) to allow having long sound names.

**Comment by Maxi22700** [comment]
Nice idea ! Should be great, to give the sound only for player inside the train and avoid using a radius with can give music to players out of the train...

**Comment by JackDn** [comment]
I think there should be a radius.
You could use it for music or sound effects in specific areas.

**Comment by mg-1999** [comment]
@timmaker

**Comment by timmaker** [comment]
I think we might be able to change the effect sign, if i'm not mistaking it can already play some sounds

**Comment by michal12sk** [comment]
Yes, it can. 
[train]
effect
<name of sound>
I don't know if it's compatibile with 1.11.2, since in the 1.9 the sounds changed
