### ISSUE TITLE
Feature request: Handle collisions with different kinds of mobs differently

### ISSUE THREAD

**Issue by kpaulisse** [bergerhealer/TrainCarts#9]
I am working on this for my own use. Please let me know whether this would be desired in the release.

Currently collisions of carts with mobs are controlled by one setting (collision.mobs) which manages collisions with animals, monsters, villagers, and pets. I would like this to be more granular. For example, I might want to have the train kill monsters, have animals enter, and have pets be ignored.

I propose these categories:
- Tamed animals (aka "pets") -- tamed horses, cats, dogs
- Other animals (including untamed horses, wolves, ocelots)
- Monsters
- NPCs

This would be backward compatible:
- Any reference to "mob" in the configuration files would be replaced by new entries for animals, monsters, NPCs, ...
- Any reference to "mob" on signs would set collision modes for all of the above entity types.

I've got this as a work in progress [here](https://github.com/kpaulisse/BKCommonLib/tree/mobcollisions) and [here](https://github.com/kpaulisse/TrainCarts/tree/mobcollisions)

**Comment by mg-1999** [comment]
Very cool idea, only I think that you should use the mob categories.
* Passive
* Neutral
* Hostile
* Tameble
* Utility
* Boss

**Comment by kpaulisse** [comment]
:+1: I'll keep this as a work in progress in my branches until it's done.

**Comment by mg-1999** [comment]
Those are the Mob categories provided by the Minecraft Wiki.
