### ISSUE TITLE
2 Traincarts Bugs/Glitchs

### ISSUE THREAD

**Issue by 72juju** [bergerhealer/TrainCarts#91]
I've found 2 bugs on TrainCarts please solve them in the video you have the versions of spigot and traincarts and i'm running BkCommonLib Latest Version :+1: 

https://www.youtube.com/watch?v=qC7XmpMPzEc&feature=youtu.be

**Comment by harm27** [comment]
First, it is not the correct way to report bugs. In your bug report here you need to tell what spigot/bukkit version you are using, what traincarts version and what bkcommonlib version. See the template voor github issues of this repo.
Second, your way of asking is not to nice to the developers of this plugin.
They are developing for free on this plugin, so they do it in the time they have.

**Comment by 72juju** [comment]
All is in the video.

**Comment by 72juju** [comment]
About the versions.

**Comment by mg-1999** [comment]
Please use the provided format.

**Comment by 72juju** [comment]
;('
