### ISSUE TITLE
The 2 bugs/glitches of traincart.

### ISSUE THREAD

**Issue by 72juju** [bergerhealer/TrainCarts#92]
##### BkCommonLib version:

1.67

##### TrainCarts version:

1.75

##### Spigot version:

1.8.7 SNAPSHOT

<hr>

#### Problem or bug:

Train goes in floor

Train get stuck in turns

#### Expected behaviour:

A train is not doing this! ( Normally )
#### Steps to reproduce:
Like in the video :)

#### Video to explain:

https://www.youtube.com/watch?v=qC7XmpMPzEc

Thanks for resolving this in the future.

**Comment by mg-1999** [comment]
Update spigot to 1.8.9.

**Comment by 72juju** [comment]
Ok i will try.

**Comment by 72juju** [comment]
I can't find the 1.8.9 version 0_0

**Comment by harm27** [comment]
I think you need 1.8.8. There is no server version of 1.8.9, since that was only a realms patch.

**Comment by mg-1999** [comment]
@harm27 forgot that :smile: 

@72juju Sharp 'U'-turns cause individual carts to lose perceptive of their direction. Keep at least one piece of track in between corner sections! Thus it can't be fixed.

The train in ground problem is already know and hasn't been fixed yet.

**Comment by harm27** [comment]
@mg-1999 That can happen.

**Comment by mg-1999** [comment]
@72juju check #43 or #20
