### ISSUE TITLE
Leaving train when teleported

### ISSUE THREAD

**Issue by 72juju** [bergerhealer/TrainCarts#93]
##### BkCommonLib version:

1.70-2
##### TrainCarts version:

1.75
##### Spigot version:

1.8.8

<hr>
#### Problem or bug:

Essentials teleportation causes leaving of a minecart if it forces you stay in.
#### Expected behaviour:

You can't leave
#### Steps to reproduce:

Enter a minecart where the property to not leave the cart is set.
Do 1 time /tpa (player)
With another account accept teleportation with /tpaccept
Then this time you leave the minecart and the second time it really teleport.

**Comment by timmaker** [comment]
This has nothing to do with traincarts, it has always been this way. It's just something from vanilla minecraft

**Comment by JackDn** [comment]
@timmaker Essentials calls Player.leaveVehicle() before teleporting the player.

**Comment by mg-1999** [comment]
Solution:
Don't use Essentials. JK. :joy: 

Maybe I could override that and make an option in the config for enabling the feature of blocking essentials tp when in a cart.

**Comment by RyanHecht** [comment]
This would actually be nice, I usually end up handling it through other means and this would be much better!

**Comment by 72juju** [comment]
mg-1999 the /tp command do this too.

Solution:
Don't use MINECRAFT. JK. :joy:

--'
